### ISSUE TITLE
Foundation + Modernizr.touch return TRUE on IE if body font-size = 9px

### ISSUE THREAD

**Issue by Daynos** [Modernizr/Modernizr#1004]
Strange bug. In a page, include Modernizr 2.6.2 (dev) + foundation.min.css (generated online) then override CSS body font-size with 9px. Under IE10/9/8/7 (WIN 7 FR), Modernizr.touch returns TRUE (instead of FALSE). Change font-size to 10px and it returns FALSE (as expected).

Reproduced with Foundation 3 and 4. No problem with Modernizr 2.5.1. I can't say if the problem comes from Foundation or Modernizr.

Test page :
```javascript
<!DOCTYPE html>
<html class=" no-js" lang="fr">
<head>
<meta charset="utf-8">
<title>Test</title>
<meta name="description" content="">
<?php // FOUNDATION 4 or 3 ?>
<link rel="stylesheet" href="/libs/foundation/css/foundation.min.css">
<style>
	body { font-size: 9px; }
</style>
<script src="/libs/modernizr-2.6.2.dev.js"></script>
<script type="text/javascript">
	if(Modernizr.touch){
		alert("true");
	} else {
		alert("false");
	}
</script>
</head>
<body></body>
</html>
```

**Comment by patrickkettner** [comment]
closing as outdated
