### ISSUE TITLE
Coverage Suggestion

### ISSUE THREAD

**Issue by tntim96** [Modernizr/Modernizr#1011]
Thanks for the great library.

Are you interested in [coverage reports](http://jscover.sourceforge.net/modernizr/jscoverage.html) for your [test suite](http://modernizr.github.com/Modernizr/test/)?

The above results are from combining a few browsers (IE10, FF21.0, Chrome 28). The tests are currently included but can easily be excluded.

Also a few tests are failing in browser with or without JSCover instrumentation - haven't investigated as to why yet.

**Comment by patrickkettner** [comment]
we are fully covered with istanbul and coveralls now, but thank you a ton for opening this up!
