### ISSUE TITLE
css-hyphens focus event trigger keyboard, Firefox for Android

### ISSUE THREAD

**Issue by pascalduez** [Modernizr/Modernizr#1052]
css-hyphens.js line 163 `dummy.focus();`

https://github.com/Modernizr/Modernizr/blob/master/feature-detects/css/hyphens.js#L163

Triggers keyboard in Firefox for Android.

**Comment by doublecompile** [comment]
+1. Still a problem on Firefox 37.0.2, Android 5.1, Modernizr 2.8.3. Keyboard triggered and see "lebowski" written twice.

**Comment by ivaylosp** [comment]
+1 Firefox 41 on Android Lolipop Modernizer 3.0.0 The input field is visible and lebowskilebowski bellow it. Keyboard get triggered by default as its the first element on the page.

**Comment by slavanga** [comment]
See also: #1438

**Comment by mario-areias** [comment]
This bug is being around for two years and it keeps happening consistently. No updates on this yet?

**Comment by patrickkettner** [comment]
PRs are welcomed

**Comment by mario-areias** [comment]
Working on it. It is a shame nobody has fixed yet :(

**Comment by mario-areias** [comment]
Actually @patrickkettner there is a PR already 

https://github.com/Modernizr/Modernizr/pull/1514

Does that fix the issue?

**Comment by ryanseddon** [comment]
Just merged it! Closed via #1514

**Comment by mario-areias** [comment]
Awesome! Thanks @ryanseddon . I am not familiar how the Modernizr is released :(. Do you know when this fix will be released then?

**Comment by baicaigithub** [comment]
I just saw lebowskilebowski recently ff 63 on https://ceac.state.gov/.

**Comment by alexandroid** [comment]
For posterity (also shows up on the main page):
![lebowski](https://user-images.githubusercontent.com/555063/57211108-500b2600-6f9c-11e9-8766-ef90478be78f.png)

**Comment by StormBlade97** [comment]
Confirmed that this is a thing. I was thinking that it was a backdoor for admin or something... 🤔

**Comment by rejas** [comment]
@StormBlade97 what version of modernizr are you experiencing this with?
