### ISSUE TITLE
Use the GitHub Releases pages

### ISSUE THREAD

**Issue by nschonni** [Modernizr/Modernizr#1094]
Might be useful to use the [GitHub releases page](https://github.com/Modernizr/Modernizr/releases) as described [here](https://github.com/blog/1547-release-your-software) so it is easier to see what has changed between releases.

**Comment by FlashJunior** [comment]
+1

**Comment by nschonni** [comment]
Closing since it looks like the later releases are now using the releases page https://github.com/Modernizr/Modernizr/releases
