### ISSUE TITLE
Need to discuss v3 development version

### ISSUE THREAD

**Issue by stucox** [Modernizr/Modernizr#1148]
@SlexAxton @paulirish @ryanseddon @patrickkettner @joecritch

Hi folks, thought we could do with a final decision on this.

We’ve agreed that v3 won’t distinguish between “core” and “community” detects. So, what goes in the development version?

* Do we still have a dev version, or encourage people to use a custom build (or grunt-modernizr) from the start?
* If we do have a dev version, do we put *every* detect in the dev version? This would be ~60kB min’d (and growing), taking about 300ms (including async tests) on my MBA

Obviously the concern is that some may deploy a heavy dev version to production… then we’ve contributed to someone having a bit of a shit experience on the web.

Also worth considering what kind of build we’d expect HTML5 Boilerplate to include, as that’s probably an easy way to accidentally end up with a heavy Modernizr dev build in production.

**Comment by patrickkettner** [comment]
we shipped!
so don't need this anymore (basically just went with what we did before)
