### ISSUE TITLE
Add dependency badges to the HTML5 Cross Browser Polyfills wiki site

### ISSUE THREAD

**Issue by dvorapa** [Modernizr/Modernizr#1171]
What about to review the HTML5 Cross Browser Polyfills wiki site and add small badges (coloured dots or fields) to all polyfills, which could show the dependencies or required libraries about each polyfill...
For example simple badge for dependency of the jQuery v1.7.1:
![Pic1](https://f.cloud.github.com/assets/5113916/1825001/6ca3e68e-71a6-11e3-9dd1-3c839e1f9bde.PNG)

**Comment by patrickkettner** [comment]
@joecritch whatcha think about adding something like this to the list of polyfills on different modules?

**Comment by patrickkettner** [comment]
closing from a lack of support. if anyone wants this, please open up as a new issue on the modernizr-neue repo
