### ISSUE TITLE
Video autoplay error: Cannot call method 'removeChild' of null

### ISSUE THREAD

**Issue by robwierzbowski** [Modernizr/Modernizr#1196]
Running Modernizr 3.0.0pre in Chrome I get the error:

``` js
elem.parentNode.removeChild(elem); // <- Uncaught TypeError: Cannot call method 'removeChild' of null
```

coming from [line 30 of the video auto play test](https://github.com/Modernizr/Modernizr/blob/ff40a84fdde704a53d6a762767e9a1fbb90f0456/feature-detects/video/autoplay.js#L30).

**Comment by samccone** [comment]
Been plagued by this one for a few months now, able to reproduce intermittently on 

Chrome Version 43.0.2357.130 (64-bit) osx


![screen shot 2015-07-01 at 7 33 04 pm](https://cloud.githubusercontent.com/assets/883126/8468946/08aa88b8-2028-11e5-8d35-b6ca0e504c25.png)
