### ISSUE TITLE
Feature request: Save detections to localStorage

### ISSUE THREAD

**Issue by tinganho** [Modernizr/Modernizr#1202]
I wonder if you can save all detections to localStorage, so that you don't need run all detects on every page request.

**Comment by patrickkettner** [comment]
closing from a lack of updates - PRs area always welcome, though.

**Comment by frontenddeveloping** [comment]
What do you think about such solution https://github.com/frontenddeveloping/Modernizr-Loader/blob/master/modernizr.loader.js ? I think it will enough for static prop values which are the common case. 
Loader just control Modernizr cache status and load it if needed.

**Comment by patrickkettner** [comment]
Hey @*frontenddeveloping <https://github.com/frontenddeveloping>*!
​open to anything, would just want benchmark results before its added
