### ISSUE TITLE
Don’t test against every prefix every time for `testAllProps()` / `prefixed()`

### ISSUE THREAD

**Issue by stucox** [Modernizr/Modernizr#1223]
As highlighted by @hexalys on #878: it’s wasteful to iterate through every prefix every time – the prefix an engine uses is always the same. IE gets a particularly raw deal, because we test `-ms-` last every time.

I also like the idea of exposing the detected prefix as `Modernizr._prefix`.

How should we determine the prefix? [This method](http://davidwalsh.name/vendor-prefix) by @darkwing looks as reliable as any other (taking @mathiasbynens’ [comment re. IE < 8 support](http://davidwalsh.name/vendor-prefix#comment-49324) into account)

**Comment by patrickkettner** [comment]
gonna close this, as browsers now support a mish mash of prefixes and you can't guarantee which any browser will implement.

**Comment by hexalys** [comment]
Well, for the record, you can!
I do it in my own library now... where it's one of the prerequisite, which allows some undetectables to become identifiable along the way. But I'll aggree that the logic required to identify the native prefix for the engine properly outweigh the single benefit here, and doesn't appear well suited for Modernizr's approach.
