### ISSUE TITLE
List of new detects in v3.0.0

### ISSUE THREAD

**Issue by stucox** [Modernizr/Modernizr#1230]
*Thought I’d keep this separate from #805.*

Here’s a list of all the new detects coming in v3.0.0, generated by fairly manually comparing the repos / builder (last count: 99):

* ambientlight
* animation
* audioloop
* audiopreload
* background-blend-mode
* backgroundcliptext
* beacon
* canvasblending
* canvaswinding
* capture
* checked
* contains
* cssall
* cssescape
* csschunit
* cssexunit
* cssinvalid
* csspseudoanimations
* csspseudotransitions
* customevent
* dart
* datachannel
* directory
* documentfragment
* ellipsis
* es5
* es5array
* es5date
* es5function
* es5object
* es5string
* es5syntax
* es5undefined
* es6array
* es6math
* es6number
* es6object
* es6string
* flash
* flexboxtweener
* flexwrap
* generators
* getrandomvalues
* hidden
* hiddenscroll
* htmlimports
* indexeddbblob
* inputformaction
* inputformenctype
* inputformmethod
* inputformtarget
* inputsearchevent
* intl
* jpegxr
* localizednumber
* nthchild
* oninput
* pagevisibility
* peerconnection
* picture
* pointerevents *(previous “pointerevents” detect renamed to “csspointerevents”)*
* preserve3d
* promises
* proximity
* queryselector
* requestautocomplete
* search
* serviceworker
* shapes
* sizes
* siblinggeneral
* speechrecognition
* speechsynthesis
* srcset
* svgasimg
* target
* template
* templatestrings
* textalignlast
* textareamaxlength
* todataurlpng
* typedarrays
* unicoderange
* unknownelements
* videoautoplay
* videoloop
* videopreload
* vml
* webplossless
* webpalpha
* webpanimation
* willchange
* wrapflow
* xhrresponsetype
* xhrresponsetypearraybuffer
* xhrresponsetypeblob
* xhrresponsetypedocument
* xhrresponsetypejson
* xhrresponsetypetext

**Comment by stucox** [comment]
Updated again. 95…

**Comment by jraller** [comment]
is `formvalidation` missing from this list?

**Comment by patrickkettner** [comment]
That was in 2.X

**Comment by patrickkettner** [comment]
#1585 _removes_ draganddrop

**Comment by patrickkettner** [comment]
closing since we shipped 3.0
