### ISSUE TITLE
CSS Filter Join Error

### ISSUE THREAD

**Issue by TwisterMc** [Modernizr/Modernizr#1253]
I'm trying to detect CSS filters and I get this error in Chrome "Uncaught TypeError: Cannot call method 'join' of undefined"

Firefox says "TypeError: Modernizr._prefixes is undefined"

Build: http://modernizr.com/download/#-svg-shiv-cssclasses-css_filters-load

**Comment by typeoneerror** [comment]
@patrickkettner doesn't appear to be fixed for all css props, fyi https://github.com/Modernizr/Modernizr/issues/2119
