### ISSUE TITLE
IE 11 flexbox bug

### ISSUE THREAD

**Issue by michaeltrilford** [Modernizr/Modernizr#1301]
IE 11 has recently made an error with Flexbox. It was / still is working fine in IE10, but the latest browser has made the CSS Feature unusable for those users.

What happens:

When an image is a child of a flex item, it doesn't resize the height to auto when specified, which doesn't keep the correct constraints when resizing for responsive elements. 

Attached is an example of this: 
![screen shot 2014-04-11 at 3 27 40 pm](https://cloud.githubusercontent.com/assets/2483515/2690594/80a9e266-c352-11e3-8f08-f9a016b92178.png)

Live example of the code in the screenshots:
http://codepen.io/boostnewmedia/full/kvtoF

Phil Walton ( Solved by Flexbox ) said "philwalton: @themiketee the most annoying thing is I reported it well before IE11 shipped and it didn’t make it in. Months later, it’s still not fixed."

Known issue for Microsoft dating back to 10/1/2013:
https://connect.microsoft.com/IE/feedback/details/802625/min-height-and-flexbox-flex-direction-column-dont-work-together-in-ie-10-11-preview#tabs

They have dropped the ball again.

**Comment by joaopgrassi** [comment]
Did as @i-fekete said and it worked for me.
In my case, I was having issues with images. They were stretching when inside of a flexbox container. Thanks!

**Comment by michaeltrilford** [comment]
@joaopgrassi Yes, that was the original problem.

**Comment by tasos-ch** [comment]
The solution of @i-fekete worked for me, too.

I can't thank you enough!

**Comment by brendanpatterson** [comment]
Thanks @i-fekete - Life saver!

**Comment by samholguin** [comment]
Thank you @i-fekete

**Comment by maaniek9** [comment]
@i-fekete, thank you! It works for me, but I had to add `min-width` property too.

**Comment by saraheagle** [comment]
Adding overflow:hidden worked for me, although I had a problem with the width, not the height!
.flex-wrapper	{display:flex; flex-wrap:wrap}
.flex-item	        {overflow:hidden}
