### ISSUE TITLE
pointerEvents false positive in browsers that don't support it

### ISSUE THREAD

**Issue by supernintendo** [Modernizr/Modernizr#1363]
Hello,

`Modernizr.testProp('pointerEvents')` returns true in IE9 and IE10 where the property is not fully supported. Searching for this issue reveals [old](https://github.com/Modernizr/Modernizr/issues/80) [threads](https://stackoverflow.com/questions/11786919/test-pointer-events-in-ie-with-modernizr) where this is discussed but none of the proposed workarounds seem to work.

I am using the latest release, 2.8.2.

Thanks,

Michael

**Comment by machwatt** [comment]
Any further information here?
Same issues with emulated IE9/10 and the following build

/*! modernizr 3.2.0 (Custom Build) | MIT *
 * http://modernizr.com/download/?-csspointerevents-setclasses !*/

**Comment by ryanseddon** [comment]
Just tested a build and it's reporting no support in IE10/9 correctly? https://codepen.io/anon/pen/bENrbb

**Comment by trwill** [comment]
Same issue still exists with IE9/10 emulator - returning false positives. Anyone else seeing this? I am going to try to get my hands on a native version to see if I can reproduce.

**Comment by trwill** [comment]
Disregard above - seemed to only return false positives on IE emulator. On native versions both IE9 & 10 reporting no support correctly
