### ISSUE TITLE
css-scrollbars false positive in firefox

### ISSUE THREAD

**Issue by codekipple** [Modernizr/Modernizr#1365]
Seems to be returning true in firefox but as far as i know there is no way to styles scrollbars in the latest version of firefox.

**Comment by patrickkettner** [comment]
ping @codekipple

**Comment by codekipple** [comment]
@patrickkettner Hi, yeah ok I'll get on it and create a pull request. It's been a while since I tried the css-scrollbars test. I'll fire it up and re test it before submitting pull request.

**Comment by patrickkettner** [comment]
:D thanks dude - don't hesitate to ask for a hand, would be stoked to have you land it

**Comment by patrickkettner** [comment]
@codekipple hows it goin?

**Comment by galtalmor** [comment]
I think this should be closed now...
