### ISSUE TITLE
Option to stop Modernizr converting "no-js" to "js"

### ISSUE THREAD

**Issue by triblondon** [Modernizr/Modernizr#1385]
I would like to propose a new option to govern this default behaviour.  Perhaps:

```
ModernizrProto._config['jsSupportClass'] = true | false | ["from", "to"];
```

If true (default behaviour for backwards compatibility) it replaces `no-js` with `js`.  If false, it doesn't do anything.  If an array, it replaces the first value with the second.

Use case: A site (eg ft.com) chooses to set the bar for JavaScript execution higher than the simple presence of some kind of JavaScript engine.  This approach has been popularised by the BBC and was named [Cuts the mustard](http://responsivenews.co.uk/post/18948466399/cutting-the-mustard) by their dev team.  UAs that do not 'cut the mustard' should be treated as if they have no JS capability, thereby reducing testing overhead and easing support of legacy clients.

This will increasingly become more of an issue as the performance gap between ES6-supporting UAs and those that support only ES3 challenges developers to write increasingly bizarre code to take advantage of ES6 features while somehow continuing to provide some capability for legacy clients.

We also wish to support a more complex use case in which there are multiple cuts the mustard tests - eg one for dynamic advertising and analytics, and a higher one for everything else.

If there's agreement from maintainers on an approach I'm happy to code it up and submit a PR.

Cheers.

**Comment by patrickkettner** [comment]
@triblondon - this is in master now, thanks @rose!

**Comment by triblondon** [comment]
Excellent, thanks!
