### ISSUE TITLE
The specified value ':)' does not conform to the required format, 'yyyy-MM-dd'.

### ISSUE THREAD

**Issue by JRGould** [Modernizr/Modernizr#1412]
I'm receiving this javascript error in the latest build of chrome canary ( 39.0.2127.0 ) with modernizr 2.8.3 on line 536. 

`The specified value ':)' does not conform to the required format, 'yyyy-MM-dd'. modernizr.js:536`

It looks like the variable `smile` is set to `:)` and is being used to set the values on HTML5 form elements that are being generated by modernizr and when the `<date>` element is created with a value of `:)` it's causing Canary to fire a validation error.

**Comment by snymax** [comment]
I am getting this error in node-webkit am I stuck with it until nw.js is updated

**Comment by patrickkettner** [comment]
@snymax this isn't an error - its just a super annoying warning. you can ignore it.

**Comment by brilyuhns** [comment]
Cant ignore it. The date field is not populated due to this.

**Comment by patrickkettner** [comment]
@brilyuhns what do you mean?
