### ISSUE TITLE
False negative on Video Autoplay (Modernizr V3)

### ISSUE THREAD

**Issue by germanalvarez** [Modernizr/Modernizr#1427]
After checking how did video Autoplay work on v3, I just opened my website from Firefox and it had a no-videoautoplay class, this is a false negative as it does support it:

![screenshot_1](https://cloud.githubusercontent.com/assets/8863375/4359358/2dc8370c-4271-11e4-9579-dab1600c30aa.jpg)

On Chrome, there's another false positive (no-videoautoplay).
On IE11, there's another false positive (no-videoautoplay).
On Opera, it detects it correctly (videoautoplay).

**Comment by ryanseddon** [comment]
I believe I've found the fix wanna [test this](https://codepen.io/anon/pen/QyWQjQ) and see if you get the correct results?

**Comment by ryanseddon** [comment]
Closed via #1795

**Comment by yuchant** [comment]
Chrome 48.0.2564.116 unreliably detected. First load is OK, subsequent loads shows no-videoautoplay class.

**Comment by petrklus** [comment]
Same on Chrome 55

**Comment by glomotion** [comment]
Chrome 84.0.4147.105 in Mac 10.15.6 is incorrectly reporting false:
https://codepen.io/glomotion/pen/gOrpoXG
<img width="795" alt="Screen Shot 2020-08-10 at 11 30 08 am" src="https://user-images.githubusercontent.com/1452237/89746432-eb267000-dafc-11ea-883f-dc4effc9b44c.png">
