### ISSUE TITLE
cssvhunit and cssvwunit broken detection

### ISSUE THREAD

**Issue by cgythm** [Modernizr/Modernizr#1449]
Under Chrome 37.0.2062 Android 4.4.4, vhunit and vwunit works BUT modernizr reports no-cssvhunit and yes to cssvwunit even though vh and vw unit works.

upon further investigation, chrome 37.0.2062 failed 8 tests it expected to past:
- contentsecuritypolicy
- css-featurequeries
- viewport-units for both cssvimunit and cssvhunit
- html5semantic
- use-strict
- notifications
- and it died on the rest

#### Follow up on cssvwunit issue:
when it sets div#modernizr height to 50vh, it doesn't equal window.innerHeight/2, but it equals something very close to it. On my phone, it's off by a pixel, and that is why the test case fails :(

**Comment by patrickkettner** [comment]
@organdonor47 this is fixed in the latest master
