### ISSUE TITLE
Chrome 38.0.2125.111 (& possibly earlier versions) throwing a number of false negatives

### ISSUE THREAD

**Issue by ghost** [Modernizr/Modernizr#1451]
I'm experiencing a false negative being thrown for CSS 3D Transforms in Chrome 38.0.2125.111 (first time I've noticed it, not sure if older versions are affected) in a custom Modernizr build from a couple of months ago.

Checking the Modernizr test suite in Chrome 38.0.2125.111 also produces the CSS 3D Transforms false negative, along with a number of other false negatives against the expected results from caniuse.com. 
Modernizr Test Suite: 
    (image) http://i.imgur.com/kf76sqU.png
    (url) http://modernizr.github.io/Modernizr/test/
Ref tests from caniuse and Modernizr:
    (image) http://i.imgur.com/jbqLisT.png
    (url) http://modernizr.github.io/Modernizr/test/ + click on "show the ref from Caniuse and Modernizr"

However, the caniuse.com test suite (independent of http://modernizr.github.io/Modernizr/test/), produces the proper results (although tests.caniuse.com apparently incorporates Modernizer into their tests):
    (image) http://i.imgur.com/fhPgoyl.png
    (url) http://tests.caniuse.com/?feat=transforms3d

Additionally, testing in Codepen produces the proper results:
    (url) http://codepen.io/anon/pen/fdDBe

And the Chromium Dashboard shows that CSS 3D Transforms has been supported, prefix free, since Chrome 36:
    (url) https://www.chromestatus.com/feature/6437640580628480

Every other major browser (FF, Opera, Safari, Canary, sorry no IE) works properly. I am on a fresh, clean install of every browser, on a machine that is no more than two or three days old.

I don't think this is a browser issue, but it seems strange that it's only happening in Chrome (but no Canary). Any input or information would be great appreciated. Thanks.

_T

**Comment by hay** [comment]
FWIW, i've seen this bug occurring on three different instances of recent Chrome stable (>44) versions (two Mac OS X, one Windows), and i have no clue what's causing it. I've even seen it reporting correctly for one host (a development server) and giving a false negative on another (a production server).

**Comment by patrickkettner** [comment]
Which bug?

**Comment by hay** [comment]
@patrickkettner false negatives for 'csstransforms3d' on Chrome.

**Comment by patrickkettner** [comment]
Would you happen to be using a non 100% zoom level? That does not seem related to this issue
