### ISSUE TITLE
WebGL false positive on safari  iOS7

### ISSUE THREAD

**Issue by nanusefue** [Modernizr/Modernizr#1456]
Detect that window.WebGLRenderingContext function exist and return false positive because webgl is not activated. If you use this function, works fine:

```javascript
hasWebGL = function() {
    var canvas, gl;
    gl = null;
    canvas = document.createElement('canvas');
    try {
      gl = canvas.getContext("webgl");
    } catch (_error) {}
    if (gl == null) {
      try {
        gl = canvas.getContext("experimental-webgl");
      } catch (_error) {}
    }
    return gl != null;
  };
```

**Comment by brendankenny** [comment]
@patrickkettner I don't have iOS 7 handy to verify, but we just got burned by Safari 7 on this if WebGL isn't manually enabled. Can we reopen this issue?

`supportsContext ` doesn't appear to be supported there, so not sure if there's a good way of verifying support short of actual (slow) context creation :(

**Comment by paulirish** [comment]
we could sniff to isolate to ios7+ mobile safari before we context create…

**Comment by patrickkettner** [comment]
hey @brendankenny!

So I am seeing different results in iOS 7 

![image](https://cloud.githubusercontent.com/assets/465414/5887894/441d79c6-a3b6-11e4-8da5-65d32925d2bf.png)


any chance you could go into more details on how you are seeing the failure?

**Comment by brendankenny** [comment]
hey @patrickkettner! Thanks for taking a look.

I just realized the name of this issue only has "iOS 7" in it while one of the comments refers to both iOS 7 *and* Safari 7, which is the string I had searched for. I can move to a new issue if that's better.

I'm seeing no support for `supportsContext` in *desktop* Safari 7.1.2 (yet `WebGLRenderingContext` is on `window`), which unfortunately is the latest Safari you can get if you haven't made the upgrade to Yosemite.

**Comment by patrickkettner** [comment]
@brendankenny I think a new issue would make the most sense. If you want to open one up, we can continue over there.

cheers!

**Comment by brendankenny** [comment]
sounds good. opened #1499
