### ISSUE TITLE
Question: config injection

### ISSUE THREAD

**Issue by mahnunchik** [Modernizr/Modernizr#1476]
Maybe it makes sense to move config injection
from Grunt task https://github.com/Modernizr/Modernizr/blob/master/Gruntfile.js#L202
to initial generator https://github.com/Modernizr/Modernizr/blob/master/src/generate.js 

It is also possible to dynamically insert library version.

What do you think about this?

**Comment by patrickkettner** [comment]
sure! submit a PR, and we can discuss details
