### ISSUE TITLE
Unnecessary metadata generation

### ISSUE THREAD

**Issue by mahnunchik** [Modernizr/Modernizr#1477]
When Modernizr is required as a module it causes metadata generation in folder of modernizr: `node_modules/modernizr/dist/metadata.json`.

I think that this is wrong behavior:

1. to generate anything when module only is required
2. to change anything in the folder of module

`metadata.json` file is produced after the following lines:
```js
var Modernizr = require('modernizr');
```

**Comment by patrickkettner** [comment]
I agree its broken, that is why its currently a `pre` release. Since there are other build related issues, all of which would fix this (at least in order to be merged), I don't think this needs to be a separate issue.
