### ISSUE TITLE
Build script not detecting classes in Javascript?

### ISSUE THREAD

**Issue by CFXd** [Modernizr/Modernizr#1483]
I'm not sure if this is unexpected behavior, but neither of these selectors:

 1. `$('.touch .foo')`
 2. `$('.no-touch .foo')`

cause the `touch` test to be included in my build. Using the `Modernizr.touch` test does work though, so wasn't sure if this is expected behavior or an issue.

Thanks for feedback!

**Comment by patrickkettner** [comment]
Hey there!
I'm not sure what you mean. Selectors in no way effect your build. Its
static. Could you elaborate on what is going on?

**Comment by CFXd** [comment]
Sorry, meant this for grunt-modernizr!
