### ISSUE TITLE
Progress to v3

### ISSUE THREAD

**Issue by davidnormo** [Modernizr/Modernizr#1484]
I've had a look around at the open issues and v3 milestone but can't tell exactly how close v3 is to release. Is it 1 week, 1 month, 3 months away? 
Are there any blockers? If so what are they?

I also don't know what I can do to help move the release date nearer. Are there particular issues that need solving for this release and what are they?

Thanks

**Comment by patrickkettner** [comment]
hey @davidnormo!

There are two main things that are preventing a release. One is a redoing the build tool, and then redoing the website. Hopefully we can get them going finished soon, but thats really the closest thing to a date I have. It would be at minimum a few weeks.

cheers!
