### ISSUE TITLE
Store minimized version so bower consumer can have it (dist/ or .min.js)

### ISSUE THREAD

**Issue by kienpham2000** [Modernizr/Modernizr#1497]
Most other repo have dist/ or .min.js file. Can we include one also?

**Comment by patrickkettner** [comment]
hey @kienpham2000!
This was literally the last closed issue on Modernizr - #1496 

short answer is no, long answer is in the previous versions.

out of curiosity, what made you request this? is there a conversation somewhere that caused multiple people to open an issue?

either way - cheers!

**Comment by roblarsen** [comment]
Deja vu. I thought Github was having a hiccup.

**Comment by kienpham2000** [comment]
all of my packages in my angularjs app have either dist or .min.js file. Just wondering why mondernizer doesn't have it (all the cool kids have it!). 

If this is a recurring issues for you guys, maybe put a FAQ on the README.md so people don't submit this issue again.

**Comment by patrickkettner** [comment]
@kienpham2000 no worries!

The issue is that we don't even have the file that is in bower anymore. we are 100% modular. so there really isn't a thing to submit to bower. [there are plans to make it work](https://www.youtube.com/watch?v=7YMZMHRgUrE) it just takes..some time
