### ISSUE TITLE
WebGL false positive in Safari 7

### ISSUE THREAD

**Issue by brendankenny** [Modernizr/Modernizr#1499]
tested in Safari 7.1.2 (OS X 10.9.5)

If WebGL has not been enabled in the Develop menu, `WebGLRenderingContext` is still found on `window` and `supportsContext` was not added to later builds of Safari 7 for some reason, so the current test returns true.

I haven't found a workaround yet, short of the old, slow way of actually trying (and failing) to create a WebGL context.

**Comment by patrickkettner** [comment]
hey @brendankenny!

I am still not able to reproduce (I actually tested on a earlier version of safari). 

![image](https://cloud.githubusercontent.com/assets/465414/5911707/1c45e798-a597-11e4-9eef-c4d26a48f6df.png)


Could you load up [this](http://jsconsole.com/?%27supportsContext%27%20in%20document.createElement(%27canvas%27)) url and let me know what the results are? 

cheers!

**Comment by brendankenny** [comment]
yep, returns false for me. Very weird.

**Comment by patrickkettner** [comment]
can you get the exact build for safari and os x?

**Comment by brendankenny** [comment]
Ah, found it. I missed this, but `supportsContext` was apparently renamed `probablySupportsContext`. https://developers.whatwg.org/the-canvas-element.html#dom-canvas-probablysupportscontext

changed in WebKit here: https://bugs.webkit.org/show_bug.cgi?id=120716

Interesting that they left in `supportsContext` in other versions of Safari but not this one.

**Comment by brendankenny** [comment]
Sure

Safari Version 7.1.2 (9537.85.11.5)
OS X 10.9.5

**Comment by patrickkettner** [comment]
hah!

would you be able to create a PR?

**Comment by ryanseddon** [comment]
What that's so weird does safari dev tools do warnings like chrome does when they've deprecated APIs. Thanks for the heads up @brendankenny
