### ISSUE TITLE
Video autoplay support test breaks FF35 on Mac (Modernizr v3)

### ISSUE THREAD

**Issue by sarukuku** [Modernizr/Modernizr#1500]
The new **Firefox 35** seems to have some problems with the videoautoplay test (on **Mac** at least). I'm getting only false positives from it and to me it looks like the test can break other videos on the page too. At least my lazily loaded Vimeo embedded players refuse to work after the test is run. Otherwise they work fine. The weirdest part is that it seems that some times the Modernizr test can paralyze videos on other tabs too.

I've created a few reduced test cases:

##### File as video source
- http://bond.fi/demos/firefoxvideotest/index.html
- Works as expected

##### Data URI as video source
- http://bond.fi/demos/firefoxvideotest/index2.html
- Works as expected

##### Modernizr (v3) videoautoplay test
- http://bond.fi/demos/firefoxvideotest/index3.html
- `<html>` gets a `no-videoautoplay` class added (false negative)
- Tab loading icon keeps spinning indefinitely
- Have to force quit FF to close it

##### Modernizr (v3) videoautoplay test + one video (file as video source)
- http://bond.fi/demos/firefoxvideotest/index4.html
- `<html>` gets a `no-videoautoplay` class added (false negative)
- Tab loading icon keeps spinning indefinitely
- The `<video>` element on the page works
- Have to force quit FF to close it

##### Modernizr (v3) videoautoplay test + one video (data URI as video source)
- http://bond.fi/demos/firefoxvideotest/index5.html
- `<html>` gets a `no-videoautoplay` class added (false negative)
- Tab loading icon keeps spinning indefinitely
- The `<video>` element on the page works
- Have to force quit FF to close it

I'm not sure why this is happening but I'm quite sure that the Modernizr test is triggering the unexpected behavior in Firefox 35 (Mac). Could it be the video files that have been embedded in the test as data URI's that the FF can't handle?

**Comment by sarukuku** [comment]
I tried the Modernizr test but with a different video source. Didn't help. Here's the Modernizr videoautoplay test but with the same test video as in the above examples.
- http://bond.fi/demos/firefoxvideotest/index6.html

**Comment by patrickkettner** [comment]
thank you so much for a fabulous report - seriously, awesome work!

this is almost 100% caused by 35 adding support for mp4 playback on OS X. Moving the check for `Modernizr.video.ogg` [above the check for h264](https://github.com/Modernizr/Modernizr/blob/8862e4797279e96c987e747e7a8d985b5233a677/feature-detects/video/autoplay.js#L40-L43) would likely work around this problem.

**Comment by sarukuku** [comment]
Tested changing the check order in the beginning but there must have been so much other things going on that page that I just screwed it up somehow. I now tried a reduced test case with the check order switched and it seems to fix the problem. Here's a link to a test case where the check order has been switched: http://bond.fi/demos/firefoxvideotest/index7.html

Now the behavior is as expected. Thanks @patrickkettner :+1:

**Comment by patrickkettner** [comment]
@sarukuku you manually reordered the modernizr file, right? if so, can you open up a PR with the change?

**Comment by sarukuku** [comment]
@patrickkettner yep, just copy and paste. Will do the PR tomorrow.

**Comment by patrickkettner** [comment]
no worries - I took care of it.

cheers!
