### ISSUE TITLE
Add a test for video "Javascript intiated" play

### ISSUE THREAD

**Issue by jraoult** [Modernizr/Modernizr#1505]
Modernizr 3 already has a test to detect if `autoplay` value is fulfilled by the browser. There is another cas that diverges a little bit when the video playback is triggered by JS (method `play()` of the `HTMLMediaElement`).

For example, FF for Android (as of v35) prevents video from playing even if `autoplay` attribute is set to `true` (hence the Modernizr's "videoautoplay" test is negative) but doesn't prevent the video playback to be initiated by JS even without user intervention.

I wrote a Modernizr test for that very similar to "videoautoplay" where instead of setting `autoplay` to `true` I called the method `play()` on the video element.

**Comment by patrickkettner** [comment]
Hey Jonathan!
Thanks a ton for the heads up!
Would you be interested in writing a PR adding that detect? The only main
pointer I would have is to abstract out the gigantic base64 srcs into
another file, then `require`ing them as needed

**Comment by jraoult** [comment]
Sure @patrickkettner, I'll use the week upcoming week end for that and yes I'll make sure to not copy these big base64 guys over ;-)

**Comment by patrickkettner** [comment]
sounds awesome!

thanks so much dude!

On Wed, Jan 28, 2015 at 10:33 PM, Jonathan Raoult <notifications@github.com>
wrote:

> Sure @patrickkettner <https://github.com/patrickkettner>, I'll use the
> week upcoming week end for that and yes I'll make sure to not copy these
> big base64 guys over ;-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Modernizr/Modernizr/issues/1505#issuecomment-71963492>
> .
>



-- 
patrick

**Comment by jraoult** [comment]
Sorry @patrickkettner it took me a little bit longer than expected to find the time work on it. Please see #1526
