### ISSUE TITLE
Modernizr QUnit tests fail on Windows

### ISSUE THREAD

**Issue by jacobrossi** [Modernizr/Modernizr#1507]
The latest master doesn't seem to run the qunit tests on Windows. Following these steps:

1. Clone the repo
2. npm install
3. grunt build
4. grunt serve .
5. browse to <localhost:port>/test

I get the following error (and subsequent errors below that) when running on any browser on Windows:

    Modernizr classes and bools: Modernizr.audio and Modernizr.video (1, 0, 1)Rerun
    Died on test #1     at http://localhost:3000/test/js/unit.js:178:1: Cannot read property 'toString' of undefined
    Source: 	
    TypeError: Cannot read property 'toString' of undefined
        at Object.<anonymous> (http://localhost:3000/test/js/unit.js:183:24)
        at Object.Test.run (http://localhost:3000/test/qunit/qunit.js:134:18)
        at http://localhost:3000/test/qunit/qunit.js:277:10
        at process (http://localhost:3000/test/qunit/qunit.js:1233:24)
        at http://localhost:3000/test/qunit/qunit.js:376:5

I also get a similar error when running through phantom.js via grunt test.

If instead I try this on Mac, things run cleanly.

**Comment by jacobrossi** [comment]
I should note I'm using Windows 10. So it's quite possible this is an OS change that broke some tool in the toolchain.

**Comment by patrickkettner** [comment]
thanks so much for the report. 

when building and servering from a mac, I am not able to replicate. it may be a builder issue, then. Im setting up a windows 10 vm now to try and debug

**Comment by ryanseddon** [comment]
So weirdly that test case has `webglextensions` in the array it's looping over in that test. Maybe something to do with that.

**Comment by leobalter** [comment]
I tried it here and so far I've got:

- the test suite runs just fine on Chrome (Mac) when I go to http://modernizr.github.io/Modernizr/test/
- the same link doesn't work on Firefox (Mac), it loads the Modernizr checks but doesn't run the suit tests/assertions, they doesn't neither fail.
- running locally, I've got the same suit fail reported on this issue, but on Mac OS' Chrome and Firefox. The fail summary is shown below

![captura de tela 2015-02-03 19 02 55](https://cloud.githubusercontent.com/assets/301201/6032452/4efe5cba-abd7-11e4-9a55-a8de943cc2db.png)

**Comment by patrickkettner** [comment]
@leobalter that sounds like a separate issue (since its not happening on windows 10)

could you open up a separate issue?

cheers!

**Comment by leobalter** [comment]
Done. For the sake of simplicity I deleted the *huge* attached image from here.

**Comment by jacobrossi** [comment]
I think I'm going to try taking the build output from a Win <10 machine and placing that on my W10 machine and running the test. If that works, then I'll try the reverse: put the W10 build output on a W <10 machine and run the tests. That should at least figure out if the issue is rooted in the build process or in the test process.

**Comment by jacobrossi** [comment]
It looks like the issue is in building.  On Windows 10, the modernizr-build.js output from grunt build is missing several thousand lines. :open_mouth:

**Comment by patrickkettner** [comment]
@jacobrossi both the testing page and the builder have been completely redone. Could you give it another go?

**Comment by ryanseddon** [comment]
ping @jacobrossi are the new tests working for you know in windows 10?

**Comment by jacobrossi** [comment]
Yup, working now. Thanks @patrickkettner and @ryanseddon  :-)

**Comment by patrickkettner** [comment]
![yay](http://media.tumblr.com/tumblr_lzl20bbqEL1r50pfh.gif)

**Comment by jacobrossi** [comment]
FWIW, I think this is just lucky that it works (still a good thing). It looks to me like what I was actually hitting was the Windows file path length limit (~260 characters).  That's our bug, not yours, of course. So I'll see if I can make friends with whoever at Microsoft owns that and petition a change. ;-)

**Comment by patrickkettner** [comment]
the file path limit applies to urls as well?

**Comment by jacobrossi** [comment]
Ironically, no (I could poke fun and say that the browser team understands paths better than the file system team...but I'm sure there's a lengthy story as to why this limitation still exists). So it's not about Modernizr's code, but about files/paths generated from the build/tests pipeline. So if you're storing the project root in a deep folder, it's possible to hit this path length limit with deep node dependency graphs.

**Comment by ryanseddon** [comment]
Interesting, thanks for the insights @jacobrossi

**Comment by patrickkettner** [comment]
thanks @jacobrossi :]
