### ISSUE TITLE
Local tests fails

### ISSUE THREAD

**Issue by leobalter** [Modernizr/Modernizr#1508]
Based on #1507, I've done some investigation trying to help fixing and found more stuff.

- http://modernizr.github.io/Modernizr/test/ runs just fine on Chrome (Mac)
- the same link doesn't work on Firefox (Mac) (I'll address this in a individual issue with references)
- running locally, I've got some tests failing both on Mac OS' Chrome and Firefox, as listed below

![fail summary](https://cloud.githubusercontent.com/assets/301201/6032452/4efe5cba-abd7-11e4-9a55-a8de943cc2db.png)

**Comment by patrickkettner** [comment]
what version of firefox and os x?

running on yosemite, firefox 34, I am getting all green on the web test
liniut <http://modernizr.github.io/Modernizr/test/>

On Tue, Feb 3, 2015 at 7:11 PM, Leo Balter <notifications@github.com> wrote:

> Based on #1507 <https://github.com/Modernizr/Modernizr/issues/1507>, I've
> done some investigation trying to help fixing and found more stuff.
>
>    - http://modernizr.github.io/Modernizr/test/ runs just fine on Chrome
>    (Mac)
>    - the same link doesn't work on Firefox (Mac) (I'll address this in a
>    individual issue with references)
>    - running locally, I've got some tests failing both on Mac OS' Chrome
>    and Firefox, as listed below
>
> [image: fail summary]
> <https://cloud.githubusercontent.com/assets/301201/6032452/4efe5cba-abd7-11e4-9a55-a8de943cc2db.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Modernizr/Modernizr/issues/1508>.
>



-- 
patrick

**Comment by patrickkettner** [comment]
what version of firefox and os x?

running on yosemite, firefox 34, I am getting all green on the [web test link](http://modernizr.github.io/Modernizr/test/)

**Comment by leobalter** [comment]
yosemite

- Firefox 35 (stable) - `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:35.0) Gecko/20100101 Firefox/35.0`
- Chrome 40 (stable) - `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.94 Safari/537.36`

**Comment by leobalter** [comment]
@patrickkettner, the results are different from the local and the web links.
