### ISSUE TITLE
gh-pages tests are not running on Firefox 

### ISSUE THREAD

**Issue by leobalter** [Modernizr/Modernizr#1509]
I can get the tests from http://modernizr.github.io/Modernizr/test/ to run on Chrome (Mac) but not on Firefox.

It lists the Modernizr check-ins but it doesn't run the QUnit test blocks and assertions. The browser mentions it's loading eternally but it doesn't mention on which resource at the network panel.

By the Modernizr check-ins I meant the listed below (as an example):

![captura de tela 2015-02-03 19 15 47](https://cloud.githubusercontent.com/assets/301201/6032643/5a377b14-abd9-11e4-9bc1-01b40fd664a6.png)

Ref #1507
Ref #1508

**Comment by leobalter** [comment]
This problem is specific to the gh-pages suite as I can't reproduce them locally (#1508)

**Comment by patrickkettner** [comment]
this is because of https://github.com/Modernizr/Modernizr/issues/1500

**Comment by leobalter** [comment]
So it should be fixed as soon the gh-pages get updated, right?

**Comment by patrickkettner** [comment]
Yep! I will update when I get back home tonght
