### ISSUE TITLE
Referencing Modernizr in a .svg file produces "Modernizr is not defined"

### ISSUE THREAD

**Issue by SaraSoueidan** [Modernizr/Modernizr#1516]
I got a `.svg` file, and the idea was to use Modernizr's media query detection inside the SVG. I referenced Modernizr from a CDN first and then used it:

```
<scrip src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>
<script>
/* ... */
if (Modernizr.mq('screen and (max-width: 30em)'))
/* ... */
</script>
```
The code didn't work and I got "Modernizr is not defined" in the console.

I thought it might be the CDN or something so I copy-pasted the Modernizr source code into the svg file:

```
<script>
<![CDATA[
  /* Modernizr source code here. Note that I tried both minified and development versions */
]]>
</script>
```
This got me the same "Modernizr is not defined" error and a couple of additional errors concerning variables defined in the Modernizr script.

I might me missing something here; or maybe I'm doing it wrong? 

I tweeted about it, no one responded with any solution and some people asked to share my solution with them once I got one, so apparently this is not a common thing.

Patrick [asked me to open an issue](https://twitter.com/patrickkettner/status/561918368085991424) so here it is. Help is much appreciated and I'll be happy to share the results in a blog post for whoever is interested.

Thanks!

**Comment by patrickkettner** [comment]
thanks so much for opening up the issue!
I am not sure off hand, but I will jump in tomorrow morning to try and find
out

cheers!

On Sun, Feb 8, 2015 at 4:44 AM, Sara Soueidan <notifications@github.com>
wrote:

> I got a .svg file, and the idea was to use Modernizr's media query
> detection inside the SVG. I referenced Modernizr from a CDN first and then
> used it:
>
> <scrip src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>
> <script>
> /* ... */
> if (Modernizr.mq('screen and (max-width: 30em)'))
> /* ... */
> </script>
>
> The code didn't work and I got "Modernizr is not defined" in the console.
>
> I thought it might be the CDN or something so I copy-pasted the Modernizr
> source code into the svg file:
>
> <script>
> <![CDATA[
>   /* Modernizr source code here. Note that I tried both minified and development versions */
> ]]>
> </script>
>
> This got me the same "Modernizr is not defined" error and a couple of
> additional errors concerning variables defined in the Modernizr script.
>
> I might me missing something here; or maybe I'm doing it wrong?
>
> I tweeted about it, no one responded with any solution and some people
> asked to share my solution with them once I got one, so apparently this is
> not a common thing.
>
> Patrick asked me to open an issue
> <https://twitter.com/patrickkettner/status/561918368085991424> so here it
> is. Help is much appreciated and I'll be happy to share the results in a
> blog post for whoever is interested.
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Modernizr/Modernizr/issues/1516>.
>



-- 
patrick

**Comment by SaraSoueidan** [comment]
Sure! Thanks for looking into it. 

Have a great weekend!

**Comment by stucox** [comment]
> `<scrip src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>`

Is that the exact code you used? If so, looks like a typo in the opening tag (should be `script` rather than `scrip`). Although from a quick test it doesn’t look like remote scripts in SVGs are loaded, in Chrome at least.

I tried copy-pasting an unminified full v3 build straight into an SVG myself, and got:

```
Uncaught TypeError: Cannot read property 'backgroundBlendMode' of null
```

– probably because we create our `<modernizr>` test element using `document.createElement()` and then assume it’s an `HTMLElement` – but in an SVG document it’ll be an `SVGElement` which has different properties.

I’m afraid Modernizr’s a bit too geared towards being used in HTML at the moment…

**Comment by roblarsen** [comment]
Inside the context of an SVG document you need to use namespace aware DOM methods. In this case using:
```
modElem = document.createElementNS('http://www.w3.org/2000/svg',mod)
```
instead of 

```
modElem = document.createElement(mod)
```
fixes it. 

Plunk with just the mq modernizr build 

http://plnkr.co/edit/vV8RUt?p=preview

**Comment by stucox** [comment]
We specifically need an HTML element I think, so maybe we should try to
inject a `<foreignObject>`?

I'd be up for adding some kind of in-SVG support to Modernizr, although it
would need some thorough testing (so probably not until v3.1).

**Comment by patrickkettner** [comment]
@SaraSoueidan were you able to try @roblarsen's plunker?

**Comment by SaraSoueidan** [comment]
@patrickkettner Not yet! I just saw the comments, had a look at the code and it looks like it _should_ work. Will give it a spin and let you know. 

Thanks @roblarsen

**Comment by SaraSoueidan** [comment]
@stucox That typo was made here when I wrote the snippet, not in the SVG doc I was working on. My bad!

**Comment by roblarsen** [comment]
@SaraSoueidan let me know if you have any questions, this was the most interesting thing I've done all week.

**Comment by roblarsen** [comment]
>I'd be up for adding some kind of in-SVG support to Modernizr, although it
would need some thorough testing (so probably not until v3.1). 

How would you imagine it working? As a build option?

**Comment by patrickkettner** [comment]
I would imagine that it would involve detecting the type of document we are in, and changing various things accordingly. If it was a non trivial amount of code being added, we may want to use a flag, but I would not think it would be necessary.

**Comment by SaraSoueidan** [comment]
@patrickkettner SVG support would be brilliant. The use case I was using it for is very practical and will even write about it in an upcoming blog post, so it will definitely come in handy! For the client work I had, I was able to avoid using Modernizr inside the SVG for now because the client already had Modernizr referenced in the page and I could access the SVG externally and just change some styles from the outside. But were he not using it already, then Modernizr inside the SVG would have been a great alternative.

**Comment by SaraSoueidan** [comment]
Oh and btw @roblarsen 's plunker script works! 

Thanks so much for this, Rob. :)

**Comment by ryanseddon** [comment]
Just playing around a quick test doing the following inside an svg

```js
({}).toString.call(document) // [object SVGDocument]
```
We could use that to figure out if we're inside an svg context and then call createElementNS from there. As for having an `<html>` element we target `document.documentElement` which will be fine.

**Comment by ryanseddon** [comment]
Something like this works http://plnkr.co/edit/8CMPIVmUZ3pijf3wusdU?p=preview
