### ISSUE TITLE
Unofficial npm packages

### ISSUE THREAD

**Issue by doctyper** [Modernizr/Modernizr#1522]
Today I [was alerted](https://github.com/doctyper/customizr/issues/9#issuecomment-73754804) that unofficial packages of [customizr](https://www.npmjs.com/package/customizr), [gulp-modernizr](https://www.npmjs.com/package/gulp-modernizr), and [modernizr](https://www.npmjs.com/package/modernizr) can be found on npm.

These modules are probably the reason there was so much exposure around #1517. A few developers had no idea `gulp-modernizr` was in pre-release.

We should figure out how to transfer control of these packages and unpublish them until we are ready for Modernizr 3.0 to land.

/cc @metalshark

**Comment by metalshark** [comment]
Hi @doctyper thinking that `npm owner add doctyper customizr` followed by `npm owner rm metalshark customizr`, etc is the best way to go - can you confirm please?

**Comment by patrickkettner** [comment]
Thanks so much for the quick response, @metalshark!

**Comment by metalshark** [comment]
@patrickkettner apologies for the problems its causing you. I can at least add developers as owners then you'll have control which makes sense and seems harmless operation-wise.

**Comment by patrickkettner** [comment]
that sounds like a great way to proceed - thanks again!

**Comment by doctyper** [comment]
Re: un-publishing, these packages have been available for months now. So we are in a bit of a tough spot. Someone is likely depending on these modules, and un-publishing will probably cause their environment to break.

**Comment by patrickkettner** [comment]
im fine with just updating them to latest master. we want to cut 3.0 really soon anyway. I am pushing the last three months as `3.0.0-alpha`

**Comment by patrickkettner** [comment]
everythings been transferred. I don't believe we should remove the existing modules as people are depending on them. they should be updated with clear alpha//beta tags until we cut an official 3.0
