### ISSUE TITLE
dependency integration via npm install

### ISSUE THREAD

**Issue by ronny-springer** [Modernizr/Modernizr#1532]
At my project I'm using npm install-er to handle my client side dependencies for all libraries from GitHub. I enter `npm install --save https://github.com/Modernizr/Modernizr/archive/v2.8.3.tar.gz` (see [npm install](https://docs.npmjs.com/cli/install)) and the installation routine are not working because there is no `package.json` inside this tagged release version (see resolved issue at [NPM: ENOENT errno -4058](https://github.com/npm/npm/issues/7393)).

I, as a library consumer, ask you for a internal code arrangement including a `package.json` and `/dist` folder as a new feature which ensure to provide executable code with node package manager (compare with discussion at [Download builder at jQuery](https://github.com/jquery/jquery/issues/1691)).

There is a similar open ticket for [Add exports statement as a build option for commonjs](https://github.com/Modernizr/Modernizr/issues/1204) here. This issue cover a question about the usage of modularity and their effects like [Addy Osmani draft in his post](http://addyosmani.com/writing-modular-js/). But, I think, this is on top of my build integration issue (sharing sources as open source library).

And there is no need to use bower as an additional tool. NPM is quite powerful to do the job for one to one flat dependency integration into `/node_modules` (don't care about internal sub-dependencies e.g. `npm install --save-dev`) and it is still part of Node.js or io.js.

I'm looking forward to discuss it and add a change for next v3 release.
Best,
Ronn

**Comment by patrickkettner** [comment]
npm install is not doing to be added to previous releases. It does exist on the 3.0pre/alpha releases, and will continue to do so. I would consider it production ready.

We cannot check in a `dist` version of the repo, because there are several hundred thousand combinations possible. Instead we have a `bin` available when you npm install, as well as a node api.

cheers!

**Comment by patrickkettner** [comment]
Actually, im a little off on the combinations. Theres currently 176 `options`/`detects`, so 176<sup>176</sup>, or around 2X10<sup>24</sup>
