### ISSUE TITLE
Errors trying to use the NPM version of Modernizr

### ISSUE THREAD

**Issue by cdomkokao** [Modernizr/Modernizr#1534]
When I use NPM to get the latest version of Modernizr and put the modernizr-build.js or modernizr-build.min.js from the dist folder of the package I get the following error and my whole page doesn't load.  I googled this and didn't find any solutions.  Anyone have any ideas on what I am doing wrong?

    WebSocket connection to 'ws://./' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED
    modernizr-build.js:5781 Resource interpreted as Image but transferred with MIME type image/vnd.ms-photo: "data:image/vnd.ms-photo;base64,SUm8AQgAAAAFAAG8AQAQAAAASgAAAIC8BAABAAAAAQAA…AAAAAAAAAkw91vA07+S7GFPXd2jckNV01QSE9UTwAZAYBxAAAAABP/gAAEb/8AAQAAAQAAAA==".modernizr-build.js:5781 (anonymous function)modernizr-build.js:117 testRunnermodernizr-build.js:7931 (anonymous function)modernizr-build.js:7952 (anonymous function)

Thanks in advance.

**Comment by patrickkettner** [comment]
hey @cdomkokao!
neither are errors, perse, they are the result of sniffing for features. the first is a websockets detect, the second is sniffing for jpegxr.

You can safely ignore both of them, however are you really using jpegxr and websockets on your site? You should make sure you configure the build to _only_ build what you need to make it work.

**Comment by cdomkokao** [comment]
I am using neither of those and when I comment out the modernizr JS call my page works and when I leave it in the page breaks.  I have a very basic page so far and this seems to be preventing me from running the page.  Below is the code.  I have nothing in the styles.min.css and the application.js file and the other plugins are brand new latest versions.  If I uncomment the one line with modernizr my page content loads and if I don't the content doesn't show up and the errors show up in the console.

    <!DOCTYPE html>
    <html class="no-js" lang="en">
    <head>
         <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>TITLE GOES HERE</title>

        
        <link rel="stylesheet" href="src/css/bootstrap.min.css">
        <link rel="stylesheet" href="src/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="css/styles.min.css">

        
        <link rel="shortcut icon" href="images/favicon.ico">

        
        <script src="src/js/modernizr-build.js"></script>
        <script src="src/js/jquery.min.js"></script>
        <script src="src/js/angular.min.js"></script>
        <script src="src/js/bootstrap.min.js"></script>
    </head>
    <body>
        
        <div id="wrapper">
            <form role="form" action="#">
                <header>
                    <p>Header Goes Here.</p>
                </header>
                
                <div id="layout-base" class="">
                    <p>Body content goes here.</p>
                </div>
            </form>
        </div>
        <footer>
            <p>Footer Goes Here.</p>
        </footer>
        
        <script src="js/application.js"></script>
    </body>
    </html>

**Comment by patrickkettner** [comment]
ehlo again

> when I comment out the modernizr JS call my page works and when I leave it in the page breaks

seems to contradict 

> If I uncomment (...) modernizr my page content loads and if I don't the content doesn't show up and the errors show up in the console


But that is besides the point.

The "errors" are not errors that affect anything other than your desire to not log any errors. They **will not** have any impact on the page. It is residue from testing, and something we as a team will prevent from showing in the future, however in the mean time, you can ignore it completely.

That being said, nothing in jquery, angular, or bootstrap requires modernizr, and as a result I am not sure what you mean by the page "breaking". If I had to wager a guess, one of the bootstrap themes you are using relies on modernizr's html classes to style the page accordingly. You should go through the code and find the classes that are desired by the build, and then create a custom build either with the cli or [the downloader](http://modernizr.com/download). 

If you are unable or uncomfortable in doing that, you can download one of the older monolithic builds, the latest (and probably last of them) is 2.8.3. 

Beyond that, the issue seems to be a site specific implementation problem, so I am going to close out this issue. If you have any further questions, please open up a problem on stackoverflow.com, and tag it with modernizr. I follow it religiously, and will be more than happy to help you over there.

good luck!

**Comment by cdomkokao** [comment]
Ok, so maybe I was confusing in my last comment.  I was saying that if I leave the script reference for modernizr in, my page content disappears.  When I take out the reference my page content shows up.

That being said, I found the problem and I am surprised that no one else has this problem.  In some of the content that is put into the head of the page when the page runs, there is a class "hidden" being put on.  Not sure why this would be put on as a detected feature.  This is picked up by the bootstrap css core code and the entire HTML tag is hidden.  Do you know of a way to get rid of whatever it is that is printing out the .hidden?

**Comment by patrickkettner** [comment]
@cdomkokao that is there because you are using a full build. [hidden is a detect](https://github.com/Modernizr/Modernizr/blob/master/feature-detects/dom/hidden.js)

you _really_ need to use a custom build. Its probably several orders of magnitude larger than you actually need it to be.

**Comment by cdomkokao** [comment]
The problem is that I am trying to use NPM include it as a node_module for my project.  Is there not a way of getting an older version through NPM or excluding things in the NPM syntax?  I tried getting the 2.x version but only the 3.x version can be obtained this way.

I also tried using my gulp script to get a different version because there is a project out there with gulp for modernizr but that didn't work quite right either.

Any suggestions?

Thank you for your quick response btw.  Out of all of the git repos out there you are by far the quickest I have seen.

**Comment by patrickkettner** [comment]
>  Is there not a way of getting an older version through NPM or excluding things in the NPM syntax?

no

> I also tried using my gulp script to get a different version because there is a project out there with gulp for modernizr but that didn't work quite right either.

it should, you should open up an issue on gulp-modernizr. 

We are not even checking in a modernizr file into npm, just the builder. How are you actually getting the modernizr.js file? All you should be doing is adding a json config with it and bobs your uncle, you are in perf heaven

**Comment by cdomkokao** [comment]
"modernizr": "3.0.0-alpha",

Or 

    "modernizr": "latest",

in my package.json loads up the full package and then within the dist folder I get modernizr-build.js and modernizr-build.min.js.

What do you mean add a json config?  Were you meaning the package.json or something else?

I did a work-around but this isn't pretty:

	<style>
		html.hidden {
			visibility: visible !important;
			display: block !important;
		}
	</style>

**Comment by patrickkettner** [comment]
that dist folder should not be there, I am not sure why it is, but it will be removed asap. The npm module is not for inclusion on websites. Its to expose an api to build a version of modernizr. 

I am talking about a config for the modernizr builder. You can read more about it in the project's [readme](https://github.com/Modernizr/Modernizr/blob/master/readme.md).

you should not work around it. you should fix your build process to generate a custom build of modernizr. This would almost certainly mean fixing whatever issue you have with gulp-modernizr.

**Comment by cdomkokao** [comment]
So I would have to have someone who sets up my app run my npm install and then also run some compile commands to compile modernizr?

**Comment by patrickkettner** [comment]
no. you want it to be in your build step.

If you aren't using something like grunt or gulp, you could install a `postinstall` hook in your package.json that generate the file.

**Comment by cdomkokao** [comment]
I have gulp.  I just don't know how to build the modernizr files with it.  So you are saying that I could use the npm install to get the latest and then set up the build in my gulp build?  That would be nice if I could do that.  I would want to only have basic feature/browser detection.

Once again, thank you for all of your help with this.

**Comment by patrickkettner** [comment]
you should use gulp modernizr. It does what you are wanting to be done. If you are having an issue with it - please open an issue on that repo.

**Comment by patrickkettner** [comment]
its more than a pleasure to help you with the problem - cheers!

**Comment by cdomkokao** [comment]
Ok sounds good.  I will give that another shot and see if I can work that out.

**Comment by patrickkettner** [comment]
godspeed!
