### ISSUE TITLE
Uncaught ReferenceError: define is not defined

### ISSUE THREAD

**Issue by isarmstrong** [Modernizr/Modernizr#1538]
The latest V3 beta is giving me this error when called into an otherwise blank file. Identical errors in Chrome & Firefox. Options selected seem not to matter.

```
Uncaught ReferenceError: define is not definedmodernizr.v3.js:25
    (anonymous function)modernizr.v3.js:25
    (anonymous function)
```

Using: http://pastebin.com/A0D853Zd

Calling into the head as:
```
<script type="text/javascript" charset="utf-8" src="library/js/modernizr.v3.js"></script>
```

**Comment by patrickkettner** [comment]
hm, thats really strange. there isn't even a `define` in that file...

that being said, I just updated the builder on v3.modernizr.com - can you try generating it again?

**Comment by isarmstrong** [comment]
That did it.

Last time around the minified code was all one giant comment as well; there
was a typo somewhere.

Thanks!

**Comment by patrickkettner** [comment]
sorry about that!

**Comment by isarmstrong** [comment]
I'm actually still getting the error. Here's an example on a page I'm doing
a PSD conversion on for a client.
http://staging.imperativeideas.com/video/

It's not actually affecting anything and clearly the check is working - but
it's throwing the error.

Is this "Designer has a case of the Fridays" error or code error?

**Comment by SlexAxton** [comment]
I also saw this last night. Seems like the regex to strip that broke/got
removed.

**Comment by patrickkettner** [comment]
ah - see the error now. updating momentarily.

**Comment by patrickkettner** [comment]
@isarmstrong - how are you generating your code? node or browser? if in browser - which?

**Comment by patrickkettner** [comment]
nevermind! issue existed in minified builds. #1542 fixes it

**Comment by isarmstrong** [comment]
Beat me to it by about 30 seconds. Was at a late lunch :)

Thanks!

**Comment by patrickkettner** [comment]
fix on v3.modernizr.com - super sorry about that!

**Comment by nabokov-ef** [comment]
I still get this error. I downloaded a custom build with the only one feature detection -- HTML5 Video.

**Comment by patrickkettner** [comment]
How did you do it otherwise?

**Comment by nabokov-ef** [comment]
I just use the build from v3.modernizr.com (if I understand your question).

**Comment by patrickkettner** [comment]
oh, im sorry. I forgot the difference between the two urls. totally my misunderstanding. 

can you provide the build url that you are seeing the issue with?

**Comment by nabokov-ef** [comment]
I chose the same option (HTML5 video on modernizr.com/download) and got the link: blob:https%3A//modernizr.com/2cc28764-5431-4a02-9ee3-3a1d3e97bdf6
I cannot ensure that this is the code which did not work today, becase now I do not see 'define'. I am not at work PC to run it.

**Comment by patrickkettner** [comment]
Could you give the link the the build? It's in the file, or just the URL since it is autouodated

**Comment by nabokov-ef** [comment]
Now I cannot reproduce the bug. The code which I get from modernizr.com/download also works. Sorry to disturb you.

**Comment by mrhota** [comment]
I'm seeing this on both v3.modernizr.com and modernizer.com.

Selecting the development build on either site produces source with the call

```
define("test/network/beacon", function(){});
```

**Comment by staimanovo** [comment]
there is the same error again, in the latest 3.4.0 version, minified or not:
- "ReferenceError: define is not defined" (modernizr-3.4.0.js:30:1)
line 29, column 1, code: "define("test/network/beacon", function(){});"

**Comment by brongineers** [comment]
confirm that error in  * modernizr v3.5.0.*
and that is happening in firefox only

**Comment by kireevevgenii** [comment]
Hello! I have the same problem Uncaught ReferenceError: define is not defined. Yesterday i installed modernizr by using terminal with help of bower manager. After the install i did not find the modernizr.js file inside of modernizr folder where is usually being. But i found its a little bit deeper in src folder. Please can you help me how can i fix this bug?

**Comment by rejas** [comment]
HI @kireevevgenii did you also have "beacon" as a test in your config? And how did you call bower? (The file in the src folder shouldnt be used btw, normally you find your build in the dist folder).

Anyway, regarding the beacon issue @brongineers & @staimanovo I openend an issue in the websites repo, since it seems that it is a problem there an dnot in the modernizr code itself: https://github.com/Modernizr/modernizr-neue/issues/126. or did you experience the error also with self build modernizrs?

**Comment by fabricetheytaz** [comment]
The problem still seems to be present :-( I have selected all the tests except Beacon API and it works, but if I add the Beacon API test it no longer works (Uncaught ReferenceError: define is not defined)
Build > Copy to Clipboard or Build > Download
