### ISSUE TITLE
Custom build link is not working :(

### ISSUE THREAD

**Issue by nico3333fr** [Modernizr/Modernizr#1546]
Dear all,

when I generate a custom build, Modernizr website provides a link to get it back on Modernizr website. It was really useful if I needed to update my build.

![modernizr](https://cloud.githubusercontent.com/assets/2578321/6480343/1ae1e856-c253-11e4-87ca-647f520470ee.png)

If you copy/paste this link in a new window, it is not working: all checkboxes (flexbox, etc. in this example) are not checked. http://modernizr.com/download/#-flexbox-csstransitions-svg-touch

I hope it will be easy to fix, it is a small bug, but very annoying :(

EDIT : it seems to be working on Chrome, but not on Firefox. Could you fix it anyway ?

Thanks for reading,
Nicolas

**Comment by patrickkettner** [comment]
fixed in [modernizr.com/c21eb](https://github.com/Modernizr/modernizr.com/commit/c21ebb)

**Comment by nico3333fr** [comment]
Confirmed. Thanks a lot :+1:
