### ISSUE TITLE
So... which tests are async?

### ISSUE THREAD

**Issue by baloneysandwiches** [Modernizr/Modernizr#1547]
I would love to see some documentation of the new ".on" syntax for async tests. If this is what the async tests require, it would great to see a list of which tests are async.

Possibly a little icon indicator for each test in the build tool to indicate async? thanks!

**Comment by patrickkettner** [comment]
thats on the plan for the new site, in the mean time [here are the async tests](https://github.com/Modernizr/Modernizr/search?utf8=%E2%9C%93&q=addasynctest)

**Comment by baloneysandwiches** [comment]
Thanks!
