### ISSUE TITLE
SVG inline test false positive

### ISSUE THREAD

**Issue by eltonmesquita** [Modernizr/Modernizr#1552]
Recently i've gone through some false positive with the inline SVG test and found about using SVGRect for testing SVG support. So I've tested Modernizr and SVGRect to see which one is more reliable.
I've even written about it [here](http://codepen.io/eltonmesquita/blog/loading-inline-svg/) (I'm going to update it soon).

The problem is both methods give false positives in different browsers. I've tested both tests in some browsers and you can see the results and the tests [here](http://codepen.io/eltonmesquita/pen/GgXbvo/).

Although in my data both methods returned false positive in just one browser each, another Samsung device returned the wrong result in previous tests with Modernizr, but I decided to not include it because I don't have access to it anymore and can not retest. It seems like it is a problem related to some [Chromia](http://www.quirksmode.org/blog/archives/2015/02/counting_chromi.html) browsers that are shipped with some vendor's Android devices. The AOSP browser (the official Android browser) doesn't seem to have this issue.

This situation can be a problem, depending on the user target.

I was thinking about using both methods to try to detect the inline SVG support in a more relaible way, but I couldn't find a way.

Any thoughts on that?

**Comment by patrickkettner** [comment]
So you are suggesting we return true if both methods work properly?

**Comment by eltonmesquita** [comment]
If we do that, we would return less accurate results, but it would be at least false negatives and that is "less bad". It would be a trade-off, but more important this situation should be clear to the users, no matter what is the solution.

What do you think? Would it be a good trade-off?

**Comment by patrickkettner** [comment]
Wanna PR the change?
