### ISSUE TITLE
@pp-koch versus input types: worth incorporating?

### ISSUE THREAD

**Issue by jokeyrhyme** [Modernizr/Modernizr#1555]
@pp-koch just posted an excellent if not disturbing article on input type support research he undertook: http://www.quirksmode.org/blog/archives/2015/03/better_modern_i.html

Is it worth adding the "hello world" test to Modernizr's input type tests? Is there anything else we should be doing in light of his research results?

**Comment by patrickkettner** [comment]
unless I misread it, its what we already do, we just use a smiley rather than 'hello world'.

**Comment by jokeyrhyme** [comment]
Yep, this is just me having a moment. :) Carry on!
