### ISSUE TITLE
Modernizr is free JS, but LibreJS detects it as otherwise

### ISSUE THREAD

**Issue by kozross** [Modernizr/Modernizr#1556]
I am using Modernizr as part of the [Octopress blogging framework][1], and we are trying to address its issues with [LibreJS][2]. One these is Modernizr, which, even though I can see is [free software][3], does not declare itself as such to LibreJS. Could this be fixed?

[1]: https://github.com/imathis/octopress
[2]: https://www.gnu.org/philosophy/javascript-trap.html
[3]: https://www.fsf.org/about/what-is-free-software

**Comment by patrickkettner** [comment]
howdy @kozross!

I haven't ever heard of librejs, what issues does it detect with modernizr?

**Comment by kozross** [comment]
Hi @patrickkettner! [LibreJS][1] is a program meant to address the problem of nonfree Javascript. The problem it detects specifically is this:

NONTRIVIAL: an open method similar to xhr.open is used
http://retro-freedom.nz/javascripts/modernizr-2.0.js

This can be seen by navigating to [my blog][2] with LibreJS enabled.

[1]: https://www.gnu.org/software/librejs/
[2]: http://retro-freedom.nz/

**Comment by stucox** [comment]
LibreJS is a bit like cutting off your nose to spite your face tbh. Modern apps use heavy use of script loading and minification (2 things which LibreJS doesn’t immediately “trust”), **to improve the experience for users**. Most aren’t trying to take away your civil liberties or sell your children.

---

Anyway, with my opinions out the way, for Modernizr to not fall into LibreJS’ net it looks like we’d have to (a) wrap our licence in `@licstart` / `@licend` and (b) add a `@source:` comment pointing to an unminified copy.

The latter may not be straight forward, as Modernizr allows a near infinite number of possible custom builds. It would have to be up to developers using Modernizr in their sites to create & serve both minified & unminified builds and populate the `@source` URL themselves. Alternatively, devs could [serve the licence information appropriately](http://www.gnu.org/software/librejs/free-your-javascript.html#step3)… I don’t think Modernizr can do this for them.

Happy to accept a PR for (a), and discuss any ideas you might have about (b)?

**Comment by stucox** [comment]
Does a `@source` URL have to point directly to an unminified JS file? Or just somewhere where it can be obtained? We could just link to e.g. modernizr.com/download#-whatever-build-options, which is a reliable URL where an unminified equivalent can be obtained (you’d have to click “build” to get it – maybe that’s ok).

**Comment by kozross** [comment]
@stucox First-off, thank you for putting in effort to resolve an issue with which you personally disagree - I appreciate that.

I can put up a PR with the @licstart and @licend stuff (it'll take me a little while), and I am asking the LibreJS people about your second question.

**Comment by kozross** [comment]
@stucox I've asked the folks at LibreJS, and your solution for the source code is considered fine. LibreJS doesn't actually do any parsing of what's held at the link - it's provided for a human reader only.

As far as minimization is concerned, there appears to be a way to [deal with it][1] while not making LibreJS unhappy.

[1]: https://www.gnu.org/software/librejs/free-your-javascript.html

I'll put up the pull request as soon as I can and figure out how (new to JS)..

**Comment by patrickkettner** [comment]
@kozross - hows it going?

**Comment by kozross** [comment]
@patrickkettner To be honest, it's not - I've been buried in a buch of other, unrelated projects.

**Comment by patrickkettner** [comment]
No problem at all. Considering the low priority, and the fact this can be handeled by an individual site using the html weblabels, I am going to close this out for now. 

PRs are always welcome, however :)
