### ISSUE TITLE
v3 minifed download contains syntax error

### ISSUE THREAD

**Issue by ujay68** [Modernizr/Modernizr#1559]
The current minified code download from http://v3.modernizr.com/download/#- ends like this (note the comma before the final closing brace):

```javascript
… Modernizr=Modernizr,}(window,document);
```

The non-minified version http://v3.modernizr.com/download/#--dontmin works fine:

```javascript
…
// Leak Modernizr namespace
  window.Modernizr = Modernizr;


;

})(window, document);
```

**Comment by patrickkettner** [comment]
crap. super sorry about that. the regex that strips out the define is a bit different with the uglified version. PRed a fix, just waiting for it to turn green
