### ISSUE TITLE
cssvwunit/cssvhunit tests give false negative in some browser zoom/widths

### ISSUE THREAD

**Issue by chearon** [Modernizr/Modernizr#1569]
To reproduce (all latest browsers except Safari, more on that below):
1. Set your browser to 961px width
2. Zoom to 110%
3. http://jsfiddle.net/6L7n2243/show/

`window.innerWidth` and `window.innerHeight` appear to be _rounded_ by the browser based on the calculated viewport size after a zoom, rather than _floored_ like we're used to.

If the window is 961px wide and the zoom is 110%, the viewport width is 961 \* 1/1.1 = 873.63, and the innerWidth is 874. The test div with 50vw would then be 873.63/2 = 436.815. Which when floored is one less than innerWidth/2 because `floor(round(n)/2) == floor(n/2)` is not true for every n. There are several other zoom level/window width combinations to make this happen.

Problem is, Safari DOES floor innerWidth and innerHeight (which I think is right). That makes it impossible to just do `round(testDivWidthFloat * 2) == innerWidth` which would be really nice. The other solution I'm exploring is using `getComputedStyle(document.documentElement).width` which gives you the fractional value of the viewport, rather than `innerWidth`, but I can't find enough information to know if that is reliable or not.

**Comment by RealMakAttak** [comment]
What is going on with this?
