### ISSUE TITLE
Instal problem with Win 7

### ISSUE THREAD

**Issue by potamustnt** [Modernizr/Modernizr#1575]
Instal failed with the following:
Script: //////modernizr2_8_3\modernizr.latest.js
Line:25
Char 1
Error 'window' is undefined
Code 800A1391
Source MS JScript runtime error.

Does anybody have a workaround??

**Comment by patrickkettner** [comment]
@potamustnt what is the build you are using? Do you have a page where this is happening? What is the browser you are using?

**Comment by potamustnt** [comment]
Patrick, this is the only version data that I have other than the browser, which is IE 11    I also use Startpage and am not sure which I was using when I visited the site; it may well have been startpage.


* 

Hi, Great concept, but I tried to download the developer version into Windows 7 and got the following error

Script: //////modernizr2_8_3\modernizr.latest.js
Line:25
Char 1
Error 'window' is undefined
Code 800A1391
Source MS JScript runtime error.

Do you have a workaround??

**Comment by patrickkettner** [comment]
what site are you running this on? What is Startpage?

**Comment by potamustnt** [comment]
Patrick, Startpage is a portal that blocks your IP address; I use it for all my internet access, but that should not affect the download. My development website is being developed in Visual Studio 2010, and it is running from a file on my laptop. 

 

Peter

**Comment by patrickkettner** [comment]
Is there any chance you could post the site somewhere like jsbin or codepen? There really isn't anything to go on based on what you have mentioned thus far.

**Comment by potamustnt** [comment]
Patrick, thanks for your help. I finally managed to get the VS2010 SP1 to load and now I have some level of HTML5/CSS3 working so I think I will stick with that. 

 

Thanks for your help and good luck to you

 

Peter

**Comment by patrickkettner** [comment]
cheers!
