### ISSUE TITLE
CSS pseudo class :target not working properly in IE if Modernizr is loaded after styles

### ISSUE THREAD

**Issue by smohadjer** [Modernizr/Modernizr#1577]
In IE 9-11 if Modernizr is loaded after css rules using :target pseudoclass will be ignored on page load. Refreshing page seems to fix the problem. 

Correct behavior (modernizr loading before css):
http://sandbox.saeidmohadjer.com/css3.target.modernizr.before.html#test

Wrong behavior (modernizr loading after css):
http://sandbox.saeidmohadjer.com/css3.target.modernizr.after.html#test

It seems to be a bug of IE rather than Modernizr, but if it can be fixed in Modernizr that would be nice.

**Comment by ryanseddon** [comment]
Oh weird can you try a v3 build

http://v3.modernizr.com/download/#-applicationcache-audio-backgroundsize-borderimage-borderradius-boxshadow-canvas-cssanimations-csscolumns-cssgradients-cssreflections-csstransforms-csstransforms3d-csstransitions-draganddrop-flexbox-flexboxlegacy-fontface-generatedcontent-geolocation-hashchange-history-hsla-indexeddb-inlinesvg-localstorage-multiplebgs-postmessage-rgba-sessionstorage-smil-svg-svgclippaths-textshadow-touchevents-video-webgl-websockets-websqldatabase-webworkers

That should be the same as your tests. I created a testcase that seems to work in IE11 can you verify that this is the same as your test http://jsbin.com/mizapufaxu/2/

**Comment by smohadjer** [comment]
Yes, V3 indeed resolves the problem with IE. Do you know when it will become an official release?

**Comment by patrickkettner** [comment]
very, very soon. its the sole thing I am doing in my free time until it ships.

**Comment by smohadjer** [comment]
Rumors are that you have been saying that for a year! ;)

**Comment by patrickkettner** [comment]
feel free to pitch in
