### ISSUE TITLE
Untrue statement: "And remember, none of your users view your site in more than one browser; It’s okay if it looks and acts differently."

### ISSUE THREAD

**Issue by PhilT** [Modernizr/Modernizr#1584]
http://v3.modernizr.com/docs/#polyfills

I think it's fine to say, "It’s okay if it looks and acts differently" but saying users only use your site on one browser is a bit short-sighted. People use laptops, desktops, work computers, tablets and mobile phones and the browsers can all be different.

It's minor but thought I'd mention it.

**Comment by patrickkettner** [comment]
Hey @PhilT!

The docs are currently be rewritten from scratch, and as such this line won't be included. I will 100% make sure the intent is clearer, though.

thank you so much for raising this!
