### ISSUE TITLE
unicode-range tests returns false negative on firefox beta in linux

### ISSUE THREAD

**Issue by ryanseddon** [Modernizr/Modernizr#1588]
Firefox beta (v38) now supports unicode ranges that doesn't require enabling a flag. 

Our unicode test returns a false negative because linux doesn't have arial and fallsback to the monospace font.

**Comment by patrickkettner** [comment]
so, `layout.css.unicode-range.enabled` is actually false in Firefox 38 in sauce. But is _is_ true in firefox 39.

**Comment by patrickkettner** [comment]
In addition, the caniuse tests actually seem to be failing in firefox 39. I think this may actually be a false false negative

![image](https://cloud.githubusercontent.com/assets/465414/7555774/be0c2398-f723-11e4-9773-28292fb9939e.png)

**Comment by ryanseddon** [comment]
Firefox 39 does support unicode-ranges but i think it has bugs. However this issue will still false negative in FF40 on linux due to the nature of the test using a font that doesn't exist on linux.

**Comment by patrickkettner** [comment]
firefox 38 has unicode-range enabled as well. it seems that it is enabled on dev and disabled later on down the release train.

"arial" doesn't really mean arial. in actually loads `LIberation Sans` on (most) linux if you were to set it to set its `font` property directly. This is one of the reasons its a "web safe" font. 

Our test _is_ failing in firefox 40, but so is every unicode-range demo I can find (including [caniuse](http://tests.caniuse.com/?feat=font-unicode-range)).

**Comment by ryanseddon** [comment]
But that's not the case in FF aurora (v39) our test works and passes support on windows & osx but not on linux because arial isn't on there. So the test renders all characters in monospace.

Linux:
![bs_linux_firefox_39 0 aurora](https://cloud.githubusercontent.com/assets/143402/7603525/4dc6aa02-f978-11e4-96a2-263507fdb906.png)

OSX:
![bs_macyos_firefox_39 0 aurora](https://cloud.githubusercontent.com/assets/143402/7603527/4e1f25ec-f978-11e4-91b9-764f07680920.jpg)

Windows:
![bs_win8_firefox_39 0 aurora](https://cloud.githubusercontent.com/assets/143402/7603526/4e1e723c-f978-11e4-8739-f85fff987fb7.jpg)

**Comment by patrickkettner** [comment]
Set arial as the font-family on the Linux browser before unicodeRange
