### ISSUE TITLE
tests['csstransforms3d'] return false on maxthon browser

### ISSUE THREAD

**Issue by HyperKat** [Modernizr/Modernizr#1589]
Hello, 
the tests['csstransforms3d'] function return false on MAxthon browser, but it is -webkit-transform3d()...
when i remove the if(Modernizr.csstransforms3d) then my  script works on Maxthon cloud browser to...

here useragent:
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Maxthon/4.4.5.1000 Chrome/30.0.1599.101 Safari/537.36

**Comment by patrickkettner** [comment]
@HyperKat what build are you using? I am testing mater in Maxthon Version 4.1.3.5000 on OS X and `csstransform3d` is `true`

**Comment by HyperKat** [comment]
i've yusing the last build v2.8.3

ps wow thats a very fast answer ;)

**Comment by HyperKat** [comment]
ok perhaps the new version of maxthon has the propblem

**Comment by patrickkettner** [comment]
what version of Maxthon are you on? I just updated to Version 4.5.2, and am still getting it passing

![image](https://cloud.githubusercontent.com/assets/465414/7444414/f5d81078-f14e-11e4-9695-3cf1d4743e88.png)

**Comment by HyperKat** [comment]
Maxthon/4.4.5.1000

**Comment by HyperKat** [comment]
this.support = Modernizr.csstransforms3d;
        alert(this.support);
        if(this.support) {
            this._init();
        }
![maxthon](https://cloud.githubusercontent.com/assets/6559772/7444435/8226efa8-f182-11e4-8c39-86363beae6cb.png)

**Comment by patrickkettner** [comment]
digging into it a bit more, seems possible you may be hitting [this](https://github.com/Modernizr/Modernizr/blob/f250324f6e23075af1d53be289259c45db34bff6/feature-detects/css/transforms3d.js#L17-L20). Can you double check that 3d transforms are actually working? [heres a good quick test](http://www.keithclark.co.uk/labs/css-fps/nojs/)

**Comment by HyperKat** [comment]
ah ok i've ovreaded this, i'm sorry
thank you

**Comment by patrickkettner** [comment]
no worries! thats why we test for it :]
