### ISSUE TITLE
Modernizr command line interface is broken

### ISSUE THREAD

**Issue by barrysteyn** [Modernizr/Modernizr#1596]
Hi There

If using modernizr on the command line, the -c option is ignored. Look at https://github.com/Modernizr/Modernizr/blob/master/bin/modernizr#L147

I think the error is there, because whatever one gives an input gets overridden by setting configPath to that value.

Thanks so much for modernizr btw - really love using it.

**Comment by patrickkettner** [comment]
well that is embarrassing... 

thanks @barrysteyn!

**Comment by barrysteyn** [comment]
No problem @patrickkettner! I have been a professional software engineer for close on 20 years now, and I still make those mistakes (many times) :)

**Comment by barrysteyn** [comment]
Hi @patrickkettner 

Unfortunately, we are not out of the woods yet! Making the change in cc5340e results in an exception. The reason seems to be that the config one passes in the with -c option is expecting commonjs, not pure json. Try it and see.

**Comment by patrickkettner** [comment]
I tried it with

```json
{"feature-detects": ["test/ambientlight"]}
```

and it is working for me - can you give a bit more detail?

**Comment by barrysteyn** [comment]
Ignore this - I am sorry. I did not realize that Node forces one to use .json for json objects in commonjs. Sorry, please close this issue, the fix works! Sorry again.
