### ISSUE TITLE
Fixed issue

### ISSUE THREAD

**Issue by erichonkanen** [Modernizr/Modernizr#1600]
Hello,

I was just playing with V3 downloaded from the site (with video autoplay only) and got error when attempting to load the script (ember-cli).

The issue was fixed by checking for both "feature && feature.name" and adding conditional for "feature" as below...

```
      if ( feature && feature.name ) {
        featureNames.push(feature.name.toLowerCase());

        if (feature.options && feature.options.aliases && feature.options.aliases.length) {
          // Add all the aliases into the names list
          for (aliasIdx = 0; aliasIdx < feature.options.aliases.length; aliasIdx++) {
            featureNames.push(feature.options.aliases[aliasIdx].toLowerCase());
          }
        }
      }

      if ( feature ) {
        // Run the test, or use the raw value if it's not a function
        result = is(feature.fn, 'function') ? feature.fn() : feature.fn;
      }
```

**Comment by patrickkettner** [comment]
@erichonkanen was this intended to be a PR?

**Comment by erichonkanen** [comment]
@patrickkettner well I can, I havent contributed to this project so wasn't sure which branch to push to for v3?

**Comment by patrickkettner** [comment]
Master.

that being said, feature.name should ALWAYS exist. What feature did it not?

**Comment by erichonkanen** [comment]
@patrickkettner it was for html5 videoautoplay... I first pulled the code off [here](http://codepen.io/anon/pen/VYoWWY?editors=00) and then just pulled the code off the main modernizr v3 site with only video autoplay selected...

**Comment by erichonkanen** [comment]
I added a debugger statement and it seemed like it was called twice, the first time feature was == 'videoautoplay', the 2nd time it was null.. Not sure why that was, it was included in /vendor/modernizr.js as part of an ember-cli project

**Comment by patrickkettner** [comment]
can you post a test case showing the issue?

On Wed, May 20, 2015 at 2:13 PM, Eric Honkanen <notifications@github.com>
wrote:

> @patrickkettner <https://github.com/patrickkettner> it was for html5
> videoautoplay... I first pulled the code off here
> <http://codepen.io/anon/pen/VYoWWY?editors=00> and then just pulled the
> code off the main modernizr v3 site with only video autoplay selected...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Modernizr/Modernizr/issues/1600#issuecomment-103978748>
> .
>



-- 
patrick

**Comment by erichonkanen** [comment]
sure, do you mean something like a jsbin?

**Comment by erichonkanen** [comment]
ps your website says "illegal arguments"! http://patrickkettner.com/

**Comment by patrickkettner** [comment]
Sure, just something showing how its broken

**Comment by patrickkettner** [comment]
Yeah, its a really old dumb inside joke

**Comment by patrickkettner** [comment]
@erichonkanen hows it goin

**Comment by erichonkanen** [comment]
whats up? sorry this is pretty old so probably should be closed...
