### ISSUE TITLE
Vide.play() not working from inside Modernizer.on('videoautoplay', function(){.. call

### ISSUE THREAD

**Issue by erichonkanen** [Modernizr/Modernizr#1601]
Hello,

I am trying to add autodetect for html5 video autoplay to my app and found Modernizr v3, however when I initiate the autoplay from inside the .on() callback, it doesn't work. I realize this is async but is there a way to make it work?

```
import Ember from 'ember'

IndexView = Ember.View.extend
  didInsertElement: ()->
    wW = Ember.$(window).width()
    $video = Ember.$('.landing-video')

    # Initiate landing video playback if the feature is supported.
    Modernizr.on 'videoautoplay', (result)->
      if result
        $player = $video[0]

        Ember.$.each Ember.$('source'), (index, value)->
          Ember.$(value).attr 'src', Ember.$(value).attr('data-src')

        $player.play()

        # Handle video ending - fix for chrome replay bug.
        $player.onended = ()->
          $player.load()
          $player.play()


export default IndexView
```

**Comment by patrickkettner** [comment]
hiya @erichonkanen!

in what way does it not work?

**Comment by erichonkanen** [comment]
@patrickkettner doh looks like for some reason Ember.$ (embers jquery object) isn't available from inside the callback.. switching to regular jquery seemed to do the trick.. also I had to call $player.load() first which I hadnt done before.. works now thx!
