### ISSUE TITLE
Support for Safari 9.0 Webkit Force Touch Trackpad Event Detection

### ISSUE THREAD

**Issue by KraigWalker** [Modernizr/Modernizr#1606]
Safari 9 will add support for Force Touch Trackpad events, as seen in new Macbook models. From a developer perspective, It may be good to use Modernizr to test for such support on the user's device to provide an enhanced experience.

> Use event.webkitForce to create interactivity with the following events and constants.
>
> webkitmouseforcewillbegin
> webkitmouseforcedown
> webkitmouseforceup
> webkitmouseforcechanged
> Constants:
> MouseEvent.WEBKIT_FORCE_AT_MOUSE_DOWN
> MouseEvent.WEBKIT_FORCE_AT_FORCE_MOUSE_DOWN

https://developer.apple.com/library/safari/releasenotes/General/WhatsNewInSafari/Articles/Safari_9.html#//apple_ref/doc

Right now the feature is very young, and of course the API may change on the way to OSX 10.11 being released, but may be good to get in if Force touch becomes the norm on Apple Devices.

**Comment by patrickkettner** [comment]
Hey @KraigWalker!

Would you want to create a PR for it?

**Comment by KraigWalker** [comment]
I would if you'd consider it's worth having :smile:

**Comment by patrickkettner** [comment]
well, im not really for the feature because I think they should use point-events. But im all for detecting something.

**Comment by patrickkettner** [comment]
fixed with #1613
