### ISSUE TITLE
object-fit is not usable as Modernizr.object-fit cause of reserved word object and -

### ISSUE THREAD

**Issue by timomayer** [Modernizr/Modernizr#1607]
object-fit is not usable as Modernizr.object-fit cause of reserved word object and -.
This can be roundworked with Modernizr['object-fit'] but this syntax is not checked by grunt-modernizr and therefor the test will not be added to modernizr :(
Can this pls be fixed by renaming this test to just: Modernizr.objectfit pls?

**Comment by patrickkettner** [comment]
hi @timomayer!

I am not sure I understand what you are saying. The property used for object-fit [is `objectfit`](https://github.com/Modernizr/Modernizr/blob/30d6322256ce2bc1dd669e9980d2dba7876fcdb2/feature-detects/css/objectfit.js#L5).

Could you elaborate on the problem?

**Comment by timomayer** [comment]
It is? For me it says Modernizr.objectfit is not defined and object-fit seems to work, strange will Look into it again and post my feedback
________________________________
Von: patrick kettner<mailto:notifications@github.com>
Gesendet: ‎19.‎06.‎2015 19:01
An: Modernizr/Modernizr<mailto:Modernizr@noreply.github.com>
Cc: Timo Mayer<mailto:timo.mayer@virtual-identity.com>
Betreff: Re: [Modernizr] object-fit is not usable as Modernizr.object-fit cause of reserved word object and - (#1607)


hi @timomayer<https://github.com/timomayer>!

I am not sure I understand what you are saying. The property used for object-fit is objectfit<https://github.com/Modernizr/Modernizr/blob/30d6322256ce2bc1dd669e9980d2dba7876fcdb2/feature-detects/css/objectfit.js#L5>.

Could you elaborate on the problem?

**Comment by timomayer** [comment]
Tested it again for me the objectfit test only works with Modernizr['object-fit'] NOT Modernizr.objectfit nor Modernizr.object-fit (last one throws JS error)

**Comment by patrickkettner** [comment]
Can you provide some code showing this?

**Comment by lhwparis** [comment]
I am using a modernizr build from modernizr.com with the objectfit test. in the modernizr.js file this gets added for the custom test: 

Modernizr.addTest('object-fit',
	!!Modernizr.prefixed('objectFit')
);;

in my js code i try Modernizr.objectfit and it is undefined
when i use Modernizr.object-fit it complaints about the reserved word object followed by a -.
when i use Modernizr['object-fit'] i get a valid test result (true/false)

see jsbin here: http://jsbin.com/xukihoxizo/edit?html,js,console,output

**Comment by timomayer** [comment]
I am using a modernizr build from modernizr.com with the objectfit test. in the modernizr.js file this gets added for the custom test: 

Modernizr.addTest('object-fit',
	!!Modernizr.prefixed('objectFit')
);;

in my js code i try Modernizr.objectfit and it is undefined
when i use Modernizr.object-fit it complaints about the reserved word object followed by a -.
when i use Modernizr['object-fit'] i get a valid test result (true/false)

see jsbin here: http://jsbin.com/xukihoxizo/edit?html,js,console,output

**Comment by patrickkettner** [comment]
Ah, apologies. You should [use 3.0](http://new.modernizr.com/download), where we have fixed this.

cheers!

**Comment by timomayer** [comment]
mh thats not a real option for me since its a large website and there is no stable release for modernizr 3 till now. and i am not sure if there is a stable version for grunt-modernizr for modernizr 3 and we rely on grunt-modernizr. so when will be modernizr3 and grunt-modernizr be ready?

**Comment by patrickkettner** [comment]
grunt-modernizr supports 3

**Comment by timomayer** [comment]
doesnt answer my other questions about a stable release for modernizr3 :( but ok... you are working on it for years now :( seem to me like the duke nukem forever of web frameworks ;) any timeframe for a stable release?

**Comment by patrickkettner** [comment]
"soon"
its taken so long because you haven't contributed anything :p
we have to finish the documentation/website. The code for 3.0 should not change between now and the release

**Comment by timomayer** [comment]
thanks ;) i try to contribute some tests for v4 :)
