### ISSUE TITLE
wordpress comment form is not submiting due to modernizer

### ISSUE THREAD

**Issue by Sagar37** [Modernizr/Modernizr#1614]
Hi there,
I ran into weird problem.i have included modernizer in my web pages everything was working fine except wordpress comment form. when i removed morernizr script everything work fine. here is link of comment page   (http://warkpress.com/great-square-box/).

**Comment by patrickkettner** [comment]
Hi there - I saw [this](http://wordpress.stackexchange.com/questions/195036/comment-form-is-not-submitting-due-to-modernizr-js). As a result, i'm gonna assume this was fixed. 

Lemme know if I am wrong and we can reopen it
