### ISSUE TITLE
Open Code of Conduct

### ISSUE THREAD

**Issue by ryanseddon** [Modernizr/Modernizr#1615]
The TODO group released the [Open Code of Conduct](http://todogroup.org/blog/open-code-of-conduct/) today and I think it would make sense for Modernizr to adopt this too.

We can simply link to the [template](http://todogroup.org/opencodeofconduct/#Modernizr/conduct@modernizr.com) or we can create a page on the new website with the copy.

**Comment by patrickkettner** [comment]
we've been lucky in not _needing_ one, but I think having one is a great idea. 200% for it.

**Comment by patrickkettner** [comment]
@ryanseddon sup?

**Comment by ryanseddon** [comment]
Looks like the issues raised with this project have been resolved. I was waiting for that to happen before continuing.
