### ISSUE TITLE
How to use Modernizr v3?

### ISSUE THREAD

**Issue by mattdesl** [Modernizr/Modernizr#1616]
Trying to use Modernizr3 and unfortunately I can't really figure it out. Installing from `npm` does not work:

```js
var modnernizr = require('modernizr')
```

Cloning and installing the repo, then running `./bin/modernizr` leads me to the following error:

```sh
{ [AssertionError: missing path]
  name: 'AssertionError',
  actual: undefined,
  expected: true,
  operator: '==',
  message: 'missing path',
  generatedMessage: false }
```

**Comment by patrickkettner** [comment]
Hiya @mattdesl!

Can you give more details as to what you are doing? What is the exact command you are using to run the modernizr bin?

**Comment by tscholl2** [comment]
I got the same error when I ran `$ ./bin/modernizr` without any arguments. Then I read the help and you need to pass in the config file manually. So use this `$ ./bin/modernizr -c lib/config-all.json`.

Sometimes it helps to read :)
