### ISSUE TITLE
Modernizr.hasEvent('focusin') returns false in browsers which support this event

### ISSUE THREAD

**Issue by dfilatov** [Modernizr/Modernizr#1617]
It returns `false` at least in Chrome and Safari which have support of this event.

**Comment by dmethvin** [comment]
The Chrome event is there but isn't compliant with W3C DOM Events Level 3.
https://github.com/jquery/jquery/blob/master/src/event.js#L814-817

 In addition they seem to have made it impossible to detect, the normal focusin check doesn't work.
https://github.com/jquery/jquery/blob/master/src/event/support.js#L5

**Comment by ryanseddon** [comment]
Thanks for the response @dmethvin! 

I'm going to close this off. @dfilatov if you can figure out a way to detect it we'd very much appreciate a PR.
