### ISSUE TITLE
jp2 / jpeg2000

### ISSUE THREAD

**Issue by EricWVGG** [Modernizr/Modernizr#1618]
Greatly appreciate seeings tests for WEBP and JPEGXR. Why no support for JPEG 2000, though?

**Comment by patrickkettner** [comment]
Because we were waiting on you to PR one :p

Would you be willing to?

**Comment by EricWVGG** [comment]
challenge accepted

**Comment by patrickkettner** [comment]
@EricWVGG hows it goin?

**Comment by EricWVGG** [comment]
Hiya. I have a test that is cycling through PhantomJS fine, but I hit a wall with testing in browser. 

The instructions here say…
grunt build
serve .
visit <url>/test

I don't have this "serve" command, and "grunt serve" doesn't work either.

**Comment by SlexAxton** [comment]
npm install -g serve

Will get you that. Python simpleserver works too. Anything really to serve
up that directory in a browser works.

**Comment by EricWVGG** [comment]
Awesome, thank you. 

https://github.com/EricWVGG/Modernizr

I’m a bit new to this sort of contribution so thanks in advance for any feedback.

**Comment by patrickkettner** [comment]
@EricWVGG quick scan looks good - can you [create a pull request](https://help.github.com/articles/creating-a-pull-request/) to get it started officially?

**Comment by patrickkettner** [comment]
@EricWVGG I pulled in your changes manually and merged them. Thanks for creating the detect!
