### ISSUE TITLE
gradient detection requires old gradient syntax

### ISSUE THREAD

**Issue by dbaron** [Modernizr/Modernizr#1621]
As reported in https://bugzilla.mozilla.org/show_bug.cgi?id=1176496#c22 , Modernizr's gradient detection depends on the old gradient syntax.  Its attempt to detect unprefixed gradients fails because it's testing legacy syntax that's only supported in prefixed form.  This means that if browsers ever remove prefixed gradients (which is seeming increasingly unlikely due to things like this), Modernizr will report that gradients are not supported.

Gradient syntax is described in https://drafts.csswg.org/css-images/#linear-gradients , and requires "to left top" rather than just "left top" in https://github.com/Modernizr/Modernizr/blob/master/feature-detects/css/gradients.js#L29

**Comment by karlcow** [comment]
And the [cross rendering test](http://codepen.io/anon/pen/OVaPpr)

1. Firefox Gecko 42.0a1 (2015-07-27)
2. Opera Blink 31.0.1889.92 (aka Chrome/44.0.2403.89)
2. Safari WebKit Version 8.0.7 (10600.7.12)

![capture d ecran 2015-07-28 a 09 05 24](https://cloud.githubusercontent.com/assets/505230/8920738/f725e476-3507-11e5-854b-06a136043a32.png)
