### ISSUE TITLE
Build with fish fails

### ISSUE THREAD

**Issue by jeromecovington** [Modernizr/Modernizr#1624]
Using [fish](http://fishshell.com/) the build seems to fail. Any idea how to get the build to succeed?
```
modernizr> ./bin/modernizr
undefined is not valid JSON.
{ [AssertionError: path must be a string]
  name: 'AssertionError',
  actual: false,
  expected: true,
  operator: '==',
  message: 'path must be a string' }
```

**Comment by patrickkettner** [comment]
its not a code failure, its a UX failure. its been patched in master, but has yet to be released.

The issue is you need to pass a config file or feature flags. use `--help` for more info

cheers!
