### ISSUE TITLE
CSS Transform properties (translate, rotate, and scale)

### ISSUE THREAD

**Issue by jonathantneal** [Modernizr/Modernizr#1625]
It probably ain’t no thing to get a test for this, right? Independent CSS Transform properties (translate, rotate, and scale) are available in Canary behind a flag.

[![Screenshot](https://pbs.twimg.com/tweet_video_thumb/CLbzTpeW8AAX3u9.png)](https://pbs.twimg.com/tweet_video/CLbzTpeW8AAX3u9.mp4)

**Comment by ryanseddon** [comment]
Oh nice, wanna do a PR?
