### ISSUE TITLE
bgsizecover test fails in IE Edge 12

### ISSUE THREAD

**Issue by tdmalone** [Modernizr/Modernizr#1626]
bgsizecover test is failing in IE Edge 12... despite the browser obviously supporting cover.

**Comment by patrickkettner** [comment]
Hey Tim!

Could you clarify what you mean by IE 12? I assume you mean Edge. If that
is the case, I am actually not replicating it.

[image: Inline image 1]

could you go into more details about what and where you are seeing what you
are seeing?

thanks!

On Wed, Aug 5, 2015 at 9:20 PM, Tim Malone <notifications@github.com> wrote:

> bgsizecover test is failing in IE Edge 12... despite the browser obviously
> supporting cover.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Modernizr/Modernizr/issues/1626>.
>



-- 
patrick

**Comment by tdmalone** [comment]
Man that was fast! Yes I was referring to Edge :)

I've set up a basic test:
http://tim.chromatix.com.au/tests/modernizrbg.html

That's just got a custom Modernizr with a few of the bg tests in it, with the classes then printed out into the body.

In Chrome 44 I get:
js backgroundsize bgpositionshorthand no-bgrepeatround no-bgrepeatspace bgsizecover bgpositionxy

In IE10 I get:
js backgroundsize bgpositionshorthand no-bgrepeatround no-bgrepeatspace bgsizecover bgpositionxy

In Edge I get:
js backgroundsize bgpositionshorthand no-bgrepeatround no-bgrepeatspace no-bgsizecover bgpositionxy

I've only just upgraded to Windows 10 so am still getting to know Edge, but I appear to be running Edge 12.10240 (user agent is `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240`)

**Comment by patrickkettner** [comment]
ah-ha!
You are testing 2.8.3, I am testing 3.0

Could you try using 3.0 and let me know if it works? If you need web ui to build it, try http://new.modernizr.com/download

**Comment by tdmalone** [comment]
OH there we go!
http://tim.chromatix.com.au/tests/modernizrbg-v3.html

Hahaha sorry, I didn't realise there was a v3 in the works!

**Comment by patrickkettner** [comment]
awesome to hear!

cheers!

On Wed, Aug 5, 2015 at 10:19 PM, Tim Malone <notifications@github.com>
wrote:

> Closed #1626 <https://github.com/Modernizr/Modernizr/issues/1626>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Modernizr/Modernizr/issues/1626#event-374863230>.
>



-- 
patrick
