### ISSUE TITLE
Firefox touch 

### ISSUE THREAD

**Issue by sihuiDG** [Modernizr/Modernizr#1628]
in 2.8.3 or 3.0 Modernizr sees firefox 39 desktop as touch device, in OSX and Win7

**Comment by patrickkettner** [comment]
Hiya @sihuiDG!

Modernizr does not detect touch devices - it detects touch events (which is why it was renamed in v3).

That being said - I am not replicatin

**Comment by sihuiDG** [comment]
thank you for the quick feedback, Patrick :)

in OSX firefox 39 has "touch" class, while chrome has "no-touch" class.
for me, i think there is something we could improve here.

**Comment by patrickkettner** [comment]
There is no `touch` in v3. Could you double check using it?

**Comment by sihuiDG** [comment]
So,
in v2.8.3 firefox gets "touch" class, in v3.0b firefox gets "touchevents" class

**Comment by patrickkettner** [comment]
ok - I showed in my original update that I am not able to replicate it.

Could you check out [the test page](http://modernizr.github.io/Modernizr/test/) to see what you get?

Also, could you check the `about:config` part of firefox and see the value for `dom.w3c_touch_events.enabled`

**Comment by sihuiDG** [comment]
Thanks, Patrick 
Sorry, my bad,  my firefox about:config section has been changed somehow.  
and thanks for the tip
:+1:

**Comment by patrickkettner** [comment]
My pleasure!

**Comment by jesstelford** [comment]
Looks like the events are disabled by default for desktop Firefox:

> As of Gecko 24.0, the touch events support introduced with Gecko 18.0 has been disabled on the desktop version of Firefox (bug 888304), as some popular sites including Google and Twitter were not working properly. Once the bug is fixed, the API will be enabled again. To enable it anyway, open about:config and set the dom.w3c_touch_events.enabled preference to 2. The mobile versions including Firefox for Android and Firefox OS are not affected by this change. Also, the API has been enabled on the Metro-style version of Firefox for Windows 8.

- [MDN's Touch Events page](https://developer.mozilla.org/en-US/docs/Web/API/Touch_events)

@patrickkettner Maybe this is worth pointing out in the [Touch Events section of the docs](http://modernizr.com/docs/#touch)?

**Comment by patrickkettner** [comment]
@jesstelford hmm... not sure why we would want to note that. It seems logical to me that a desktop browser doesn't enable touch events by default. Why do you think we should?

**Comment by jesstelford** [comment]
It seems like an unexpected behaviour - especially with the line being blurred by laptops with touch screens, etc, these days.

Also, there is already a discussion about WebOS & Chrome's support - I figured mentioning that touch events are disabled on desktop might be worth avoiding this gotchya.

**Comment by patrickkettner** [comment]
its not that it is disabled on desktop, it is displayed on desktop firefox - for now. Are you seeing a touch screen laptop turn up with this as false?

**Comment by jesstelford** [comment]
No, I'm basing my info entirely off of the [MDN Touch Events](https://developer.mozilla.org/en-US/docs/Web/API/Touch_events) page:

> As of Gecko 24.0, the touch events support introduced with Gecko 18.0 has been disabled on the desktop version of Firefox (bug 888304), as some popular sites including Google and Twitter were not working properly. Once the bug is fixed, the API will be enabled again.

It may be that info is out of date, and my suggestion is no longer valid. I don't have a means to test my assertion about touch-screen laptops above unfortunately.

**Comment by roblarsen** [comment]
Testing `('ontouchstart' in window)` on a touchscreen laptop

 http://jsfiddle.net/robreact/uqodo7aw/1/

Chrome: True (expected)
Firefox: False (unexpected without the above MDN article) 
Edge: False (expected)

**Comment by jesstelford** [comment]
Excellent, thanks for the test results @roblarsen.
