### ISSUE TITLE
what are the differences between  `Flexbox`, `Flexbox (legacy)` and `Flexbox (tweener)`?

### ISSUE THREAD

**Issue by ganlanyuan** [Modernizr/Modernizr#1636]
Hi,
What are the differences between  `Flexbox`, `Flexbox (legacy)` and `Flexbox (tweener)`?

Thanks

**Comment by patrickkettner** [comment]
Hey @ganlanyuan!
There were three major states to the flexbox spec, and these are the most common names for each era. [Here](https://css-tricks.com/using-flexbox/) is one of the better articles on making it work.

have fun!

**Comment by ganlanyuan** [comment]
Hi, thanks for your fast response!

So `.flexbox` means support the latest syntax, or include 2009 and 2012 version as well?
And `.flexbox(legacy)` only for 2009 version, `flexbox (tweener)` only for 2012 version?
Sorry, I'm very new for the back part of the Modernizr.

**Comment by patrickkettner** [comment]
The flexbox test is for he latest syntax.

Cheers!

**Comment by ganlanyuan** [comment]
Great! thanks ^^
