### ISSUE TITLE
Occasional 'Aw, Snap!' in Chrome when devtools open

### ISSUE THREAD

**Issue by mwcz** [Modernizr/Modernizr#1637]
We've been experiencing an occasional Aw, Snap (tab crash) in Chrome.  
- it only occurs when devtools are open
  - which devtools panel doesn't seem to matter
- it occurs roughly one in every 10 page reloads
  - sometimes less, sometimes more.  occurs every time when you're trying to show someone something ;)
  - the variation may be due to asynchronous loading of Modernizr with an AMD loader (RequireJS)
- we're using the development build of Modernizr, all tests included
- happens in Chrome in Linux and Macs, have not tested Windows
  - not sure on specific versions, but has been happening for about a year, and continues to happen in Chrome unstable (currently 44.0.2391.0 for me)

I just discovered this morning that Modernizr is the cause of these, so I'm pretty excited to finally bury this annoying development bug.  I see that there were some issues way back in Chrome 10 with Aw Snaps relating to the webgl test.  I'm going to try turning off all the tests we don't use and see if that helps.  I'll post here when more info surfaces.

**Comment by patrickkettner** [comment]
@paulirish may be able to help figure out the issue with chrome crash ids?

**Comment by chrisblakley** [comment]
For what it's worth I've also had this issue in the past (Chrome on Mac, too). My temporary fix was to use a non-dev build of Modernizr (not that that is a viable solution for others). Can not confirm if this is fixed by v3 or not.

**Comment by mwcz** [comment]
Also confirmed fixed by either...

 - removing Modernizr completely
 - or, preferably, using a custom build with only the needed tests

The dev build seems to have been the source of the problem for us as well.  Still, Modernizr probably shouldn't be able to crash a Chrome tab.

**Comment by ryanseddon** [comment]
I defintely shouldn't would appreciate any help in finding the source of the crash. If you can reproduce it and get the crash dump that would be helpful.

http://stackoverflow.com/questions/10896281/how-do-i-debug-a-tab-crash-in-google-chrome

**Comment by mwcz** [comment]
@ryanseddon, are you still waiting on a crash dump?  Forgive my memory, I think I emailed you a crash dump but I'm not sure.

**Comment by ryanseddon** [comment]
Hmm no I didn't get any email from you?

**Comment by yuvilio** [comment]
I ran into this problem as well (Getting aw snap frequently on refreshes).    I eliminated modernizr tests I was using in an attempt to track down which ones might be causing it. In my case this test turned out to be the culprit.

`"test/workers/blobworkers"`

Once I removed that one, the "aw snap" messages went away.

Chrome version: Google Chrome 50.0.2657.0 dev
OS: Ubuntu 15.10

**Comment by ryanseddon** [comment]
@yuvilio you think you could put a PR together to fix it since you've discovered the offending test?

**Comment by yuvilio** [comment]
@ryanseddon , 

I think what I noted is more of a workaround rather than a fix.  That is, generate a modernizr.js that does not have `test/workers/blobworkers` in the "feature-detects" list of the modernizr-config.json you're using.  Or if you prefer downloading modernizr, make sure it's without the "Workers from Blob URIs" Test checked.

I'm not sure what there is to PR there other than perhaps a note in the documentation somwhere about this issue.  

A fix might be more about reproducing a test for the "aw snap" when devtools is open and then adjusting the [feature-detects/workers/blobworkers.js](https://github.com/Modernizr/Modernizr/blob/master/feature-detects/workers/blobworkers.js) test to avoid it from happening.   For that, I don't have an answer.

**Comment by ryanseddon** [comment]
@yuvilio, Cool then you have a good idea of what needs to be looked into to help us solve this issue, sounds like your the perfect person to contribute a fix for this :)

**Comment by paulirish** [comment]
For anyone getting this crash please do the following:

* go to `chrome://crashes/`
* find a crash ID that matches whenever you got the aw,snap
* paste the ID here and tweet it to me @paul_irish as well.

I'll be able to find out a lot more on why the renderer thread is crashing.

**Comment by yuvilio** [comment]
Thanks @paulirish ,  I just recreated the error and generated the crash:

Crash ID 1721873400000000 (Chrome).

Tweeted as well.

**Comment by paulirish** [comment]
Thanks. It's this bug, though currently private: https://bugs.chromium.org/p/chromium/issues/detail?id=581576

**Comment by paulirish** [comment]
Can someone who's experiencing this post a reduced testcase to jsbin?  We will need to reproduce the crash to get a fix sorted.

**Comment by yuvilio** [comment]
Odd. Try as i might, i can't get [a strictly modernizr blobworkers jsbin example](https://output.jsbin.com/qepebaj) to cause that issue when developer tools is open. Maybe it's something in my local gulp asset pipeline that's involved. For now, strictly local issue.

**Comment by bs-thomas** [comment]
I did the "getaround", and confirm it works.
Would be great if there is a fix soon!!  (On the Google side I assume)

**Comment by rejas** [comment]
hi @mwcz is this still an issue in chrome or got it fixed somehow in the meantime?

**Comment by mwcz** [comment]
@rejas I'll do a quick test to see if I can still reproduce it.  We removed the WebGL test from our modernizr build back in 2015 to dodge this issue, so I'll add it back in and see what happens.

**Comment by mwcz** [comment]
@rejas I'm not able to reproduce it any longer.  I reverted back to the exact modernizr file we had back then, with the full suite of tests, at version 2.8.3.  No luck reproducing, so I'd say you're right that this has been fixed in Chrome.
