### ISSUE TITLE
[npm] — Error: module "./process" not found

### ISSUE THREAD

**Issue by baptistebriel** [Modernizr/Modernizr#1639]
Hello,
I just installed the latest version of modernizr from npm, and I get this error:

`Error: module "./process" not found from "/.../node_modules/modernizr/node_modules/requirejs/bin/r.js"`

Could it be fixed on npm?
Thanks!

**Comment by patrickkettner** [comment]
how are you trying to run it?

**Comment by baptistebriel** [comment]
Just a basic `require('modernizr')`, with `gulp` and `browserify`.
Am I doing something wrong? Thanks!

**Comment by patrickkettner** [comment]
unfortunately, yes. The node module is only an API for the builder. You can't browserify it. You need to build it, then include the produced file.

good luck!

**Comment by baptistebriel** [comment]
Oh, okay. Thanks Patrick!
