### ISSUE TITLE
testAllProps set twice

### ISSUE THREAD

**Issue by dracos** [Modernizr/Modernizr#1645]
`ModernizrProto.testAllProps = testPropsAll;`, and then a few lines later, `ModernizrProto.testAllProps = testAllProps;` (or in a minified version, I have `…,w.testAllProps=v,w.testAllProps=y,…`). Sorry if I've misunderstood something, but it doesn't seem right - especially as the function has a different signature each time.

**Comment by patrickkettner** [comment]
hi @dracos!
can you provide more information? Where are you seeing this, replication steps, etc.

thanks!

**Comment by dracos** [comment]
Any build on https://modernizr.com that includes testAllProps (/download is currently 404ing though).

**Comment by dracos** [comment]
In terms of the source, it's defined twice at https://github.com/Modernizr/Modernizr/blob/master/src/testPropsAll.js#L29 and https://github.com/Modernizr/Modernizr/blob/master/src/testAllProps.js#L42

**Comment by rejas** [comment]
@patrickkettner  he points out those two lines that look weird:

https://github.com/Modernizr/Modernizr/blob/4e56bfd8353f3aee25a1354e593ceec96cf1016b/src/testPropsAll.js#L38

and

https://github.com/Modernizr/Modernizr/blob/4e56bfd8353f3aee25a1354e593ceec96cf1016b/test/browser/src/testPropsAll.js#L71

The question is if the "testPropsAll" "testAllProps" mixup is intentional?

**Comment by dracos** [comment]
Second quote should be https://github.com/Modernizr/Modernizr/blob/4e56bfd8353f3aee25a1354e593ceec96cf1016b/src/testAllProps.js#L42 I think :)

**Comment by rejas** [comment]
I think that line is okay @dracos but I let @patrickkettner decide sicne he knows the code best :-D

**Comment by dracos** [comment]
Hi, sure I've misunderstood this, but if you could explain why it's not a bug that the modernizr output sets the same `ModernizrProto.testAllProps` variable twice, I'd appreciate it, thanks :)
