### ISSUE TITLE
Builds tagged as alpha-4

### ISSUE THREAD

**Issue by dcrocks** [Modernizr/Modernizr#1646]
When creating a build for ver 3.0 I saw the following description in the 1st line of the file:
/*! modernizr 3.0.0-alpha.4 (Custom Build) | MIT *
But this should be labeled as ver 3.0 stable, shouldn't it?

**Comment by ryanseddon** [comment]
@patrickkettner any ideas? package.json is up to date with the right version?

**Comment by patrickkettner** [comment]
I'm not able to replicate this. How were you building it, @dcrocks?

**Comment by dcrocks** [comment]
I just went thru the web Build interface. I'm not the only one to see this. I have a small involvement in the Drupal project and someone there created an issue to upgrade their version of modernizr to 3.0 and the alpha tag was pointed out there. They are about to release a new version of drupal and they are adverse to releasing it with alpha code.

On September 15, 2015, at 10:32 AM, patrick kettner <notifications@github.com> wrote:

I'm not able to replicate this. How were you building it, @dcrocks?

**Comment by patrickkettner** [comment]
Ah, ok. This is actually an issue with the web builder. @kurafire opened up
an issue tracking that on the modernizr-neue repo, so I will fix it there.

Thanks for the report!

**Comment by ryanseddon** [comment]
Modernizr-neue pulls in modernizr so this issue is coming from here the banner in /lib should be reading from package.json so not sure if it's cached or something.
