### ISSUE TITLE
hidden attribute on <html> hides the whole html document on Bootstrap 3

### ISSUE THREAD

**Issue by laupkram** [Modernizr/Modernizr#1650]
see the following generated classes below

![hidden](https://cloud.githubusercontent.com/assets/1390979/9877880/51a29528-5bf2-11e5-905d-fd8eab4ac633.png)

the problem was the `hidden` class on `<html>` hides the whole html document

I removed the `hidden` class on `<html>` element and now it works fine. It seems Modernizr needs to rename the result class for hidden attribute test

**Comment by patrickkettner** [comment]
Hey @laupkram!
We have actually discussed this previously. You can and should be changing bootstrap to fit your styles. In addition,  you probably don't need a vast majority of the detects you are using. Check out the custom builder - its neat!
