### ISSUE TITLE
Smaller files for videoautoplay

### ISSUE THREAD

**Issue by joshuabaker** [Modernizr/Modernizr#1652]
Might [this MP4](https://github.com/mathiasbynens/small/blob/59fbd49ba36dbd9a94e5c80f52473d2b5362cae2/mp4.mp4) be better? Looks to be ~42% smaller. The [WebM](https://github.com/mathiasbynens/small/blob/59fbd49ba36dbd9a94e5c80f52473d2b5362cae2/webm.webm) might also be worth looking at.

I’ve tested the MP4 in latest Chrome, Firefox and Mobile Safari (device). IE isn’t working but I think that’s a general issue with the test (#1619).

<sup>Test: [feature-detects/video/autoplay.js#L45](https://github.com/Modernizr/Modernizr/blob/381a68e3453ee55b1793cafd18f8488793825158/feature-detects/video/autoplay.js#L45)</sup>

**Comment by patrickkettner** [comment]
Want to PR a change with it?

**Comment by patrickkettner** [comment]
@joshuabaker

**Comment by joshuabaker** [comment]
@patrickkettner: I’ve no idea what the protocol is here. What branch am I submitting this too? Are there tests that PRs should conform to?

**Comment by patrickkettner** [comment]
Master, npm test will run the tests locally, but Travis will run it
automatically for you on PR

**Comment by patrickkettner** [comment]
ping @joshuabaker

**Comment by patrickkettner** [comment]
ping @joshuabaker

**Comment by ryanseddon** [comment]
Seems that mp4 is corrupt, closing.
