### ISSUE TITLE
Infinite loop when using formvalidation test in Opera Mini

### ISSUE THREAD

**Issue by mbaluta** [Modernizr/Modernizr#1653]
Pages using formvalidation test don't load in Opera Mini, because it uses newer Presto version and it validates form after `preventDefault()`. However `preventDefault()` is not called, so the form is submitted, the test is executed again and it loops.

The fix is already provided, however for some reason not integrated, so I ask to do it:
https://github.com/Modernizr/Modernizr/pull/1594

**Comment by patrickkettner** [comment]
#1594 was merged, so closing this.

cheers!
