### ISSUE TITLE
no-js class is not removed when setting classPrefix

### ISSUE THREAD

**Issue by jakestubbz** [Modernizr/Modernizr#1654]
When setting a `classPrefix` the `no-js` class is not being replaced, tested in version 3.0.0-alpha.4. In the below example, I'd expect `no-js` to be replaced with `js`.

Example JS Bin:
https://jsbin.com/hegimiboxa/edit?html,js,output

**Comment by kmuncie** [comment]
@jakestubbz if you are using a classPrefix such as "feature-" then you must include that on your no-js class (e.g. feature-no-js)

**Comment by jakestubbz** [comment]
@kmuncie Thanks a lot, that worked.

It's not clear from the documentation that this is necessary though, unless I missed something.

**Comment by patrickkettner** [comment]
Awesome point - would you be interested in submitting a documentation PR to
help future travelers?
