### ISSUE TITLE
Missing tags for version v3.x?

### ISSUE THREAD

**Issue by PeterDaveHello** [Modernizr/Modernizr#1655]
Hi there, seems we don't have version v3.x's tags, would you please add that? Thanks!

**Comment by patrickkettner** [comment]
sorry about that!

fixed now

**Comment by PeterDaveHello** [comment]
Thanks a lot.

**Comment by patrickkettner** [comment]
a pleasure

On Fri, Sep 18, 2015 at 9:48 AM, Peter Dave Hello <notifications@github.com>
wrote:

> Thanks a lot.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Modernizr/Modernizr/issues/1655#issuecomment-141505094>
> .
>



-- 
patrick

**Comment by PeterDaveHello** [comment]
@patrickkettner seems the current tag for v3.0.0 is not like v2.x as before, like we have built modernizr.js there, is it possible to add it back? So that we can use auto-update on [cdnjs](https://cdnjs.com/libraries/modernizr), thanks!

**Comment by patrickkettner** [comment]
There isn't a file for cdnjs to distribute. It's a modular build system.

I am confused as to what the issue with the tag is. Can you elaborate?

**Comment by PeterDaveHello** [comment]
Oh sure, our auto-updater uses tag to recognize the versions and and grab the dist file in that commit, like this: https://github.com/Modernizr/Modernizr/raw/v2.8.3/modernizr.js

**Comment by patrickkettner** [comment]
Ah. Could the issue be that there is no dist file?

**Comment by PeterDaveHello** [comment]
If there is no dist file in both git repo and npm package, we can not auto-update a lib.

**Comment by patrickkettner** [comment]
Ok, yeah. Well as I mentioned, there isn't a file to distribute. It's fully
modular now.

**Comment by PeterDaveHello** [comment]
So if we wanna host this lib on cdnjs, what's the fastest method if we want a officially built file? Or if you would like to send PR to add it :smile:

**Comment by SlexAxton** [comment]
There is no longer a single file that is Modernizr. If you wanted to add modernizr to cdnjs, you'd need to add the set of all combinations of modernizr feature detects each built as a separate build.

**Comment by SlexAxton** [comment]
> a officially built file

There is no officially built file.

**Comment by PeterDaveHello** [comment]
hmmmm ... a little bit complex, anyway, thanks for your explanation!
