### ISSUE TITLE
Custom Packages via Bower

### ISSUE THREAD

**Issue by JKillian** [Modernizr/Modernizr#1656]
The [most recent blog post][0] said that you can now "dynamically create a custom package that can be installed via bower" with the new Modernizer website. This is great! I can't find any instructions anywhere on how to do this though - what are the steps to do this?

[0]: https://modernizr.com/news/modernizr-3-new-release-site

**Comment by patrickkettner** [comment]
A blog post will be coming with more details shortly (currently on vacation). But the long and short of it is

Get the build URL for your custom build (its in the header  of any custom build - e.g. https://modernizr.com/download?-setclasses-ambientlight)
Add .zip or .tar to the end of it (e.g. https://modernizr.com/download?-setclasses-ambientlight.zip) 
Bower install that jam (e.g. bower install --save https://modernizr.com/download?-setclasses-ambientlight.zip)

More details will be in the blog post, but that should get you going

**Comment by SlexAxton** [comment]
If you make your custom build on the cli or website, in the header of the file there is a build URL. Something like

`https://modernizr.com/download?setclasses-ambientlight`

If you add a .zip to the end of that, you can now bower install your own custom build!

`bower install --save https://modernizr.com/download?setclasses-ambientlight.zip`

This absolutely not-really-documented yet as we're still doing post-major-version-launch cleanup


UGGGHHHH PATRICK BEAT ME TO IT

**Comment by JKillian** [comment]
Fantastic! Thanks @patrickkettner and @SlexAxton

**Comment by T1st3** [comment]
Thanks for this!
Note that it also works when inserted directly in `bower.json`:

```json
{
  "name": "mypackage",
  "dependencies": {
    "modernizr": "https://modernizr.com/download?canvas-emoji-setclasses.zip"
  }
}
```
