### ISSUE TITLE
Bind is undefined with 3.0.0

### ISSUE THREAD

**Issue by kmuncie** [Modernizr/Modernizr#1658]
Modernizr 2.8.3 Function.prototype.bind was declared. At commit 4e128f6 this was changed. 

Users of this and past versions of Modernizr may have inadvertently relied on this function. The consequence is that when upgrading to 3.0.0 any non-ES5 supporting browsers will break without including this function if bind is being used in their codebase. A fix for users encountering this problem will be to create a shim for Function.prototype.bind when it is not defined. 

Overall there is no problem with the implementation of Modernizr, but this breaking change should be documented for users upgrading to Modernizr 3.0.0 

Thanks to @onebytegone for helping debug this problem.

**Comment by patrickkettner** [comment]
Hey @kmuncie!

I am really sorry - that must have ben a drag to debug :[

[This was documented in the release notes](https://github.com/Modernizr/modernizr-neue/blame/master/posts/2015-09-11-modernizr-3-new-release-site.markdown#L65), however.
