### ISSUE TITLE
support for Web Crypto API

### ISSUE THREAD

**Issue by UnsungHero97** [Modernizr/Modernizr#1659]
It doesn't seem like Modernizr currently supports checks for the Web Crypto API. Both Chrome and Firefox (haven't checked others) have an implementation in their latest browsers under `window.crypto.subtle`.

- https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API
- https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto
- http://caniuse.com/#feat=cryptography

Is there a plan to add support for this API soon?

**Comment by roblarsen** [comment]
Is a test for `window.[prefix]crypto.subtle` enough? It's an easy enough test to write if that's all that's required.

**Comment by UnsungHero97** [comment]
I think that would be enough for now, though I'm not sure if this should be split in 2, for `crypto` and for `subtle`.

**Comment by patrickkettner** [comment]
We have a single crypto detect, getrandomvalues. Any new detects should be
added to the crypto folder

https://github.com/Modernizr/Modernizr/tree/master/feature-detects/crypto
