### ISSUE TITLE
Notification feature detect gives false positives Chrome 45 on Android

### ISSUE THREAD

**Issue by alexgibson** [Modernizr/Modernizr#1660]
Feature detect for Web Notifications is bit of a mess in Chrome on Android :-/

See https://github.com/alexgibson/notify.js/issues/38 for details.

**Comment by ryanseddon** [comment]
Thanks @alexgibson would you be able to put a PR together since you're way more in the know of what you need to test

**Comment by alexgibson** [comment]
Sorry @ryanseddon this ping hasn't gone unnoticed, will try and get to this soon!
