### ISSUE TITLE
Modernizr removed from Bower?

### ISSUE THREAD

**Issue by jensechu** [Modernizr/Modernizr#1664]
We can't get Modernizr to build anywhere using bower anymore. We also can't find it in Bower's package search. Was it removed from bower...?

We're specifying: `"modernizr": ">= 2.7.2",`.

Build failure: 

```
12:20:28 ENOENT, no such file or directory '/home/jenkins/workspace/DeployCoreClient/tmp/simple_concat-input_base_path-zmKIwbV4.tmp/0/bower_components/modernizr/modernizr.js'
12:20:28 Error: ENOENT, no such file or directory '/home/jenkins/workspace/DeployCoreClient/tmp/simple_concat-input_base_path-zmKIwbV4.tmp/0/bower_components/modernizr/modernizr.js'
```

We haven't changed anything on our end and this has been working flawlessly up until now. Any guidance would be much appreciated. :bow:

**Comment by patrickkettner** [comment]
We never had a package on bower, there was an unofficial package there
previously, however.

That being said, you can now get custom builds off of modernizr.com. you
just get the build URL you for a custom build ( available at the top of
each file that is built ), add .zip to the end of it, and you can bower
install it!

e.g. bower install https://modernizr.com/download?-ambientlight.zip

**Comment by jensechu** [comment]
Thanks for the response! A foundation package had it as a dependency and threw us for a loop. :D 

:beers:
