### ISSUE TITLE
Website's custom-build checkboxes out of sync.

### ISSUE THREAD

**Issue by joshbader** [Modernizr/Modernizr#1668]
The checked state on the detects gets out of sync when unchecking them. (Chrome 45.0.2454.93 on Mac OS 10.10.5)

![modernizer-checkbox-bug](https://cloud.githubusercontent.com/assets/3035031/9993575/8ca2e882-6046-11e5-943a-44966dab79ae.gif)

**Comment by patrickkettner** [comment]
Hey josh!
There is actually another repo for the site (Modernizr/modernizr-neue). There's an open issue for this one, so I'm gonna close this out in favor of it.

Thanks a lot for reporting!

**Comment by joshbader** [comment]
@patrickkettner, thanks. I must have not noticed that during my morning hustle. All the best.
