### ISSUE TITLE
Build generates no output file

### ISSUE THREAD

**Issue by srad** [Modernizr/Modernizr#1671]
I have a bower checkout and tried to build modernizr with the example and there's no output:

```
cd vendor/modernizr
./bin/modernizr -u -V -c lib/config-all.json
Modernizr 3.0.0
```
No file is generated in ```./```, the config-all file is the default one which seems to contain all feature detects.

What am I missing here?

**Comment by patrickkettner** [comment]
-V outputs the version. It will work if you don't include that flag.

**Comment by srad** [comment]
The problem is that the readme.md is wrong, you write that executing:

```
npm install
./bin/modernizr
```
outputs the file, which it doesn't. It just shows the help and exits. You need to include at the minimum:

```
npm install
./bin/modernizr -c lib/config-all.json
```
That are these kind of details with github projects that could be just slapped on the readme.md fronpage and would prevent that I waste my time.

**Comment by patrickkettner** [comment]
would you care to create a PR so that others don't "waste their time"?
