### ISSUE TITLE
Provide a download on website for a simple minified build file

### ISSUE THREAD

**Issue by srad** [Modernizr/Modernizr#1672]
I know all that build on demand stuff is fancy but I'm not interested in all those details.
I would like to see - like jQuery - just a simple download link to a simple file which is already build with all feature and minified

**Comment by patrickkettner** [comment]
JQuery is built completely differently then Modernizr. Only use the detects you need so that your users don't have to run code you don't need.

**Comment by srad** [comment]
What I requested here is (like earlier available) a prebuild modernir.js with all features for download.

**Comment by patrickkettner** [comment]
I understand. I am saying that that file would take over a half a second
just to parse on a 2015 macbook pro, let alone a 3 year old android device.
its a dangerous file, and not one that 99.9999% of developers should ever
use. By making it easily available, we will be hurting the web.

On Tue, Sep 22, 2015 at 9:47 AM, Saman <notifications@github.com> wrote:

> What I requested here is (like earlier available) a prebuild modernir.js
> with all features for download.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Modernizr/Modernizr/issues/1672#issuecomment-142345734>
> .
>



-- 
patrick

**Comment by srad** [comment]
A compromise would be to make two or three editions, because I doubt that anybody needs ES6 and other rare feature detects in production right now or things that are only relevant for specific devices (mobile).

**Comment by patrickkettner** [comment]
prebuilt files mean people shipping code that they don't need, which just
punishes their users. You can automate this with grunt-modernizr or the
modernizr build tool with gulp. prebuilt files are a bad idea, and I can't
imagine a way in which we will support them.

On Tue, Sep 22, 2015 at 12:43 PM, Saman <notifications@github.com> wrote:

> A compromise would be to make two or three editions, because I doubt that
> anybody needs ES6 and other rare feature detects in production right now or
> things that are only relevant for specific devices (mobile).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Modernizr/Modernizr/issues/1672#issuecomment-142397437>
> .
>



-- 
patrick

**Comment by roblarsen** [comment]
Prebuilt files are a problem. I spend a little bit of time on every project with existing code figuring out what (if anything) my clients need from their Modernizr builds.
