### ISSUE TITLE
nth-child false negative

### ISSUE THREAD

**Issue by mstrutt** [Modernizr/Modernizr#1675]
I'm seeing a `no-nthchild` class added in browsers that support nth-child.

No errors in the console, but adding a breakpoint in to [line 35](https://github.com/Modernizr/Modernizr/blob/master/feature-detects/css/nthchild.js#L35) of that test reports the `offsetWidth` of each `div` to be `0` (should be `1` even if not supported).

Using the following build of modernizr: https://modernizr.com/download?flexbox-flexboxlegacy-flexboxtweener-flexwrap-nthchild-dontmin-setclasses-shiv

Tested: Chrome/Firefox latest on Ubuntu 15.04, IE11/Edge on Windows 10

**Comment by jaredbeck** [comment]
> I'm seeing a no-nthchild class added in browsers that support nth-child.

I can reproduce this is FF latest (41.0) using `modernizr 3.0.0-alpha.4 (Custom Build)`

**Comment by ryanseddon** [comment]
@mstrutt wanna put together a PR?

**Comment by mstrutt** [comment]
I'll give it a go

**Comment by SimenB** [comment]
This fails in Chrome as well, in 3.2.0

**Comment by patrickkettner** [comment]
@mstrutt - any luck?

**Comment by mstrutt** [comment]
@patrickkettner think I managed to get the the bottom of it, just raised a PR
