### ISSUE TITLE
:checked on IE9

### ISSUE THREAD

**Issue by massic80** [Modernizr/Modernizr#1676]
Hi,
I just downloaded a custom build of modernizr
https://modernizr.com/download?checked-placeholder-setclasses-shiv

I tried Modernizr.checked on IE9, and it says "false", but looks like :checked pseudo class is supported

https://msdn.microsoft.com/en-us/library/jj127296%28v=vs.85%29.aspx

http://codepen.io/massic80/pen/Gpjyag
(My example doesn't work by clicking on first radio, only on the tab but I didn't investigate why)

**Comment by patrickkettner** [comment]
Hey @massic80!
Thanks a lot for reaching out, I am getting `true` for IE 9, though.

Have you made sure your doc mode is IE 9 (you can see this in the F12 tools)?

**Comment by massic80** [comment]
Hi Patrick,
it's embarassing, but I don't know why it told me "false" :) At the moment, it's correctly saying "true". :)
I checked in the developer Tools, but... who know, IE9 misteries :D

**Comment by patrickkettner** [comment]
No worries!
