### ISSUE TITLE
when i download the build json from https://modernizr.com/ and install modernizr

### ISSUE THREAD

**Issue by YY030913** [Modernizr/Modernizr#1687]
D:\Program Files\nodejs\modernizr>modernizr -c modernizr-config

D:\Program Files\nodejs\modernizr\modernizr-config:2
  "minify": true,
          ^
D:\Program Files\nodejs\modernizr\modernizr-config is not valid JSON.
[SyntaxError: Unexpected token :]

**Comment by YY030913** [comment]
this is the modernizr-config
{
  "name": "modernizr",
  "version": "3.0.0",
  "description": "Modernizr is a JavaScript library that detects HTML5 and CSS3 features in the user’s browser.",
  "directories": {
    "test": "test"
  },
  "dependencies": {
    "doctrine": "^0.6.4",
    "file": "^0.2.2",
    "find-parent-dir": "^0.3.0",
    "lodash": "^3.1.0",
    "marked": "^0.2.8",
    "mkdirp": "^0.5.0",
    "requirejs": "^2.1.16",
    "yargs": "^2.3.0"
  },
  "devDependencies": {
    "expect.js": "^0.3.1",
    "grunt": "~0.4.0",
    "grunt-contrib-clean": "~0.4.0",
    "grunt-contrib-connect": "~0.5.0",
    "grunt-contrib-copy": "^0.8.0",
    "grunt-contrib-jade": "^0.14.1",
    "grunt-contrib-jshint": "^0.11.0",
    "grunt-coveralls": "^1.0.0",
    "grunt-env": "^0.4.2",
    "grunt-istanbul": "^0.4.0",
    "grunt-jscs": "^1.6.0",
    "grunt-mocha": "^0.4.11",
    "grunt-mocha-test": "^0.12.7",
    "grunt-saucelabs": "^8.6.0",
    "joi": "^6.4.1",
    "jquery": "^1.11.2",
    "json3": "^3.3.2",
    "load-grunt-tasks": "~0.2.1",
    "proxyquire": "^1.3.1"
  },
  "scripts": {
    "test": "grunt test --stack"
  },
  "main": "./lib/cli",
  "bin": {
    "modernizr": "./bin/modernizr"
  },
  "repository": {
    "type": "git",
    "url": "git://github.com/Modernizr/Modernizr.git"
  },
  "bugs": {
    "url": "https://github.com/Modernizr/Modernizr/issues"
  },
  "inch": {
    "files": {
      "included": [
        "feature-detects/",
        "src/"
      ]
    }
  },
  "keywords": [
    "html5",
    "css3",
    "browser",
    "feature detection"
  ],
  "author": {
    "name": "Modernizr",
    "url": "http://modernizr.com/"
  },
  "contributors": [
    {
      "name": "Faruk Ates"
    },
    {
      "name": "Paul Irish"
    },
    {
      "name": "Alex Sexton"
    },
    {
      "name": "Ryan Seddon"
    },
    {
      "name": "Alexander Farkas"
    },
    {
      "name": "Patrick Kettner"
    },
    {
      "name": "Stu Cox"
    },
    {
      "name": "Richard Herrera"
    }
  ],
  "license": "MIT",
  "gitHead": "a9a90192ea11dc0ff916431b40227734af9074b6",
  "homepage": "https://github.com/Modernizr/Modernizr#readme",
  "_id": "modernizr@3.0.0",
  "_shasum": "c8f2db9ebcf97e68244b767269e54140dfaec5db",
  "_from": "modernizr@",
  "_npmVersion": "2.14.2",
  "_nodeVersion": "0.12.7",
  "_npmUser": {
    "name": "patrickkettner",
    "email": "patrickkettner@gmail.com"
  },
  "maintainers": [
    {
      "name": "patrickkettner",
      "email": "patrickkettner@gmail.com"
    },
    {
      "name": "paulirish",
      "email": "paul.irish@gmail.com"
    },
    {
      "name": "slexaxton",
      "email": "alexsexton@gmail.com"
    },
    {
      "name": "ryanseddon",
      "email": "seddon.ryan@gmail.com"
    },
    {
      "name": "doctyper",
      "email": "rich@doctyper.com"
    },
    {
      "name": "stucox",
      "email": "stuart.cox@gmail.com"
    }
  ],
  "dist": {
    "shasum": "c8f2db9ebcf97e68244b767269e54140dfaec5db",
    "tarball": "http://registry.npmjs.org/modernizr/-/modernizr-3.0.0.tgz"
  },
  "_resolved": "https://registry.npmjs.org/modernizr/-/modernizr-3.0.0.tgz",
  "readme": "ERROR: No README data found!"
}

**Comment by patrickkettner** [comment]
hey @YY030913!

I am not able to replicate the problem. I saved the file you posted, validated it as 100% valid JSON, then built a build of modernizr with it as well.
Are you certain there is nothing additional in the file you are using?

**Comment by gare-bear** [comment]
I noticed the same issue on Ubuntu 12.04. I had to manually add the .json extension after downloading my build from https://modernizr.com/.

**Comment by ryanseddon** [comment]
Looks like chrome knows how to intelligently add the right extension but firefox takes the download attribute literally and gives you an extensionless file.

**Comment by ryanseddon** [comment]
Created an issue on the website repo modernizr/modernizr-neue#56
