### ISSUE TITLE
false negative for videoautoplay in Safari 9.0

### ISSUE THREAD

**Issue by br4nnigan** [Modernizr/Modernizr#1692]
https://codepen.io/anon/pen/meRajz
Videos still autoplay.

**Comment by benediktvaldez** [comment]
+1

**Comment by ericthor** [comment]
+1

**Comment by vivekagr** [comment]
+1

**Comment by ryanseddon** [comment]
Anyone want to have a go at a PR to fix this?

**Comment by yanwsh** [comment]
same issue. And I found another problem, if you refresh the page, the test will also fail. (Do it on your host machine, codepen will generate another HTML page, so it works.)

Here is my solutation: http://vip.e-measurement.net/test.html

It works on safari 9, but It has a problem, it should use external video file, base64 video will also made the test fail.  

Does anyone have a good solution?

**Comment by ArnaudBan** [comment]
Same here. 

Safari 9.0.1
OSX 10.10.5
Modernizr 3.2.0

**Comment by ryanseddon** [comment]
Finally had sometime to look into this, seems it was a encoding issue in our h264 base64 video.

Try this demo in Safari https://codepen.io/anon/pen/QyWQjQ I'm getting consistent correct true result.

**Comment by yanwsh** [comment]
thanks
