### ISSUE TITLE
Modernizr v3 and Prototype.js

### ISSUE THREAD

**Issue by svossen** [Modernizr/Modernizr#1709]
I'm using Modernizr in Magento projects so I have to load Prototype.js on my pages. This results in a lot of `no-*` classes added to the HTML element. I'm using a custom build of Modernizr 3.1.0 and Prototype 1.7.

When I include Prototype.js the HTML element has the following classes: `js cssanimations flexbox csstransforms supports csstransforms3d csstransitions no-each no-eachslice no-all no-any no-collect no-detect no-findall no-findall no-grep no-include no-include no-ingroupsof no-inject no-invoke no-max no-min no-partition no-pluck no-reject no-sortby no-clone no-zip no-size no-inspect no-reverse no-foreach no-clear no-first no-last no-compact no-flatten no-without no-uniq no-intersect no-clone`.

When I remove Prototype.js, only the following classes remain: `js cssanimations flexbox csstransforms supports csstransforms3d csstransitions`.

**Comment by SlexAxton** [comment]
I'm on my phone, sorry to be brief, but those classes look like they're from somewhere else. We replace 'no-js' but many of those appear to be tests for es5/6 features that Modernizr doesn't have detects for, especially at that granularity. Is there a missing second library?

**Comment by svossen** [comment]
I don't think another library is missing. When I just include prototype.js and modernizr in an almost empty HTML file, the classes are also added to HTML element.

I took a look at the prototype.js file and I see a lot of the added classes return in the code. For example, see the code snippet below.

    Object.extend(arrayProto, {
        _each:     _each,

        map:       map,
        collect:   map,
        select:    filter,
        filter:    filter,
        findAll:   filter,
        some:      some,
        any:       some,
        every:     every,
        all:       every,

        clear:     clear,
        first:     first,
        last:      last,
        compact:   compact,
        flatten:   flatten,
        without:   without,
        reverse:   reverse,
        uniq:      uniq,
        intersect: intersect,
        clone:     clone,
        toArray:   clone,
        size:      size,
        inspect:   inspect
    });

When I remove a line, for example `intersect: intersect,`, this specific class is removed from the HTML element as well.

**Comment by SlexAxton** [comment]
But isn't this in prototype, not Modernizr?

**Comment by svossen** [comment]
Yes this code is from the prototype.js file. Since there is a conflict when using both scripts, one of the two should be edited to resolve this conflict. Although I'm not sure if this should be Prototype or Modernizr. My best guest was Modernizr because there is no conflict between Prototype and Modernizr v2.

**Comment by roblarsen** [comment]
What is the conflict?

**Comment by svossen** [comment]
With conflict I mean the `no-*` classes which are added. It's not _really_ a conflict because all other functionality seems to be working just fine. The HTML-tag just looks a little messy with all these classes.

**Comment by roblarsen** [comment]
Stop using prototype? This isn't a bug and if it was it doesn't have anything to do with Modernizr.

**Comment by svossen** [comment]
I wish I could stop using Prototype but I can't since a lot of Magento's functionality depends on it.

I don't have enough JavaScript knowledge to see what's really going on. But I can see that when I console.log an empty array (Modernizr's `tests` array at line 26), it looks a lot more different with Prototype included than without it.

![with_prototype](https://cloud.githubusercontent.com/assets/5097018/10489066/d6e85a5a-729b-11e5-8eff-cb4545b10b45.png)
_With Prototype included_

![without_prototype](https://cloud.githubusercontent.com/assets/5097018/10489065/d6e55594-729b-11e5-88fe-06eacaa2e50c.png)
_Without Prototype included_

I guess I better accept the extra classes or move back to Modernizr v2 for now.

**Comment by roblarsen** [comment]
Ah, that is a bug. Prototype enhances `Array.prototype` and the `testRunner` doesn't do a hasOwnProperty test so it iterates through the Prototype enhancements in addition to the actual tests.

with the check (as expected)
http://plnkr.co/edit/8TnbG8p4T7Cg4P2NeEBR?p=preview

without the check (failing "tests" for Prototypes enhancements on the HTML element)
http://plnkr.co/edit/TDgXxP1Glnz2sgd2yOqr?p=preview

**Comment by svossen** [comment]
Thanks for pointing that out and resolving the issue!
