### ISSUE TITLE
input[type=number] should allow its value to be set to the empty string, but not all browsers (Webkit) allow that behavior

### ISSUE THREAD

**Issue by chadoh** [Modernizr/Modernizr#171]
According to [the spec](http://www.w3.org/TR/html5/number-state.html), "When an `input` element's `type` attribute is in the `Number` state, ...User agents should allow the user to set the `value` to the empty string." However, I just tried this out in Chrome 10 and that isn't supported. The value I just deleted pops back in.

You may want to look into putting in a check for this. I'd find it useful, but it's not a big deal. Sorry I don't have time to help out with it!

**Comment by MissAnichka** [comment]
We came across this issue as well so would like to leave a comment in case others out there are having the same issue as well. Try setting the value of the element to undefined! It worked for us:
`function clearInput(e, type) {
  e.preventDefault()
  let url = document.getElementById(`settings-${type}list-section-form-url`);
  let hrs = document.getElementById(`settings-${type}list-section-form-hrs`);
  let mins = document.getElementById(`settings-${type}list-section-form-mins`);
  url.value = "";
  url.placeholder = "google.com";
  hrs.value = undefined;
  mins.value = undefined;
}`

(the hrs and mins elements are html inputs that are of type=number)
