### ISSUE TITLE
building modernizr on the windows command line seems broken

### ISSUE THREAD

**Issue by patrickkettner** [Modernizr/Modernizr#1714]
http://stackoverflow.com/questions/33130662/building-modernizr-on-the-windows-command-line

**Comment by roblarsen** [comment]
I can verify that it's borked in cmd.exe and Powershell. 

Git Bash (MinGW) works fine (which is why I didn't realize it was busted in the core Windows shells before tonight.)

**Comment by patrickkettner** [comment]
So, its not _quite_ as big of a deal as it seems. The `bin` that is created still works (e.g. `modernizr -c ...`, after you npm install -g modernizr). The issue is when you try to run a non global version of the builder. The "fix" would be to run `node ./bin/modernizr -c ...` instead.

Leaving open for the moment to see if I can figure out something more obvious

**Comment by roblarsen** [comment]
Yeah, it's all down to relying on the shebang to tell it how to execute. Everything else is fine.

**Comment by dxcqcv** [comment]
or using git bash is better
