### ISSUE TITLE
Download-script adds "zip" to the class prefix

### ISSUE THREAD

**Issue by thasmo** [Modernizr/Modernizr#1716]
When using `https://modernizr.com/download?dontmin-setClasses-cssclassprefix:has.zip` as a dependency in `bower.json`, the generated file's config looks like this:
```js
_config: {
    'classPrefix' : "has.zip",
    'enableClasses' : true,
    'enableJSClass' : true,
    'usePrefixes' : true
},
```
The `classPrefix` should be `has` not `has.zip`.

**Comment by thasmo** [comment]
And now the service returns with status 500 all the time.

**Comment by patrickkettner** [comment]
great bug - should be easy to fix. as for the 500 thing, are you using `/download/?-...` or `/download?-...`

**Comment by thasmo** [comment]
I'm using `https://modernizr.com/download?dontmin-setClasses-cssclassprefix:has-.zip`.
Trying `https://modernizr.com/download/?dontmin-setClasses-cssclassprefix:has-.zip` gives me a bower error.

**Comment by patrickkettner** [comment]
ok. are you still getting that 500?

**Comment by thasmo** [comment]
Yes, still:
```shell
> bower install
bower modernizr#*           not-cached https://modernizr.com/download?dontmin-setClasses-cssclassprefix:has-.zip#*
bower modernizr#*              resolve https://modernizr.com/download?dontmin-setClasses-cssclassprefix:has-.zip#*
bower modernizr#*             download https://modernizr.com/download?dontmin-setClasses-cssclassprefix:has-.zip
bower modernizr#*                EHTTP Status code of 500
```
