### ISSUE TITLE
Usage with gulp.js

### ISSUE THREAD

**Issue by thasmo** [Modernizr/Modernizr#1717]
The docs state to use it like this:
```js
modernizr.build({}, function (result) {
  console.log(result); // the build
});
```
How would I use it gulp-style, piping it to an existing stream or concatenating it with other files?

**Comment by patrickkettner** [comment]
great question, @thasmo!

[you can use the callback provided via gulp](https://github.com/Modernizr/modernizr-neue/blob/048edc598a32771dda2c50339883101ee725f0ae/gulpfile.js#L181-L193)

lemme know if you have any questions

**Comment by thasmo** [comment]
@patrickkettner, is there a way to call modernizr.build() synchronously, so I can do something like this:
```js
var gulp = require('gulp');
var file = require('gulp-file');
var modernizr = require('modernizr');

gulp.task('js', function() {
  var str = modernizr.build();
 
  return gulp.src('scripts/**.js')
    .pipe(file('modernizr.js', str))
    .pipe(gulp.dest('dist'));
});
```
Additionally, do you have any hints for me how I could cache the generated modernizr build so it wouldn't need to build it everytime?

**Comment by patrickkettner** [comment]
no - why would you want to build it sync? that would go against a lot of the points of gulp

have a separate gulp job that generates the file? read from that file if it exists, otherwise create it?

**Comment by thasmo** [comment]
I'd love to generate it on the fly without storing it on disk. It would be sufficient to cache it in-memory for recurring task calls from a file watcher, if that makes sense.

**Comment by patrickkettner** [comment]
and you want to cache that file in memory?

On Thu, Oct 29, 2015 at 4:03 PM, Thomas Deinhamer <notifications@github.com>
wrote:

> I'd love to generate it on the fly without storing it on disk. It would be
> sufficient to cache it in-memory for recurring task calls from a file
> watcher, if that makes sense.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Modernizr/Modernizr/issues/1717#issuecomment-152352100>
> .
>



-- 
patrick

**Comment by thasmo** [comment]
Ye, if that makes sense at all. I thought it would make more sense, also performance-wise, to cache it in-memory, than to have Gulp read it from disk everytime. But maybe it's better to save the build on disk and read if from there, I just don't like having *intermediate* files if I can just create them on the fly. But maybe holding it in-memory isn't a good idea at all.

**Comment by thasmo** [comment]
I'm now going with creating the file beforehand and concatenating it with the other JS files in the gulp task. It does it's job. Thanks! :)

**Comment by patrickkettner** [comment]
cheers!

On Thu, Oct 29, 2015 at 4:44 PM, Thomas Deinhamer <notifications@github.com>
wrote:

> I'm now going with creating the file beforehand and concatenating it with
> the other JS files in the gulp task. It does it's job. Thanks! :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Modernizr/Modernizr/issues/1717#issuecomment-152358399>
> .
>



-- 
patrick
