### ISSUE TITLE
false negative for img.sizes in Safari 9

### ISSUE THREAD

**Issue by aFarkas** [Modernizr/Modernizr#1721]
Safari 9 does not expose the `sizes` property. Bug report here: https://bugs.webkit.org/show_bug.cgi?id=150230

Although Safari has basic `sizes` support. In case the fix is not released in a minor/patch release, the [corresponding test](https://github.com/Modernizr/Modernizr/blob/master/feature-detects/img/sizes.js) should be changed.

Currently the following detect is the shortest, I know of:
https://gist.github.com/aFarkas/2c4531393f9b1d18243c

Of course, if the browser doesn't even support `srcset` we don't need to test `sizes`.

**Comment by patrickkettner** [comment]
any interest in putting together a PR, @aFarkas ?
