### ISSUE TITLE
Can't access to all options on small screen

### ISSUE THREAD

**Issue by yukulele** [Modernizr/Modernizr#1724]
![left](https://cloud.githubusercontent.com/assets/347244/10592034/ce041100-76b9-11e5-8c58-2f6a16515a7a.PNG)

**Comment by patrickkettner** [comment]
is it not scrollable?

On Mon, Oct 19, 2015 at 4:33 PM, yukulele <notifications@github.com> wrote:

> [image: left]
> <https://cloud.githubusercontent.com/assets/347244/10592034/ce041100-76b9-11e5-8c58-2f6a16515a7a.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Modernizr/Modernizr/issues/1724>.
>



-- 
patrick

**Comment by yukulele** [comment]
not, it's `fixed`

**Comment by patrickkettner** [comment]
hm...it is fixed, but it still scrolls

![image](https://cloud.githubusercontent.com/assets/465414/10592170/f2263d68-767f-11e5-892e-f139043ca4de.png)


What browser are you testing in?

**Comment by yukulele** [comment]
https://github.com/Modernizr/modernizr-neue/issues/35

**Comment by yukulele** [comment]
firefox

**Comment by patrickkettner** [comment]
that is not the same issue. That is how the pink footer overlaps the sidebar. But, there is a scrolling issue in firefox that seems to be a recent regression. Would you be able to reopen this issue on the modenrizr-neue repo?
