### ISSUE TITLE
remove icon not aligned (firefox)

### ISSUE THREAD

**Issue by yukulele** [Modernizr/Modernizr#1725]
![remove](https://cloud.githubusercontent.com/assets/347244/10592055/f6d5adc8-76b9-11e5-9262-5a7f147f48f6.PNG)

**Comment by patrickkettner** [comment]
This is an issue with the Modernizr website, which is [here](https://github.com/modernizr/modernizr-neue). This is already reported, in [#44}(https://github.com/Modernizr/modernizr-neue/issues/44)
