### ISSUE TITLE
webkit bug (csstransforms3d)

### ISSUE THREAD

**Issue by retyui** [Modernizr/Modernizr#1726]
The error occurs in the browser webkit! 
Csstransforms3d = false if you change Zomm = 90% ??? O_o 
csstransforms3d = true if you change Zomm = 100%

[DEMO img](https://www.dropbox.com/s/nb6v6serrycoc6e/111111111111.PNG?dl=0)

[test file:](https://www.dropbox.com/s/bey81e9exuw0xl3/bag.html?dl=0)

My config:

``` javascript
{
  "minify": true,
  "options": [
    "domPrefixes",
    "prefixes",
    "prefixed",
    "prefixedCSS",
    "setClasses"
  ],
  "feature-detects": [
    "test/css/filters",
    "test/touchevents",
    "test/css/transforms",
    "test/css/transforms3d",
    "test/css/transitions",
    "test/css/flexboxlegacy",
    "test/img/webp"
  ]
}
```

**Comment by ryanseddon** [comment]
Oh nice catch that weird, confirmed your results. Wanna put together a PR?

**Comment by retyui** [comment]
"Хотите собрать PR? "
В смысле? Проблема решена?

2015-10-23 7:40 GMT+03:00 Ryan Seddon <notifications@github.com>:

**Comment by ryanseddon** [comment]
Do you know how to fix this issue? If so can you please create a pull request.

**Comment by gonsfx** [comment]
There could be a connection to this:
https://code.google.com/p/chromium/issues/detail?id=447902

What happens in the test is that the styling (width 7px, height 18px) is correctly applied to the element under test. chrome delivers wrong values for offset height when the browser is zoomed, probably a rounding error - e.g. 7px offsetWidth and 19px offsetHeight.
