### ISSUE TITLE
Firefox desktop returns touchevents "true"

### ISSUE THREAD

**Issue by laukstein** [Modernizr/Modernizr#1731]
[touchevents.js#L40](https://github.com/Modernizr/Modernizr/blob/master/feature-detects/touchevents.js#L40) `"ontouchstart" in window` always returns `true` on Firefox desktop since version 27, on Chrome 46 desktop `Emulate touch screen` will respond correctly after Tab refresh.

Firefox issue #970346 https://bugzilla.mozilla.org/show_bug.cgi?id=970346
Chrome issue #152149 https://code.google.com/p/chromium/issues/detail?id=152149

**Comment by laukstein** [comment]
**Update:** It doesn't happen to all users. Mozilla argues that happens if user earlier used Developer Tools > Responsive mode.

I can't reproduce this issue after Firefox and its settings total removal and fresh Firefox install.

**Comment by patrickkettner** [comment]
this was recently fixed in desktop firefox, sorry for leaving this open for such a long time without a response :[

**Comment by strann** [comment]
@patrickkettner where did you see this was fixed? I'm still seeing the issue in latest FF 48. It seems if you've ever used the responsive design view it may corrupt a related preference.

<img width="1317" alt="screen shot 2016-08-02 at 11 06 09 pm" src="https://cloud.githubusercontent.com/assets/1033786/17355495/d7bf5068-5905-11e6-9d43-7528cc3cff55.png">

**Comment by jsilvermist** [comment]
Still returns true for me no matter what in Firefox 52.
