### ISSUE TITLE
Installing using Build-URL via Bower uses wrong filename

### ISSUE THREAD

**Issue by thasmo** [Modernizr/Modernizr#1735]
That's my bower.json:
```json
{
  "name": "blah",
  "license": "MIT",
  "dependencies": {
    "modernizr": "https://modernizr.com/download?dontmin-setClasses-cssclassprefix:has-.zip"
  }
}
```

Running `bower install` creates these three files within the `bower_components/modernizr` directory:
* .bower.json
* bower.json
* bowerJSON.main

`bowerJSON.main` contains the actual custom Modernizr build and should be called `modernizr.custom.js` or something, I guess.

**Comment by patrickkettner** [comment]
why the close?

**Comment by thasmo** [comment]
Eh. :>

**Comment by thasmo** [comment]
It's not closed. :D

**Comment by thasmo** [comment]
You confused me with your confusion. :D

**Comment by patrickkettner** [comment]
oh. pft. 

![image](https://cloud.githubusercontent.com/assets/465414/10772590/1c7b8d7c-7cb4-11e5-9980-90473dcd48e4.png)

I am an idiot

was looking at the badge for the other issue, it popped up when you referenced it. 

Regardless, the fix for this is deploying now. Give it ~3 minutes

cheers!

**Comment by thasmo** [comment]
Hehe, thanks a lot!
