### ISSUE TITLE
Modernizr.datauri return Boolean

### ISSUE THREAD

**Issue by westyby** [Modernizr/Modernizr#1739]
http://modernizr.com/download/?-datauri-svg 

`console.log(Modernizr.datauri); `
has result:
`Boolean {over32kb: true, [[PrimitiveValue]]: true}`
But in docs return true or false
`Modernizr.datauri           // true or false`

**Comment by patrickkettner** [comment]
Hey @westyby!

not clear on what the question is - could you elaborate?

**Comment by westyby** [comment]
Hooked version of the library http://modernizr.com/download/?-datauri-svg
In the console output the Modernizr.datauri object. In the documentation it is written that should return either true or false http://joxi.ru/4AkEGEbS1WP1mq. 
But instead I returns Boolean 
`Boolean {over32kb: true, [[PrimitiveValue]]: true}`
In the end, the check will return false, although the HTML class puts datauri http://joxi.ru/LmGpjpxHbQx92l
`
if (Modernizr.datauri === true) {
    console.log('true');
} else {
    console.log('false');
}
`

**Comment by patrickkettner** [comment]
It is returning true. That is what the primitiveValue prop is. Is it breaking anything for you?

**Comment by westyby** [comment]
No, thanks. 
`if (Modernizr.datauri) { console.log('true'); } `
