### ISSUE TITLE
Add a valid license file (bower webjars)

### ISSUE THREAD

**Issue by mdedetrich** [Modernizr/Modernizr#1746]
Bower webjars (http://www.webjars.org/bower) is reporting the following error

>Failed! All attempts to determine a license have been exhausted. The bower.json did not contain a spec-compliant license definition and the license could not be determined by trolling through the GitHub repo. This problem will likely need to be resolved by working with the library maintainers directly. If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  Determined Artifact Name: modernizr Starting Deploy

This happens if a bower package doesn't have a valid license specified, would it be possible to update the package so you have a valid license defined?

**Comment by patrickkettner** [comment]
Hey there!
What bower package are you referring to?

**Comment by mdedetrich** [comment]
The one that results from `bower info modernizr`, I am personally trying to use release 2.8.3

**Comment by patrickkettner** [comment]
That is an unofficial bower package, as a result, we have no control over it. 

Sorry dude!

**Comment by mdedetrich** [comment]
Is there an official bower package?

**Comment by patrickkettner** [comment]
None in the registry. You can `bower install` any of the build URLs (listed at the top of any generated build file)

**Comment by mdedetrich** [comment]
Is it worth it to make an official bower package for Modernizr (is there already an issue for this?)

**Comment by patrickkettner** [comment]
Due to its modular nature, there can't be something in the registry. There are a number of issues about this in the repo if you search for bower
