### ISSUE TITLE
Detect data URI in links support with Modernizr

### ISSUE THREAD

**Issue by limonte** [Modernizr/Modernizr#1747]
Using data URI in links (<a href="data:) is not supported in IE and Microsoft Edge. MSDN claims that this is [for security reasons](https://msdn.microsoft.com/en-us/library/cc848897.aspx).

I'm trying to use Modernizr to detect data URI in links support.

`Modernizr.datauri` is not quite what I'm looking for, as it does not tell anything about support data URI **in links**, e.g. for Microsoft Edge it returns object `{over32kb: true}`

How can I detect using Modernizr if data URI in links is supported in browser?

**Comment by patrickkettner** [comment]
hi @limonte!

I would guess something similar to the following code _might_ work

```
Modernizr.addAsyncTest(function() {
  if (!("XMLHttpRequest" in window)) {
    Modernizr.addTest('dataurilinks', false)
  } else {
    var xhr = new XMLHttpRequest();
    xhr.open('GET', 'data:text/html, <html><head><title></title></head></html>');
    xhr.send(null);
  }

xhr.onreadystatechange = function () {
  if (xhr.readyState === 4) {
    Modernizr.addTest('dataurilinks', xhr.status === 200);
  }
})
```

I don't have the ability to test right at this moment, but let me know if it works.

**Comment by limonte** [comment]
@patrickkettner thank you for reply! Got this error: `Modernizr.addAsyncTest is not a function`. I'm using http://cdn.jsdelivr.net/modernizr/latest/modernizr.js (v2.8.3)

**Comment by patrickkettner** [comment]
You'll need to be using a build of Modernizr 3.0. Clone this repo, and create a new detect based on the same format of the detects inside of feature-detects

**Comment by patrickkettner** [comment]
@limonte any luck?
