### ISSUE TITLE
Can't generate "Development build" - all features

### ISSUE THREAD

**Issue by stopsopa** [Modernizr/Modernizr#1749]
Refactor problem:
go to homepage of Modernizr -> click Logo -> click big button on first view "Development build" -> this leads to page where all features of modernizr is checked -> then click Build and first download from list, and return file that content is:

    undefined

**Comment by stopsopa** [comment]
Hmm, now i understand what is going on, i should wait till "building..." finish, but still waiting for building ending should be handled more clearly.

Btw: Good job :)

**Comment by patrickkettner** [comment]
Hi @stopsopa!
This is actually the wrong repo. Modernizr/modernizr-neue is the website.
There is already an issue open for making this more clear, so no need to open another. Cheers, and thanks for the report
