### ISSUE TITLE
There is no button "Select all" on the list of features

### ISSUE THREAD

**Issue by stopsopa** [Modernizr/Modernizr#1750]
see page : https://modernizr.com/download?setclasses

PS: I know that i can select all features going to page:
https://modernizr.com/
and click button "Development build" but it's not obvious for all users i think.

**Comment by stopsopa** [comment]
Hmm, now i understand what is going on, i should wait till "building..." finish, but still waiting for building ending should be handled more clearly.

Btw: Good job :)

**Comment by patrickkettner** [comment]
Hi @stopsopa!
This is actually the wrong repo. Modernizr/modernizr-neue is the website. That being said, this is something that will be added, so there isn't a need for opening another issue.
