### ISSUE TITLE
touchevents true in canary  48 desktop

### ISSUE THREAD

**Issue by dwightjack** [Modernizr/Modernizr#1754]
Hi!

On Chrome Canary I got a false positive for `touchevents`, reported as `true`.

My system:
* OS: Windows 8 64bit
* Browser:  Chrome Canary 48.0.2563.0

Thanks for the great work on Modernizr!

**Comment by patrickkettner** [comment]
Thanks for the report @dwightjack, confirmed for me on canary as well. cc @paulirish

**Comment by patrickkettner** [comment]
opened a chrome bug in the mean time - https://code.google.com/p/chromium/issues/detail?id=555746&thanks=555746&ts=1447450862

**Comment by patrickkettner** [comment]
they are blocking Chrome Beta's release on this issue, so I closing this out for now
