### ISSUE TITLE
Include an already built file in the respository?

### ISSUE THREAD

**Issue by ahmadalfy** [Modernizr/Modernizr#1759]
Since version 3, development version of Modernizr (that includes all the features) is no longer available  (previously was in `dist/modernizr.js`) and you have to create it using `npm install` and `grunt`. I use `grunt-modernizr`, it generates a version specific to the features I use. That happens when I create the final build. During development, I used to include the development version that contained all the features.

Can you please include that file again? I don't want to run `npm-install` everytime I work on a project.

**Comment by patrickkettner** [comment]
Hey @ahmadalfy

We do not want to include that file because it is ridiculously large and people should not be using it. I know that in development it can be useful, but millions of websites shipped with the full version.

**Comment by ahmadalfy** [comment]
I can't disagree that around 90% of the people I saw using Modernizr used the full version ... And the reason is probably because this file was always included.

I understand your concern, I will build it myself everytime for development or perhapse use something like `postinstall` to build it automatically.

Thanks again @patrickkettner for all the awesomeness and contributions :)

**Comment by patrickkettner** [comment]
you can npm install a build using the URL form the file

e.g. `npm install https://modernizr.com/download?setclasses-emoji-ambientlight`

The full URL is ridiculously long, so if you wanted to go down this route a URL minifier like goo.gl can keep your package.json clean

**Comment by ahmadalfy** [comment]
:+1: will try that, thanks again
