### ISSUE TITLE
Add feature test for box-decoration-break

### ISSUE THREAD

**Issue by qikkeronline** [Modernizr/Modernizr#1762]
Recently I've been stumbling into use cases for the box-decoration-break property, but haven't implemented any as I havent found a way to write a feature test for this. Is this something that could be implemented into Modernizr?

Thanks, and kind regards,

Gerben van Dijk, Qikker Online

**Comment by patrickkettner** [comment]
Hey @qikkeronline 

Yep, totally!

`Modernizr.addTest('boxDecorationBreak', testAllProps(boxDecorationBreak', 'slice'))` should do the trick

**Comment by qikkeronline** [comment]
:ok_hand:

**Comment by patrickkettner** [comment]
@qikkeronline interested in creating a PR to add it to Modernizr?

**Comment by qikkeronline** [comment]
Yea, sure thing. Short on time atm, will look into it over the weekend and post back :)

**Comment by patrickkettner** [comment]
more than happy to help, if you want any. generator-modernizr-detect can
scaffold out a detect via yeoman if thats useful at all

On Thu, Nov 19, 2015 at 5:14 AM, Qikker Online <notifications@github.com>
wrote:

> Yea, sure thing. Short on time atm, will look into it over the weekend and
> post back :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Modernizr/Modernizr/issues/1762#issuecomment-158053719>
> .
>



-- 
patrick

**Comment by rejas** [comment]
@qikkeronline still interested in writing a PR for this even after this long time?

**Comment by qikkeronline** [comment]
Hi @rejas, i've added it to my task list to see if i can make some time for this in the near future :-) thanks for the mention!

**Comment by rejas** [comment]
Fixed via https://github.com/Modernizr/Modernizr/pull/2330
