### ISSUE TITLE
dupliacted npm 

### ISSUE THREAD

**Issue by yonatanmn** [Modernizr/Modernizr#1763]
Hi, 
What's the purpose of this :https://www.npmjs.com/package/modernizr2 ? 
Looks the same, different npm owner

**Comment by patrickkettner** [comment]
I am not sure. @van-nguyen, what is the purpose of modernizr2?

**Comment by van-nguyen** [comment]
To have consistent versioning and mirror what git has, the one on npm is really old.

**Comment by patrickkettner** [comment]
The one in github was updated 2 weeks ago.

**Comment by van-nguyen** [comment]
Okay sorry it was at the time of creation. 2 months ago it had the alpha 4 version or something and really messed up my gulpfile. I will update and remove. Cheers.

**Comment by patrickkettner** [comment]
looks like you published it about 26 hours before we published modernizr v3 - sorry for the delay in getting it out :)
