### ISSUE TITLE
Remove no-flexbox class for IE10

### ISSUE THREAD

**Issue by grayghostvisuals** [Modernizr/Modernizr#1764]
Since IE10 is given the ``.no-flexbox`` class it would be preferred to just have it use the ``.flexboxtweener`` class and remove the ``.no-flexbox`` class as it creates a bit of confusion since it does support flexbox; just the 2012 syntax.

Any other reasons to justify the approach I'd love to hear more on.

**Comment by patrickkettner** [comment]
Ah, ok. Understand what you mean now.

I would disagree. This is a detect for flexbox the API, not flexbox the concept. IE 10 does _not_ implement flexbox. It implements a version of flexbox based on an old outdated draft that works literally no where else. saying that it does support flexbox is disingenuous at best. There are no real codepaths that work for both versions of the spec.

**Comment by grayghostvisuals** [comment]
I see what you mean, but when ur targeting IE9 for example you get this…

```css
.no-flexbox .element {fallback styles}

.flexbox .element,
.flexboxtweener .element {flexbox styles}
```

or in this case IE10 still gets the ``no-flexbox`` styles.

```css
.no-flexbox .element {fallback styles}

.flexbox .element {flexbox styles}
```
I understand if you need to close the issue just wanted to give my opinion on the matter.

**Comment by patrickkettner** [comment]
yeah, i'd recommend `..no-flexbox.no-flexboxtweener .element`

Really appreciate the viewpoint, but I am gonna close it as a BYDESIGN sorta thing. If anyone else on the @Modernizr/team-modernizr disagrees, please reopen and we can discuss further

**Comment by stucox** [comment]
The updated docs for the `flexbox` feature actually cover this:

https://github.com/Modernizr/Modernizr/blob/docblocks/feature-detects/css/flexbox.js

(they haven't been merged yet — we should do that)

**Comment by patrickkettner** [comment]
wanna get the branch mergeable?

**Comment by stucox** [comment]
Yeah sure. I think there's a stack of conflicts now since Ryan & I both
made updates to the same docs, but I'll comb through them.
