### ISSUE TITLE
Mondernizr.on for WebP returns Boolean object

### ISSUE THREAD

**Issue by GeoffreyBooth** [Modernizr/Modernizr#1765]
In browsers that don't support WebP, something unexpected happens:

```
Mondernizr.on('webp', function (result) {
  if (result) {
    // Always runs, even if browser doesn't support WebP
  }
});
```

The value `result` in the above is a [Boolean object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean), _not_ a boolean primitive. A `new Boolean(false)` is still an object, and as a condition will evaluate as `true`, unlike a plain boolean `false`.

I suggest that this test be updated so that `result` is a boolean primitive `false` for browsers that don't support WebP.

As a workaround for now, here's my callback to work with the current implementation (CoffeeScript):

```
Modernizr.on 'webp', (result) ->
  webpSupport = if result?.valueOf? then result.valueOf() else no
```

**Comment by louisameline** [comment]
@patrickkettner I'm still getting a Boolean object from the modernizr website, modernizr 3.3.1 Custom Build. Hasn't this been rolled out? Thank you.
