### ISSUE TITLE
modernizr-config-sample.json file, containing all the possible detects, preferably with description

### ISSUE THREAD

**Issue by kremuwa** [Modernizr/Modernizr#1766]
Hello,

The modernizr documentation states, that using the node's modernizr package:

> you can quickly create multiple builds of Modernizr for different projects, without even having to open a new browser tab

It would probably be even more convenient, if there was a way to download a sample modernizr config file (e.g. modernizr-config-sample.json), which would contain all the possible feature detects and options (something similar to how it is [here](https://github.com/Modernizr/Modernizr/blob/master/lib/config-all.json)), all originally commented out. It would be even more beautiful, if over each detect there would be a description like the one on Modernizr's website, together with the helpful links leading to details.

Then, if we want to add a new feature detect to the project, we can simply uncomment the given line without the necessity to go to Modernizr's website (though it's really well optimized).

Thank You for the time taken to read it the issue, especially if it's nonsense :wink:

**Comment by patrickkettner** [comment]
Hey @kremuwa!
Its a bummer, but we _really_ don't want to make it easy to create the kitchen sink file, at least from the automation. It means that way more sites will ship bloated apps without realizing it.

It is intentionally inconvenient, as you should custom build the file you want. It is simple to migrate between versions or update through the site if you want to update and not touch the JSON itself. After creating or updating your build (using your existing build URL will auto check all of the things you had), tap on the BUILD button, then the Config File to get an updated version

thanks a lot for the feedback!

**Comment by kremuwa** [comment]
You're probably right. Particularly, I wasn't aware of the possibility of entering "existing build URL" into browser and getting the detects You decided to incorporate so far auto-checked.

Thanks for a quick reaction!

**Comment by patrickkettner** [comment]
cheers!
