### ISSUE TITLE
Builder on site returning undefined

### ISSUE THREAD

**Issue by pocesar** [Modernizr/Modernizr#1780]
I'm getting the file `modernizr-custom.js` with just `undefined` inside, using this url

https://modernizr.com/download?cookies-csstransforms-csstransforms3d-csstransitions-flexbox-flexboxlegacy-hashchange-history-hsla-inlinesvg-localstorage-opacity-placeholder-rgba-sessionstorage-svgasimg-svgfilters-setclasses

Happening on Firefox and Chrome. The devtools shows nothing wrong (script exception or such)

**Comment by patrickkettner** [comment]
@pocesar hmm... I am not [seeing the same thing](https://gist.github.com/patrickkettner/209b349e5ecdc0e41d89). Do you have any errors in devtools?

**Comment by pocesar** [comment]
@patrickkettner yes, it's showing now:

```
"Error: Error: Load timeout for modules: test/css/transforms
http://requirejs.org/docs/errors.html#timeout"
```

**Comment by patrickkettner** [comment]
interesting - are you on a slow internet connection by chance?

**Comment by pocesar** [comment]
nope, at least 15Mbit AFAIK, the latency is around 120ms to modernizr website

**Comment by patrickkettner** [comment]
hmm..Would you be able to get a HAR file from chrome showing the timeout?

**Comment by pocesar** [comment]
any pointers on how to do that?

**Comment by patrickkettner** [comment]
sorry, you have to reproduce the error with devtools open, rightclick inside of the network panel, and click "Save as HAR file"

**Comment by pocesar** [comment]
the resulting file is 6MB, where should I put it?

**Comment by patrickkettner** [comment]
whats strange is that it doesn't seem to be timing out in that response.
Are you seeting feature-detects/css/transforms as having timed out in the
networking panel?

patrick

On Fri, Nov 27, 2015 at 11:33 PM, Paulo Cesar <notifications@github.com>
wrote:

> the resulting file is 6MB, where should I put it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Modernizr/Modernizr/issues/1780#issuecomment-160256084>
> .
>



-- 
patrick

**Comment by pocesar** [comment]
it's being consistent on timing out, but not always on the same point. I got `css/transforms`, another time I tried it showed a problem with `createElement(...`, everytime it fails somewhere, but always reported as a timeout error from r.js

**Comment by patrickkettner** [comment]
which for the HAR file you posted?

**Comment by pocesar** [comment]
`Error: Error: Load timeout for modules: createElement(…)`
