### ISSUE TITLE
Using csshyphens test breaks anchors on page load

### ISSUE THREAD

**Issue by alexbaulch** [Modernizr/Modernizr#1781]
Steps to reproduce:
Load a page using the Modernizr csshyphens test with an anchor/hash in the URL e.g. https://github.com/#some-anchor-link

Observed behaviour:
Page initially moves to desired element but then jumps back up to the top of the page

Desired behaviour:
Anchors should be respected on page load.

Notes:
It took me an age to get to the bottom of this and I was concerned that I might not be correct about the cause of the issue so I created a standalone test. Below are links to two basic HTML files that reference a full development build of Modernizr with and without the csshyphens test. The one with csshyphens test creates the issue described above. The one without works as expected.

With hyphens:
http://alexbaulch.com/modernizr-hyphens-issue/modernizr-with-hyphens.html#section-3

Without hyphens
http://alexbaulch.com/modernizr-hyphens-issue/modernizr-without-hyphens.html#section-3

**Comment by ryanseddon** [comment]
@alexbaulch thanks for the detective work, think you can put together a PR to fix it?

**Comment by nibushibu** [comment]
I have same issue.

**Comment by BenjaminBeck** [comment]
same issue here, the page jumps to the top after executing the modernizr-script .
this also happens if you use the browser-back or reload button.
this is a big negative impact on usability for any site using this.

**Comment by bs-thomas** [comment]
I have the same issue.

**Comment by Sysix** [comment]
Any updates?

**Comment by usb248** [comment]
same issue

**Comment by rejas** [comment]
Debugged a little and it seems to me that those two lines are the culprits:

https://github.com/Modernizr/Modernizr/blob/c5ffa86ccfa56a4a898b9004ea7a3aa337a09551/feature-detects/css/hyphens.js#L157

https://github.com/Modernizr/Modernizr/blob/c5ffa86ccfa56a4a898b9004ea7a3aa337a09551/feature-detects/css/hyphens.js#L170

Not sure how to replace the code or make it better, PRs are welcome :-)

**Comment by rejas** [comment]
PR was already there: https://github.com/Modernizr/Modernizr/pull/1633
Has to be tested though

**Comment by theLine** [comment]
Hi, I just purposed an other PR #2369 to this issue.
I think that saving the scroll position and restoring it, like in PR #1633, isn't a nice solution, because it won't really prevent the jumping (on really fast machines at least).

Unfortunately I wasn't able to really test it on many browsers/machines.

What do you think of this?
