### ISSUE TITLE
Benefit of using Modernizr

### ISSUE THREAD

**Issue by jt4000** [Modernizr/Modernizr#1788]
I don't understand about this tool.

*What is the benefit to use this tool for web development? What can this tool facilitate my way of working as a web developer?

**Comment by patrickkettner** [comment]
Hey @jt4000!

Check out [the documentation](https://modernizr.com/docs)

cheers

**Comment by jt4000** [comment]
Do you have any concrete example that  Modernizr can easily tailor the user's experiences? Any concrete functionality or something else as a proof that can convince me to use Modernizr?

Thanks!

**Comment by patrickkettner** [comment]
As with any javascript library, if you don't have a reason to use it, you
probably shouldn't be.

The point of Modernizr is to let you easily check for features, rather then
using a user-agent sniff. If you are not using any kind of user agent
sniff, and do not have any issues with your users having broken experiences
from older browsers, then you are good to go and don't need Modernizr.

On Sun, Dec 6, 2015 at 2:32 AM, jt4000 <notifications@github.com> wrote:

> Do you have any concrete example that Modernizr can easily tailor the
> user's experiences? Any concrete functionality or something else as a proof
> that can convince me to use Modernizr?
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Modernizr/Modernizr/issues/1788#issuecomment-162284881>
> .
>



-- 
patrick
