### ISSUE TITLE
what-input style test?

### ISSUE THREAD

**Issue by FezVrasta** [Modernizr/Modernizr#1790]
I was wondering if Modernizr could be capable of run a test that would change an html class defining which kind of input method was used the last time.

The idea would be to replace https://github.com/ten1seven/what-input with a Modernizr test (hence, remove a dependency)

Thanks.

**Comment by patrickkettner** [comment]
Hey @FezVrasta!
This isn't really something Modernizr is for (detecting features of the browser). Since the test would be more or less porting their code, it really wouldn't be removing anything in the end, just changing filenames.

cheers!
