### ISSUE TITLE
a[download] attribute test fails in Edge

### ISSUE THREAD

**Issue by sirbarrence** [Modernizr/Modernizr#1793]
Even though the anchor `download` attribute [reportedly works](http://caniuse.com/#search=download) in Edge and I have confirmed it works in some private code, the [Modernizer test for it](https://github.com/Modernizr/Modernizr/blob/master/feature-detects/a/download.js) fails because the download property is not initially present on the new anchor element object Edge creates.

Not sure of another way to test for it in a generic way though.

**Comment by patrickkettner** [comment]
Hey @sirbarrence!
which version of Edge are you using?

**Comment by sirbarrence** [comment]
`navigator.userAgent` says 12.10240 but the About info in Settings says 20.10240.16384.0. I assume it's the latest version since no Windows Updates are available.

Windows 10 Enterprise 64-bit

**Comment by patrickkettner** [comment]
That is actually not the latest version ( I work on Edge :D )
[Here is a brief explanation between the version discrepancy](https://blogs.windows.com/msedgedev/2015/09/21/understanding-versions-in-an-evergreen-browser/)

`download` only exists for version 13+

**Comment by sirbarrence** [comment]
Sorry, I was confused. I was using [FileSaver.js](https://github.com/eligrey/FileSaver.js/) and because it was working fine in Edge and FileSaver.js uses the download attribute to make things work in some browsers, I was drawing the erroneous conclusion that my version of Edge had the download attribute. FileSaver.js must be using some other technique to make Edge < 13 work. Safari 9 doesn't have the download attribute and FileSaver.js doesn't work there at all, so I was using the download attribute test to avoid trying & failing to use FileSaver.js there. I'll just `||` in a userAgent check for Edge. Thanks.

**Comment by patrickkettner** [comment]
Edge has some weird proprietary methods leftover from IE (whodathunkit), like `msSaveOrOpenBlob`. Could be using one of those?

**Comment by rhessus** [comment]
[FileSaver.js](https://github.com/eligrey/FileSaver.js/) use `msSaveBlob()` for Edge.

But `msSaveBlob()` and `msSaveOrOpenBlob()` don't work with Edge on WindowsPhone :(
I have a `NotImplemented` exception !
