### ISSUE TITLE
Install a custom build via npm

### ISSUE THREAD

**Issue by jenslind** [Modernizr/Modernizr#1796]
Hello!

I am trying to install a custom build via npm.

When I run:
```
npm install https://modernizr.com/download/\?csstransforms-csstransforms3d-csstransitions-svg-domprefixes-prefixes-setclasses-shiv-testallprops-testprop-teststyles-.tar
```
It downloads the custom build, but the wrong one.
All I get is a custom build with `dontmin`:
```
...
* modernizr v3.2.0
* Build http://modernizr.com/download?--dontmin
...
```

Running npm `v3.5.1`

**Comment by patrickkettner** [comment]
:(

there was a stupid bug in the implementation. I just fixed it, and it should be live in a few minutes. i'll close once I confirm that build is working

**Comment by patrickkettner** [comment]
thanks so much for reporting!

**Comment by patrickkettner** [comment]
cleared up, was an issue with the website, rather than modernizr itself.

thanks again!

**Comment by jenslind** [comment]
Nice! Thanks for fixing this so quick. :)
