### ISSUE TITLE
Builder read from Master HEAD?

### ISSUE THREAD

**Issue by KayLeung** [Modernizr/Modernizr#1802]
Builder generated code commented as "modernizr 3.2.0" but it actually given different code. (seems like from HEAD)

For example:
http://modernizr.com/download/?-details-inputtypes-touchevents-addtest-prefixes-teststyles

It contains code from 
https://github.com/Modernizr/Modernizr/commit/695fd5ef3cad5b867785d5cff471d52a49aa82a7
(13 days ago only.)

**Comment by patrickkettner** [comment]
yep, that is the case
