### ISSUE TITLE
Use custom attribute for supported features

### ISSUE THREAD

**Issue by thasmo** [Modernizr/Modernizr#1804]
Would be cool to be able to configure Modenizr to use a custom attribute instead of the class names, e.g.:
```html
<html data-supports="js touch localstorage">
```
Thoughts?

**Comment by patrickkettner** [comment]
Why's that?

**Comment by patrickkettner** [comment]
ping @thasmo

**Comment by thasmo** [comment]
I think it's neither a big nor needed feature, but it makes reading the DOM a bit easier when there are other CSS classes assigned to the `html` element, either in the markup or set by other scripts. In addition this yields the benefit of preventing other scripts accidently messing with the modernizr classes. After all, it was just an idea and maybe not worth the effort to implement. Feel free to comment and/or close it. :)

**Comment by patrickkettner** [comment]
I haven't really ever encountered any of the issues, so I don't personally see the value

thoughts, @ryanseddon ?

**Comment by thasmo** [comment]
One more thought; it also acts as a kind of prefix, i.e. instead of using the class name prefix, a custom attribute can be used. Again, really nothing big, just want to bring it up.

**Comment by ryanseddon** [comment]
@thasmo we haven't seen any ask or need for this so I'm a :-1: on this.
