### ISSUE TITLE
detect function.prototype.bind

### ISSUE THREAD

**Issue by kocoten1992** [Modernizr/Modernizr#1810]
As the link follow, some browser do not support bind method. Can't find detect for it

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind#Polyfill

**Comment by patrickkettner** [comment]
a detect for it would be `'bind' in Function.prototype` - would you be interested in creating a pull request with it?

**Comment by kocoten1992** [comment]
I'll give it a try, is there any link/help to wrote a detect, can't seem to find it, hah should have doc to help wrote new detect method too :grin:

**Comment by patrickkettner** [comment]
you can copy one of the simpler tests - [like appcache](https://github.com/Modernizr/Modernizr/blob/master/feature-detects/applicationcache.js). just replace the metadata and actual detect. Then make sure to add it to the list in lib/config-all

**Comment by kocoten1992** [comment]
uhm @patrickkettner , if travis-ci fail can you still merge it? never use travis before, don't know, if could please do, thank you :+1:

**Comment by patrickkettner** [comment]
you'll want to look at the travis results to see why it is failing. alternativly, run `npm test` on your computer to get the same results

**Comment by kocoten1992** [comment]
Actually, my mistake, in feature-detects/es5 , it was specific test for bind prototype as 'es5function' test, but thank you anw :)

**Comment by kocoten1992** [comment]
PS: the 'bind' test was special case, it should have show on modernizr.com/download to clear confusion
