### ISSUE TITLE
Q: what is the "heartz" property in the feature-detect Touchevents

### ISSUE THREAD

**Issue by aaarichter** [Modernizr/Modernizr#1814]
what is `heartz` for?
```js
var query = ['@media (',prefixes.join('touch-enabled),('),'heartz',')','{#modernizr{top:9px;position:absolute}}'].join('');
testStyles(query, function( node ) {
  bool = node.offsetTop === 9;
});
```

**Comment by patrickkettner** [comment]
I know it is just a random string, it used to be `modernizr`, but I honestly don't remember the reasoning for it. @paulirish [you added it](https://github.com/Modernizr/Modernizr/commit/1cecd6a9660381dcd20d0f5766687edff17c8cf7) - do you remember?

**Comment by paulirish** [comment]
Oh just random. A word you'll see when slex and I are talking.

**Comment by SlexAxton** [comment]
It's long-hand for <3z

**Comment by patrickkettner** [comment]
I meant why do we include a random word

**Comment by paulirish** [comment]
Because we need something that'll be a non matching MQ to help terminate
the join()

It could probably be done another way but I didn't want to change the
prefixes array and such.

**Comment by stucox** [comment]
This is what comments are for :-D
