### ISSUE TITLE
Modernizr.csstransforms3d returns false negative in chrome iFrame

### ISSUE THREAD

**Issue by jedierikb** [Modernizr/Modernizr#1817]
See https://github.com/Modernizr/Modernizr/issues/590 for details and https://code.google.com/p/chromium/issues/detail?id=129004 for some background

**Comment by rezende** [comment]
Does this work on the latest versions of the library ? I am using an old Modernizr version (2.7.1) and it's not working either.

**Comment by rejas** [comment]
I assume it was fixed with this commit: https://github.com/Modernizr/Modernizr/commit/0239cb14df57cf884fdc717781809a5f96383747 
Can you try version 3.6.0 and report back if it is fixed for good?

**Comment by rezende** [comment]
@rejas Will test and get back to the thread. Thanks a lot!

**Comment by rezende** [comment]
It worked!

**Comment by rejas** [comment]
Good to hear. Closing this issue therefore.
