### ISSUE TITLE
Tests is undefined

### ISSUE THREAD

**Issue by schemetastic** [Modernizr/Modernizr#1818]
I made a custom build and the console shows me two critical errors:
First:
<pre>TypeError: tests is undefined
ModernizrProto.addTest()
 modernizr-custom.js:3
<anónima>
 modernizr-custom.js:3
<anónima>
 modernizr-custom.js:3
</pre>
Second:
<pre>
NetworkError: A network error occurred.
</pre>

This is my custom build:
<pre>
{
  "minify": true,
  "options": [
    "domPrefixes",
    "prefixes",
    "addTest",
    "atRule",
    "hasEvent",
    "mq",
    "prefixed",
    "prefixedCSS",
    "prefixedCSSValue",
    "testAllProps",
    "testProp",
    "testStyles",
    "html5printshiv",
    "html5shiv",
    "setClasses"
  ],
  "feature-detects": [
    "test/audio",
    "test/blob",
    "test/canvas",
    "test/contenteditable",
    "test/cookies",
    "test/eventlistener",
    "test/htmlimports",
    "test/inputtypes",
    "test/json",
    "test/svg",
    "test/touchevents",
    "test/video",
    "test/webgl",
    "test/a/download",
    "test/css/animations",
    "test/css/backgroundsizecover",
    "test/css/borderradius",
    "test/css/boxshadow",
    "test/css/boxsizing",
    "test/css/calc",
    "test/css/displaytable",
    "test/css/gradients",
    "test/css/lastchild",
    "test/css/mediaqueries",
    "test/css/nthchild",
    "test/css/remunit",
    "test/css/rgba",
    "test/css/textshadow",
    "test/css/transforms",
    "test/css/transforms3d",
    "test/css/transformstylepreserve3d",
    "test/css/transitions",
    "test/css/userselect",
    "test/es5/specification",
    "test/file/api",
    "test/file/filesystem",
    "test/forms/validation",
    "test/storage/localstorage",
    "test/svg/asimg",
    "test/svg/clippaths",
    "test/svg/filters",
    "test/svg/inline",
    "test/textarea/maxlength",
    "test/url/bloburls",
    "test/url/data-uri"
  ]
}
</pre>

**Comment by ryanseddon** [comment]
That config you pasted is not the correct shape, take a look at the example [lib/config-all.json](https://github.com/Modernizr/Modernizr/blob/master/lib/config-all.json).

It should look like this:

```json
{
  "minify": true,
  "options": [
    "setClasses",
    //...
  ],
  "feature-detects": [
    "test/svg/filters",
    //...
  ]
}
```

You can also copy the correct config to your clipboard via the https://modernizr.com/download page

**Comment by schemetastic** [comment]
I already corrected the data, sorry i had copied the grunt config.

**Comment by ryanseddon** [comment]
Oh is this for grunt-modernizr? You should file your issue there https://github.com/Modernizr/grunt-modernizr

**Comment by schemetastic** [comment]
No, i used the Custom Build download, but when you click the button "Build" it prompts a modal with three options and one of them is the "Grunt Config", the corrected post uses the same i used in the:
https://modernizr.com/download
I attached in a zip file my custom build if you want to test it yourself.
[modernizr-custom.js.zip](https://github.com/Modernizr/Modernizr/files/70309/modernizr-custom.js.zip)

**Comment by ryanseddon** [comment]
I just created my own build and ran it with the cli tool and that generates and works correctly in the browser. Do you have any problems with the other methods of getting a built file or is it just gulp?

**Comment by schemetastic** [comment]
I made another custom build and it doesn't shows me the first error but still shows me the error:
<pre>
NetworkError: A network error occurred.
</pre>

**Comment by patrickkettner** [comment]
could you post a sscreenshot of the error?

On Tue, Dec 22, 2015 at 7:38 PM, Rodrigo Isaías Cálix <
notifications@github.com> wrote:

> I made another custom build and it doesn't shows me the first error but
> still shows me the error:
>
> NetworkError: A network error occurred.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Modernizr/Modernizr/issues/1818#issuecomment-166796475>
> .
>



-- 
patrick

**Comment by schemetastic** [comment]
This was the error that appeared when i made the first custom build:
![captura de pantalla de 2015-12-22 21 46 06](https://cloud.githubusercontent.com/assets/16121280/11970783/8aa1b858-a8f6-11e5-9824-966168418322.png)

The Network Error Seems that it is caused by another script, and now it is solved, misteriously when i implement modernizr 2.8.3 says that the error is caused by it, that is another story.

With the new custom build now the error is gone.

**Comment by patrickkettner** [comment]
thanks for working it out with us

**Comment by schemetastic** [comment]
No problem, thanks for taking the time to give support.

**Comment by bugnano** [comment]
There is a bug in the web builder of Modernizr, in the sense that if I build Modernizr from the command line, everything works fine.

But, if I bulid Modernizr from the Web (https://modernizr.com/download?setclasses), the generated file does not work, as it is missing the

var tests = [];

line.

**Comment by patrickkettner** [comment]
@bugnano I am not able to reproduce this. Can you give me the specific build you are using to build that is getting this ur?

**Comment by bugnano** [comment]
I don't know whether something has changed in the web builder or not since I reported the bug, but at the time of reporting the bug it did not work, now I tried the same build, and everything works.
