### ISSUE TITLE
Typo in indexeddbblob-test

### ISSUE THREAD

**Issue by JaZo** [Modernizr/Modernizr#1834]
There is a typo in the indexeddbblob-test which prevents it from running.

In the indexeddb-test 'indexeddb.deletedatabase' is written all lowercase, but the indexeddbblob-test checks for it camelCase 'indexeddb.deleteDatabase'.

In indexeddb-test
```javascript
Modernizr.addTest('indexeddb.deletedatabase', 'deleteDatabase' in indexeddb);
```
In indexeddbblob-test
```javascript
if (!(Modernizr.indexeddb && Modernizr.indexeddb.deleteDatabase)) {
    return false;
}
```

**Comment by patrickkettner** [comment]
fixed in #1835
