### ISSUE TITLE
False negative for @font-face on Android Firefox

### ISSUE THREAD

**Issue by zipper** [Modernizr/Modernizr#1851]
I have a false negative detection of @font-face support on Android 4.4.2 with Firefox 43.0 in latest modernizr (3.3.1).

The `blacklist` function returns true for this combination as `wkvers` is `null` and `ua` match Android regexp. In previous version of modernizr (2.8) the detection was fine.

**Comment by lordlouis** [comment]
Same behavior on Firefox 46.0.1 Stable for Android, with modernizr 3.3.1 (Custom Build) [http://modernizr.com/download/?-csstransforms-fontface-formvalidation-input-inputtypes-domprefixes-mq-setclasses-testallprops-testprop-teststyles](url)

Tested on Samsung Galaxy S5 (cyanogenmod 12.1),  Samsung SM-G531H (Android 5.1.1), Samsung  SM-J110M (Android 5.1.1), Zumm P50 (Android 4.2.2)

On Firefox 3.0(11) for Iphone 4s is working properly
