### ISSUE TITLE
Swap touchevents/no-touchevents class

### ISSUE THREAD

**Issue by matyushen** [Modernizr/Modernizr#1856]
Is it possible to swap the touchevents/no-touchevents classes same way like js/no-js? I set `no-touchevents` class initially on the `html` and I expected it to be swaped with `touchevents` when needed. But I either end up with `no-touchevents no-touchevents` or `no-touchevents touchevents`. 

The build: https://modernizr.com/download?touchevents-dontmin-setclasses

Thanks!

**Comment by roblarsen** [comment]
Why would you need to do that?

**Comment by matyushen** [comment]
Forget it, it turned out I accidentally added Modernizr in the footer. That was the reason of FOUC.
