### ISSUE TITLE
Missing dependencies with bower install

### ISSUE THREAD

**Issue by benwalsh** [Modernizr/Modernizr#1857]
When I install modernizr using `bower`, it cannot find its dependencies. Even if I also install it via `npm` and all those dependencies are included.

```
$ bower install modernizr
bower modernizr#*               cached git://github.com/Modernizr/Modernizr.git#3.3.1
bower modernizr#*             validate 3.3.1 against git://github.com/Modernizr/Modernizr.git#*

$ vendor/assets/components/modernizr/bin/modernizr 
module.js:338
    throw err;
          ^
Error: Cannot find module 'lodash'
```

I end up having to `npm install loadash --save` manually. Should the dependency chain take care of this, or am I doing something .... _wrong_?

**Comment by patrickkettner** [comment]
You have to run npm install after doing this. 

That being said, this is probably not what you want. That downloads the builder, not the detection library. 

What is it you are trying to do?

**Comment by benwalsh** [comment]
Well, all I really want is a clean build of modernizr, and I can just check the built version into source -- in fact, that's what we're doing now.

The goal of the current exercise is to run the `npm` and `bower` invocations and end up with the `modernizr.js` script in my `lib/` directory.

Running `npm install modernizr` and `bower install modernizr` creates the modernizr directory with all the files I need, but then when I try to run the binary executable it complains about missing dependencies. I install them by hand with `npm install` and then I can run `bin/modernizr` and everything's OK. I just thought that the nature of `npm` / `bower` would be to include the dependencies.

**Comment by patrickkettner** [comment]
> Well, all I really want is a clean build of modernizr, and I can just check the built version into source 

Then you don't want to do this. As mentioned, this is the builder, not the file. as of modernizr 3, there is no monolithic file anymore. It doesn't really make sense to have a single published file. However, you _can_ `npm`/`bower` install any modernizr download url. That is, `npm install https://modernizr.com/download-ambientlight-csscalc`, etc. 

> The goal of the current exercise is to run the npm and bower invocations and end up with the modernizr.js script in my lib/ directory.

see above comment

> Running npm install modernizr and bower install modernizr creates the modernizr directory with all the files I need, but then when I try to run the binary executable it complains about missing dependencies
`npm install` should not result in this, `bower install` should. Bower does no install anything other than the bower dependencies, of which modernizr has none.

hope that helps!
