### ISSUE TITLE
Remove class="js" from html element on window.onerror

### ISSUE THREAD

**Issue by justmarkup** [Modernizr/Modernizr#1862]
As mentioned in the documentation the js class on the html element is often used to hide certain elements that should only be exposed in environments that execute JavaScript. This works fine as long as the JavaScript is executed correctly and no error occurs. 

Therefore I would suggest adding a ```window.onerror``` function to remove the js class and set it back to no-js if there is an error:

```
window.onerror = function () {
  document.documentElement.className = document.documentElement.className.replace(/\bjs\b/,'no-js');
}
```
This way sites would still be usable if the JavaScript failed for whatever reason.

I wrote more about it here https://justmarkup.com/log/2016/02/rethinking-setting-classjs-to-hide-elements-if-js-available/

What do you think about it?

**Comment by patrickkettner** [comment]
I don't like it. If there is a js error then js is available. If what someone wants to configure their own site to work this way soon though more power to them but I do not think this is a good decision for libraries as large as modernizer to make.

**Comment by justmarkup** [comment]
Okay, I fully understand that removing the .js class for every error may be to excessive. 

I like to be on the save side and rather deliver the working not so perfect "no-js" version than the js version where parts become inaccessible and unusable because of a JavaScript error. I quiet often experience broken sites and often if I turn off JavaScript or set the .js class via DevTools to .no-js the site is working again. As a user this can be quite annoying.

At the moment the documention about no-js says:

> This lets hide certain elements that should only be exposed in environments that execute JavaScript. 

Maybe it would be helpful to add a note clarifying that hiding elements with the .js class should be done advisedly and that a JavaScript error may make this elements inaccessible.

Thanks.

**Comment by patrickkettner** [comment]
I would be more than happy to merge a PR from you upgrading the docs - they were [here](https://github.com/Modernizr/modernizr-neue/blob/bff484323dd1e49684e3cb04a7146f008460e09b/docs/intro.md)

cheers!
