### ISSUE TITLE
Rel Preload Support?

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [Modernizr/Modernizr#1880]
Possible to add rel preload support feature detection like the link below to Modernizr?

https://gist.github.com/igrigorik/a02f2359f3bc50ca7a9c

**Comment by patrickkettner** [comment]
Hiya @vijayaraghavanramanan!

Unfortunately, not really. `tokenList.supports` is a super new API, that is only supported in chrome currently. It WILL be a great feature detect in the future, but right now a ton of browsers support it that can't be accurately detected with this code

**Comment by vijayaraghavanramanan** [comment]
Hi @patrickkettner 

It's not true that browsers support it now. That's prefetch not preload. Even Chrome is not yet supporting it, just Canary. Hopefully the version at the end of the month will have it. 

It's too early in fact to incorporate as other browsers will take more time to implement it, but I hope you consider including it in Modernizr as it's convenient for users to use Modernizr.

**Comment by patrickkettner** [comment]
sorry, misread was a failure on my part. But we can't use a feature detection that required another thing that should be feature detected. 

Anyone interested in this API will certainly find the wonderful posts that the google team has put out about how to do so

**Comment by vijayaraghavanramanan** [comment]
As you wish. Later this year all new browser versions will have preload ... will tell you "told you so"!
