### ISSUE TITLE
HTML5 Cross Browser Polyfills Wiki page is outdated

### ISSUE THREAD

**Issue by jhfrench** [Modernizr/Modernizr#1890]
[The HTML5 Cross Browser Polyfills Wiki page](https://github.com/Modernizr/Modernizr/wiki/HTML5-Cross-Browser-Polyfills) includes this text:

> Looking to conditionally load these scripts (client-side), based on feature detects?
> 
> See Modernizr.

[Modernizr no longer supports the `load()` method.](https://modernizr.com/news/modernizr-3-new-release-site#apis)

**Comment by ryanseddon** [comment]
I believe anyone can edit the wiki please update.
