### ISSUE TITLE
Add feature test for passive event listener support

### ISSUE THREAD

**Issue by RByers** [Modernizr/Modernizr#1894]
For [passive event listeners](https://github.com/RByers/EventListenerOptions/blob/gh-pages/explainer.md), feature detection is important but [non-trivial](https://github.com/RByers/EventListenerOptions/blob/gh-pages/explainer.md#feature-detection).

I don't have much experience with Modernizr but I can try to post a feature detect for this if desired.

**Comment by patrickkettner** [comment]
Yes please! Happy to guide you through it, too

**Comment by paulirish** [comment]
Here's the test (and use) for event listener options and its passive option:

```js
var supportsPassive;

var opts = Object.defineProperty({}, 'passive', {get: function(){ supportsPassive = true }});
document.createElement('div').addEventListener('test', function() {}, opts);

elem.addEventListener('touchstart', fn, supportsPassive ? { passive: true } : false); 
```

**Comment by ryanseddon** [comment]
The terse option seems better we can just wrap in a `try catch` for older browsers.

**Comment by foolip** [comment]
Since the listener argument is nullable and addEventListener does nothing in that case, one can avoid the temporary element altogether, so:
```JavaScript
var supportsPassive = false;
try {
  document.addEventListener("test", null, { get passive() { supportsPassive = true }});
} catch(e) {}
```

**Comment by foolip** [comment]
(If brevity is a plus, one can also omit `document.` as `window` is also an `EventTarget`.)

**Comment by WebReflection** [comment]
IE8 *has* `Object.defineProperty` and it throws errors with non built-in objects. The `&&` doesn't guard from throwing

**Comment by paulirish** [comment]
Good call. Thx

Latest version is now over here: https://github.com/WICG/EventListenerOptions/pull/30#issuecomment-207420765

**Comment by mgol** [comment]
@ryanseddon You can't test syntax using try-catch, the whole thing will just not parse.

**Comment by ryanseddon** [comment]
@mgol yep, we did `try { eval() } catch() {}` for ES2015 syntax feature tets but this is different to those.

**Comment by RByers** [comment]
Should I do something to get this listed in https://modernizr.com/docs?

**Comment by patrickkettner** [comment]
it'll be listed automatically once I cut a new release, which will probably be tonight

**Comment by RByers** [comment]
Great, thanks!

**Comment by patrickkettner** [comment]
​thank YOU

**Comment by amritk** [comment]
Any word on getting this into a release?

**Comment by KenjiBaheux** [comment]
From a quick look, I didn't find a mention of passive event listener in https://modernizr.com/docs
Is the release coming soon?

Thanks in advance!

**Comment by enjikaka** [comment]
Doesn't seem to be released yet. I dropped the 

```
Modernizr.addTest('passiveeventlisteners', function() {
    var supportsPassiveOption = false;
    try {
      var opts = Object.defineProperty({}, 'passive', {
        get: function() {
          supportsPassiveOption = true;
        }
      });
      window.addEventListener('test', null, opts);
    } catch (e) {}
    return supportsPassiveOption;
  });
```

into my modernizr build locally for now. When will this be released? @patrickkettner

**Comment by Bamieh** [comment]
How about cleaning up the event listener after adding finishing the test?

```javascript
Modernizr.addTest('passiveeventlisteners', function() {
    var supportsPassiveOption = false;
    try {
      var opts = Object.defineProperty({}, 'passive', {
        get: function() {
          supportsPassiveOption = true;
        }
      });
      window.addEventListener('test', null, opts);
      window.removeEventListener('test', null, opts);
    } catch (e) {}
    return supportsPassiveOption;
  });
```

**Comment by WebReflection** [comment]
@Bamieh ... cleaning a `null` listener ? I hope browsers are smart enough to realize it's pointless regardless :-)

**Comment by Bamieh** [comment]
@WebReflection browsers will always disappoint you! no but seriously, nothing in the spec mentions testing the EventListener interface for null, hence the listener will stay registered. (1.3.1.)

**Comment by WebReflection** [comment]
Does it throw if it's triggered? What do specs say about dealing with null listener on dispatch? Anyway, i'm for cleaning up too, I just think in this case might be effectively unnecessary.

**Comment by Bamieh** [comment]
Okay after further investigation,
`window.addEventListener('test', null, opts)`
does not add an event listener to the window object in the first place, hence no need to remove anything.
Only tested on chrome though.
`getEventListeners(window) // test is not listed in the object.`

**Comment by RByers** [comment]
> nothing in the spec mentions testing the EventListener interface for null, hence the listener will stay registered. (1.3.1.)

 Spec is [here](https://dom.spec.whatwg.org/#dom-eventtarget-addeventlistener).  Step 2: "If callback is null, terminate these steps."

**Comment by bgirard** [comment]
Looking at the spec here step 3 'Let capture, passive, and once be the result of flattening more options.' will happen after the step 2 early return. If I'm interpreting this correctly, this feature detection isn't spec compliant and likely most browsers aren't either given that this works in practice.

Perhaps the spec should be changed to explicitly allow for feature detection in this way?

**Comment by patrickkettner** [comment]
hi @bgirard!
I _think_ you are misreading them, but it could very well be my own misunderstanding. 

@domenic @RByers @annevk is @bgirard correct that the `.passive` property should not be being accessed by browsers without a callback also being defined (according to the spec)?

**Comment by domenic** [comment]
That's incorrect; it's accessed by the Web IDL bindings which convert the incoming object into a dictionary, and take place before any of the algorithm steps. I can appreciate that being pretty subtle though for those not familiar with Web IDL.

**Comment by patrickkettner** [comment]
thanks for the quick response!

**Comment by bgirard** [comment]
Thanks for clarifying. That means that this snippet works, unsurprisingly.

What about the spec being misleading in the way that step 2 and 3 is ordered? The spec is describing the flattening behavior that is occurring in Web IDL. Should we open a spec issue to re-order these steps to make it explicit that flattening should occur before the early return on a null callback?

**Comment by domenic** [comment]
The Web IDL conversion from object to dictionary and the "flattening" are orthogonal. Flattening operates on either a boolean or a dictionary; objects are never involved. There's no need to reorder the steps. It's not misleading to people who understand Web IDL, which again, I understand is not too many non-implementers. But you're looking at the algorithm for implementers, anyway.

**Comment by bgirard** [comment]
Ohh I understand now. Thank you for clarifying!

**Comment by eladkarako** [comment]
without using <code>Object.defineProperty</code>:
```js
//this variation will support more low-end/headless browsers.
self.is_support_passive = (function(){ "use strict";
  var is_support_passive = false
     ,opts               = {}
     ;

  function getter(){
    is_support_passive = true;
    return true;
  }

  function event_handler(ev){
    return true;
  }

  try{
  Object.prototype.__defineGetter__.call(opts, "passive", getter);
  window.addEventListener("touchend",    event_handler, opts);
  window.removeEventListener("touchend", event_handler, opts);
  }catch(err){}

  return is_support_passive;
}());

console.log(
  self.is_support_passive
);
```
<h4>If a browser is lacking <code>Object.defineProperty</code>,<br/>
it is most-likely too old to support passive events.<br/><br/>
But since we're not checking the availability of <code>Object.defineProperty</code>,<br/>
using the example above is a (slightly) better-practice,<br/>
since it relays on an older feature, and limits <code>try/catch</code> to the very core.<br/><br/><br/>Passing <code>null</code> will make a few <em>passive-compatible</em> versions of spider-monkey to <a href="#explanation_needed">fail silently</a><br/>- and will give you a false-<em>passive -is-unavailable</em> status. Therefore it is a bad practice.<br/></h4>

**Comment by WebReflection** [comment]
hey, if you assign a variable like this `opts = {}` you might as well know this is absolutely a redundant operation `Object.prototype.__defineGetter__.call(opts, "passive", getter);` 'cause the following one is exactly the same in 1/3rd of the code `opts.__defineGetter__("passive", getter);`

Moreover, this is not a "_most-likely_", this is a certain statement:
> If a browser is lacking Object.defineProperty it is most-likely too old to support passive events

there is no browser on earth that would implement passive events without being compatible with ES5 so the code is **just fine** as it is
