### ISSUE TITLE
"svg context: is able to be loaded in a SVG file" test is failing in Edge

### ISSUE THREAD

**Issue by AmazingJaze** [Modernizr/Modernizr#1900]
100% repro in the master branch of Modernizr on Edge. However, doesn't repro in [v3.3.1](https://github.com/Modernizr/Modernizr/tree/v3.3.1)

`Error: expected 'Unable to set property \'cssText\' of undefined or null reference http://localhost/TestContent/Modernizr/master/dist/modernizr-build.js 4478 5' to equal undefined
at Assertion.prototype.assert (http://localhost/TestContent/Modernizr/master/node_modules/expect.js/index.js:102:7)
   at Assertion.prototype.equal (http://localhost/TestContent/Modernizr/master/node_modules/expect.js/index.js:216:5)
   at Anonymous function[name] (http://localhost/TestContent/Modernizr/master/node_modules/expect.js/index.js:69:13)
   at object.onerror (http://localhost/TestContent/Modernizr/master/test/browser/integration/svg.js:19:13)
`

I can see that a change was made in feature-detects/css/transformstylepreserve3d.js that is setting CSSText

https://github.com/Modernizr/Modernizr/compare/v3.3.1...master

**Comment by AmazingJaze** [comment]
https://github.com/Modernizr/Modernizr/blob/9b9903953a0415ddcb09d663a85efb1830eb55ba/src/createElement.js#L19

The root cause is that the Object returned by `document.createElementNS('http://www.w3.org/2000/svg', "div")` doesn't have the style property in Edge. 

First introduced by with https://github.com/Modernizr/Modernizr/commit/220198b3f863244d21398da42315e2287c694295 to address a preserve3D test issue on IE11. But when I try this in IE11 on a recent build of Windows 10, the object returned doesn't have the style property either

**Comment by AmazingJaze** [comment]
I've filed an Edge interop issue internally.

**Comment by patrickkettner** [comment]
@AmazingJaze sorry for taking so long to reply. I opened a similar issue in Edge last year, and I don't think there is a ton of movement on it internally. In the mean time, there are a number of elements that are supported in both svg and html contexts, my default being `a`. Care to create a PR to update the preserve3D test?

**Comment by AmazingJaze** [comment]
@patrickkettner I will try it using the `a` tag this afternoon. Thanks.

**Comment by AmazingJaze** [comment]
@patrickkettner Verified that the test passes when using `<a>` tags. Sent PR #1957
