### ISSUE TITLE
CanIUse tests fail in Edge

### ISSUE THREAD

**Issue by AmazingJaze** [Modernizr/Modernizr#1902]
In the Modernizr Master branch 80 CanIUse tests are failing on Edge.  This doesn't repro on v3.3.1 of Modernizr, only the master branch,

Most of the failures mention IE5.5 
`IE5.5: Caniuse result for download matches Modernizr's result for adownload `

Possibly a bad ua sniff?

I have been trying to root cause the issue but I think I still have a lot of distance to cover before I understand how these tests work

**Comment by patrickkettner** [comment]
Man, these are some friggin AWESOME bug reports. Thanks so much! I assume you work up in Redmond?

**Comment by patrickkettner** [comment]
This whole test is from [here](https://github.com/Modernizr/Modernizr/blob/master/test/browser/integration/caniuse.js), its very strange that there would be a regression form 3.3.1 becuase there hasn't been changes to this since well before then. The actual UA parsing is just usparser, and lives [here](https://github.com/Modernizr/Modernizr/blob/a23193bf25387ccca63a05e8c74d54ec1b458c5c/test/js/lib/uaparser.js)

**Comment by AmazingJaze** [comment]
@patrickkettner  Yep in redmond. Thanks for the breadcrumbs. I was out of town last week but will try and root cause this today.

**Comment by AmazingJaze** [comment]
It looks like [this change](https://github.com/Modernizr/Modernizr/commit/da22eb27631fc4957f67607fe6042e85c0a84656#diff-fe69265c6f200c0ae0bcae798bec64beL316)  on line 316 is the responsible party.

When I run these tests from the **v3.3.1** branch I'm seeing that both 
```js
var mmResult   = browserResults[majorminor];  
var mResult    = browserResults[ua.major];  
```
are undefined, and as a result testify was *never* getting called. The `browserResults` array only contains keys ranging from 5.5 - 11 but the values of `majorminor` and `ua.major` indicate this is version 14. 

When running these tests from the the **Master** branch, the code has changed to  
```js
var versionToUse = _.findLast(_.keys(browserResults), function(ciuVersion) {  
  return parseFloat(ciuVersion) <= parseFloat(majorminor);  
});  

var latestResult   = browserResults[versionToUse];  
```
.... I see that versionToUse is resolving at "5.5" and testify is being called with that value being passed into it.
--
In summation, the failures occur inside of testify(), and previously testify() was not being called at all. Now testify is being called, but it is being passed values representative of browser version 5.5, which seems incorrect.

**Comment by AmazingJaze** [comment]
Investigating a little more today, the issue of getting browser version 5.5 is caused by this family_replacement in [uaparse](https://github.com/Modernizr/Modernizr/blob/bed5f7c699c5a774cebdd1937a142eb30896a796/test/js/lib/uaparser.js#L90-L92)

If I change the family_replacement value to  "Edge" in the debugger all of the failing caniusetests are fixed except for the result for ambient-light. I'll prepare a PR once that failure is understood.

//CC @jdalton

**Comment by AmazingJaze** [comment]
@patrickkettner 
This [data](https://github.com/Modernizr/Modernizr/blob/da22eb27631fc4957f67607fe6042e85c0a84656/test/browser/integration/caniuse.js#L2) being passed in from jsonp.php sets ambient-light on Edge 14 to "n"

But when I test `"ondevicelight" in window` in the Edge 14 JS console, it returns true. Is this just a case of hard coded data in Modernizr that needs to updated manually whenever browsers add support for features?

**Comment by AmazingJaze** [comment]
updates inline ^

**Comment by AmazingJaze** [comment]
@patrickkettner Ah It looks like the data from jsonp.php is coming from the caniuse database itself. I will ping them to see what we need to do to get the switched flipped for Ambient Light in Edge.
https://dev.windows.com/en-us/microsoft-edge/platform/status/ambientlightevents
