### ISSUE TITLE
Detect cookie support?

### ISSUE THREAD

**Issue by tauren** [Modernizr/Modernizr#191]
Perhaps I missed it, but wouldn't it make sense for Modernizr to detect if cookies are supported? I haven't tested this, but something like this might work:

```
Modernizr.addTest('cookies', function () {
  // Quick test if browser has cookieEnabled host property
  if (navigator.cookieEnabled) return true;
  // Create cookie
  document.cookie = "cookietest=1";
  var ret = document.cookie.indexOf("cookietest=") != -1;
  // Delete cookie
  document.cookie = "cookietest=1; expires=Thu, 01-Jan-1970 00:00:01 GMT";
  return ret;
});
```

I'm not sure if adding the test for `navigator.cookieEnabled` will speed things up on browsers that have that host property or not. But its in there just in case.

Perhaps this could be taken further to detect session cookie support vs. persistent cookie support.

**Comment by onassar** [comment]
Anyone running into issues with this related to `SameSite` flags? Specifically: this fails when attempting to set a cookie within an iframe, but that's because the `SameSite` isn't set to `none` (which is what I want to test for)

**Comment by onassar** [comment]
Any thoughts on this @paulirish or @tauren ?

**Comment by uniejo** [comment]
I had the same problem with SameSite warnings. The following change, eliminates that warning, by adding SameSite=none and Secure options to the cookie.

```
  Modernizr.addTest('cookies', function() {
    // navigator.cookieEnabled cannot detect custom or nuanced cookie blocking
    // configurations. For example, when blocking cookies via the Advanced
    // Privacy Settings in IE9, it always returns true. And there have been
    // issues in the past with site-specific exceptions.
    // Don't rely on it.

    // try..catch because some in situations `document.cookie` is exposed but throws a
    // SecurityError if you try to access it; e.g. documents created from data URIs
    // or in sandboxed iframes (depending on flags/context)
    try {
      // Create cookie
      document.cookie = 'cookietest=1; samesite=none; secure=1';
      var ret = document.cookie.indexOf('cookietest=') != -1;
      // Delete cookie
      document.cookie = 'cookietest=1; samesite=none; secure; expires=Thu, 01-Jan-1970 00:00:01 GMT';
      return ret;
    }
    catch (e) {
      return false;
    }
  });
```
