### ISSUE TITLE
Modernizr Build Instructions are ambiguous

### ISSUE THREAD

**Issue by zackhall** [Modernizr/Modernizr#1910]
I'm having difficulty with the [build instructions](https://github.com/modernizr/modernizr#building-modernizr-v3) for Modernizr in the README.

### Generate everything in config-all.json

The first step is:

```
npm install
./bin/modernizr -c lib/config-all.json
//outputs to ./modernizr.js
```

On Windows, running `./bin/modernizr -c lib/config-all.json` results in: 

```
> .\bin\modernizr -c lib\config-all.json
'.\bin\modernizr' is not recognized as an internal or external command,
operable program or batch file.
```

### To run tests (in Browswer)

Next issue is trying to run tests in the browser following:

```
grunt build
serve .
visit <url>/test
```

`serve` isn't recognized as a command. I dug into the Gruntfile.js and saw the `browserTests` task, but that stops the server after the test completes. Is there a serve command similar to the one above that allows me to just refresh the browser window to re-run the tests?

**Comment by SlexAxton** [comment]
`serve` is a popular npm module that just serves a directory on port 3000.

`npm install -g serve` should do the trick, then http://127.0.0.1:3000/test

**Comment by zackhall** [comment]
Thanks, @SlexAxton! That's very helpful.

What about the `./bin/modernizr -c lib/config-all.json` command? What does that command do and do you know how to call it without error?

**Comment by SlexAxton** [comment]
Not sure why that's going wrong. Maybe make sure you have a recent node.js version installed and that you successfully ran `npm install`

```
~/code/Modernizr master
❯ ./bin/modernizr -c lib/config-all.json
Modernizr build saved to /Users/alex/code/Modernizr/modernizr.js

~/code/Modernizr master*
❯ tail -f /Users/alex/code/Modernizr/modernizr.js
    Modernizr._q[i]();
  }

  // Leak Modernizr namespace
  window.Modernizr = Modernizr;


;

})(window, document);
```

**Comment by patrickkettner** [comment]
> What about the ./bin/modernizr -c lib/config-all.json command? What does that command do

that is how you create a build from the command line

> and do you know how to call it without error?

it does run on windows (at least [it does for me](http://i.imgur.com/xRLJHPc.png)). You should be running it from the root of the repo, after running npm install.

If you feel like you are able to make the directions clearer, please update the readme

cheers!

**Comment by zackhall** [comment]
Here's what I'm seeing on my windows machine: 

![image](http://g.recordit.co/COHGJROTnF.gif)

[Video](http://recordit.co/COHGJROTnF) which plays back quicker.

**Comment by roblarsen** [comment]
isn't this #1714?

**Comment by zackhall** [comment]
Great find, @roblarsen. Thanks for pointing that out. I believe it is.

**Comment by patrickkettner** [comment]
thanks @roblarsen!

lemme know if there is anything else, @zackhall

**Comment by roblarsen** [comment]
@patrickkettner I think fixing this would be a good thing. You never know how many people don't even make it here. 

It's either documentation or something like this:

https://github.com/roblarsen/Modernizr/blob/windows-command-line/bin/modernizr.bat

Which just makes the errors go away on Windows (although I didn't thoroughly test it)

**Comment by patrickkettner** [comment]
Care to make a PR?

**Comment by roblarsen** [comment]
@patrickkettner Yeah, I was planning to either way, I just wanted to put that option out there to see if it seemed okay before going through the time to test it.

**Comment by patrickkettner** [comment]
:D

**Comment by tomshaw** [comment]
The whole purpose of bower is to automagically download the dependency working/ready inst it? Now I'm being asked to cd into my bower dependencies Modernizr directory and issue a series of commands. Is there any possible way to include a pre-built ready version when using bower or is the modernizr file size becoming an issue?

**Comment by SlexAxton** [comment]
@tomshaw you're installing a builder, which is automagically downloaded and working. If you want to install a *build* you should use the zip functionality of our web builder: 

```
> npm install https://modernizr.com/download?contenteditable-emoji-notification-prefixedcssvalue-setclasses.zip
> bower install https://modernizr.com/download?contenteditable-emoji-notification-prefixedcssvalue-setclasses.zip
```

**Comment by tomshaw** [comment]
Manually downloading a build is an option I do so with gsap and place it in my bower dependency folder. Another options is to manually check for the specific functionality by hand. Either way thanks for your help.

[check-if-a-css-property-is-supported](http://lea.verou.me/2009/02/check-if-a-css-property-is-supported/)
