### ISSUE TITLE
Download link does not work!

### ISSUE THREAD

**Issue by aamironline** [Modernizr/Modernizr#1929]
It simply shows blank page... 

https://modernizr.com/download?applicationcache-atobbtoa-audio-audioloop-audiopreload-blobworkers-canvas-canvasblending-canvastext-canvaswinding-contextmenu-csspointerevents-dataworkers-emoji-fullscreen-htmlimports-inlinesvg-json-localstorage-pagevisibility-queryselector-requestanimationframe-scriptasync-sharedworkers-smil-svg-svgasimg-svgclippaths-svgfilters-svgforeignobject-todataurljpeg_todataurlpng_todataurlwebp-webaudio-webgl-websockets-webworkers-setclasses

**Comment by aamironline** [comment]
What's the update on this issue?

**Comment by mattgreenfield** [comment]
@aamironline - do you have the steps to replicate?

**Comment by patrickkettner** [comment]
sorry about that, the issue had to do with the server side checking of props. stupid mistake on my part. it is deploying now, and should be up by the time you read this

**Comment by aamironline** [comment]
@patrickkettner Thanks a lot, it works now!
