### ISSUE TITLE
generatedcontent + chrome + zoom

### ISSUE THREAD

**Issue by MariuszGorzoch** [Modernizr/Modernizr#1935]
We have notice that "generatedcontent" test on modernizer is giving us false in case of chrome when user will use "zoom" feature. 

You can simply reproduce problem by going to:
https://www.browserleaks.com/modernizr 
changing zoom to 125% and refreshing page. 

Doing above even if you were getting "Modernizr.generatedcontent" = true for 100% zoom, then in 125% you will get false. 

Can you advice how to fix that?

Chrome = 49.0.2623.87 m
Modernizr = v3.3.1

**Comment by anthonycosgrave** [comment]
I've noticed Users having a similar issue on the generated content test when at 90% and 125% zoom in Chrome (version 49.0.2623.87 m).

The version of Modernizr we're using is 2.8.3.

I can see in the CSS generated content detection test that when the zoom is 90% or 125% the node.offsetHeight is 2 and not >=3.

**Comment by ryanseddon** [comment]
This has come up in a few other tests too where page zoom returns the wrong results, [chrome fixed](https://bugs.chromium.org/p/chromium/issues/detail?id=447902) if for `scrollHeight` and `scrollWidth` but weirdly didn't fix `offsetWidth/Height`.

**Comment by tramirez89** [comment]
Running into this issue as well. Huge pain with sites in the healthcare industry as they loooove to zoom... Any news on a fix?

**Comment by ryanseddon** [comment]
@tramirez89 I've left a comment on the chromium [bug report page](https://bugs.chromium.org/p/chromium/issues/detail?id=447902) that looks like a similar issue to what we're seeing here. I'll see what comes out of that.

**Comment by ryanseddon** [comment]
Ok haven't heard anything so created a new bug report http://crbug.com/608142

**Comment by ryanseddon** [comment]
They've marked it as `WONTFIX` and have suggestd using `getBoundingClientRect` instead. I'll give that a go.

**Comment by stucox** [comment]
@anthonycosgrave are you using an old version of Modernizr? [The generatedcontent detect](https://github.com/Modernizr/Modernizr/blob/master/feature-detects/css/generatedcontent.js) checks for `offsetHeight >=7`, not 3 (I believe it changed a while ago because of similar bugs)

I presume it's a rounding error... can't we just increase the tolerance? Use a font size of 20px or something (and still check for `>= 7`)

**Comment by anthonycosgrave** [comment]
@ryanseddon Thanks for your help following up on this Ryan  :thumbsup:

@stucox yep, the system was released with version 2.8.3 and it was testing a very small number of features during a transitional phase from an "older browser" supporting system to a newer system.

At the moment we're trialing a rough workaround using devicePixelRatio and a bit of UA sniffing for Chrome. Fragile and not ideal I know but so far it appears to be doing the job.

**Comment by ryanseddon** [comment]
@stucox yeah we could just change the current detect to check for `>=6` as when chrome is zoomed the value gets rounded down to 6.

Tried `getBoundingClientRect` and it doesn't give stable numbers when zoomed either.

![screen shot 2016-05-28 at 3 13 14 pm](https://cloud.githubusercontent.com/assets/143402/15625362/363f66f8-24e7-11e6-91b6-543269400f16.png)
