### ISSUE TITLE
What is the significance of test/unit.html 

### ISSUE THREAD

**Issue by AmazingJaze** [Modernizr/Modernizr#1938]
I see that only test/index.html is highlighted as a browser runnable file on the front page of the repo. 

`Run the [test suite](https://modernizr.github.io/Modernizr/test/)`

When testing Modernizr pass rates in Edge, should we also be looking at test/unit.html? 

//CC @patrickkettner

**Comment by ryanseddon** [comment]
Probably a good idea the test page also does a check with the caniuse db and sees if there are any discrepancies.

**Comment by patrickkettner** [comment]
It wouldn't be a bad idea to check the unit page, but it is much less likely to ever have any issues. It is tests for the library's utilities (e.g. the code that we wrote to run all of the feature detection functions), and rarely changes. 

I'd add it to protractor if it isn't too much trouble.

**Comment by AmazingJaze** [comment]
Thanks @ryanseddon and @patrickkettner. We're running it in our test pass.
