### ISSUE TITLE
Detect clip-path support

### ISSUE THREAD

**Issue by fredrikekelund** [Modernizr/Modernizr#1969]
I just discovered, to my surprise, that Modernizr didn't have a test for the [clip-path CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path). This has been brought in in a [CSS-Tricks article](https://css-tricks.com/clipping-masking-css/) (look towards the end) and there's an SO question on how to detect support that has [a good answer](http://stackoverflow.com/a/30041538) outlining a functioning detect.

Is this something that we could add to Modernizr? I could submit a PR based on the code in that answer if you're keen

**Comment by patrickkettner** [comment]
please do send in a PR - never need to ask permission :]

**Comment by tedw** [comment]
Could we use this one from @shshaw?
https://codepen.io/shshaw/pen/yyOaqW

I've used it on a project before and it worked great.

**Comment by shshaw** [comment]
Haven't used that test specifically in a year or two, but I used it live on http://clarkcondon.com. Accomplished what I needed, but not positive how bulletproof of a test it is.
