### ISSUE TITLE
Modernizr crashes on Firefox with hidden iframe

### ISSUE THREAD

**Issue by arcanis** [Modernizr/Modernizr#1984]
[(bis)](https://github.com/Modernizr/Modernizr/issues/885)

Unfortunately, `getComputedStyle` still returns `null` when called from an hidden iframe. It makes Modernizr crash.

**Comment by patrickkettner** [comment]
could you create a demo?

**Comment by arcanis** [comment]
Sure, you can use the following [codepen](http://codepen.io/anon/pen/MyMjoV?editors=1010)

**Comment by elgrafico** [comment]
I'm having this issue as well. It seems to be related to this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=548397.

**Comment by patrickkettner** [comment]
fixed in e55aba3198f2aa5fa40f97a46b691e4536faef3f
