### ISSUE TITLE
On pageload HTML5 input element with autofocus losing focus 

### ISSUE THREAD

**Issue by gehlen** [Modernizr/Modernizr#1987]
On pageload the function "test_hyphens_find" will unfocus an HTML5 input element with attribute autofocus.

Using 3.3.1 with all features..

**Comment by tomciopp** [comment]
I can also confirm that this test breaks autofocus in forms. The solution is to remove the test but that kinda feels bad.

**Comment by patrickkettner** [comment]
Another solution would be to do something like `const el = document.querySelector("[autofocus]"); el&&el.focus();` after the test runs. 

The detect itself could be updated to cache and refocus `document.activeElement` as well

**Comment by rejas** [comment]
Duplicate of https://github.com/Modernizr/Modernizr/issues/1781 

Not sure if @patrickkettner solution is better than the PR https://github.com/Modernizr/Modernizr/pull/1633
