### ISSUE TITLE
background-clip:text probably needs a new test

### ISSUE THREAD

**Issue by adamavenir** [Modernizr/Modernizr#199]
Thanks for [this test for background-clip:text](https://github.com/Modernizr/Modernizr/issues/89/#comment_289104). Unfortunately—it doesn't appear to work in Firefox 4.

Is there any way to detect specifically for "background-clip:text" instead of simply "background-clip"?

**Comment by fraserpage** [comment]
This test is giving a false positive in Microsoft Edge.

**Comment by phistuck** [comment]
Edge actually does support it, but with a -webkit- prefix, for compatibility.
https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/10945389-background-clip-text

**Comment by fraserpage** [comment]
Interesting. Thanks @phistuck

**Comment by pauldraper** [comment]
> but with a -webkit- prefix, for compatibility

:thinking:
