### ISSUE TITLE
Modernizr switch the head tag and body tag position

### ISSUE THREAD

**Issue by YounesKeraressi** [Modernizr/Modernizr#1998]
Hey,
I think the best thing is to write less and understand a lot^^ ,

I am creating a templating page generator with php. The problem when I include the script tags near to closed body with modernizer top of the js script's list the head and body changed, then if i commented out modernizer the tags are correct is this a bug?, here are the pics

btw thx for this awesome "mordernizer" respect <3 👍 💯/💯 :3 gg

<img width="563" alt="capture d ecran 2016-05-26 a 18 59 22" src="https://cloud.githubusercontent.com/assets/19386064/15585135/cb63a10e-2375-11e6-8c1f-ed51ae45d90f.png">

<img width="464" alt="capture d ecran 2016-05-26 a 19 09 32" src="https://cloud.githubusercontent.com/assets/19386064/15585144/d466ea72-2375-11e6-939f-0572b6eb2f65.png">

**Comment by YounesKeraressi** [comment]
its also scroll to bottom when i refresh the page, i tried to find solution but i found that the issue was closed :(

**Comment by patrickkettner** [comment]
@YounesKeraressi I am not quite sure I understand the question.

By default, Modernizr adds a number of classes to the HTML tag after it loads. if you don't want that to happen, you can uncheck the "Add css classes" option https://modernizr.com/download

as for the scrolling to the bottom, I would need to see the page to help

**Comment by YounesKeraressi** [comment]
but why close dude is this you resolve the issue?

**Comment by radium-v** [comment]
Hi @YounesKeraressi, I think this is a duplicate of #1836.

Are you using a custom version of Modernizr, or a development build? Try to customize your build here https://modernizr.com/download and see if the issue still persists. #1836 narrowed the bug down to use of `Modernizr.localizednumber` and if you're not using that feature then you can safely remove it from your build.

**Comment by patrickkettner** [comment]
@YounesKeraressi sorry for not being clearer, it was closed because the first thing is a feature, and the second thing is a duplicate issue

**Comment by YounesKeraressi** [comment]
thx for your helping, i dint know how i couldn't get the #1836 post by searching on google

**Comment by duoeg** [comment]
I just went through basically every option, and in my case, this was the test that cause the error:

`input[type="number"] Localization`

No clue why, but removing this test fixes it, and it reoccurs when I bring it back.

FWIW:
Modernizr 3.6.0 with Chrome 68 on Mac

**Comment by AdamReece-WebBox** [comment]
Can confirm that removing `input[type="number"] Localization` also fixed our "scroll to the bottom on load" issue. +1
No idea what the number input type has to do with it.
