### ISSUE TITLE
Security Alert for Marked@0.3.5 dependency...

### ISSUE THREAD

**Issue by emveeoh** [Modernizr/Modernizr#2003]
The repository owner for Marked seems to be unresponsive after several weeks of notification of this issue. An alternate for Marked, such as Remarked, is suggested. Alternatively, you could use a fork of the project.

--
Security Advisory:
Sanitization bypass using HTML Entities

https://nodesecurity.io/advisories/101 

Sanitization bypass using HTML Entities

April 18th, 2016
CVE-NONE
marked
Vulnerable: All
Patched: None
CVSS
5.3
Medium
Overview

marked is an application that is meant to parse and compile markdown.

Due to the way that marked parses input, specifically HTML entities, it's possible to bypass marked's content injection protection (sanitize: true) to inject a javascript: URL.

This flaw exists because &#xNNanything; gets parsed to what it could and leaves the rest behind, resulting in just anything; being left.

For example:

If a malicious user could provide this input to the application javascript&#x58document;alert&#40;1&#41; resulting in a valid link, that when a user clicked it would execute alert(1).

Remediation

To mitigate the flaw you have a couple of options. There's a pull request open that fixes this issue. Another option would be to switch to another markdown library such as remarkable.

References

https://github.com/chjj/marked/pull/592
https://github.com/chjj/marked/pull/592/commits/2cff85979be8e7a026a9aca35542c470cf5da523

**Comment by ryanseddon** [comment]
Thanks @emveeoh wanna do a pr moving this to remarkable?

**Comment by emveeoh** [comment]
@ryanseddon .. Unfortunately, the job would over my head. I'm still too new to js to take it on. However, I have posted a request on marked's repo for collaborators.

**Comment by patrickkettner** [comment]
fixed in e984deefc3d4e91b794a7e603019550a2b596782
