### ISSUE TITLE
i am getting this error ReferenceError: Modernizr is not defined in consol

### ISSUE THREAD

**Issue by pkmattu** [Modernizr/Modernizr#2004]

**Comment by patrickkettner** [comment]
If that is the only error, that means that you did not load Modernizr on the page

**Comment by pkmattu** [comment]
i am using compressed js file

**Comment by pkmattu** [comment]
how to load Modernizr in compressed js file

**Comment by patrickkettner** [comment]
you add it like any other javascript file. Either to your build process that creates the compressed build, or to the page as its own file. Since this isn't really a bug with modernizr, I am going to close out this issue. If you still need help, I would suggest creating a new issue on something like stackoverflow.com. I would be happy to help further there.

**Comment by Mohsen-Khakbiz** [comment]
I ran into the same issue. just disabled the adblocker, and rebuilt. and the error was gone

**Comment by jessadejesus** [comment]
where do I find the adblocker?

**Comment by Mohsen-Khakbiz** [comment]
@jessadejesus it's an extension in your browser

**Comment by jessadejesus** [comment]
the adblocker does not work. any suggestion.

**Comment by jessadejesus** [comment]
![Screenshot_35](https://user-images.githubusercontent.com/48699739/55523438-cbd33380-56bb-11e9-8c30-84d48b4b8498.png)

this is my error

**Comment by rejas** [comment]
we would need a little more info from you @jessadejesus how do you load Modernizr into your page, how did you build it, maybe we can see the page somewhere on the net directly?

**Comment by jessadejesus** [comment]
I don't know how it happened, I'm just loading 2 pages/tabs same content and then errors came out.

**Comment by rejas** [comment]
please be more specific on how you incorporate modernizr on your page. how does your code look like ?
