### ISSUE TITLE
Module not found: Error: Cannot resolve module 'ModernizrProto'

### ISSUE THREAD

**Issue by ashbryant** [Modernizr/Modernizr#2012]
Hi,

I'm calling modenizr via webpack and I keep getting this error  

ERROR in ./~/modernizr/src/modernizr.js
Module not found: Error: Cannot resolve module 'ModernizrProto' in (path to modernizr)

I can see that ModernizrProto.js is there.

Can anyone help?

**Comment by patrickkettner** [comment]
hey @ashbryant what is it you are calling? your build? the moderizr module?

**Comment by patrickkettner** [comment]
ping @ashbryant

**Comment by ashbryant** [comment]
@patrickkettner Sorry, I've been away. 

It's in node_modules/modernizr/src/modernizr.js

**Comment by patrickkettner** [comment]
no worries!

So that is actually probably not what you want. That is the base file that the modular build is built around. Have you created the build of modernizr that you want?

**Comment by buley** [comment]
I ran into this issue as well. The reason I'm using the basefile is that the uglification and optimization processes seem to prefer raw base files. I was hoping to build from `npm` source in a repeatable way. Now planning to do a manual build instead.

**Comment by patrickkettner** [comment]
@buley I'd suggest using the npm builder we offer at modernizr.com

`npm install https://modernizr.com/download?ambientlight-batteryapi-webp-setclasses --save`

**Comment by kachkaev** [comment]
Thanks for the link @patrickhlauke. Although your method works, I'm wondering if you can make the npm verion of the library workable. The problem with the non-npm package source is that the app now depends on the availability of your website and the network. Installing modernizr in a CI looks quite painful and feels potentially error prone.
How feasible would it be to fix the npm package for webpack? I guess everyone will be happy to `import Modernizr from 'modernizer/some/extra/path'` if needed.

**Comment by patrickhlauke** [comment]
i'm assuming you meant @patrickkettner and not me ... confused me there for a second

**Comment by kachkaev** [comment]
Ah sorry!

2 @patrickkettner: Just tried your method and got this in `package.json` / `package-lock.json`:
```
    "Modernizr": "https://modernizr.com/download?ambientlight-batteryapi-webp-setclasses",
```
```
    "Modernizr": {
      "version": "https://modernizr.com/download?ambientlight-batteryapi-webp-setclasses",
      "integrity": "sha1-vQBWX2FvDUyoLiZ0fGK2P1n6Rqc="
    },
```

Running `npm install` inside CI caused 

```
npm ERR! code EINTEGRITY
npm ERR! sha1-vQBWX2FvDUyoLiZ0fGK2P1n6Rqc= integrity checksum failed when using sha1: wanted sha1-vQBWX2FvDUyoLiZ0fGK2P1n6Rqc= but got sha1-33GogvH/vyMjWkqrGcO8EGvrDps=. (30208 bytes)
```

i'll probably move Modernizr into `src` for now – fetching npm packages not from an npm registry feels like a bad idea.

**Comment by patrickkettner** [comment]
@kachkaev all that is happening is your lock file is being invalidated because of package changes. thats the point of the lock file. You just need to delete the lock file to upgrade your modernizr package.

**Comment by nikolowry** [comment]
It be awesome to programmatically use Modernize with ease -- I don't want it on the window, I don't want it to touch the `document.documentElement`.

I got it to work with mapping all the named modules and trying to figure out how to implement this dynamically in the future.

My use case:
Attempting to make all my Component classes standalone and able to add their own specific detects per Components' use-cases. Encapsulate and modularize all the things!

**Comment by AntonioRedondo** [comment]
So there is no official way to include Modernizr in a project programmatically from `package.json` and npm/Yarn? There is this [`npm-modernizr`](https://www.npmjs.com/package/npm-modernizr) package. But I don't think it's a good idea to use it.

The name of the npmjs.com [`modernizr`](https://www.npmjs.com/package/modernizr) package should actually be `modernizr-cli` since it's the library generator that can be used from [modernizr.com](https://modernizr.com) but for the command line.

**Comment by niksy** [comment]
@AntonioRedondo check out [`modernizr-esm`](https://github.com/niksy/modernizr-esm). It contains every Modernizr test as separate ES module so you can import and use what you want.

There is some effort in https://github.com/Modernizr/Modernizr/pull/2108 to do this in this repository, but project seems it’s like on life support which is shame. That is why I tried to "modernize" it with `modernizr-esm`.
