### ISSUE TITLE
Website: Please add some contrast

### ISSUE THREAD

**Issue by COLABORATI** [Modernizr/Modernizr#2017]
Grey font on grey background is not readable. Please add some contrast, thank you!

**Comment by alrra** [comment]
@COLABORATI You might want to open this issue in the [`modernizr-neue`](https://github.com/Modernizr/modernizr-neue) repository. Or, better yet, open a PR there! :)

--

According to [`contrast-ratio`](https://leaverou.github.io/contrast-ratio/), the contrast seems to be [pretty decent](https://leaverou.github.io/contrast-ratio/#%23666-on-%23ececec):

![](https://cloud.githubusercontent.com/assets/1223565/16486208/cb1aa668-3ecb-11e6-9ddc-743b320aba94.png)

**Comment by patrickkettner** [comment]
closing, as per @alrra 's comments. It passes WCAG AA, if you want to discuss it more (I would love to hear more info), please open it up at modernizr/modernizr-neue
