### ISSUE TITLE
`local | sessionStorage` vs `local | sessionstorage`

### ISSUE THREAD

**Issue by robwierzbowski** [Modernizr/Modernizr#2023]
Why are the props for local / session storage all lowercase, when the methods are camel? This bit me today, took us a while to catch the error because we were expecting the value coming from storage to be falsey anyways.

**Comment by patrickkettner** [comment]
how are you getting it? as a detect name? or...

**Comment by robwierzbowski** [comment]
Off the Modernizr object. Actually, not sure the age of this build, on a
project somewhat new to me.

On Friday, July 8, 2016, patrick kettner <notifications@github.com> wrote:

> how are you getting it? as a detect name? or...
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Modernizr/Modernizr/issues/2023#issuecomment-231274897>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA4gJw_bYxK3AMhi3cd3xPRE45T85Exjks5qTdjmgaJpZM4JHt-0>
> .
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by patrickkettner** [comment]
all Modernizr properties are lowercased for consistency

**Comment by robwierzbowski** [comment]
Gotcha. A little odd that the name of the method is camel, but the detect
result is lowercase. Thanks for the explanation.

On Friday, July 8, 2016, patrick kettner <notifications@github.com> wrote:

> all Modernizr properties are lowercased for consistency
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Modernizr/Modernizr/issues/2023#issuecomment-231276415>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA4gJ-NSq1MGcxpfXm5N84wztjKW4DSvks5qTdw-gaJpZM4JHt-0>
> .
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by patrickkettner** [comment]
its not the result of a detect, it is the name of a detect. The result is a boolean. It is similar to the `prefixed` or similar apis which return the name of the api on the platform. In this case, however, it is just an unfortunately similarly named feature.

cheers, and sorry for the confusion
