### ISSUE TITLE
Missing License Text?

### ISSUE THREAD

**Issue by teetotum** [Modernizr/Modernizr#2034]
There is no license text under [https://github.com/Modernizr/Modernizr/blob/master/LICENSE](https://github.com/Modernizr/Modernizr/blob/master/LICENSE)
Only `/*! Modernizr 3.0.0pre (Custom Build) | MIT  */`
which -to me at least- does not read as "you are granted a license".

**Comment by patrickkettner** [comment]
The license is MIT
