### ISSUE TITLE
S.H.I.T

### ISSUE THREAD

**Issue by pribilinskiy** [Modernizr/Modernizr#2047]
@paulirish in readme it says "To see the build tool install all your gems and bundles and jekyll and shit"
Could you clarify what `shit` stands for? )

**Comment by patrickkettner** [comment]
its outdated information that will be removed shortly. thank you for the reminder

**Comment by copremesis** [comment]
one could do a pull request ...

+1 on reminder and if this still resides in the readme .. why is this issue closed?
