### ISSUE TITLE
SecurityError when trying to use IndexedDB with cookies disabled

### ISSUE THREAD

**Issue by Okamoi** [Modernizr/Modernizr#2057]
You can reproduce this bug with Firefox 48 on this page:
https://embed.ted.com/talks/gian_giudice_why_our_universe_might_exist_on_a_knife_edge

Options > Privacy > Untick "Accept cookies"
You'll get this error in the browser console:

SecurityError: The operation is insecure.
i()
j()
window.Modernizr</C.indexedDB()
window.Modernizr<()
<anonymous>

If IndexedDB is disabled you instead get the following:
InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.

To disable IndexedDB, set dom.indexedDB.enabled to false in about:config

**Comment by Okamoi** [comment]
Oh. They're using Modernizr version 2.1.20.
Leaving this open because I wasn't able to check that it is fixed in current version, sorry.

**Comment by patrickkettner** [comment]
this was fixed in 164e757 - thank you for reporting!
