### ISSUE TITLE
backgroundcliptext false positive on Microsoft Edge

### ISSUE THREAD

**Issue by magicbruno** [Modernizr/Modernizr#2062]
Modrnizr.backgroundcliptext return true on Microsoft Edge 38.14393.0.0.

**Comment by patrickkettner** [comment]
Hey @magicbruno!

Edge does support background-clip text (I work on edge). Could you elaborate on what brought you to believe that?

**Comment by magicbruno** [comment]
Indeed it is'nt a false positive but this piece of scss code is rendered as espected in Chrome, Safari and Opera, but not in Microsoft Edge:
.backgroundcliptext {
    .text-wrapper {
        background-color: #f2f2f2;
        margin: 0 15px;
    }
    .site-header {
        padding-top: 15px;
    }
    .jumbotron {
        &.home-header {
            .heading-text {
                -webkit-text-fill-color: transparent;
                -webkit-background-clip: text;
                p {
                    -webkit-text-fill-color: transparent;
                    -webkit-background-clip: text;
                }
            }
        }
    }
}

**Comment by patrickkettner** [comment]
Can you post a demo please?

**Comment by magicbruno** [comment]
This is the result: [http://2016.blusole.com/home](http://2016.blusole.com/home). Soon i try to post something on Codepen.

**Comment by magicbruno** [comment]
Solved. Misunderstanding caused by different behavior of Edge compared to Chrome and Opera. In Chrome and Opera the p element inherited background from its parent in Edge not.
