### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by sdepold** [Modernizr/Modernizr#2068]
Hi all :)

I noticed that you replaced the dependency `marked` quite a while ago because it was known to be insecure. Unfortunately you didn't release any new version since then. Is there a specific reason for this?

**Comment by gilbarbara** [comment]
btw, maked just got a new vulnerability [warning](https://snyk.io/vuln/npm%3Amarked%3A20170112).

**Comment by rejas** [comment]
A new release has happened since then without marked.
