### ISSUE TITLE
Bower install

### ISSUE THREAD

**Issue by ekkis** [Modernizr/Modernizr#2073]
in my project I do:

    # bower install modernizr --save

and I get a directory tree `bower_components/modernizr`.  everything seems to work but, what file do I use in my project?  I would expect a `dist/` folder or a `modernizr.js` in the root of the project, or instructions as to which file to use but I find nothing.

there is a `src/modernizr.js` but that doesn't seem like the right place to use it from.

help?

**Comment by patrickkettner** [comment]
Hey there!

Check out [my comment here](https://github.com/Modernizr/Modernizr/issues/1664#issuecomment-141551558)

> We never had a package on bower, there was an unofficial package there
previously, however.
>
> That being said, you can now get custom builds off of modernizr.com. you just get the build URL you for a custom build ( available at the top of each file that is built ), add .zip to the end of it, and you can bower install it!
> 
> e.g. bower install https://modernizr.com/download?-ambientlight.zip

**Comment by ekkis** [comment]
what I was trying to do is move some code from another project that didn't use Bower.  when I looked at the modernizr.js file in the original project, the comment indicated the modules that were custom built, so I followed your suggestion and it all magically worked:

    # bower install --save http://modernizr.com/download/#-fontface-backgroundsize-borderimage-borderradius-boxshadow-flexbox-hsla-multiplebgs-opacity-rgba-textshadow-cssanimations-csscolumns-generatedcontent-cssgradients-cssreflections-csstransforms-csstransforms3d-csstransitions-applicationcache-canvas-canvastext-draganddrop-hashchange-history-audio-video-indexeddb-input-inputtypes-localstorage-postmessage-sessionstorage-websockets-websqldatabase-webworkers-geolocation-inlinesvg-smil-svg-svgclippaths-touch-webgl-shiv-mq-cssclasses-addtest-prefixed-teststyles-testprop-testallprops-hasevent-prefixes-domprefixes-load.zip

thanks!

**Comment by patrickkettner** [comment]
:D
