### ISSUE TITLE
Modernizr.prefixed is not a function error when including CSS Regions test

### ISSUE THREAD

**Issue by stevenorell** [Modernizr/Modernizr#2079]
Using a custom build of Modernizr v3.3.1, I get an "Uncaught TypeError: Modernizr.prefixed is not a function" only when including the "CSS Regions" test. If I exclude that test in the build, I get no errors in the console.

The build is generated by gulp-modernizr, and I can confirm that the Node package for Modernizr is up-to-date (3.3.1). I can also confirm the error occurs when replacing the custom build with a build from modernizr.com containing only the "CSS Regions" test.

Possibly related to this issue: https://github.com/Modernizr/Modernizr/issues/948

**Comment by Isthu** [comment]
Minimal test case for this. Console shows an error and test result does not display:
http://codepen.io/Isthu/pen/WGXjXQ

Test case for this with other detects included. Includes one before and one after in the build order. Shows that it prevents *any* detect from running. The call to testRunner never happens so no detect is ever executed:
http://codepen.io/Isthu/pen/amVwEx

**Comment by builtbylane** [comment]
I can confirm, when regions test is included in custom build, Modernizr.prefixed doesn't get added.
