### ISSUE TITLE
official npm distribution / security issue ?

### ISSUE THREAD

**Issue by mmc41** [Modernizr/Modernizr#2081]
On npm there is a 2.8.3 version of Modernizr (https://www.npmjs.com/package/npm-modernizr) provided by aibarra988. A pretty old version by someone that does not appear to be an official contributor the the project. Security-wise this seems to be a bit suspect. So in the interest of security and being up-2-date it would be great it there could be an official npm distribution that the github page links to.

**Comment by patrickkettner** [comment]
the up to date version is installing straight from the modernizr url

`npm i https://modernizr.com/download?webp-setclasses`, etc. This is documented on the blog, and will be documented in the updated readme
