### ISSUE TITLE
Modernizr not detecting js inside iframe

### ISSUE THREAD

**Issue by robbertrosario** [Modernizr/Modernizr#2082]
Hi,

I have Modernizr loaded in a page, that page has an iframe and the iframe also has Modernizr in it.
The page is getting all the options I selected in my Modernizr build. The iframe is getting all the options except it doesn't apply the "js" and "no-js" class it just inserts an empty space.

I am using a command line generated version (v.3.3.1) can anyone help me out?

**Comment by patrickkettner** [comment]
Modernizr 3 doens't add `js`. it will just modify `no-js` to `js`

**Comment by robbertrosario** [comment]
Ok so it is not added, but is there a reason why it doesn't appear?

**Comment by patrickkettner** [comment]
I dont understand the question. what is the difference between being added and appearing?

**Comment by robbertrosario** [comment]
You said that it modifies the no-js class to js class. Thats fine by me. But I am not getting any of these classes it inserts an empty space.

**Comment by patrickkettner** [comment]
it doesn't add any class. If the no-js class is not there in your html already (meaning included by you, in the original source code of the page), then nothing will happen.

**Comment by robbertrosario** [comment]
I see, its clear to me now thanks for helping! :)
