### ISSUE TITLE
Need a way to disable flash detection

### ISSUE THREAD

**Issue by robstove** [Modernizr/Modernizr#2084]
The latest versions of Chrome and Firefox are showing disabled plugin icons anywhere modernizr is used due to adding flash detection. We need a way (if not already possible and I've missed it) to disable certain tests if we know we don't need them.

**Comment by SlexAxton** [comment]
Modernizr has been custom buildable since version 2, I believe. Just head over to the website and choose the detects you need.

**Comment by robstove** [comment]
Uh...does that work as an NPM build dependency?

**Comment by SlexAxton** [comment]
Sure. There are a few ways people prefer to do that since naturally we don't publish every combination of detect to npm separately.

http://blog.npmjs.org/post/132110321170/guest-post-building-resilient-web-apps

**Comment by SlexAxton** [comment]
(Id just use the "add .tar.gz" method to our build URL thing)

**Comment by robstove** [comment]
Will give it a shot. Thanks!

**Comment by patrickkettner** [comment]
fwiw - as of npm v3 you no longer need to include the `.tar.gz`. Just using the build url as is works hunkydory

**Comment by SlexAxton** [comment]
Woah. Tite.
