### ISSUE TITLE
webaudio detect description wrong

### ISSUE THREAD

**Issue by Isthu** [Modernizr/Modernizr#2085]
I believe the description in the comments of the webaudio feature detection is wrong.

The description says:

> Detects the older non standard webaudio API, (as opposed to the standards based AudioContext API)

While the notes reference this W3C spec, which seems to be the one that uses AudioContext:
https://dvcs.w3.org/hg/audio/raw-file/tip/webaudio/specification.html

And the detect code seems to check for the presence of AudioContext:
`var prefixed = 'webkitAudioContext' in window;
    var unprefixed = 'AudioContext' in window;`

**Comment by rejas** [comment]
hi @Isthu would you be willing to create a PR for that so we can discuss it?
