### ISSUE TITLE
bgpositionshorthand incorrectly named

### ISSUE THREAD

**Issue by Isthu** [Modernizr/Modernizr#2086]
I think the bgpositionshorthand detect is not named quite right. Just a naming issue so I'm not sure how important it is. But here's the case for it.

The name is: bgpositionshorthand
The description says:
>Detects if you can use the shorthand method to define multiple parts of an element's background-position simultaniously.

The feature it detects is the ability to use the long, 3- or 4-value syntax in the CSS background-position property. This was added in CSS3:
https://drafts.csswg.org/css-backgrounds-3/#background-position

If anything, this is the more explicit, NON-shorthand syntax. The older syntax is now a shorthand for the newer, more explicit values.

For example, you can say in the new syntax (detected by this detect):
`left 10px top 10px`

Or you can say in the old syntax, which is effectively shorthand for the same thing:
`10px 10px`

Maybe something along the lines of bgpositionlong would be more accurate.

Name: bgpositionlong
Description: Detects support for the CSS3 long value syntax for the background-position property.

**Comment by patrickkettner** [comment]
Hey @Isthu!
The longhand version would be `background-position-x`, and  `background-position-y`, this is still considered shorthand, despite having multiple arguments.

**Comment by Isthu** [comment]
I see what you mean! Thanks for clarifying. Didn't know about those other properties.

Is it possible it's doing too strict of a check in that case? It's currently detecting the long syntax specifically. So there are some environments (CSS1 and CSS2) where the detect will fail, but the background-position property is actually available.

The tested value is currently:
`right 10px bottom 10px`

Relevant part of the CSS1 spec, 1- or 2-value syntax only, where I believe that check will fail:
https://www.w3.org/TR/CSS1/#background-position
`Value: [<percentage> | <length>]{1,2} | [top | center | bottom] || [left | center | right]`

Relevant part of the CSS2 spec, expanded syntax but still only 1- or 2-value:
https://www.w3.org/TR/CSS2/colors.html#propdef-background-position
`Value: [ [ <percentage> | <length> | left | center | right ] [ <percentage> | <length> | top | center | bottom ]? ] | [ [ left | center | right ] || [ top | center | bottom ] ] | inherit`

Sorry if it's been discussed. I searched the issues but didn't find it mentioned.

**Comment by Isthu** [comment]
I made a reduced test case for this as requested in the wiki:
https://codepen.io/Isthu/pen/KgvzNq

On an Android 4.1.1 system the detect fails yet the background image is repositioned.

I'm not sure now what the intended test is (background-position property vs long value syntax), so possibly that is actually the expected result.
