### ISSUE TITLE
need to add a detect for mix-blend-mode

### ISSUE THREAD

**Issue by TheWebTech** [Modernizr/Modernizr#2094]
For examples of it in use:
https://css-tricks.com/basics-css-blend-modes/

Not to be confused with the similar feature background blend modes. 
It is possible that the same tests may be valid as I would guess that if a browser was going to add background blend modes you'd probably do mix-blend-mode at the same time. That said it'd be better to actually test mix-blend-mode itself though.

Being able to test for this feature is important because if someone is displaying a transparent graphic with mix-blend-mode, that graphic could visually disappear in a browser that doesn't support it if the colors are similar.

**Comment by patrickkettner** [comment]
see #1388 - PRs or other solutions are more than welcomed, happy to reopen with any new discoveries
