### ISSUE TITLE
onInput event detection support

### ISSUE THREAD

**Issue by thatmarvin** [Modernizr/Modernizr#210]
It'll be nice if Modernizr can detect support for the <code>input</code> event [1]. At the moment, at least Gecko and WebKit supports it.

[1] http://www.whatwg.org/specs/web-apps/current-work/multipage/common-input-element-attributes.html#common-event-behaviors

**Comment by johan** [comment]
These days, there's about three levels of input events support: I guess the initial `oninput` this probably is about (input events that don't have an `inputType` property) that Firefox supports might be called InputEvents 0, and then there's the latter type specified by the W3C specs [InputEvents Level 1](https://www.w3.org/TR/input-events-1/) and  [InputEvents Level 2](https://www.w3.org/TR/input-events-2/) (that also add the `beforeinput` event, which I don't know of any intuitive more direct way to detect) that I'd suggest this hack to detect:

```js
const input_events_level1_or_better = 'inputType' in (new InputEvent('input'));
```
