### ISSUE TITLE
Add a function to test all features at once

### ISSUE THREAD

**Issue by 0x80** [Modernizr/Modernizr#2126]
I'm building a custom Modernizr via a Webpack loader using [modernizr-loader](https://www.npmjs.com/package/modernizr-loader). 

To test all features you have to loop over the resulting object and check each feature separately to know if all tests pass.

The feature strings used to configure the build are also not the same as the ones to check the resulting boolean props. For example `css/backgroundsizecover` config becomes `bgsizecover` on the built Modernizr.

Therefor I need to:
* Keep two separate lists of features. One for configuring and one for testing
* Loop over all of the test properties explicitly to know if they all passed.

This feels silly. To solve this I think it would be very useful to have a `testAll()` or something which just tests all of the features in the build and returns a boolean.

**Comment by futurist** [comment]
👍 +1
