### ISSUE TITLE
Please add for a new datalist polyfill

### ISSUE THREAD

**Issue by George3d6** [Modernizr/Modernizr#2127]
Can be found here:

https://github.com/Fyrd/purejs-datalist-polyfill

Seems to work fine

**Comment by rejas** [comment]
hi  @George3d6 could you create a PR for this? Thx.

**Comment by George3d6** [comment]
Wow... talk about blast from the past.
Will try and see if I can add it this weekend.

**Comment by rejas** [comment]
Thx @George3d6 :-)
