### ISSUE TITLE
Download links drop cssclassprefix

### ISSUE THREAD

**Issue by typeoneerror** [Modernizr/Modernizr#2129]
I followed a link from a modernizr build file:

https://modernizr.com/download?-bgsizecover-cssanimations-csstransitions-flexbox-flexwrap-history-inlinesvg-smil-svg-svgasimg-svgclippaths-svgfilters-svgforeignobject-addtest-domprefixes-prefixes-printshiv-setclasses-testprop-dontmin-cssclassprefix:mz-

And after it loads the link is now

https://modernizr.com/download?bgsizecover-cssanimations-csstransitions-flexbox-flexwrap-history-inlinesvg-smil-svg-svgasimg-svgclippaths-svgfilters-svgforeignobject-addtest-domprefixes-dontmin-prefixes-printshiv-setclasses-testprop

Differences:

* "-" after ? removed (probably shouldn't be there to begin with
* dontmin shifts locations
* cssclassprefix:mz- is gone

**Comment by ryanseddon** [comment]
There is an existing report here if you know how to fix it please do a PR https://github.com/Modernizr/modernizr-neue/issues/79
