### ISSUE TITLE
svgclippaths, needs augmented documentation

### ISSUE THREAD

**Issue by nsfmc** [Modernizr/Modernizr#213]
I just tried, with this [handy test page](http://generic.cx/for/webkit/test.html) to get a svg clipping path on _html content,_ to no avail (although firefox does support this).

Instead, what safari does support is the svg `clipPath` command, which you can see (weirdly) [here](http://srufaculty.sru.edu/david.dailey/svg/newstuff/clipPath4.svg).

i think maybe the documentation should be slightly changed to reflect that _svgclippaths_ refers primarily to svg proper (or doesn't link to the mdc page on using svg clip paths to clip html content (which, admittedly, is a _nifty_ feature))

maybe an admonition or some note on the documentation of what svgclippaths refers to basically, because it's a bit unclear at the moment.

**Comment by Daniil-333** [comment]
@nsfmc , You are well done! God bless you)
There is very little information on the Internet on this subject.
