### ISSUE TITLE
Modernizr.inputtypes no class set.

### ISSUE THREAD

**Issue by northerndesigner** [Modernizr/Modernizr#2130]
Tested this in latest Chrome, Safari, and Firefox. No class set for any input types.

**Comment by patrickkettner** [comment]
What build are you using?

**Comment by northerndesigner** [comment]
modernizr v3.3.1
https://modernizr.com/download?-backgroundblendmode-flexbox-flexboxlegacy-geolocation-inlinesvg-inputtypes-svg-svgasimg-touchevents-setclasses-dontmin

**Comment by richiekastl** [comment]
I'm having the same issue

**Comment by rejas** [comment]
Can confirm it still happens with Modernizr v3.6
