### ISSUE TITLE
`touchevents` is `true` on Chrome 54+ Windows

### ISSUE THREAD

**Issue by pracucci** [Modernizr/Modernizr#2134]
The file [`touchevents.js`](https://github.com/Modernizr/Modernizr/blob/master/feature-detects/touchevents.js) contains the following comment:
> Chrome (desktop) used to lie about its support on this, but that has since been rectified: http://crbug.com/36415

This is actually no more true, since `'ontouchstart' in window` returns `true` on Chrome 54+ on Windows (I personally tested Chrome 55 on Windows 10).

Are you aware of any workaround to fix it?

**Comment by rejas** [comment]
Testing on my Chrome-67/Win-10 machine I get the correct 'false' as a result of this test. Does this error still happen to you and if so what kind of machine are you running it on?

**Comment by pracucci** [comment]
The issue was reported some time ago. I'm no more working on such project, so I'm going to close it, cause turn on the testing environment would require me time. Thanks anyway for checking it.
