### ISSUE TITLE
ES6 arrow feature detect is not being released

### ISSUE THREAD

**Issue by ricardobrandao** [Modernizr/Modernizr#2139]
Is there any reason for [arrow.js](https://github.com/Modernizr/Modernizr/blob/master/feature-detects/es6/arrow.js) not being released (e.g. [3.3.1](https://github.com/Modernizr/Modernizr/tree/v3.3.1) tag)?

**Comment by rejas** [comment]
hi @ricardobrandao v3.6.0 contains that test, enjoy.

**Comment by ricardobrandao** [comment]
Great, thanks! 👍
