### ISSUE TITLE
Possibility to distinguish between IE10 and 11 regarding flexbox?

### ISSUE THREAD

**Issue by backflip** [Modernizr/Modernizr#2141]
AFAIK, both IE10 and IE11 report `flexboxtweener`. However, in order to work around https://github.com/philipwalton/flexbugs#8-flex-basis-doesnt-support-calc, it would be nice to be able to distinguish between the two:

```scss
.col {
	flex: 1 0 calc(100% - #{$something});

	// IE11 pseudo-code selector
	.flexboxtweener-ie11 & {
		flex-basis: calc(100% - #{$something});
	}

	// IE10 pseudo-code selector
	.flexboxtweener-ie10 & {
		width: calc(100% - #{$something});
	}
}
```

**Comment by ryanseddon** [comment]
You could use one of the Modernizr APIs to determine support for flex-basis with a calc.

```js
Modernizr.testAllProps('flex-basis', 'calc(100% - 20px)')
```

Returns true in IE11 and false in IE10. See [test case](http://output.jsbin.com/papawidobi/1/quiet).

**Comment by ryanseddon** [comment]
Closing above code can get you where you want.
