### ISSUE TITLE
Modernizr + bootstrap only showing blank white page issue

### ISSUE THREAD

**Issue by tschallacka** [Modernizr/Modernizr#2147]
Bootstrap has this file
https://github.com/twbs/bootstrap/blob/96d8553becfdf219c40e046e1202d4f2a2723010/scss/mixins/_visibility.scss#L4

When the hidden attribute is selected in the Modernizr feature composer the hidden attribute gets added to the html tag.
This causes the html tag to get display:none and a complete blank page with correctly made up invisible content to show up.
This is undesireable for reasons.

I'm not sure if the fix should be with modernizr changing the attribute name, or implementing that if it's added that a style="display:initial !imporant;" is added to the html tag if the hidden attribute is selected.

I'm also cross posting this at the bootstrap github, if they can make their hidden selector into `html .hidden`

I fixed it for myself in my style, by overwriting the important styling rule, but it is a thing to consider, and maybe add to the documentation.

**Comment by ryanseddon** [comment]
One way to work around this is to add a class prefix to the tests e.g.

```json
{
  "minify": true,
  "classPrefix": "foo-"
  "options": [
    "setClasses"
  ],
  "feature-detects": [
    "test/dom/hidden",
  ]
}
```

That way `.hidden` becomes `.foo-hidden`

**Comment by elektromntr** [comment]
Seems like hav similar problem here.
@ryanseddon Where and how should I add this part of code?

**Comment by patrickkettner** [comment]
you set it in the right hand column on the web builder, or in your modernizr config object. This is done before you generate your modernizr file

**Comment by rejas** [comment]
@tschallacka @elektromntr did it fix your problem?

**Comment by tschallacka** [comment]
@rejas this was fixed in bootstrap https://github.com/twbs/bootstrap/pull/22113
