### ISSUE TITLE
`touchevents` doesn't appear to be working

### ISSUE THREAD

**Issue by jchristianhall** [Modernizr/Modernizr#2156]
I'm on version 3.3.1 and I recently noticed that every device I've been testing is having `no-touchevents` applied incorrectly. Correct me if I'm wrong, but that test is supposed to detect whether a browser supports the Touch Events spec. However, on the browsers I've tested that should support that spec, they're still showing up as `no-touchevents`. We recently upgraded to the latest Modernizr, so I'm wondering if this introduced a regression.

**Comment by patrickkettner** [comment]
what devices are you testing on?

**Comment by jchristianhall** [comment]
I've tried out iPhone 7 (iOS 10.2), Samsung Galaxy Tab 4 (Android 4.4.2), and a variety of other devices through Browserstack and the iOS simulator.

**Comment by patrickkettner** [comment]
quick [sanity check on codepen](https://codepen.io/anon/pen/dNQmja) is returning touchevents on my iPhone 7 and galaxy tab 5. Could you post a quick dmeo showing the problem?

**Comment by jchristianhall** [comment]
@patrickkettner I'm fairly confident this is a problem with our environment and not Modernizr itself. Thanks for looking into it though!

**Comment by patrickkettner** [comment]
lemme know if youd like any help figuring it out!
cheers
