### ISSUE TITLE
Modernizr + Bower

### ISSUE THREAD

**Issue by WaKeMaTTa** [Modernizr/Modernizr#2157]
Hello,

You can add this package to [bower](https://bower.io/). 

I use https://rails-assets.org/ and rails-assets.org require the `bower.json` file to generate the gem for rails.

Here you can see the problem: 

![image](https://cloud.githubusercontent.com/assets/3450257/22890283/2b39aba4-f20c-11e6-94b8-06492e5038e1.png)

https://rails-assets.org/#/components/modernizr

Thanks in advance.

**Comment by roblarsen** [comment]
See [this comment](https://github.com/Modernizr/Modernizr/issues/1664#issuecomment-141551558)

**Comment by WaKeMaTTa** [comment]
@roblarsen Ok, thanks.
