### ISSUE TITLE
audiopreload always returns false when web inspector open

### ISSUE THREAD

**Issue by ulisessp** [Modernizr/Modernizr#2162]
I don't know if I'm actually missing something and is the expected behaviour, but Modernizr.audiopreload always returns false when the web inspector is open. I'm testing inChrome 56, so audio preload is actually possible.

**Comment by ryanseddon** [comment]
I'm not seeing the same thing in Chrome 56 on osx?

https://modernizr.com/download?audiopreload-dontmin-setclasses&q=preload

![screen shot 2017-02-23 at 11 23 59](https://cloud.githubusercontent.com/assets/143402/23239326/98fee54a-f9ba-11e6-8c41-70c7044cec7c.png)

**Comment by ulisessp** [comment]
I've been testing today and I'm not getting false anymore. Not sure what happened last day, I tried to reproduce it again and I don't see it anymore.
