### ISSUE TITLE
Builder UI is buggy in firefox

### ISSUE THREAD

**Issue by stof** [Modernizr/Modernizr#2167]
See this screenshot of a selected detect:
![modernizer_bug](https://cloud.githubusercontent.com/assets/439401/23413394/d6c5ba9e-fdd8-11e6-8215-4f0f58c08fd4.png)

**Comment by ryanseddon** [comment]
Can you file this on https://github.com/Modernizr/modernizr-neue/issues

If you're up for a PR that would be even better.

**Comment by stof** [comment]
Actually, it was already reported: https://github.com/Modernizr/modernizr-neue/issues/44
