### ISSUE TITLE
Feature detect CSS Grid

### ISSUE THREAD

**Issue by Gandem** [Modernizr/Modernizr#2168]
Hello !

I noticed that Modernizr isn't able to feature detect **CSS Grid** support yet !
As the grid is shipping with the next version of Google Chrome and will soon be available for general usage, it would be a nice to have the appropriate feature-detect in Modernizr.

Is it planned ? If no one is working on it yet, I'll be glad to try and work on a **PR** 😃 !

**Comment by Stexxen** [comment]
Wow! 25 thumbs up, clearly a much needed feature.
I notice pull https://github.com/Modernizr/Modernizr/pull/2189 has just been merged, which offers some support.

**Comment by patrickkettner** [comment]
Hey folks! this is included in v3.5.0
