### ISSUE TITLE
input-formtarget detection not working

### ISSUE THREAD

**Issue by andreacc** [Modernizr/Modernizr#2171]
At least here at my browser (firefox 52 32bit, windows 7 64bit), the feature detection is not working.

I  think it only works when the "t" in "formTarget" is uppercase, but Modernzr it uses lowercase in the script and that is why is not working, I think. See the results in my console just changing the "t" case:

12:12:31.590 !!('formtarget' in document.createElement('input'))
12:12:31.666 false
12:12:40.831 !!('formTarget' in document.createElement('input'))
12:12:40.891 true

I sent a pull request with the fix. Also sent another pull request with feature detection for input: formNoValidate.

**Comment by rejas** [comment]
Merged your PR :-) Thx.
