### ISSUE TITLE
Page scrolls to iframe that includes modernizr

### ISSUE THREAD

**Issue by tavosansal** [Modernizr/Modernizr#2172]
Hello, 

I have a page that does not include modernizr but has an iframe at the bottom of the page that does include it. When I do a page refresh, the window scrolls to the iframe that does contain modernizr. If I remove the modernizr dependency from the iframe, then this behavior does not occur. Wondering if anyone had any ideas on why this would happen.
Thank you.

**Comment by ryanseddon** [comment]
Weird can you create a reduced test case of this behaviour so we can narrow down what's causing it.

**Comment by 3zzy** [comment]
Having the same issue, just including the modernizr on the page auto scrolls it to the bottom of the page on load.

**Comment by rejas** [comment]
hi @tavosansal and @3zzy could you post your config for modernizr? we know that the hyphens test does some unwanted scrolling so maybe in your case it might be the same.

**Comment by cmoock** [comment]
We encountered this same issue in all versions of Modernizr from 3.3.1 to 3.6.0. The culprit was the focus() call in CSS Hyphens. Short excerpt:

```
if (dummy.setSelectionRange) {
  dummy.focus();
  dummy.setSelectionRange(0,0);
}
```

We were able to workaround the problem by removing CSS Hyphens from our Modernizr custom build.

**Comment by ManuelBoucault** [comment]
Having the same, including only the ```input[type="number"] Localization``` detection.
You can see the issue here : https://codesandbox.io/s/o6vzzvj7z

**Comment by AlexTr** [comment]
I confirm the above issue - with `input[type="number"] Localization` detection

**Comment by alizain** [comment]
We're experiencing the same problem with `input[type="number"] Localization` detection

**Comment by rejas** [comment]
Closing this since 
- the `hyphen` test was fixed in https://github.com/Modernizr/Modernizr/pull/2369
- the `input[type="number"] Localization` will be tracked in #2492 thanks to @alizain 

Any other test that messes with the focus should get its own isssue...
