### ISSUE TITLE
When can i use css grid, varibles,and so on..

### ISSUE THREAD

**Issue by zyc8904** [Modernizr/Modernizr#2182]
My projects need CSS Grid and Variables , But I can't find them in download list, What time can i use these?

**Comment by everget** [comment]
@zyc8904 
![image](https://user-images.githubusercontent.com/19395364/30925365-41e33ac2-a3ba-11e7-8a44-f624c87e26ba.png)

**Comment by rejas** [comment]
hi @zyc8904 hopefully variables land soon when v3.7.0 is released. still to ETA for it though, waiting for maintainers to react and publish something. closing this issue in the meantime.
