### ISSUE TITLE
No sure about a new version issue (v3.4.0)?

### ISSUE THREAD

**Issue by ucsdmath** [Modernizr/Modernizr#2184]
The information within the websites differ slightly.  Is there a v3.4.0?  `npmjs.com` says something might be available.  Thank you, Daryl

Modernizr 3.3.1:  https://modernizr.com/news
Modernizr 3.3.1:  https://github.com/Modernizr/Modernizr/releases/tag/v3.3.1
... ?
Modernizr 3.4.0:  https://www.npmjs.com/package/modernizr

**Comment by patrickkettner** [comment]
There just wasn't a blog post about the release yet. I'll tag it shortly

**Comment by victor-tafro** [comment]
3.4.0 and 3.5.0 are up on the site, this issue should be closed.
