### ISSUE TITLE
Modernizr injecting ' style="height: 3000px;" ' attributes on Safari (OSX/iOS) for no apparent reason?

### ISSUE THREAD

**Issue by KrisJanssen** [Modernizr/Modernizr#2186]
I am running:

OSX 10.12.5 Beta (16F43c)
iOS 10.3 (14E5277a)

In these versions, but also in previous ones for the last couple of months I have been noticing that pages like this one:

http://onlinelibrary.wiley.com/doi/10.1002/anie.201608625/abstract

do not load properly. They display as a white page, both on OSX Safari as well as the iOS variant.

It took me a while to figure out the page was there but a seemingly unnecessary `style="height: 3000px;` is being added to the `<body>` tag, making the content render way below the viewport.

On a friends iOS device (10.2.x) the issue doesn't present itself, neither on my devices in Chrome or Safari.

Some debugging and googling quickly led me to:

1. A [Gist](https://gist.github.com/bobslaede/1221602) related to an extension of Modernizr to enable iOS/Safari positionfixed functionality. 
2. An offending line in the websites [Modernizr.custom.js](http://onlinelibrary.wiley.com/enhanced/static/common/js/vendor/modernizr.custom.js): `root.style.height="3000px";`

I suspect this is some kind of custom hack to fix some general issue but it is messing with the usability of the website.

I lack the experience with Modernizr to understand why this is happening and who is at fault here.

**Update**

On OSX, Safari is at 10.1.1 (12603.2.1): the issue is present
When I check the recovery partition of my Mac, it still uses Safari 10.0.1 (12602.2.14.0.7), here the page renders normally. The same goes for a friends machine with 10.0.3 ...

This issue is perhaps not an issue related directly to Modernizr itself but I have found a number of websites/tutorials that seem to apply the customisations from the Gist referenced above so it might be relevant...

**Comment by ryanseddon** [comment]
This isn't an issue with Modernizr looks like they've copied some code from a long standing issue with trying to reliably detect it https://github.com/Modernizr/Modernizr/issues/167

**Comment by WebStew** [comment]
@KrisJanssen - Thank you for logging this. I have just debugged our app on Online Library and tracked it down to the iospositionfixed test in the Gist you mention. We're looking to patch this as soon as possible.

**Comment by KrisJanssen** [comment]
@WebStew - Thanks for the update! So there is no need to send further info to the Wiley support team? Many users at our uni will thank you for getting this fixed :)

**Comment by WebStew** [comment]
Hi @KrisJanssen - That is correct, this issue has already been picked up by our support team.
