### ISSUE TITLE
Latest release tag points to v2.8.3

### ISSUE THREAD

**Issue by codingzenster** [Modernizr/Modernizr#2191]
As seen in the screenshot, the latest release points to v2.8.3. Is this intentional or should this be pointing to v3.5.1?

![screen shot 2017-04-20 at 12 42 50 pm](https://cloud.githubusercontent.com/assets/27775352/25218031/fe7f4120-25c6-11e7-8690-5fd00b3cb314.png)

**Comment by patrickkettner** [comment]
thanks for the heads up - fixed
