### ISSUE TITLE
Modernizr.load() is not a function

### ISSUE THREAD

**Issue by peijin1990** [Modernizr/Modernizr#2194]
when I used Modernizr.load(), I found there is a problem.Chrome told me:
Uncaught TypeError: Modernizr.load is not a function
I can't find this function.
Is it disabled?or has already been deleted? 
please tell me. Thank you every much!

**Comment by patrickkettner** [comment]
Hey @peijin1990!

Modernizr.load was removed several years ago. If you want the same functionality, you can use yepnope which was the underlying library that powered modernizr
