### ISSUE TITLE
Modernizr.positionfixed returns false in safari iphone 7 

### ISSUE THREAD

**Issue by abdul-kalam** [Modernizr/Modernizr#2196]
Modernizr.positionfixed is returning false in safari (ios 10.3.1). As fas as I know safari ios supports position fixed from 5.0+. Please let me know if it is bug in Modernizr or I am missing something.

**Comment by patrickkettner** [comment]
[it has never been added to Modernizr because of that issue](https://github.com/Modernizr/Modernizr/issues/167)
