### ISSUE TITLE
cssomPrefixes is not defined

### ISSUE THREAD

**Issue by medinasod** [Modernizr/Modernizr#2199]
I'm trying to debug this error on a site that I inherited. Am I missing a dependency?

> **Uncaught ReferenceError: cssomPrefixes is not defined**
>     at Object.z [as testAllProps] (modernizr.custom.78977.js?opfy1k:4)
>     at modernizr.custom.78977.js?opfy1k:4
>     at Object.e.addTest (modernizr.custom.78977.js?opfy1k:4)
>     at modernizr.custom.78977.js?opfy1k:4

**The line the error is coming from is commented on below:**

/\* Modernizr 2.8.3 (Custom Build) | MIT & BSD
 \* Build: http://modernizr.com/download/#-cssclasses-css_boxsizing-load
 \*/

```
;window.Modernizr = function(a, b, c) {
    function u(a) {
        j.cssText = a
    }
    function v(a, b) {
        return u(prefixes.join(a + ";") + (b || ""))
    }
    function w(a, b) {
        return typeof a === b
    }
    function x(a, b) {
        return !!~("" + a).indexOf(b)
    }
    function y(a, b, d) {
        for (var e in a) {
            var f = b[a[e]];
            if (f !== c)
                return d === !1 ? a[e] : w(f, "function") ? f.bind(d || b) : f
        }
        return !1
    }
    function z(a, b, c) {
        var d = a.charAt(0).toUpperCase() + a.slice(1)
          , e = (a + " " + cssomPrefixes.join(d + " ") + d).split(" ");  /* ERROR HERE */
        return w(b, "string") || w(b, "undefined") ? testProps(e, b) : (e = (a + " " + domPrefixes.join(d + " ") + d).split(" "),
        y(e, b, c))
    }
```

Thanks for any help you can give.

**Comment by patrickkettner** [comment]
Hey @medinasod 
You using a very very very old version of Modernizr. Are you able to rebuild using the link in the comment at the top of your file?

**Comment by medinasod** [comment]
Hey @patrickkettner 
Thanks for your help with this. Actually, when I follow the link it resolves to this:
https://modernizr.com/download/?boxsizing-setclasses
Which I'm not sure is equivalent. I thought about upgrading Modernizr, but the site I'm working on is quite large and complex and I want to avoid breaking it. It's a Drupal 7 site using the [Modernizr module](https://www.drupal.org/project/modernizr) and needless to say with anything D7 it's a quite elaborate setup.

**Comment by patrickkettner** [comment]
>Which I'm not sure is equivalent

it is equivalent, with one missing piece. Modenrizr.load. This was actually just yepnope under the covers, and if you use the cli tool to build, you can still include it in your options if you also include yepnope.js in the same page'/js bundle.

I totally appreciate the aversion to breaking other tings. I can say with a very high level of confidence that things should work if you follow the above paragraph. However, if you just want the thing to work, you can grab [this line](https://github.com/Modernizr/Modernizr/blob/7db55bbfa9de67289892b94b60bf2f088c11d669/src/cssomPrefixes.js#L2) and then paste it anywhere inside of the IFFE (i.e. below `;window.Modernizr = function(a, b, c) `)

cheers!

**Comment by medinasod** [comment]
Thank you so much, @patrickkettner!

**Comment by medinasod** [comment]
@patrickkettner How would I include Modernizr.load? I don't see it as an option on the custom build page and it gets removed when I add it to the parameter string. Thanks again.

**Comment by patrickkettner** [comment]
hey @medinasod ,

sorry, I wasn't clearer. It isn't on the download page, as it has been depreciate and it is just a warning that says it has been removed. It also detects if yepnope is also included on the page, and deffers to that if present. You have to use the npm package manually in order to use it. That is what I meant by

> if you use the cli tool to build, you can still include it in your options

Alternatively, include yepnope in your build/script, and then below where your scripts define Modernizr, you can do 

```
Modernizr.load = yepnope
```

**Comment by medinasod** [comment]
Ok, thanks for the clarification. I appreciate the help, @patrickkettner!
