### ISSUE TITLE
Hoping for support for Variable Fonts (via support for font-variation-settings)

### ISSUE THREAD

**Issue by jpamental** [Modernizr/Modernizr#2200]
Hi there -

Variable fonts are ticking along in their development, with a draft specification in the works and support in the nightly builds of Webkit, Chrome, Firefox and Opera. It would be great to get detection of support into Modernizr. It might be worth it to hook in to browser support for `font-variation-settings` (the low-level method of controlling variable font properties)

https://drafts.csswg.org/css-fonts-4/#low-level-font-variation-settings-control-the-font-variation-settings-property

Jason

**Comment by zachleat** [comment]
I’ll leave a comment in support of this too ❤️

**Comment by jpamental** [comment]
That was fast @patrickkettner :)

Looking forward to checking it out!

**Comment by patrickkettner** [comment]
:D it'll be a little bit before it gets merged, in the mean time, `'fontVariationSettings' in document.documentElement.style` will give you the same information without modernizr
