### ISSUE TITLE
How to check browser is IE9 or less than IE9

### ISSUE THREAD

**Issue by sathyalog** [Modernizr/Modernizr#2204]
Team,

We were using Modernizr 2.8.3 in our project. The first thing to let you know all, I m new to Modernizr and not aware of complete documentation. However, I have gone through https://modernizr.com/docs to find out the script to check IE compatibility, but couldn't find a possible solution to check the browser version with IE9 or less than IE9. Could anyone help me to find out the same??

I need to write in 'if' condition whether the browser is IE9 or less than that..then execute my statements in that block. Please help.

Thanks
Sathya

**Comment by patrickkettner** [comment]
Hello Sathya,
The purpose of Modernizr is to test for features, not specific browsers. To check for IE (any version) would be against the entire purpose of Modernizr. 

Why are you wanting to know if the browser is IE9?

**Comment by sathyalog** [comment]
Hi Patrick,

Oh ok, I got it :). I have an if condition where we were checking modernizr.csstransitions to execute some statements. On the same condition, I would like to also check if IE version less than 11 or 9 (project requirement). I thought we have some way to test this using modernizr and as I didn't found in docs I thought to check with your team. Apologies for that :). If we have some way to check using modernizr script just let me know..else please close this issue. Thanks for your quick response.

**Comment by patrickkettner** [comment]
Hey Sathya,
My question is _why_ is it a project requirement? What does IE 9 do/no do that you are trying to prevent? You should almost never need the actual browser, so this really feels like an [xy problem](https://meta.stackexchange.com/questions/66377/what-is-the-xy-problem).

**Comment by sathyalog** [comment]
Hi Patrick,

I am trying to prevent the execution of some piece of code if it's less than IE9 as our project do not support less than IE9 browsers.

Thanks

**Comment by patrickkettner** [comment]
I understand. WHY though. What will work/not work in IE9 SPECIFICALLY that makes you want to prevent it running there.

**Comment by sathyalog** [comment]
Ok. Let me explain with code. 
if (Modernizr.csstransitions) {
            $root.parent().bind(defaults.events.transition, removeCookie);
}

On binding events we were calling removeCookie function, this we wrote initially to support IE browsers. But now this removeCookie is being called everytime in all browsers when we click on the slider which is breaking some functionality in our project. So, we planned to execute this statements only if the browser is IE or less than IE9/IE11. Hence I was looking for some code which helps to resolve my issue. My lead suggested me to use modernizr to achieve this functionality.

Thanks

**Comment by patrickkettner** [comment]
Ok cool, moving in the right direction.

So, I totally understand being under a deadline and wanting to just get the thing finished, but I want to suggest that the way you are framing the problem is incorrect.

The issue is not that you want to run different code in IE 9, The issue is you want to run different code when a browser behaves in a certain way. 

It sounds like IE is firing events in a different manner than other browsers - is that the case? If so, what we want to do here is check for those events (I would need more information as to what you are doing in your code in order to help write the code you are wanting here), and then check based on the results of that.

**Comment by roblarsen** [comment]
> if (Modernizr.csstransitions) {
$root.parent().bind(defaults.events.transition, removeCookie);
}

If that's your real code, then IE9 will never see the body of that if statement code because `Modernizr.csstransitions` would be false (it doesn't support CSS transitions). Only browsers that support CSS Transitions would get that binding.

**Comment by sathyalog** [comment]
Hi Patrick,
yes. I might be framing it incorrect manner. Apologies for that :).

What's happening is...

When I click on slider next/prev buttons, click event is binding with above code on page load and removeCookie is being called in all browsers when I click on slider prev/next buttons which was not the requirement. This binding should happen only if it's IE browser else it has to execute else block statements. Currently, if block statements being executed in chrome/firefox and all browsers. Hence I was looking for solutions from modernizr docs. Just let me know if is there any script to check whether its IE browser or not.

Roblarsen,

Yes. I understood the issue now. I will fix this at my end now. 

Thanks, both of you. You can close the ticket. But at least for future reference, just let me know if is there any script to check whether the browser is IE or not. That would be really helpful for me in future :)

**Comment by patrickkettner** [comment]
> Thanks, both of you. You can close the ticket. But at least for future reference, just let me know if is there any script to check whether the browser is IE or not. That would be really helpful for me in future :)

Hey Sathyalog
That is exactly the thing you _should not_ be doing. You keep saying you want to execute code in IE. I am struggling to explain to you that you should be trying to run code based on the behavior of the browser, not the name of the browser.  You are saying that you want to remove a cookie if it is IE, but you are not explaining WHY you want to do that. You want to step back from your problem and ask yourself what behavior IE 9 has that is making you not want to run the code there. Once you can answer that question, you want to create a detect that checks for that behavior. This is something I would be more than happy to help you with.

If you insist on checking for the IE version, than you do not want to use Modernizr. Googling that question will give you a large number of answers on how to achieve that.

best of luck
