### ISSUE TITLE
media-query max-resolution not working anymore

### ISSUE THREAD

**Issue by ray007** [Modernizr/Modernizr#2208]
Upgrading `Modernizr` from version 2.8.2 to 3.5 caused the media query
```
@media screen and (max-resolution: 100dpi)
```
in one of my css files to stop working.

Interactive testing in the developer console (google chrome) showed the first part still returning true, but I couldn't get any resolution queries to work anymore.

**Comment by patrickkettner** [comment]
can you provide code/live site/reproduction? It is much more likely that there was a class change or collisson that is causing the problem, as we do not touch any of the native media query bindings

**Comment by ray007** [comment]
The difference is, old Modernizr added a class `no-touch` which I was using, new Modernizr adds a class `no-touchevents`.

**Comment by patrickkettner** [comment]
@ray007 to be clear, this is resolved correct?

**Comment by ray007** [comment]
yes it is.
