### ISSUE TITLE
Checkbox is incorrectly positioned

### ISSUE THREAD

**Issue by whmountains** [Modernizr/Modernizr#2210]
![screen shot 2017-05-23 at 15 58 41](https://cloud.githubusercontent.com/assets/8680147/26373745/bc3031e8-3fd0-11e7-84ae-a6f95cc0457e.jpg)

Browser: Firefox 54
Operating System: Mac OS Sierra

**Comment by patrickkettner** [comment]
this issue is being tracked on the website's' repo, https://github.com/Modernizr/Modernizr-neue
