### ISSUE TITLE
How to detect touch event on Kiosk screen?

### ISSUE THREAD

**Issue by beany-vu** [Modernizr/Modernizr#2213]
I know the Modernizr supports detecting touch event on iPad. On surface, I can use point event instead. However, I have no idea how can we detect a touch event on **Kiosk** screen. Anyone has recommendation for this case?

**Comment by patrickkettner** [comment]
What is the browser powering it?

**Comment by beany-vu** [comment]
The **Google Chrome**. I can detect the click event but no way for touch/point :|.

**Comment by patrickkettner** [comment]
Chrome supports PointerEvents , you can use that

**Comment by beany-vu** [comment]
I use this logic:
if (Modernizr.touchevents || Modernizr.pointerevents) {...//my logic}

Modernizr.touchevents works on iPad

Modernizr.pointerevents works on surface(Edge browser)

However, it didn't work on Kiosk. I realize that click event is okay on Kiosk. And I had a trick to detect this screen by a formula:  Kiosk = fullscreen + click detect.
Because the show room of my client always open web on Kiosk in full screen mode so it's fine. I'm not sure if we have a nicer solution?

**Comment by beany-vu** [comment]
Sorry for this issue, I think this screen support only the click event because I can see a pointer on it. I can detect the kiosk mode by checking if it's on the full screen mode. It's enough for the time being. It can be closed now.
