### ISSUE TITLE
Update cdn

### ISSUE THREAD

**Issue by klihelp** [Modernizr/Modernizr#2214]
Modernizr on CDN could have only for classes or all features.

https://cdnjs.com/libraries/modernizr is at 2.8
https://cdn.jsdelivr.net/modernizr/3.3.1/modernizr.js

**Comment by patrickkettner** [comment]
Thanks for reaching out! But unfortunately we have nothing to do with the CDN file, nor do we want to have the entire kitchen sink build there as it would encourage folks to ship WAY more code than they need
