### ISSUE TITLE
getusermedia not returning correct values

### ISSUE THREAD

**Issue by flowen** [Modernizr/Modernizr#2219]
I used modernizr.getusermedia on a website with https enabled. I used this simple code:

```
window.addEventListener('DOMContentLoaded', () => {
    if (Modernizr.getusermedia) {
        const mic = new p5.AudioIn()
        mic.start()
    } else {
        console.log('getUserMedia() is not supported in your browser');
    }
})
```
It returned: console.log('getUserMedia() is not supported in your browser');
But modernizr.getusermedia returned true and the class was on the html element. 

I started this on stackoverflow:
https://stackoverflow.com/questions/44494029/getusermedia-does-not-work-with-ssl-certificates-installed?noredirect=1#comment76123378_44494029

**Comment by patrickkettner** [comment]
What browser did you hit the issue in?

**Comment by flowen** [comment]
Chrome Version 58.0.3029.110 (64-bit)

**Comment by patrickkettner** [comment]
Chrome definitely has getUserMedia support. Can you post a repro on jsbin/codepen?

**Comment by flowen** [comment]
You can see it live here: https://flowen.me/   

First ignore the errors from vimeo (not sure what that is). You'll see the log:
getUserMedia() is not supported in your browser
but Modernizr.getusermedia returns true. The code is here:
https://github.com/flowen/flowen.me/blob/master/src/js/depthmap-visualiser.js
line 139
