### ISSUE TITLE
EINTEGRITY: npm 5.0 integrity check and modernizr.com dependency

### ISSUE THREAD

**Issue by tlenex** [Modernizr/Modernizr#2220]
https://stackoverflow.com/questions/44699090/eintegrity-npm-5-0-integrity-check-and-modernizr-com-dependency
Any hits will be much appreciated.

**Comment by patrickkettner** [comment]
You have an integrity check to know when files change. The error is the result of the files changing. 

What is your question?

**Comment by tlenex** [comment]
Let's say we have this scenario:
1. In my work I have installed dependency with `https://modernizr.com/download?setclasses-flash`, so the `package-lock.json` has set up an `sha` checksum.
2. I go for a home and started working remotly, cloned my repo and run `npm install` 
3. I have EINTEGRITY error, and my project can't run, because Modernizr and other devDependencies are not installed.

Questions:
1. Is there a way to be sure that `sha` checksum won't change on next install with `https://modernizr.com/download?setclasses-flash` url?
2. How to solve this, without updating/setting up in `.gitignore` the `package-lock.json` file?

**Comment by tlenex** [comment]
I finally resolved this issue.

Our team moved away from URL dependency without SEMVER notation, in this case `https://modernizr.com/download?setclasses-flash` and used `modernizr-loader` with `webpack`. There are also equivalents for `gulp` and `grunt` tools available on npm, pick and use one you like the most.

After using them, we finally get rid of returning `EINTEGRITY` npm error without nuking `package-lock.json` or `node_modules`.
