### ISSUE TITLE
H265 check

### ISSUE THREAD

**Issue by vasimi** [Modernizr/Modernizr#2231]
It would be nice to have H265 support check in Modernizr. Edge and Safari already support HEVC.

**Comment by patrickkettner** [comment]
@MekliCZ would you be interested in helping create a feature detection for it?

**Comment by rejas** [comment]
@patrickkettner is there some test that @MekliCZ (or whoever feels like taking over this issue) could take as a blueprint?

**Comment by patrickkettner** [comment]
any of the [video detects](https://github.com/Modernizr/Modernizr/blob/master/feature-detects/video.js) would be a great example. Bsically `canPlayType`
