### ISSUE TITLE
3.5.0 'arrow' test not working in Google Chrome 60.0.3112.90

### ISSUE THREAD

**Issue by Kruithne** [Modernizr/Modernizr#2234]
**Test:** arrow (ES6)
**Version:** 3.5.0
**Browser:** Google Chrome Version 60.0.3112.90 (Official Build) (64-bit)

**Expected:** `arrow` class to be applied to the `<html>` tag, and `Modernizr.arrow` to be true.
**Result:** `no-arrow` class is applied, and `Modernizr.arrow` is false.

Feature verification via console:
```
> eval('()=>{}');
()=>{}

> a = () => { console.info("Hello from the other side."); }; a();
Hello from the other side.
```

**Comment by Kruithne** [comment]
**Problem identified:** The test uses `eval`, which was blocked by a CSP (Content Security Policy) directive to prevent unsafe evaluations. Closing issue, hopefully serves useful to anyone else encountering this failure.

**Comment by GeoMarkou** [comment]
Just ran into this issue. Is the recommended solution really to allow unsafe eval in the CSP? Is there no other way to detect arrow function support in the browser?

**Comment by Markel** [comment]
Yeah, I agree with @GeoMarkou . Moreover, a test which result in a false negative due to errors with CSP doesn't work correctly, as arrow functions may be implemented but they are not detected correctly. I'll try to look further into the issue on the weekend :)
