### ISSUE TITLE
Building custom version: drag and drop & select all

### ISSUE THREAD

**Issue by joomlabeat** [Modernizr/Modernizr#2235]
What I should choose to include the drag and drop detection?
And isn't there a way to create a file that will include the whole library by a select all option?

**Comment by patrickkettner** [comment]
The drag and drop detect was removed because it was not reliable.
I would HIGHLY suggest not using a build with everything, it's several megabytes in size. But you can click the development version link on the homepage to take you to a version with everything checked off

**Comment by joomlabeat** [comment]
So currently there isn't a way to detect the drag and drop capabilities?? 

The "include-all" build isn't meant for a production site, rather for testing/experimenting - so to create a single file and use it for all the tests I would like to do - without having to go and generate files each time.

**Comment by patrickkettner** [comment]
> So currently there isn't a way to detect the drag and drop capabilities??
> 

Correct. There is not a reliable way to detect it
> 
> The "include-all" build isn't meant for a production site, rather for testing/experimenting - so to create a single file and use it for all the tests I would like to do - without having to go and generate files each time.
> 
Ok sounds good

**Comment by rejas** [comment]
@joomlabeat so is your question answered? can this issue be closed?
