### ISSUE TITLE
[Googlebot] typeof window.Modernizr is undefined

### ISSUE THREAD

**Issue by hinok** [Modernizr/Modernizr#2236]
Hey,
I've been working on a few experiments which focus on Googlebot. I've used `Modernizr` to detect some features and I've found that:

* `window.Modernizr` is always `undefined` (for Modernizr > `v3.0.0`)
* Even if `window.Modernizr` is `undefined`, It's quite easy to check that it has added CSS classes to `<html>` so something is working...
Classes below has been taken from the DOM and then sent to my API but still when I try access Modernizr, it's always `undefined`.

```
htmlimports no-proximity no-audiopreload sizes no-videoautoplay no-flash no-indexeddb
transferables blobworkers no-exiforientation webpalpha webpanimation webp no-apng 
no-jpeg2000 no-jpegxr webp-alpha webp-animation datauri no-dataworkers webp-lossless
```

* I'm using "[Fetch as Google](https://www.google.com/webmasters/tools/googlebot-fetch)" service from Google Search Console so debugging is hard. I use DOM (see screenshots below) and ajax calls to my API for logging.
* ~~This problem doesn't exist for Modernizr `v2.8.3`~~ This problem doesn't exist for Modernizr v2.8.3 without [feature-detects](https://github.com/Modernizr/Modernizr/tree/v2.8.3/feature-detects). When all `feature-detects` are included from `v2.8.3` tag, it works only for `This is how Googlebot saw the page` but it doesn't work for `This is how visitor to your website would have seen the page`.

 

---
Screenshots from _Fetch as Google._

**Modernizr `3.0.0+`**

![1](https://user-images.githubusercontent.com/1313605/29453220-220e2854-8409-11e7-9ba9-d08ed458cb4d.png)

**Modernizr `2.8.3`**

![2](https://user-images.githubusercontent.com/1313605/29453251-3e29c624-8409-11e7-8663-eea00e41aa8a.png)

**Modernizr `2.8.3` with all [feature-detects](https://github.com/Modernizr/Modernizr/tree/v2.8.3/feature-detects)**

![aaaaa](https://user-images.githubusercontent.com/1313605/29487147-0497b500-84f5-11e7-95ab-b6d80e783ee4.png)

I would like to understand why `Modernizr` cannot be accessed when Googlebot crawls the website.

Source code of Modernizr 2.8.3: https://gist.github.com/hinok/21130a47b1b1dfe5a7fd280229de6788

**Comment by igrigorik** [comment]
@hinok can you ping me the URLs you're using in your tests here?

**Comment by igrigorik** [comment]
If you [log the error](https://developers.google.com/search/docs/guides/debug-rendering):

> Uncaught NotSupportedError: Failed to construct 'RTCPeerConnection': No PeerConnection handler can be created, perhaps WebRTC is disabled?

It looks like RTCPeerConnection test passes, because the interface _is_ exposed, but the constructor returns an error. In turn, DataChannel test tries to call the constructor and triggers the exception:
 https://github.com/Modernizr/Modernizr/blob/aff821e42996f8996ba872e217441266bc1debd1/feature-detects/webrtc/datachannel.js#L21-L27

If you exclude the DataChannel test, I think the rest (v3.5.0) works just fine. Test URL I'm using: https://output.jsbin.com/leleves/latest/quiet

**Comment by hinok** [comment]
I'm pretty sure that I checked `window.onerror`, weird 🤔. I will check my tests and write a follow-up here.
