### ISSUE TITLE
feature-detects/img/srcset.js, notes: wrong link 

### ISSUE THREAD

**Issue by andreasgroth** [Modernizr/Modernizr#2252]
The link URL for the first note in the metadata is wrong. In line 7 of feature-detects/img/srcset.js
```
    "name": "Smashing Magazine Article",
    "href": "https://en.wikipedia.org/wiki/APNG"
```
A likely URL is https://www.smashingmagazine.com/2013/08/webkit-implements-srcset-and-why-its-a-good-thing/, which is mentioned in the article of the other note.

**Comment by rejas** [comment]
Thx for the hint, fixed it :-)
