### ISSUE TITLE
Could i install modernizr v2.8.x ? 

### ISSUE THREAD

**Issue by ridoansaleh** [Modernizr/Modernizr#2255]

**Comment by rejas** [comment]
Of course, either download the release directly from this github page (https://github.com/Modernizr/Modernizr/releases/tag/v2.8.0) or specify it in your projects package.json like this 

   ` "modernizr": "2.8.0"`

in the dependencies section. Or is that not what you meant?

**Comment by patrickkettner** [comment]
@ridoansaleh we no longer host modernizr 2.X on modernizr.com, however you can follow @rejas' instructions to get the file yourself. It is also available on various public CDNs, like [cdnjs](https://cdnjs.com/libraries/modernizr)

**Comment by ridoansaleh** [comment]
@rejas .. thanks for your info. That was  what i meant.
