### ISSUE TITLE
Is modernizr prefixedCSSValue cached?

### ISSUE THREAD

**Issue by mboevink** [Modernizr/Modernizr#2258]
Or should I implement one when creating elements in bulk?

**Comment by patrickkettner** [comment]
hey @mboevink 
cached in what sense? Its a sub microsecond operation - I would really be surprised if this was going to be the level of performance optimization an application would have at the top of its impacts

**Comment by mboevink** [comment]
Hey,
I meant in terms of taking an inordinate amount of elements from a server response. But if you think it has no real impact then it is case closed. 

Cheers
