### ISSUE TITLE
hyphens test uses invalid CSS property

### ISSUE THREAD

**Issue by lolmaus** [Modernizr/Modernizr#2261]
On these two lines `text-justification:newspaper` is used:

https://github.com/Modernizr/Modernizr/blob/master/feature-detects/css/hyphens.js#L61
https://github.com/Modernizr/Modernizr/blob/master/feature-detects/css/hyphens.js#L67

But there's no such property.

Should probably be [text-justify](https://developer.mozilla.org/en-US/docs/Web/CSS/text-justify) but I dunno if such change is safe for the test.

**Comment by rejas** [comment]
Changed it in PR https://github.com/Modernizr/Modernizr/pull/2339 doesnt seem to affect the tests
