### ISSUE TITLE
Correction (Pull request to avoid type error)

### ISSUE THREAD

**Issue by kressly** [Modernizr/Modernizr#2263]
To avoid type error when using this with other libraries change 

 ```
for (var k in windowResizer.resizeHandlers) {
        windowResizer.resizeHandlers[k]()
    }
```

to 

```
windowResizer.resizeHandlers.each(function(item){
            item();
    });

```

[Check Stackoverflow's link](https://stackoverflow.com/questions/47123639/how-to-solve-typeerror-iterator-is-not-a-function-with-prototypejs-when-jquery-i/47130870#47130870)

**Comment by rejas** [comment]
Closing since no further info was given.
