### ISSUE TITLE
'probablySupportsContext' in WebGL support test

### ISSUE THREAD

**Issue by bluzi** [Modernizr/Modernizr#2272]
Hello,

in [webgl.js](https://github.com/Modernizr/Modernizr/blob/5eea7e2a213edc9e83a47b6414d0250468d83471/feature-detects/webgl.js) you're testing if `webgl` and `experimental-webgl` are supported using a method called `probablySupportsContext` (and `supportsContext` as a fallback), but it seems like these methods are not available in Chrome (not even in Chrome Canary)

I also checked [MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement), and it seems like `probablySupportsContext` is only supported in a standard called "Living Standard" (and honestly, I have not idea what it means)

Will these methods be available soon? 

Thanks!

**Comment by patrickkettner** [comment]
Hey @bluzi!
A living standard is essentially just the latest, most up to date version of the standard. I don't have any insight to when they may be added to chrome. If you are interested in it, I'd suggest opening a bug (after checking to make sure one doesn't already exist) on crbug.com

**Comment by bluzi** [comment]
@patrickkettner 

fyi: i checked with whatwg (the ones who maintain living standard), and it looks like `porbablySupportsContext` has been removed from the standard and won't ever be supported.

https://github.com/whatwg/html/issues/3572
