### ISSUE TITLE
502 Bad Gateway on modernizr.com

### ISSUE THREAD

**Issue by tlenex** [Modernizr/Modernizr#2275]
https://modernizr.com is down currently. Any info when the issue might be resolved?

**Comment by drinkops** [comment]
As of 7:35:41 PM GMT Thursday 4th January 2018 also getting 502 error.

**Comment by patrickkettner** [comment]
this has been fixed, thanks for the report!

**Comment by gautam1168** [comment]
@patrickkettner Its giving 502 error again 8 May, 2019 1:13pm(IST)
