### ISSUE TITLE
State of the project?

### ISSUE THREAD

**Issue by rejas** [Modernizr/Modernizr#2278]
Hi guys and girls, 
love modernizr and how useful it is, but I guess not only I am wondering if this project still gets maintained? When people from the community close their own PR because they get no reaction in half a year (see https://github.com/Modernizr/Modernizr/pull/2229#issuecomment-356705934) something has to be done I guess. 
Do you need help, new maintainer, people to review etc? In what way can we help?
Cheers, V

**Comment by ryanseddon** [comment]
Yes I'm definitely guilty of having no time to work on this.

> Do you need help, new maintainer, people to review etc? In what way can we help?

We need all of this, any help to get this going again would be forever appreciated.

@patrickkettner do you have any input on this.

**Comment by ryanseddon** [comment]
I guess my first ask would be triaging the build up of issues and pull requests and seeing what needs to be done, updated or closed. This way we can have an overview on where we stand.

**Comment by patrickkettner** [comment]
> @patrickkettner do you have any input on this.

Basically I had a kid and got a new job, and haven't had the chance to sit down and go through it all.

but the first step would be triaging open bugs, as @ryanseddon mentioned

**Comment by rejas** [comment]
@patrickkettner first of all: congrats to the kid, hope it comes bugfree in v1 :-) 

as for helping triaging: i can only ask in the issues for more infos but closing is of course not yet in my power (as is adding labels). Issue #2232 would be something though you guys should answer: how can we contribute exactly, what procedure does a issue/bugfix/pr has to adhere to?

**Comment by rejas** [comment]
@patrickkettner @ryanseddon I am still wondering on how to proceed with reagrds to contributing. Should I make a list of PR that I deem worthy for a bugfix release?

**Comment by ryanseddon** [comment]
Yeah that makes sense, if you're keen and want to put in the work then I don't see why we couldn't make you a contributor to give you more control. @patrickkettner thoughts?

**Comment by rejas** [comment]
add my ideas in #2295

**Comment by rejas** [comment]
@ryanseddon I am still hoping this project isnt dead..

**Comment by rejas** [comment]
@ryanseddon @patrickkettner @doctyper  as you three are the only responding to my requests since I started my interest in the Modernizr ecosystem could we finally have a discussion how you envision the future of this Modernizr-org here on github?
- Yes, Modernizr isnt as relevant as it used to be but it isnt finished yet. Neither in the sense that it isnt used anymore nor in the feature-complete sense as seen by the open PR for new tests. 
- I am not sure myself if a v4 would be necessary (except when some groundbreaking stuff like es6 modules in https://github.com/Modernizr/Modernizr/pull/2108 is still on the table) but at least some more tests and fixes should be added. 
- As for the community aspect: I am just short of quitting my contributions too seeing that nearly half a year has passed with some but slow progress. But for each PR and issue cropping up I have the impression I must poke each one again and again which is frustrating as hell. 
- I do understand that you got real jobs and families too but lets invest some time in adding somebody to the team instead of having only 30% of the group reacting to issues and PRs. Or are there other reasons why the team is the size it is now? 

Sorry, had to vent a little, hope I brought my points across. Have a good week.

**Comment by ryanseddon** [comment]
@rejas I've just added you as a collaborator, feel free to start actually doing stuff. 

Apologies for not giving this any attention but I've burnt out on this project.

**Comment by ryanseddon** [comment]
You'll need to bug @patrickkettner for any access needed for pushing changes out

**Comment by rejas** [comment]
thanks a lot @ryanseddon I'll try to be worthy of your trust. will take alook at what could go into a new release and then try to get a hold of @patrickkettner  have a nice day

**Comment by niksy** [comment]
Would also love to see this project updated and would like to work on this if possible!

**Comment by patrickkettner** [comment]
PRs welcome!

**Comment by niksy** [comment]
@patrickkettner there are a lot of open PRs which can be reviewed and merged and @rejas has shown interest in maintaining the project, but it seems like we’re "stuck" with only collaboration but no pushing rights. Should we focus on creating PRs and let other project managers handle all the publishing=

**Comment by rejas** [comment]
@niksy I got the rights to push, the problem is publishing IMO. I'd love to get the page back online and adding changelogs for 3.6 [with this PR](https://github.com/Modernizr/modernizr-neue/pull/130) Yes, unfortunalty only @patrickkettner is helping out from the original maintainers but he is busy with work / family which I dont blame him for, thats important). 
But with those infrastructural problems getting a new release out seems unlikely in the near future. I hope after the summer holidays that gets better?

**Comment by niksy** [comment]
Yes, I completely understand issue with time, I’m in a similar situation myself!
But if we can all agree that this can become a point of project staleness, maybe core contributors can give more maintenance rights to people who have time and will to work on the project, for now just to bring it "from the ground"?

**Comment by ryanseddon** [comment]
I don't think I even have permissions to publish so can't help you there.
