### ISSUE TITLE
Object-fit check not working

### ISSUE THREAD

**Issue by 450b** [Modernizr/Modernizr#2282]
I wrote a fallback for object-fit in IE which is working, except the fallback is applied to all browsers.

So I wrote a simple check that logs if object-fit is supported in the current browser, I get the `object-fit not supported` log, in all browsers, not just in IE.

My code:

```
if ( ! Modernizr.objectfit ) {
    console.log('object fit is not supported');
    tpj('.featuredpost').each(function () {
        var $container = tpj(this),
                imgUrl = $container.find('.img-responsive').prop('src');
        if (imgUrl) {
            $container
                .css('backgroundImage', 'url(' + imgUrl + ')')
                .addClass('compat-object-fit');
        }
    });

    tpj('.big-post').each(function () {
        var $container = tpj(this),
                imgUrl = $container.find('.img-responsive').prop('src');
        if (imgUrl) {
            $container
                .css('backgroundImage', 'url(' + imgUrl + ')')
                .addClass('compat-object-fit');
        }
    });
}else{
    console.log('object is supported');
}
```

The above code logs `object fit is not supported` in all browsers.

**Comment by rejas** [comment]
Does Modernizr add the no-objectfit no-object-fit tags to your html class also?

**Comment by rejas** [comment]
@LancerOfTruth got to ask you the same question: is it not working in the js only or does modernizr add the html class tags also wrongly? and what modernizr version are you running?

**Comment by LancerOfTruth** [comment]
I've only tested it in the js.  I'm using modernizr-3.4.0.js so the version is 3.4.  I just created a quick test to see if Modernizr.objectfit was working here:

```
    var result = $('#result');
    $(function () {
        if (Modernizr.objectfit) {
            result.text('Object Fit is supported in this browser');
        } else {
            result.text('Object Fit is NOT supported in this browser');
        }
    });
```
This always returns "Object Fit is NOT supported in this browser", even though I'm using Chrome version 67 and can visually see that object fit is supported.  I've tested this on the latest version of Chrome, Firefox, Edge, and IE, they all return the same "NOT supported" message.  IE is the only browser where I can see Object Fit is actually not supported.

**Comment by rejas** [comment]
Could you try it out with modernizr v3.6.0 ?

**Comment by LancerOfTruth** [comment]
@rejas That did it!  Upgraded to the latest version and it worked. Thanks!

**Comment by rejas** [comment]
Glad to hear that. Closing this issue for now since @450b didnt react.
