### ISSUE TITLE
Website certificate expired 

### ISSUE THREAD

**Issue by ajhsu** [Modernizr/Modernizr#2284]
I think the certificate of letsencrypt for https://modernizr.com/ just expired few minutes ago.

![osx 2018-01-30 at 1 15 19 pm](https://user-images.githubusercontent.com/7029623/35549423-7dd1718a-05c0-11e8-9281-b0d104603865.png)

**Comment by patrickkettner** [comment]
updated! let me know if you are still hitting any issues

**Comment by ajhsu** [comment]
@patrickkettner It works now, thanks for lightning fast renewing!
