### ISSUE TITLE
Social link icons for Diaspora* & Mastodon

### ISSUE THREAD

**Issue by GammaNu** [Modernizr/Modernizr#2288]
Right now there is many many icons for many social media, but none for these free media : 
- Diaspora* https://wiki.diasporafoundation.org/images/6/62/Diaspora-asterisk-large.png
- Mastodon https://upload.wikimedia.org/wikipedia/commons/4/48/Mastodon_Logotype_(Simple).svg

Can you do something for it soon ?

**Comment by GammaNu** [comment]
Modernizr include a social panel shortcut in footer. you can add your social media link via WP customize UI, but there is some missing icons

**Comment by patrickkettner** [comment]
are you suggesting to add links to something on modernizr.com's footer? If so, to what?

**Comment by GammaNu** [comment]
ok, i've got it... i'm not on the good repository... i'm about a wordpress theme named modernizr...

**Comment by GammaNu** [comment]
I was thinking it was free software and try to improve it, but it's a commercial product with a free demo using the same name as you :/

https://presscustomizr.com/customizr/
