### ISSUE TITLE
Feature detect request: text-decoration-skip-ink

### ISSUE THREAD

**Issue by fredrikekelund** [Modernizr/Modernizr#2292]
Even though the W3C standard for Text Decoration Module Level 4 ([link](https://drafts.csswg.org/css-text-decor-4/)) is currently only an editor's draft, Chrome recently implemented `text-decoration-skip-ink` ([ref](https://www.chromestatus.com/features/5631679087509504)) and Safari has `text-decoration-skip`.

The web developer community are using our own hack-ish solution to implement the same behavior on some sites (by using linear-gradient background-images and text-shadows, see [this Medium post](https://medium.design/crafting-link-underlines-on-medium-7c03a9274f9)). But that hack is significantly more complex than the new CSS property and has the drawback of requiring a solid background color behing the underlined text. Therefore, it would be great to be able to feature detect the new property with Modernizr!

**Comment by rejas** [comment]
Hi @fredrikekelund Would this PR https://github.com/Modernizr/Modernizr/pull/2269/files fulfill that need in your opinion?

**Comment by fredrikekelund** [comment]
Hi @rejas! Thanks for alerting me to the PR. It's not really what I was looking for, no – `text-decoration-color` support is not tied to `text-decoration-skip-ink`. It seems they are actually part of the ]CSS Text Decoration Module Level 3](https://drafts.csswg.org/css-text-decor-3/) and [CSS Text Decoration Module Level 4](https://drafts.csswg.org/css-text-decor-4/) standards respectively

**Comment by rejas** [comment]
Right, reading through your ticket and the PR a second time made me realitze my mistake too :-) Anyway, care to make a PR for this skip-ink feature?

**Comment by fredrikekelund** [comment]
Sure! Could use a pointer or two, though. Would it be as simple as mimicking the PR you referenced? Ie calling `testAllProps('text-decoration-skip-ink')`

**Comment by rejas** [comment]
Well, since I am farely new to the party too I cannot help you as much as one of the original maintainers. But that PR could be a good starting point indeed. Not sure what the difference betweeen testProps and testAllProps is but I think thats in the code documentation.

**Comment by patrickkettner** [comment]
```js
Modernizr.addTest('skipInk', testProp('textDecorationSkipInk', 'auto'));
```

would do the job. `skipInk` could be whatever you want the detection to be named


```

**Comment by rejas** [comment]
Thx, created a PR for this (https://github.com/Modernizr/Modernizr/pull/2324)

**Comment by fredrikekelund** [comment]
Thanks for getting a PR up so quickly! 👍 Will keep an eye out for when 3.7 is released then
