### ISSUE TITLE
Bugfix release proposal

### ISSUE THREAD

**Issue by rejas** [Modernizr/Modernizr#2295]
Hi, as promised here are my ideas on what could go into a bugfi release. 

Taking "focus-within" as a precedent I also included some
**new tests**:
Add Font Display detection #2256 
Add test for CSS custom properties. #2244 (for this i would add the reworked code from #2229 afterwards)

**Discussed extensivly**:
Use `roundedEquals` to test vw and vh units #2264  
Brought across @myakura's code changes to fix #1812 #2250 

**Cleanups**
Spelling #2267

**Comment by patrickkettner** [comment]
Thanks a bunch. Added comments to relative links, and will release shortly

**Comment by rejas** [comment]
Thx a lot @patrickkettner. Cant check the release out though, literally 1 hour away from boarding my holiday flight :-) back in two weeks to clean up and see whats next for modernizr :-)

**Comment by rejas** [comment]
@patrickkettner so, back in action. just wondering why the package.json still says 3.5.0 and why the website isnt updated? can I help there somehow too?

**Comment by rejas** [comment]
@patrickkettner aou are probably busy with family but is there no other person active here anymore?

**Comment by patrickkettner** [comment]
@rejas sorry about that. i'll try to update this afternoon

**Comment by rejas** [comment]
still no version update :-( @patrickkettner
