### ISSUE TITLE
Feature request: <link rel="preload" /> feature detection

### ISSUE THREAD

**Issue by Giovanni-Mattucci** [Modernizr/Modernizr#2297]
It would be great if there was feature detection for `rel=preload` on `<link>` elements.

Preload isn't supported in IE11 and Edge for now, and I'd like to provide a fallback to those browsers.

I've run into issues, where [the onload javascript handler on the `<link>` doesn't fire if `rel=preload` is set](https://stackoverflow.com/questions/49136399/onload-on-link-element-event-doesnt-fire-on-ie11-preload-fallback-for-ie), and only works if it is set to `rel=stylesheet` in IE/Edge. 

I could get around this with a feature detect.

**Comment by roblarsen** [comment]
https://github.com/w3c/preload/issues/7

**Comment by Giovanni-Mattucci** [comment]
I ended up utilizing the `supports` API through [Yoav Weiss's article](https://www.smashingmagazine.com/2016/02/preload-what-is-it-good-for/) detection code:
```js
var DOMTokenListSupports = function(tokenList, token) {
  if (!tokenList || !tokenList.supports) {
    return;
  }
  try {
    return tokenList.supports(token);
  } catch (e) {
    if (e instanceof TypeError) {
      console.log("The DOMTokenList doesn't have a supported tokens list");
    } else {
      console.error("That shouldn't have happened");
    }
  }
};

var linkSupportsPreload = DOMTokenListSupports(document.createElement("link").relList, "preload");
if (!linkSupportsPreload) {
  // Dynamically load the things that relied on preload.
}
```
[preload_feature_detection.js gist](https://gist.github.com/yoavweiss/b1f798bb2be4e671107b#file-preload_feature_detection-js)

**Comment by HipsterZipster** [comment]
Note all to all who read this. @Giovanni-Mattucci code snippet returns unsupported for Firefox versions  Firefox v59+ even though they do actually support `preload`.

**Comment by Giovanni-Mattucci** [comment]
@HipsterZipster looked into it and found [the ticket for adding preload functionality in firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1222633#c130). It seems that the preload flag is disabled in Firefox? 

Go to `about:config` and search for `network.preload` and it is false. If I set `network.preload` manually to `true` then it will evaluate supports preload correctly.
