### ISSUE TITLE
Modernizr.indexeddbblob is undefined

### ISSUE THREAD

**Issue by kalitine** [Modernizr/Modernizr#2301]
Tested with the following configurations:

```json
{
  "minify": false,
  "options": [],
  "feature-detects": [
    "test/indexeddb",
    "test/indexeddbblob"
  ]
}
```
and
```json
{
  "minify": false,
  "options": [],
  "feature-detects": [
    "test/indexeddbblob"
  ]
}
```
**Current behaviour**
In Chrome and Firefox:
```
Modernir.indexeddbblob
undefined
```

**Expected behaviour**
```
Modernir.indexeddbblob
true
```

or
```
Modernir.indexeddbblob
false
```

If it's asynchronous, then using Promise would be nice.

**Comment by rejas** [comment]
Hi @kalitine sorry for the late reply. Also unfortunatly I cannot reproduce this, neither with v3.6 nor with the current master. Which version did you use?

**Comment by kalitine** [comment]
Hi, sorry it was long time ago. I created a database for testing whether indexeddb is available (It was for private navigation in browsers).

**Comment by rejas** [comment]
So, would you mind if I close the issue then?

**Comment by kalitine** [comment]
Yeah of course! Thank you.
