### ISSUE TITLE
Beacon API breaks build

### ISSUE THREAD

**Issue by stordoff** [Modernizr/Modernizr#2303]
Calling Modernizr via:
`<script src="js/vendor/modernizr-3.6.0.custom.min.js"></script>`

When Modernizr is built using `https://modernizr.com/download/?-beacon-localstorage-video-webp-addtest-setclasses-shiv`, Modernizr fails to load with the following issue:

> modernizr-3.6.0.custom.min.js:3 Uncaught ReferenceError: define is not defined at modernizr-3.6.0.custom.min.js:3

Adjusting to `https://modernizr.com/download/?-localstorage-video-webp-addtest-setclasses-shiv` (i.e. removing the Beacon API) works fine.

This also applies to the development build `https://modernizr.com/download?do_not_use_in_production`

Tested in latest Chrome; can be replicated in Firefox as well.

**Comment by rejas** [comment]
Seems to be aproblem with the download-builder at modernizr.com since manually building it works for me but using the builder over there doesnt. Could you open an issue at https://github.com/Modernizr/modernizr-neue ?

**Comment by rejas** [comment]
Opened issue at https://github.com/Modernizr/modernizr-neue/issues/126 closing this one.
