### ISSUE TITLE
Feature detect request: css variables

### ISSUE THREAD

**Issue by odysseuscm** [Modernizr/Modernizr#2306]
Hi,

detection of support for CSS variables would be nice. You can detect them like this:
(window.CSS && window.CSS.supports && window.CSS.supports('--fake-var', "0")

Thanks
Christopher

Update: Just found out the above method doesn't work on Safari (iOS) :-(

**Comment by rejas** [comment]
There is already a PR for this, I hope to get it included soon: https://github.com/Modernizr/Modernizr/pull/2310
Could you check if it works on your Safari (iOS)?

**Comment by odysseuscm** [comment]
I tested on iOS 11.3 (Safari), Android 8 (Chrome and Firefox), Windows 10 (Edge, IE 11, Firefox 59, Chrome 66) and Windows 7 (IE 9, 10, Firefox 3, 28, ESR) and Windows Phone (IE 11) and the results always were as expected. Good work!

 

Best

Christopher

 

 

Von: Veeck <notifications@github.com> 
Gesendet: Donnerstag, 3. Mai 2018 12:45
An: Modernizr/Modernizr <Modernizr@noreply.github.com>
Cc: Christopher <mail.cmcm@gmail.com>; Author <author@noreply.github.com>
Betreff: Re: [Modernizr/Modernizr] Feature detect request: css variables (#2306)

 

There is already a PR for this, I hope to get it included soon: #2310 <https://github.com/Modernizr/Modernizr/pull/2310> 
Could you check if it works on your Safari (iOS)?

**Comment by rejas** [comment]
PR https://github.com/Modernizr/Modernizr/pull/2310 got merged, I hope it gets release soon so that you can close this issue

**Comment by odysseuscm** [comment]
Great, thanks!

**Comment by daGUY** [comment]
Did this ever make it into the release version of Modernizr? I still don’t see it on the website.

FYI, to make this work in Safari, you can replace `window.CSS.supports('--fake-var', "0")` with `window.CSS.supports("color", "var(--primary)")`.

**Comment by Markel** [comment]
> Did this ever make it into the release version of Modernizr? I still don’t see it on the website.

The website is outdated and it is not recommended to use it 😔. Sorry for the inconvenience
