### ISSUE TITLE
Bugfix release proposal v2

### ISSUE THREAD

**Issue by rejas** [Modernizr/Modernizr#2311]
Following up my proposal in https://github.com/Modernizr/Modernizr/issues/2295 I recommend the next merges @patrickkettner. Also a release in npm would be nice but tell me if you need help in any way for that ;-)

**new tests**:
Add test for CSS custom properties. #2310

**bugfixes**:
Passive event listener detection causes error for EdgeHTML 15 #2299 

**cleanups**
Update eslint #2304
Spelling #2267

**Comment by past** [comment]
Can we get #2309 in a new release as well? We would like to talk to sites about updating for that fix.

**Comment by rejas** [comment]
the good news @past : since #2309 is already merged it would be included too.
the bad news : god knows when @patrickkettner kid lets him find the time for it as he is the only one still somehow active. for the rest of the team: who knows...
