### ISSUE TITLE
Experiencing problem with 'remove' icon positioning on website

### ISSUE THREAD

**Issue by schalkventer** [Modernizr/Modernizr#2321]
![image](https://user-images.githubusercontent.com/14258328/40971534-45be6030-68be-11e8-987e-cb098aa94eb1.png)

https://modernizr.com/download?setclasses
OS: Windows 10.
Browsers: Chrome Version 66.0.3359.181 (Official Build) (64-bit)

**Comment by rejas** [comment]
Yeah, noticed that too and had a PR already prepared: https://github.com/Modernizr/modernizr-neue/pull/125 Hopefuly somebody  with access to the site repo merges it someday...
