### ISSUE TITLE
detecting whether or not createMediaElementSource works? 

### ISSUE THREAD

**Issue by greggman** [Modernizr/Modernizr#2322]
In older versions of iOS Safari and Android Chrome it was impossible to use an Audio tag to stream audio and connect that as input the the WebAudio API. You could manually load MP3s using binary XHR and `decodeAudioData` but not stream audio via `createMediaElementSource`

Sometime recently that was fixed. Both iOS Safari and Android Chrome now support this feature. AFAIK there is no way to detect support. The best you can do is check the version of the browser. After version X that feature works, before version X it doesn't. If there is another way I'm unaware of it.

In any case, is that a feature modernizr should check for?

**Comment by patrickkettner** [comment]
@greggman can you post a codepen/jsbin/glitch/something of what you mean?

**Comment by greggman** [comment]
here's an example

     http://jsfiddle.net/greggman/540ptxka/show

It works in Safari iOS 10.3 and 11.4 but not in 8.2 (no idea about 9)

Safari gives no errors. There is no indication that it won't work. AFAICT the only way to know if it will work or not is to check Safari's version number.

The same is true of Chrome. It looks like it was suppose to start working as of Chrome 52 [(see issue)](https://bugs.chromium.org/p/chromium/issues/detail?id=419446) but similarly AFAIK there is no API to tell. All you can do is check the version. >= 52 it works. < 52 it doesn't

**Comment by patrickkettner** [comment]
I don't see any obvious failure pattern from the IDL, but I am far from well versed in webaudio.

It does seem like `analyzer.getByteFrequencyData` returns 0 for data, however. @greggman what do you think about constructing a fileblob of high frequency, calling createMediaElementSource and then checking the frequency after N ms? Closest thing I have that could work at the moment, I think

**Comment by greggman** [comment]
Since you can't play audio without a user gesture it's kind of hard to play a high frequency audio sample to see if it's possible to analyse audio.
