### ISSUE TITLE
Feature test suggestion: IntersectionObserver

### ISSUE THREAD

**Issue by rejas** [Modernizr/Modernizr#2331]
Moved from https://github.com/Modernizr/modernizr-neue/issues/119:

@LucaRosaldi commented on 14 Feb
> Given the growing popularity of the Intersection Observer API, it would be cool to have a test to detect support, i.e. if ( 'IntersectionObserver' in window ) {   // supports IntersectionObserver }

**Comment by aFarkas** [comment]
Please also have a look into the [supports test of the most used polyfill](https://github.com/w3c/IntersectionObserver/blob/d201f46c91f9c13c3b30e8f9e3b1e2607a2ae74b/polyfill/intersection-observer.js#L16-L31).

**Comment by rejas** [comment]
Care to write a PR @aFarkas or @LucaRosaldi :-) ?
