### ISSUE TITLE
Detect if browser is an in-app one (as Facebook)?

### ISSUE THREAD

**Issue by valeriosillari** [Modernizr/Modernizr#2335]
I need to detect if the browser in use is on IOS and an in-app browser, for apps as Facebook or Instagram.

Very specific case, I know ...

But wondering if I can detect it maybe using some options in Modernizr, also as "indirect" trick, like only IOS in-app browser could use a specific browser feature.

I am not sure if possible. anyone has some suggestions or faced the same problem?

Best

**Comment by patrickkettner** [comment]
Why do you want to know this

**Comment by valeriosillari** [comment]
Really specific User case in a project. I need to know if the user is watching a page from iOS device inside an in-app browser, so I can trigger a special event only in this case

**Comment by patrickkettner** [comment]
An in app browser isn’t a feature, it’s a browser. So we wouldn’t really be a good use for modernizr.

**Comment by valeriosillari** [comment]
oki. i will also thinking to use a simple user agent for detecting tte case I need.
I close the issue :)

**Comment by patrickkettner** [comment]
cheers!
