### ISSUE TITLE
Cleanup JSdoc 

### ISSUE THREAD

**Issue by rejas** [Modernizr/Modernizr#2338]
Check if links are still working / valid
Convert http to https

**Comment by Alexkho82** [comment]
#2338

**Comment by rejas** [comment]
@Alexkho82 could you please stop polluting the issues with your comments? or is there a reason for your cryptic posts?

**Comment by Nicholas-Eng** [comment]
Hi, I would like to take this issue as my first bug.

**Comment by patrickkettner** [comment]
Go for it!

**Comment by rejas** [comment]
Of course it would be nice to have replacements for invalid links but I think getting old versions of links via archive.org would be more feasible.
as for links that dont have https? I'd say we leave those as is.

**Comment by Nicholas-Eng** [comment]
@patrickkettner @rejas ok, ty

**Comment by rejas** [comment]
Thx to @Nicholas-Eng
