### ISSUE TITLE
Custom Feature Detection: No Such File or Directory

### ISSUE THREAD

**Issue by chrisalexander55** [Modernizr/Modernizr#2350]
ENV: OSX 10.11.6
WebPack: 4.8.3
Modernizr: 3.6.0
Modernizr-Loader: 1.0.1

.modernizrrc
```json
{
  "minify": true,
  "options": [
    "domPrefixes",
    "hasEvent",
    "testAllProps",
    "testProp",
    "html5shiv",
    "setClasses"
  ],
  "feature-detects": [
    "contenteditable",
    "customelements",
    "customevent",
    "history",
    "indexeddb",
    "indexeddbblob",
    "serviceworker",
    "flexbox",
    "fetch",
    "localstorage",
    "sessionstorage",
    "svgasimg",
    "inlinesvg"
  ]
}
```

webpack.config.js
```javascript
resolve: {
    alias: {
      modernizr$: path.resolve(__dirname, "../.modernizrrc")
    },
  }

module: {
    rules: [
      {
        test: /\.modernizrrc$/,
        use: [ 'modernizr-loader', 'json-loader' ]
      },
    ]
}
```

Webpack appears to be correctly parsing its config and .modernizrrc but throws the following:

![screen shot 2018-07-18 at 9 43 18 am](https://user-images.githubusercontent.com/1727612/42886152-d5efcabc-8a70-11e8-93cb-5eea9b4c1bd8.jpg)

Any ideas what I am doing wrong? Thank you very much in advance!

**Comment by rejas** [comment]
Looking at your crosspost there https://github.com/peerigon/modernizr-loader/issues/48 it really seems like an issue for the modernizr-loader guys/girls. Cant help you with webpack stuff, sorry :-(
