### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by acschwartz** [Modernizr/Modernizr#2358]
Link to Open Code of Conduct is broken

**Comment by niksy** [comment]
@acschwartz PR welcome! Do you have alternative link?

**Comment by rejas** [comment]
Do you know of any alternatives for such a CoC?

**Comment by roblarsen** [comment]
We used [Contributor Covenant: A Code of Conduct for Open Source Projects](https://www.contributor-covenant.org/)

**Comment by rejas** [comment]
Sounds like a good option. One just has to add oneself to the list via PR and add the .md to ones own repo?

**Comment by roblarsen** [comment]
Yeah, there's a command line utility to add the markdown file. 

If you're in there I'd suggest moving things like that to a .github folder. It really helps clean up a project's root and stays neatly integrated with GitHub.
