### ISSUE TITLE
Consider adding ESLint disable in Modernizr custom build output.

### ISSUE THREAD

**Issue by durbanski** [Modernizr/Modernizr#2361]
Hello everyone!

Is there any chance that you would consider disabling ESLint for this specific line of output:

```
// Needs a try catch block because of old IE. This is slow, but will
// be avoided in most cases because `skipValueTest` will be used.
try {
  mStyle.style[prop] = value;
} catch (e) {}
```

I mean empty block in catch statement.

```
// Needs a try catch block because of old IE. This is slow, but will
// be avoided in most cases because `skipValueTest` will be used.
try {
  mStyle.style[prop] = value;
} catch (e) {} // eslint-disable-line no-empty
```

Our linter settings are complaining about some minor things we can fix automatically during our build process by using --fix flag, but this one is unfixable. Only possible by hand, which is bit of a pain as we want to keep "no-empty" rule, and now the only option is to disable it completely.

Or if this is to specific, maybe there could be an option in build options (on modernizr.com), to add ESLint ignoring, and put:

```
/* eslint-disable */
```

at the beginning of file, if selected.

Thanks!

EDIT: I wasn't sure, should I put this request here or in this repo: 
https://github.com/Modernizr/builder-ui

**Comment by niksy** [comment]
@durbanski as @rejas says, Modernizr built code should be linted by your ESLint rules. You have `.eslintignore` as option to exclude this file from linting.

**Comment by durbanski** [comment]
Yup. This was easy. Sorry for taking your time on this.

I wrongly assumed that if we are bundling modernizr.js into our production pipeline, all files needs to pass linter.

Adding modernizr to .eslintignore made it work as expected.
Thanks!
