### ISSUE TITLE
Modified Modernizr used to hack 380 000 British Airways clients

### ISSUE THREAD

**Issue by lekoaf** [Modernizr/Modernizr#2371]
> For this research, we decided to focus our efforts by identifying individual scripts on the British Airways website and examining their appearance over time—we would verify all the unique scripts on the website and only look at them again if their appearance changed in our crawling. Eventually, we recorded a change in one of the scripts. Opening up the crawl, we saw this script was a modified version of the Modernizr JavaScript library, version 2.6.2 to be precise. The script was loaded from the baggage claim information page on the British Airways website.

https://www.riskiq.com/blog/labs/magecart-british-airways-breach/

**Comment by rejas** [comment]
Thx for the info, but whats the issue for us?

**Comment by rejas** [comment]
Closing this since there doesnt some to be any steps necessary from modenrizr site and the OP didnt respond...
