### ISSUE TITLE
CSS Custom Properties missing

### ISSUE THREAD

**Issue by crhallberg** [Modernizr/Modernizr#2372]
Looks like this was added in May (#2229) but I do not see it in the documentation or the download options.

**Comment by rejas** [comment]
Correct, it was merged via https://github.com/Modernizr/Modernizr/pull/2310 but we havent released a new version since then. I hope @patrickkettner can take a look at the open issues for a v3.7 release and give his feedback so that we can get this out finally.

**Comment by philwolstenholme** [comment]
I can [see the custom properties test in the 3.8 codebase](https://github.com/Modernizr/Modernizr/blob/v3.8.0/feature-detects/css/customproperties.js) but it doesn't seem to be listed on https://modernizr.com/docs or in the builder?
