### ISSUE TITLE
Modernizr.speechsynthesis and Modernizr.speechrecognition in Headless Chrome

### ISSUE THREAD

**Issue by jlchereau** [Modernizr/Modernizr#2374]
Modernizr.speechsynthesis is true in HeadlessChrome despite the fact that without a profile, and therefore a language, voices are not available.

Like with #2375, speech recognition cannot work without access to the microphone.

See:
- https://github.com/GoogleChrome/puppeteer/issues/2141#issuecomment-370525613
- https://groups.google.com/a/chromium.org/forum/#!topic/headless-dev/OVXsRrZwGwM

**Comment by jlchereau** [comment]
Karma tests based on browser features.
It is certainly possible to test useragent, but isn't the point of Modernizr?

**Comment by jlchereau** [comment]
Correct!

**Comment by rejas** [comment]
Our tests for speechsynthesis and speechrecognition are fairly simple and just test for the existence of the APIs in the window object. Could it be that headless-chrome nonetheless has those APIs but just throws an error when they are accessed?

**Comment by jlchereau** [comment]
You are absolutely right.

My understanding is these API always require that the user "Allows" access to the microphone or webcam but ChromeHeadless runs without user profile, so there is no way to allow them.

See the links in my first comment.

**Comment by rejas** [comment]
I added some error handling in a branch "issue_2374" Could you test a build from that to see if it now reports a correctly "false" ?

**Comment by rejas** [comment]
Hi @jlchereau did you have time to test my branch?

**Comment by rejas** [comment]
pinging @jlchereau :-)
