### ISSUE TITLE
FR: Detection for Array.prototype.includes()

### ISSUE THREAD

**Issue by evanrmurphy** [Modernizr/Modernizr#2376]
I don't see any feature detection in Modernizr for [`Array.prototype.includes()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes). I would find this useful, would others?

Perhaps we could add this to the [series of checks in es6/array.js](https://github.com/Modernizr/Modernizr/blob/v3.6.0/feature-detects/es6/array.js#L20-L28), or is `Array.prototype.includes()` considered post-es6?

Modernizr is an excellent library - a staple of modern web development. Thanks for everyone who has worked to make it so great!

**Comment by rejas** [comment]
Would be nice to have something. Not sure if it is post-es6, will there every be an official es7?

**Comment by evanrmurphy** [comment]
Ok, I just confirmed that this is part of the [es7 a.k.a. es2016 spec](https://www.ecma-international.org/ecma-262/7.0/).

I could create a PR with a new file `feature-detects/es7/array.js` that basically just performs a check for `Array.prototype.includes()`. This would give us something for this and provide a place for other es7 checks to be layered on.

How does this sound?

**Comment by rejas** [comment]
Sounds good to me! PR are very welcome, but I have to point out that no new release will be coming until @patrickkettner shows up again....

**Comment by rejas** [comment]
HI @evanrmurphy since releases start flowing again, I wanted to ask if you are still interested in creating a PR for this?

**Comment by dabretin** [comment]
Hi !
Is this thread dead?

**Comment by rejas** [comment]
well @evanrmurphy didnt respond so maybe. do you want / need this feature?

**Comment by dabretin** [comment]
Ohhh yes,I need this feature :)
May I try to make a PR ?
