### ISSUE TITLE
modernizr in iframe will occur error in safari browser.

### ISSUE THREAD

**Issue by limuyan** [Modernizr/Modernizr#2377]
safari iframe indexeddb

devices:mac,iphone,ipad
browser:safari

when Modernizr use in iframe page,it will occur error 
"SecurityError:IDBFactory.open() called in an invalid security context"

shoud the following code include in try{}
var req = indexeddb.open(testDBName);

**Comment by rejas** [comment]
Duplicate of https://github.com/Modernizr/Modernizr/pull/2315 
Not yet released though, still waiting for @patrickkettner to check his github notifications....
