### ISSUE TITLE
Adding navigator.connection.effectiveType

### ISSUE THREAD

**Issue by escodel** [Modernizr/Modernizr#2378]
Saw navigator.connection feature detection but not seeing this in the docs, on the site, or in the issues.

Basically proposing that detecting the effectiveType would be helpful for determining a more specific kind of connection (slow-2g, 2g, 3g, 4g).

More here: [MDN web docs](https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation/effectiveType) and [here](https://dev.to/addyosmani/adaptive-serving-using-javascript-and-the-network-information-api-331p)

Apologies if this is completely unhelpful... just an idea. Thanks!

**Comment by rejas** [comment]
Sounds like a good idea, want to provide a PR for it :-) ?

**Comment by escodel** [comment]
@rejas Sure thing, I'll see what I can do soon. Thanks!

**Comment by escodel** [comment]
Ok so this is a pretty straightforward change, but it required changes to package.json for me in order to make sure PhantomJS was up to date (for some reason). Wondering if those changes can just be ignored if everything is working on your end (an extension of [Issue 2355](https://github.com/Modernizr/Modernizr/issues/2355)).

All this does is detect the presence of effectiveType. Is there anything more I can do? Did you need to take a look at the branch in my forked repo or should I just go ahead and submit the PR?

**Comment by rejas** [comment]
Please submit a PR, I can take a better look at your code and comment there....
