### ISSUE TITLE
CSS custom properties check returns false (incorrectly) in Edge

### ISSUE THREAD

**Issue by nali** [Modernizr/Modernizr#2383]
The [custom properties check](https://github.com/Modernizr/Modernizr/blob/master/feature-detects/css/customproperties.js) will fail in Edge (tested in version  44.17763.1.0).

The existing code does a check in the form of:
`supportsFn('--f:0')`
This returns `true` correctly in other browsers I've tested that support CSS custom properties, however Edge will return false.
When providing the check in the property/value format, however, Edge correctly returns `true`:
` supportsFn('--f', 0)`
(However Safari [tested in version 12.0] will return true on the first test and false for the second.)

A simple fix would be to check if either of these are true in the custom property support check:
`supportsFn('--f:0') || supportsFn('--f', 0)`

Happy to submit a PR for this if it sounds like the way forward!

**Comment by rejas** [comment]
Can confirm its buggy :-) Happy to receive a PR.

**Comment by nali** [comment]
Thanks @rejas , have opened a PR. :)
