### ISSUE TITLE
Mixed content error:  Refused to load the font 'https:'

### ISSUE THREAD

**Issue by cagross** [Modernizr/Modernizr#2392]
My page ([page here](https://www.horizonhomes-samui.com/)) is suddenly displaying an unidentified mixed content error in the JavaScript console, and my troubleshooting steps _seem_ to point towards the Modernizr library.  The exact error message is:

`Mixed Content: The page at 'https://www.horizonhomes-samui.com/' was loaded over HTTPS, but requested an insecure font 'https:'. This request has been blocked; the content must be served over HTTPS.`

The reason I say it may be related to Modernizr is because as a test, on my private dev site ([dev site here](https://dev.horizonhomes-samui.com/)), I added an additional response header to my page to hopefully gain more insight into the mixed content error (per [these Google instructions](https://developers.google.com/web/fundamentals/security/prevent-mixed-content/fixing-mixed-content#finding_mixed_content_with_content_security_policy)), and loaded the page. This time the JS console contained more information and directly referenced the Modernizr library ([screenshot](https://imgur.com/skQY3JJ)).  

Any ideas what's happening here and how I can resolve it?

The website in-question is a WordPress site.  As a test, I tried switching from my child theme to my parent theme, and the issue went away.  So I can assume there is something about my child theme files that is causing the issue.

**Comment by rejas** [comment]
Hi @cagross  soory for the late response. Looking at your page I see that you are using v2.5.2 of modernizr. This is an unsupperted version which I can you not help you with. Is there a possibilty for you to update to the lkatest version (3.6.0)?

**Comment by cagross** [comment]
@rejas OK yes, I do indeed see that my version is out of date.  I am currently working to update the theme on my site, which should hopefully update Modernizr in the process.

I should also note that it appears other, non-WordPress sites are having a similar issue ([see here](https://bugs.chromium.org/p/chromium/issues/detail?id=902115&can=2&start=0&num=100&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=)).  I don't know if their sites have Modernizr installed or not.  I'm monitoring that other thread, so if there is a resolution there, I can update this ticket here.  I'll also update if I manage to get Modernizr updated on my site.

**Comment by cagross** [comment]
Just to update you, after several weeks, an update to WordPress core (to v5.0), and several plugin updates, the issue seems to be gone now.  So I guess we can close this issue.
