### ISSUE TITLE
autoplay.js missing in npm package and in release package on Github v3.6.0

### ISSUE THREAD

**Issue by many20** [Modernizr/Modernizr#2395]
hi
the node_modules/modernizr/feature-detects/audio/autoplay.js 
is missing in the npm package (v3.6.0) and also in the Release zip on Github (v3.6.0)

I tried out:
```
var config = require("node_modules/modernizr/lib/config-all.json");
var modernizr = require("modernizr");

modernizr.build(config , function (result) {
  console.log(result); // the build
});
```
I get this error:
{ Error: Error: ENOENT: no such file or directory, open 'Z:\MergeBranch\Main\Src\Client\8_Program\DisplayHtml\DisplayEngine.Html\DisplayEngine.H5\node_modules\modernizr\feature-detects\audio\autoplay.js'
In module tree:
    modernizr-init
    at Object.fs.openSync (fs.js:660:18)
   ....

Mario

**Comment by rejas** [comment]
This is not surprising since Modernizr 3.6 was released in May, while the autoplay feature was only added in July. I wish I could tell you when 3.7 will be released but @patrickkettner doesnt seem to have time to do this :-(
