### ISSUE TITLE
argparse / underscore.string security vulnerability

### ISSUE THREAD

**Issue by mschipperheyn** [Modernizr/Modernizr#2396]
https://snyk.io/test/npm/modernizr reports a security vulnerability. It can be solved by upgrading the `argparse` dependency.

**Comment by rejas** [comment]
Thx for the info. WOuld you like to submit a PR for this?

**Comment by mschipperheyn** [comment]
Sorry, I'm slammed. Best I can do right now is report it.

**Comment by rejas** [comment]
Proposed a PR at https://github.com/jonschlinkert/remarkable/pull/315 ...

**Comment by rejas** [comment]
Lets wait for https://github.com/jonschlinkert/remarkable/pull/312 to be merged
