### ISSUE TITLE
Input[search] search event - documentation error

### ISSUE THREAD

**Issue by odysseuscm** [Modernizr/Modernizr#2404]
The documentation and example wrongly states that the test for input[search] event is done like this:
Modernizr. search
-> returns unassigned on Chrome

But in fact it is done like this:
Modernizr.inputsearchevent
-> returns true on Chrome

**Comment by rejas** [comment]
You're right. Care to create a PR for that?

**Comment by rejas** [comment]
Thx for the quick PR.
