### ISSUE TITLE
Safari SecurityError

### ISSUE THREAD

**Issue by acahir** [Modernizr/Modernizr#2410]
I made the changes in  #2337 directly but it did not fix the SecurityError problem in Safari.

Opening this since all the others are already closed thinking the PR fixed the issue.

 @steffenweber @rejas

**Comment by rejas** [comment]
hi @acahir could you provide a url or codepen or somthign si,ilar where I can see myself the errors?

**Comment by acahir** [comment]
Just tried to create a slimmed down example and realized it's only happening when served locally on macOS via file:/// URI in Safari. The same file opened via Firefox using file:/// works fine, which is why I opened this issue. It does work in Safari from a http:// URI, even without the changes from #2337.

Example file to demo:
http://cahir.net/test/modernizr.html

To test the failure locally on macOS, the following zip file includes the files linked above and a second copy modified with #2337:
http://cahir.net/test/modernizr.zip

Given that, I'd say just close this issue as it's probably not worth digging into what safari is doing locally with an iframe that Firefox doesn't. Maybe just make a note in a faq somewhere, or leave this issue as the doc.

**Comment by rejas** [comment]
Closing it, keeping ot for future reference :-) Thx for the reply and demo
