### ISSUE TITLE
Option enableClasses always is true

### ISSUE THREAD

**Issue by horprogs** [Modernizr/Modernizr#2412]
Hi! I try to build modernizr via https://modernizr.com/download?webp-dontmin&q=webp

Option `enableClass` always is `true`, but I don't select "Add CSS classes", and Modernizr always set classes to html tag, but I don't need it.
Via command `modernizr -c modernizr-config.json` same. Config 
```
{
  "minify": false,
  "options": [],
  "feature-detects": [
    "test/img/webp"
  ]
}
```
What I doing wrong?

**Comment by rejas** [comment]
Well, you are not doing anything wrong. Its a known issue that configuration options are not working see https://github.com/Modernizr/Modernizr/issues/1663
I'll try to get the corresponding PR into shape. 
In the meantime you can edit your build modernizr file and change the line that says:` 'enableClasses': true,` to `false`
That might help, could you confirm that?

**Comment by horprogs** [comment]
Yes, if I set `enableClasses: false` it works.

Do you mean to test this branch?
https://github.com/Modernizr/Modernizr/tree/issue_1663

**Comment by rejas** [comment]
Good to hear that the "hack" works at least ;-)
Yes, thats the branch.
