### ISSUE TITLE
modernizr.com TLS certificate has expired

### ISSUE THREAD

**Issue by EdenSG** [Modernizr/Modernizr#2415]

**Comment by rejas** [comment]
@patrickkettner this is kind of important, could you take a look at this?

**Comment by rejas** [comment]
Seems to be fixed, new certificate valid until april 2019. Would be good to know who's responsible for this...

**Comment by zupo** [comment]
Seems to have resurfaced. I get the following:

<img width="1170" alt="Screenshot 2019-07-29 at 14 47 14" src="https://user-images.githubusercontent.com/311580/62049555-c6bc6600-b20f-11e9-850a-8f6f22d15fab.png">
