### ISSUE TITLE
List all features

### ISSUE THREAD

**Issue by omzy83** [Modernizr/Modernizr#2425]
I want to build a CSS3 feature testing page, so I was wondering if there is any way to get a list of all features that Modernizr can detect, and output them on the page? Instead of adding each feature manually.

So for example suppose Modernizr can provide a list of all features in a JS array, I'd just loop over the array and append the feature name to my `<ul>`. Example output would be:

```
<li class="supported">Border Radius</li>
<li class="not-supported">Emoji</li>
```

**Comment by rejas** [comment]
That's a good question @omzy83 unfortuntunatly I am not as deep in the code to know if thats already possible. Might I ask why you want such a feature? If you are using/building Modernizr you should already know which features are tested in that build and you could check the root element for all supported/not-supported classes...

**Comment by omzy83** [comment]
@rejas I wanted to build a page that would serve as a CSS3 browser test page. A bit like css3test.com

So a user could find out what features their browser supports.

**Comment by rejas** [comment]
You could iterate over the lib/config-all.json files "feature-detects" entry, in there "should" be all tests that Modernizr supports. You got to make sure of course that you build Modernizr with that config set.

**Comment by patrickkettner** [comment]
To do what you wanted, you an click on "development build" on the homepage ([modernizr.com/download?do_not_use_in_production](https://modernizr.com/download?do_not_use_in_production)). This is just everything clicked off for you. From there you can do BUILD, and **click open in codepen.io** to open a page with all tests running in it.

That being said, I wouldnt suggest it. Only a small portion of the tests are related to css 3, and not all features in css 3 have tests

**Comment by max19931** [comment]
why not run use a full test build and just report back the classes tag on the html body dom element?
