### ISSUE TITLE
Modernizr touch events on not touch devices

### ISSUE THREAD

**Issue by Giovancruz** [Modernizr/Modernizr#2428]
Hi, 

I think that the Pull request #2409, to Modernizr is broken my site, because are setting True to Modernizr.touch events on no touch devices as follow:
Old Version:
![image](https://user-images.githubusercontent.com/16118429/54561389-4ead7c00-49a3-11e9-94f1-098a9710a11f.png)

New Version:
![image](https://user-images.githubusercontent.com/16118429/54561422-6422a600-49a3-11e9-8e50-7c4eff6ca4d6.png)

I can't share the site link because is not published yet.

Details:
OS: Ubuntu 16.04 LTS
Browser: Google Chrome v72.0.3626.121 64 bits

Relates to: #2409

**Comment by rejas** [comment]
This is not a bug but a feature @Giovancruz ;-) The test detects if the browser is capable of detecting touches, not if the device is a touch dedevice. See the warning comment in the code:
https://github.com/Modernizr/Modernizr/blob/5afbd1205843ea0c3bb920f073a47efc783533b4/feature-detects/touchevents.js#L12
