### ISSUE TITLE
Desktop chrome touchevent tests returns "true" always.

### ISSUE THREAD

**Issue by koskinpark** [Modernizr/Modernizr#2431]
Hello there.
I know about https://github.com/Modernizr/Modernizr/pull/2409
But question is "why"? Of course now it works as expected in terms of "description" of this test. But usage of this test was to detect real touch screens, not browser feature. I don't against last fixes for touchevents, but i'd say we need to have both possibilities to check any case:
1. Does this browser support touch feature? // btw, please tell me for what exactly it is useful to use this test?
2. Does current device have the real touch screen?

**Comment by roblarsen** [comment]
See #869 

Also check out [Getting touchy](https://patrickhlauke.github.io/getting-touchy-presentation/#Cover)

**Comment by gregmatys** [comment]
it works incorrectly from 3.7.1 version where `window.TouchEvent` is added

**Comment by rejas** [comment]
Closing this since we deprecated the test with v3.8.0
