### ISSUE TITLE
FR: add feature detect for native lazy loading

### ISSUE THREAD

**Issue by rejas** [Modernizr/Modernizr#2434]
As described in https://addyosmani.com/blog/lazy-loading/
chrome  75 will add native lazy loading functionality. 
Feature detection could be done according to the blog post with 
```
<script>
if ('loading' in HTMLImageElement.prototype) { 
    // Browser supports `loading`..
}
</script>
```

**Comment by horprogs** [comment]
Hi! I prepared my first PR to Modernizr about this issue. Please could you check it?

https://github.com/Modernizr/Modernizr/pull/2453
