### ISSUE TITLE
Is this a typo error?

### ISSUE THREAD

**Issue by ayumihamsaki** [Modernizr/Modernizr#2439]
The following file code line: https://github.com/Modernizr/Modernizr/blob/8cfeb97459c13a250029c8b4d71dfe34b3dc163a/src/domPrefixes.js#L1

Is it meant to be this:

`define(['ModernizrProto', 'domPrefixes'], function(ModernizrProto, domPrefixes) {`

I'm guessing you don't want to write: `omPrefixes` when the filename is called: domPrefixes

My own ref: https://github.com/octobercms/october/issues/3867

**Comment by patrickkettner** [comment]
No, it's intentional. It is importing omPrefixes (I.e. prefixes for the Document Object Model and CSS Object Model

Thanks for the sanity check!

**Comment by ayumihamsaki** [comment]
Thanks for quick reply.
