### ISSUE TITLE
Add configuration option: don't add classes to <html>

### ISSUE THREAD

**Issue by tbela99** [Modernizr/Modernizr#244]
a good reason is here

http://code.google.com/p/chromium/issues/detail?id=78157&q=ohada&colspec=ID%20Stars%20Pri%20Area%20Feature%20Type%20Status%20Summary%20Modified%20Owner%20Mstone%20OS

google chrome can't render the site http://ohada.org, the bug seems to be related to the class attribute of the <html> element. when I empty the class attribute with chrome inspector seems to solve the issue,

I don't need moodernizer to add those classes and I would have esaily turned that off if it was possible, I'll need to hack Moodernizr for that.

**Comment by escopecz** [comment]
Thanks for the option @paulirish!

If I understand correctly, the option must be set by hacking the modernizr.js, file. Is that right? Or am I missing a way how to configure it from outside? I'd like to turn it off only for some pages.
