### ISSUE TITLE
The download (build) page still creates V3.6.0

### ISSUE THREAD

**Issue by ayumihamsaki** [Modernizr/Modernizr#2440]
Not sure if I created the issue in the correct repo, so will create here as well.

As per here: https://github.com/Modernizr/modernizr-neue/issues/140

Hi,

When I try to create a build at the following web page: https://modernizr.com/download/?setclasses

It still creates V3.6.0 and not V3.7.1

----

my own ref: https://github.com/octobercms/october/issues/3867

**Comment by rejas** [comment]
Duplicate of https://github.com/Modernizr/modernizr-neue/issues/140
