### ISSUE TITLE
Purpose of contextMenu test

### ISSUE THREAD

**Issue by meowsus** [Modernizr/Modernizr#2450]
This test fails in all non-Gecko browsers and [even that support is going away](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMenuItemElement). 

Is this test useful any longer?

**Comment by rejas** [comment]
In Firefox it's still supported and doesnt fail. Or do I get somethign wrong here?

**Comment by meowsus** [comment]
@rejas you're right, it passes in Firefox since it's a Gecko-based browser.

**Comment by rejas** [comment]
Closing this since the test doesnt harm anyone :-)
