### ISSUE TITLE
Moderizr 3.7.1 Fails Basic CSP Rules

### ISSUE THREAD

**Issue by ayumihamsaki** [Modernizr/Modernizr#2454]
Hi,

I built the latest version and see that there are now many `data:audio` and `data:video` elements in the code, please see here: https://raw.githubusercontent.com/octobercms/october/30f2755f37ebf9fb9ebd9d4c7723d63c5534cb06/modules/system/assets/ui/vendor/modernizr/modernizr.js

I get the following when testing:

![csp](https://user-images.githubusercontent.com/17784082/58427791-89651c00-8098-11e9-95d6-dfc56222c67b.png)

Is there any reason for them and are they important? I would like to cut them out of the code and still run the polyfills without them.

My ref: https://github.com/octobercms/october/pull/4316

**Comment by ayumihamsaki** [comment]
Ah ok sorry will make a note of that for future issues.

**Comment by rejas** [comment]
As for your question: those data:audio and data:video elements are used in the `audio\autoplay`, `audio\preload` and `video\autoplay` tests. So if you want to get rid of them, just exclude those tests from your build.

**Comment by ayumihamsaki** [comment]
ok thanks.
