### ISSUE TITLE
Modernizr.cssvh returns false negative on Chrome on Android.

### ISSUE THREAD

**Issue by Ferroin** [Modernizr/Modernizr#2456]
Most recently seen on Chrome version 74.0.3729.157 for Android.  I've also seen this on the past few versions too, but didn't have conclusive evidence yet that Modernizr was wrong (I now have checked a couple of ways, and all indications show that the `vh` unit works).

Possible sticking point here, Chrome on Android resizes the view-port when the on-screen keyboard pops up, and then again when it disappears, so the `vh` unit being used there results in potentially unstable layouts when the page has focusable inputs.

**Comment by rejas** [comment]
Hi @Ferroin could you test if https://github.com/Modernizr/Modernizr/pull/2452 fixes this issue for you?

**Comment by Ferroin** [comment]
Sorry about taking so long to get back with you about this.  #2452 does indeed appear to fix the issue for me.

**Comment by rejas** [comment]
Fixed with v3.8.0 since #2452 got merged
