### ISSUE TITLE
FR: Detect Proxy compatibility

### ISSUE THREAD

**Issue by jakepeyser** [Modernizr/Modernizr#2458]
Most modern browsers support the ES6 [`Proxy` object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy), but there are some old versions/browsers that do not. It would be great to add a check for the existence of this object.

**Comment by rejas** [comment]
hi @jakepeyser care to make a PR for this?

**Comment by jakepeyser** [comment]
I can try when I have some time :)

Opted for a simpler solution with checking browsers/versions bc I needed this in a crunch.

**Comment by BrockBeaudry** [comment]
I need this as well; here's a PR for it: https://github.com/Modernizr/Modernizr/pull/2459
