### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by webfacer** [Modernizr/Modernizr#2462]
[This package](https://www.jsdelivr.com/package/npm/modernizr) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

**Comment by rejas** [comment]
not sure @webfacer which file should be the default file set?

**Comment by webfacer** [comment]
i got this automated generated issue comment i didn´t create it. This means for instead copy pasting your library from the cdn provider "jsdelivr"

**Comment by webfacer** [comment]
also could you add an integrity for security reason?

**Comment by rejas** [comment]
where did you get the issue comment from?

**Comment by webfacer** [comment]
the main js i think modernizer it is described on the link of "default file"

**Comment by rejas** [comment]
there is a main field in the package json:
```
  "main": "./lib/cli",
```
so I guess this issue is not on our side.

**Comment by rejas** [comment]
I'll add the js extension to the entry, maybe that helps....

**Comment by rejas** [comment]
Fixed with https://github.com/Modernizr/Modernizr/commit/377a6303b3b6d400979eeae351e1dcf43972eef4
