### ISSUE TITLE
How can i use custom builder?

### ISSUE THREAD

**Issue by vagnerbefore** [Modernizr/Modernizr#2464]
How can I use the custom builder (https://modernizr.com/download?setclasses)  to make a file with 3.7.1 version?

**Comment by rejas** [comment]
Unfortunatly I am not able to update the homepage myself with the latest custom builder. Still waiting for @patrickkettner to do that :-( 
You can still build one yourself by downloading this repo and running the command-line tool mentioned in the README.

**Comment by niksy** [comment]
@vagnerbefore if you wish to use only set of tests with smallest output, you can try ESM version of Modernizr: https://github.com/niksy/modernizr-esm
