### ISSUE TITLE
Expired Certificate - Let's Encrypt

### ISSUE THREAD

**Issue by BasJan81** [Modernizr/Modernizr#2465]
🚨 PLEASE 🚨

![CleanShot 2019-07-28 at 20 49 43](https://user-images.githubusercontent.com/10583358/62011502-6f6bb680-b179-11e9-906f-9908d9c26671.png)

**Comment by rcdeoliveira** [comment]
Is this related with the following error on bower install?:
`bower modernizr#*            CERT_HAS_EXPIRED certificate has expired`

**Comment by manojkamothi** [comment]
I got same error 

       bower modernizr#*              CERT_HAS_EXPIRED certificate has expired

       npm ERR! code ELIFECYCLE

       npm ERR! errno 1

       npm ERR! portal@0.1.0 postinstall: `bower install`

       npm ERR! Exit status 1

       npm ERR! 

       npm ERR! Failed at the portal@0.1.0 postinstall script.

       npm ERR! This is probably not a problem with npm. There is likely additional logging output above

**Comment by Neurozone** [comment]
Yup same error, can't access the website

**Comment by rejas** [comment]
Again I have to hope @patrickkettner  reads this since he seems to be the only one with the keys to that page :-(

**Comment by roblarsen** [comment]
Who owns the domain? At this point it seems like the only way to solve these issues long-term is to move the site.

**Comment by rejas** [comment]
I dont know who actually owns itbut @patrickkettner was always able to fix issues with the certificate 
As for a move: Would the github.io page (https://modernizr.github.io/Modernizr/) be a valid replacement spot ?

**Comment by corykeane** [comment]
Same error here. Hopefully they update the cert soon...

**Comment by 190n** [comment]
It's working now for me.

<img width="600" alt="image" src="https://user-images.githubusercontent.com/7763597/62310370-3a43ba80-b43e-11e9-8280-3b1425976bdc.png">

**Comment by mrleblanc101** [comment]
The certificate is expired again blocking all install throught bower...
