### ISSUE TITLE
FR: Add detection for flexbox {column|row}-gap

### ISSUE THREAD

**Issue by ppiyush13** [Modernizr/Modernizr#2473]
I really likes Modernizr library, thanks everyone to make it excellent.

I am requesting a new feature detection in Modernizr.
According to [CSS Align 3 specs](https://www.w3.org/TR/css-align-3/#gaps) the gap property, and its row-gap and column-gap sub-properties, are being extended to Flex layout as well.
As of today only [Firefox 63+](https://developer.mozilla.org/en-US/docs/Web/CSS/gap#Support_in_Flex_layout) supports gap properties for flex box.
I don't see any feature detection in Modernizr for it, would it be helpful if we add it ?

**Comment by rejas** [comment]
Hi @ppiyush13 might be useful, would you like to write a test yourself with some help?

**Comment by ppiyush13** [comment]
Hi @rejas, I can contribute. Please provide me some help on how should I begin

**Comment by rejas** [comment]
I'd take a look at https://github.com/Modernizr/Modernizr/blob/master/feature-detects/css/flexwrap.js 
Your test should be very similiar to that one :-)

**Comment by chris13524** [comment]
Looks like there may be an issue detecting this one. Reason being is that `row-gap` *is* valid for grid layouts but not flex layouts on Chrome. So running `Modernizr.testProp("row-gap", undefined)` returns true. We need some way to clarify that `display:flex`. Though I don't know much about this, so maybe I'm wrong.

**Comment by chris13524** [comment]
See my PR #2485 for an implementation. I tested it and it works in my application.
