### ISSUE TITLE
Modernizr CLI fails to find getusermedia.js

### ISSUE THREAD

**Issue by isubasinghe** [Modernizr/Modernizr#2483]
Steps to reproduce:

1. Download modernizr 3.8.0
2. Use the following JSON config
```json
{
  "classPrefix": "",
  "enableClasses": false,
  "enableJSClass": true,
  "scriptGlobalName": "window",
  "usePrefixes": true,
  "minify": true,
  "options": [],
  "feature-detects": ["indexeddb", "serviceworker", "getusermedia"]
}
```

3. Run `modernizr -c ,.modernizr.config.json -d ./m.js -u`

Then this error comes up:
{ Error: Error: ENOENT: no such file or directory, open '/Users/isubasinghe/Documents/Work/react_app/node_modules/modernizr/lib/../feature-detects/getusermedia.js'

I believe the problem is because getusermedia.js seems to be in the feature-detects/webrtc not in feature-detects itself but the cli tool looks in feature-detects.

Details:
    OS: MacOS Catalina

**Comment by rejas** [comment]
You are referencing the getusermedia test wrong, your config is missing the directory. It should read 

>   "feature-detects": ["indexeddb", "serviceworker", "webrtc/getusermedia"]

See https://github.com/Modernizr/Modernizr/blob/master/lib/config-all.json
