### ISSUE TITLE
CSS custom properties appears to be missing from docs and download builder

### ISSUE THREAD

**Issue by philwolstenholme** [Modernizr/Modernizr#2488]
I can [see the custom properties test in the 3.8 codebase](https://github.com/Modernizr/Modernizr/blob/v3.8.0/feature-detects/css/customproperties.js) but it doesn't seem to be listed on https://modernizr.com/docs or in the builder.

**Comment by rejas** [comment]
Yeah, i know :-) Website is outdated until further notice, sorry. Duplicate of https://github.com/Modernizr/modernizr-neue/issues/140

**Comment by philwolstenholme** [comment]
Ah, thanks for the info. I'm using the CLI now and it all looks okay 👍
