### ISSUE TITLE
Modernizr.com is outdated - v3.6 instead of v3.8

### ISSUE THREAD

**Issue by IamManchanda** [Modernizr/Modernizr#2490]
How I reproduced

1. I can't search for [Proxy Object](https://github.com/Modernizr/Modernizr/pull/2459) 
2. Created Build on Codepen with the website and the version is 3.6 https://codepen.io/IamManchanda/pen/mdyQjNR

**Comment by rejas** [comment]
Yes, this issue is well known. Unfortunatly the owner of the website isnt updating it anymore although numerous issues are open: https://github.com/Modernizr/modernizr-neue/issues/140 https://github.com/Modernizr/modernizr-neue/issues/141

**Comment by rejas** [comment]
Pinging @patrickkettner one more time about this....
