### ISSUE TITLE
inputnumber-l10n test causing unintended scrolls

### ISSUE THREAD

**Issue by alizain** [Modernizr/Modernizr#2492]
Building off of the last few comments on #2172, `inputnumber-l10n.js` also has a [`input.focus()`](https://github.com/Modernizr/Modernizr/blob/master/feature-detects/forms/inputnumber-l10n.js#L38) call which is causing unintended scrolls on pages

CC: @ManuelBoucault @AlexTr

**Comment by rejas** [comment]
Thx for the report @alizain Do you want to also help out with a PR or testing a possible fix?

**Comment by GuiMaron** [comment]
PR with a possible fix: https://github.com/Modernizr/Modernizr/pull/2496

Tested in: IE 11.973..17763.0, EDGE 72.0.2, Chrome 79.0.3945.130, Mozilla Firefox 72.0.2

We were having troubles with a single-spa application in my job, so I focused of finding the origin of the scrollings.

The solution was very simple, using a fixed-position input to test the inputnumber thus avoiding it to be outside the browser's viewbox wen .focus()ed.

**Comment by alizain** [comment]
thank you folks 👍

**Comment by GuiMaron** [comment]
You are welcome ...

Em ter., 4 de fev. de 2020 às 11:00, Alizain Feerasta <
notifications@github.com> escreveu:
