### ISSUE TITLE
Touchevents not working properly in Chrome

### ISSUE THREAD

**Issue by Epho** [Modernizr/Modernizr#2495]
See https://github.com/Modernizr/Modernizr/blob/master/feature-detects/touchevents.js#L41

`window.TouchEvent` is passing in Chrome desktop Version 79.0.3945.130 (Official Build), as it is still on the window object in desktop, returning native code, where as in Firefox it returns undefined and does not exist on the window object.

**Comment by rejas** [comment]
The TouchEvent feature detect was marked as deprecated in the latest release due to its unclear nature. For info on why please take a look at https://github.com/Modernizr/Modernizr/pull/2472
