### ISSUE TITLE
Question: Does this detect the latest browser version?

### ISSUE THREAD

**Issue by artoodeeto** [Modernizr/Modernizr#2498]
Hello we're trying to solve an issue about browser compatibility. so were trying to  check current browser and if its 2 versions away from the latest browser version.

something like:
```
if ('chrome' && (currentVersion >= (latestVersion - 2)) )
```

the current version we can get but the latest version is the problem. I'm trying to read thru the documentation and I could find were to get the latest version. thanks for the help

**Comment by rejas** [comment]
Hi there. No, Modernizr just detects features, not what browser version it is running in. You probably could try the browserslist tool: 
https://github.com/browserslist/browserslist#js-api

**Comment by artoodeeto** [comment]
ahhh. thank you.
