### ISSUE TITLE
Modernizr Download builder on official website providing older version i.e 3.6.0

### ISSUE THREAD

**Issue by prbt2016** [Modernizr/Modernizr#2500]
Hi,

Tried to download Modernizr via Modernizr download builder i.e visiting 

https://modernizr.com/download?dontmin-setclasses

( i.e unchecking the minify option) and clicking on Build and then clicking Download button. But it downloads the older build of modernizr-custom.js i.e 3.6.0.

How do i download Modernizr latest build of (modernizr-custom.js) i.e 3.9.1, as latest version here on Github is 3.9.1 : 

https://github.com/Modernizr/Modernizr/releases

Could you fix this on your official website?.

**Comment by roblarsen** [comment]
😭  Modernizr/modernizr-neue#140 Modernizr/modernizr-neue#141

**Comment by rejas** [comment]
Closing due to it being a duplicate. Thanks for the info anyway.
