### ISSUE TITLE
possible missing caniuse mappings

### ISSUE THREAD

**Issue by PavMel** [Modernizr/Modernizr#2519]
Hi. there. Thank you for your very nice and helpful project.  
I'm not javascript developer, I just noticed that a few modernizr's tests haven't mappings to caniuse db. 

Left side    ==>> caniuse  
Right side ==>> modernizr  

**Possible** mappings:
```python
CANIUSE_TO_MODERNIZR_PATCH = {
    "audio": "audio",
    "ambient-light": "ambientlight",
    "css-background-offsets": "bgpositionshorthand",
    "rem": ["csschunit", "cssexunit"],
    "css-snappoints": "scrollsnappoints",
    "css-text-align-last": "textalignlast",
    "will-change": "willchange",
    "custom-elementsv1": "customelements",
    "passive-event-listener": "passiveeventlisteners",
    "template": "template",
    "gamepad": "gamepads",
    "iframe-sandbox": "sandbox",
    "iframe-srcdoc": "srcdoc",
    "apng": "apng",
    "jpeg2000": "jpeg2000",
    "webp": "webp",
    "input-search": "inputsearchevent",
    "internationalization": "intl",
    "pointer-events": "pointerevents",
    "speech-recognition": "speechrecognition",
    "speech-synthesis": "speechsynthesis",
    "urlsearchparams": "urlsearchparams",
    "vibration": "vibrate",
     "xhr2": "xhr2",
    "rtcpeerconnection": "peerconnection",
    "beacon": "beacon",
    "addeventlistener": "eventlistener",
    "serviceworkers": "serviceworker",
}
```

**Comment by rejas** [comment]
Thanks for the list @PavMel Would you be interested in creating a PR for these?

**Comment by PavMel** [comment]
Hi, @rejas. I think that we need javascript programmer for these changes. I have just one month experience with javascript. Therefor coding review of my PR will be very hard for me and for you too.

**Comment by rejas** [comment]
Hi @PavMel you dont have to be a javascript programmer to add these infos in the top-comments of the feature-tests. But if you dont want to I can take care of this.

**Comment by MarkelFe** [comment]
Wouldn't mind doing it, however, I haven't been able to find a specific file of caniuse mapping, the best that I found is this file from commit a80a7ee which has been deleted since. Do you mean adding the mappings as notes in the feature detections?

**Comment by rejas** [comment]
Correct, there is not one single file for that. The mapping is done in each feature-detect file in the caniuse field in the doc like this:
https://github.com/Modernizr/Modernizr/blob/5a784e7978727cc1d37c752544cd3347485fd091/feature-detects/canvas.js#L5
