### ISSUE TITLE
Changing scriptGlobalName causing an exception - Cannot read property 'position' of undefined

### ISSUE THREAD

**Issue by HadadTomer** [Modernizr/Modernizr#2520]
By default, Modernizr is attached to the window. 
I want to attach it to a different variable in order to not pollute the global scope.
When I change `scriptGlobalName` to a different global variable I get the following error during script evaluation:

  ```
Uncaught TypeError: Cannot read property 'position' of undefined
    at <anonymous>:2751:30
    at injectElementWithStyles (<anonymous>:569:11)
    at <anonymous>:2748:7
    at Object.fn (<anonymous>:2808:12)
    at testRunner (<anonymous>:144:55)
    at <anonymous>:3193:3
    at <anonymous>:3212:3
```

I'm using Modernizr version 3.9.1 and building with the following config.json:

```
{
  "minify": false,
  "scriptGlobalName": "myGlobalObject",
  "options": [
    "setClasses"
  ],
  "feature-detects": [
    "test/ambientlight",
    "test/applicationcache",
    "test/audio",
    "test/battery",
    "test/blob",
    "test/contenteditable",
    "test/contextmenu",
    "test/cors",
    "test/crypto",
    "test/custom-elements",
    "test/custom-protocol-handler",
    "test/customevent",
    "test/dart",
    "test/dataview-api",
    "test/emoji",
    "test/eventlistener",
    "test/exif-orientation",
    "test/flash",
    "test/forcetouch",
    "test/fullscreen-api",
    "test/gamepad",
    "test/geolocation",
    "test/hiddenscroll",
    "test/htmlimports",
    "test/ie8compat",
    "test/indexeddb",
    "test/indexeddbblob",
    "test/intl",
    "test/json",
    "test/ligatures",
    "test/lists-reversed",
    "test/mathml",
    "test/messagechannel",
    "test/notification",
    "test/pagevisibility-api",
    "test/performance",
    "test/pointerevents",
    "test/pointerlock-api",
    "test/proximity",
    "test/queryselector",
    "test/quota-management-api",
    "test/requestanimationframe",
    "test/serviceworker",
    "test/touchevents",
    "test/typed-arrays",
    "test/unicode-range",
    "test/unicode",
    "test/userdata",
    "test/vibration",
    "test/video",
    "test/vml",
    "test/web-intents",
    "test/webanimations",
    "test/webgl",
    "test/websockets",
    "test/xdomainrequest",
    "css/hairline"
  ]
}
```

**Comment by rejas** [comment]
Does this only happen when you change the `scriptGlobalName` ?
Also, could you check if this happens only with a specific feature-detect enabled?

**Comment by HadadTomer** [comment]
Yes, it only happens when I change `scriptGlobalName`.
It's not related to a specific feature. When I set `scriptGlobalName` configuration, the Modernizr.js script looks like that:
```
;(function(window, document, undefined){

// ....
// script content 
// ....

  // Leak Modernizr namespace
  window.Modernizr = Modernizr;

;

})(myGlobalObject, document);
```
It gets as a parameter the name of my object and calls it `window` inside the script - what leads to an error when trying to query the actual page window.

**Comment by rejas** [comment]
Thanks for the info. 
Could you identify if older versions of modernizr didnt have this?

**Comment by rejas** [comment]
And: Could you try it just with the test "test/touchevents" compiled into it? I think this is a test that uses the mq class which triggers the call where position isnt found

**Comment by HadadTomer** [comment]
According to the changelog, `scriptGlobalName` was first introduced on 3.7.0, so I built the script using Modernizr version 3.7.0 with the following configuration
```
{
  "minify": false,
  "scriptGlobalName": "myGlobalObject",
  "options": [
    "setClasses"
  ],
  "feature-detects": [
    "test/touchevents"
  ]
}

```
Got the same result
The script looks the same as my [previous comment](https://github.com/Modernizr/Modernizr/issues/2520#issuecomment-599532571) and got the error `Cannot read property 'position' of undefined` on the browser.

**Comment by rejas** [comment]
Like I said, the error comes from the mq class that is used by the touchevents test. 
Alas, this was before my time and I am not so firm with the code to understand it...

More questions: 
- What object is your myGlobalObject ? Does it have a getComputedStyle function? 
- Does the error also occurs if you ONLY have the subpixelfont compiled into it?

**Comment by HadadTomer** [comment]
`myGlobalObject` is an object attached to the window. I can also get it by `window.myGlobalObject`. It doesn't have [getComputedStyle](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle) function, but the global `window` object has it.

I believe that the bug is that Modernizr is invoked with `myGlobalObject` as `window` and then tries to invoke methods that belong to `window` on it:
```
;(function(window, document, undefined){

// ....
// script content 
// window.getComputedStyle // window is now myGlobalObject
// ....

  // Leak Modernizr namespace
  window.Modernizr = Modernizr;

;

})(myGlobalObject, document);
```

instead of something like that:
```
;(function(myGlobalObject, window, document, undefined){

// ....
// script content 
// window.getComputedStyle
// ....

  // Leak Modernizr namespace
  myGlobalObject.Modernizr = Modernizr;

;

})(myGlobalObject, window, document);
```

**Comment by rejas** [comment]
maybe the original author @mreinstein can shed some light on this topic?

**Comment by rejas** [comment]
looking at the tests that came with the commit the call to this feature there is
           'scriptGlobalName': 'window.awesomeco',
maybe you have to set it like 
```
})(window.myGlobalObject, document);
```
?

**Comment by HadadTomer** [comment]
I tried it, no luck :/

**Comment by mreinstein** [comment]
It looks like the PR I developed for `scriptGlobalName` may not work for all feature detects. We didn't catch this at the time when I developed the patch. :(

**Comment by HadadTomer** [comment]
Can you give me an access to create a pull request with a fix? I got it ready

**Comment by mreinstein** [comment]
You can submit a pull request now, just fork Modernizr and submit a PR from your own copy back here.

**Comment by rejas** [comment]
@mreinstein could you give me and @HadadTomer a hand on what or how to fix those tests? what is wrong with the feature detect in this case and how should it be fixed?

**Comment by mreinstein** [comment]
my guess is this line is a bug?
 https://github.com/HadadTomer/Modernizr/blob/9aebc1a650abdb195334610d0d800d6382125060/src/generate.js#L79

**Comment by HadadTomer** [comment]
I fixed the tests. 
updated the PR

**Comment by mreinstein** [comment]
really this whole thing is a workaround for the fact that modernizer is still based on an antiquated module format. The more elegant solution would be to embrace esm and cut a 4.x api breaking modernizr release.

@rejas  if you agree maybe we could re-open https://github.com/Modernizr/Modernizr/issues/1333 ?

**Comment by rejas** [comment]
@mreinstein I totally agree that modernizr needs to a modern module format for its next major version. will talk about that in the mentioned ticket.
in the meantime abou this bug here: could you check out https://github.com/Modernizr/Modernizr/pull/2521 and give your opinion on it? thanks in advance.

**Comment by mreinstein** [comment]
great work everyone!
