### ISSUE TITLE
update mkdirp (to not use old version of minimist with security vulnerabilities)

### ISSUE THREAD

**Issue by gharlan** [Modernizr/Modernizr#2524]
modernizr [requires mkdirp 0.5.1](https://github.com/Modernizr/Modernizr/blob/0c2381083199c873857e89b27cf880eb961abd01/package.json#L54).
And mkdirp 0.5.1 [requires minimist 0.0.8](https://github.com/isaacs/node-mkdirp/blob/d4eff0f06093aed4f387e88e9fc301cb76beedc7/package.json#L19), which has a security vulnerability: https://snyk.io/vuln/SNYK-JS-MINIMIST-559764

**Comment by rejas** [comment]
This dependency wont get updated until the next major version, see https://github.com/Modernizr/Modernizr/issues/2499 on why I reverted that update.
I'll keep this issue open though to have it as a reminder for whenever that next major version will happen.

**Comment by gharlan** [comment]
https://github.com/isaacs/node-mkdirp/issues/7

maybe you could update mkdirp from 0.5.1 to 0.5.3?

**Comment by rejas** [comment]
ah, true. ok, will do :-)
