### ISSUE TITLE
Why tooling.js.org does not recommend using modernizr?

### ISSUE THREAD

**Issue by jt3k** [Modernizr/Modernizr#2525]
link: https://github.com/slikts/tooling/blob/master/not-recommended.md

Is modernizr really no longer needed in most use cases?

**Comment by rejas** [comment]
Yes, most modern websites dont need Modernizr as a default, but it still has its purpose.
The explanation on that page is rather strange though: I cant just replace it with @babel/preset-env since that transpiles the code but doesnt add detection to it....

**Comment by rejas** [comment]
But maybe you should ask that question in the repository of toolings.js. org @jt3k  ?

**Comment by rejas** [comment]
Ah, you did via https://github.com/slikts/tooling/issues/6 Sorry didnt see that
