### ISSUE TITLE
BUG: css/fontdisplay

### ISSUE THREAD

**Issue by dabretin** [Modernizr/Modernizr#2529]
Hello !
I think there's a bug in the `feature-detects/css/fontdisplay.js `:

> define(['Modernizr'], function(Modernizr, testProp) {
>   Modernizr.addTest('fontDisplay', testProp('font-display'));
> });

There's no reference to `testProp` so it raise an `Uncaught ReferenceError: testProp is not defined`

May I do a PR ?

**Comment by rejas** [comment]
You are right :-)
And you may :-)

**Comment by dabretin** [comment]
Done : https://github.com/Modernizr/Modernizr/pull/2530
:-)
