### ISSUE TITLE
Rel Prefetch Support?

### ISSUE THREAD

**Issue by jhned** [Modernizr/Modernizr#2536]
Any chance we could get a detect for rel prefetch? It'd be super-helpful for WebKit browsers. There's a [bug out for it](https://bugs.webkit.org/show_bug.cgi?id=194539) now, but no movement yet.

**Comment by roblarsen** [comment]
I wonder if there's any easy way to test that feature. 🤔

**Comment by rejas** [comment]
Maybe there is some similar test in Modenrizr already that can be used as a blueprint?

**Comment by roblarsen** [comment]
I'm going to look at it a little bit since I've got a bit more time on my hands and this strikes me as a funny problem to solve (also: potentially impossible?)

**Comment by patrickkettner** [comment]
https://github.com/Modernizr/Modernizr/issues/2297

**Comment by roblarsen** [comment]
I wouldn't have thought of that, which is funny, because I replied to that other issue. I don't know that I looked after posting the pointer, though. Thanks Patrick

**Comment by jhned** [comment]
Yeah, looks like [this might work](https://github.com/w3c/preload/issues/7#issuecomment-566791118).

**Comment by rejas** [comment]
So, feeling ready to do a PR? :-)

**Comment by HeroProtagonist** [comment]
👋 I would like to take a crack at this one.

**Comment by rejas** [comment]
Go for it!

**Comment by HeroProtagonist** [comment]
PR submitted! 
If desired, I could also add detection for `rel=preload` in the same directory in another PR

**Comment by HeroProtagonist** [comment]
Is it ok to do browser detection for the IE11 edge case pointed out on the PR?
https://github.com/Modernizr/Modernizr/pull/2610#issuecomment-709717161

**Comment by rejas** [comment]
At least a note / warning should be added to the docs of the feature detect. Not sure if detecting IE11 specifically should be done....
