### ISSUE TITLE
HTTPS certificate expired

### ISSUE THREAD

**Issue by MarkelFe** [Modernizr/Modernizr#2546]
The issue has been solved now, just leaving it here for the few information it can be collected. Close it when it's no use.

Hi, right know [modernizr.com](https://modernizr.com) can't be accessed as the certificate (at least that is the error it is showing me) has expired.
`Not After 4/26/2020, 7:27:08 PM (Central European Summer Time)`

And due to HSTS (a good thing) the server can't be accessed whatsoever.

Just changed the clock back and verified it is not a problem with the server. Maybe a problem with the auto-renewal or the release of v3.11.0? As a funny side note: Is curious to see Github saying: _opened this issue in 3 days._

**Comment by rejas** [comment]
Thats for @patrickkettner to fix, maybe he also pushes the blogposts for the past releases while he's there ;-)

**Comment by rejas** [comment]
Seems to be fixed. Still no blog updates though :-(
