### ISSUE TITLE
datachannel test leaks a PeerConnection object in Chrome and Firefox

### ISSUE THREAD

**Issue by basro** [Modernizr/Modernizr#2565]
In both chrome and firefox `new RTCPeerConnection()` will leak unless closed.

This isn't much of a resource usage problem, but it's an annoyance when trying to look at the webrtc debug pages `about:webrtc` in Firefox and `chrome://webrtc-internals/` in Chrome. Since the modernizr test RTCPeerConnection will appear there.

This can be fixed by adding a `peerConnection.close()` [here](https://github.com/Modernizr/Modernizr/blob/59f35a14c5e63dab964dd25d2c10ffcbecbfb918/feature-detects/webrtc/datachannel.js#L22).

I'm unsure if this is a bug in Chrome and Firefox. Given that both are acting the same way, perhaps it's meant to be this way.

**Comment by rejas** [comment]
Thanks for the report. Fixed in v3.11.2
