### ISSUE TITLE
add support for indexeddb 2.0

### ISSUE THREAD

**Issue by alsotang** [Modernizr/Modernizr#2571]
https://caniuse.com/#search=indexeddb

Now the indexeddb detect script only detects basic indexeddb apis.

But some browser versions implement 1.0 and some 2.0. 

So we can add a new script to detect 2.0 support.

In my opinion, 2.0 add some new apis compared to 1.0. Such as `getAll/getAllKeys`.

So we can use `'getAll' in IDBIndex.prototype` to determine whether the browser supports it.

**Comment by alsotang** [comment]
https://github.com/Modernizr/Modernizr/blob/c1a3e04b33d9021e9c7d415f0ea749c0d8092ce4/feature-detects/indexeddb.js

**Comment by MarkelFe** [comment]
I was wondering whether a new file should be created or add it to indexeddb.js as happens to webp (for example). I vote for creating a new file, especially as we can't for example put the 2 caniuse id in one file.

**Comment by alsotang** [comment]
Creating a new file is better imo. Because 1.0 and 2.0 support are two different features. And caniuse also distinguish they two.  

In my business situation, I wanna use indexeddb. I write a script to collect browser support. 
The support ratio of 1.0 is 100%, while 2.0 is 99.54% because some users using ios < 10.3. So if care about the 0.5% users, I cant use 2.0 api.

**Comment by alsotang** [comment]
btw, this a my detect condition: 

1.0: `'indexedDB' in global`
2.0: `'getAll' in IDBIndex.prototype`
