### ISSUE TITLE
Clipboard API

### ISSUE THREAD

**Issue by Markel** [Modernizr/Modernizr#2572]
I was thinking that it would be interesting to create detections for the various Clipboard APIs.

Here are [the caniuse compatibility tables](https://caniuse.com/#search=clipboard%20API) and the [MDN Docs](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API)

I would need to give a thought about how this could be approach, unfortunately, I'm going to be pretty busy until mid-July (time to catch up for all the time lost in quarantine) so I leave an issue so I don't forget + if someone is interested to give it a go.

**Comment by MarkelFe** [comment]
Love to see how 2 days ago I was saying that I was pretty busy and now I have opened a pull request (I continue to be busy, but it is funny)
