### ISSUE TITLE
Expired Certificate - Let's Encrypt

### ISSUE THREAD

**Issue by mrleblanc101** [Modernizr/Modernizr#2578]
Hi,
Since June 28th, the Modernizr certificate expired.
The website is now marked as «Not secure» and every install throught bower fail with error:
`bower modernizr#* CERT_HAS_EXPIRED certificate has expired`
<img width="487" alt="Capture d’écran, le 2020-06-29 à 09 35 17" src="https://user-images.githubusercontent.com/17392251/86012366-e0e86080-b9eb-11ea-8d56-afd59c0ad1b7.png">
<img width="743" alt="Capture d’écran, le 2020-06-29 à 09 36 28" src="https://user-images.githubusercontent.com/17392251/86012501-0d9c7800-b9ec-11ea-876f-c7f4af63c9d3.png">

**Comment by patrickkettner** [comment]
Thanks! Auto renew script broke. this is fixed
