### ISSUE TITLE
Add support for ResizeObserver

### ISSUE THREAD

**Issue by AnderssonChristian** [Modernizr/Modernizr#2581]
As far as I know this feature-detect does not exist. I'll be happy to create a PR for this if needed.

**Comment by MarkelFe** [comment]
We probably can check for the `ResizeObserver` existence to check whether it is supported or not

I'll leave links around here for the metadata :)

[MDN](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver)
[Web.dev article](https://web.dev/resize-observer/)
[Specification](https://www.w3.org/TR/resize-observer/)
[Caniuse](https://caniuse.com/#feat=resizeobserver)
[A Digital Ocean tutorial](https://www.digitalocean.com/community/tutorials/js-resize-observer)
