### ISSUE TITLE
AppVeyor failing tests

### ISSUE THREAD

**Issue by Markel** [Modernizr/Modernizr#2583]
Okay so lately AppVeyor has been failing tests when everything should be alright, it probably has something to do with dependencies, but I'm leaving here the failed test links to have them sorted:

Node 10 (it may be a different error):
[https://ci.appveyor.com/project/rejas/modernizr/builds/33584351/job/r5ep279yhw242qu6](https://ci.appveyor.com/project/rejas/modernizr/builds/33584351/job/r5ep279yhw242qu6) from #2573 

Node 14:
[https://ci.appveyor.com/project/rejas/modernizr/builds/33844485/job/7vhg1gixlejc4qu7](https://ci.appveyor.com/project/rejas/modernizr/builds/33844485/job/7vhg1gixlejc4qu7) from 9b62ec82 but #2570 works
[https://ci.appveyor.com/project/rejas/modernizr/builds/33873075/job/amtqdpvlaq2qog3f](https://ci.appveyor.com/project/rejas/modernizr/builds/33873075/job/amtqdpvlaq2qog3f) from #2582 
[https://ci.appveyor.com/project/rejas/modernizr/builds/33873936/job/gaurj6flrktput5g](https://ci.appveyor.com/project/rejas/modernizr/builds/33873936/job/gaurj6flrktput5g) from #2582 
[https://ci.appveyor.com/project/rejas/modernizr/builds/33877675/job/7t4617vhqf1to2s2](https://ci.appveyor.com/project/rejas/modernizr/builds/33877675/job/7t4617vhqf1to2s2) from #2584

External resources:
[https://github.com/mapbox/node-sqlite3/issues/1318](https://github.com/mapbox/node-sqlite3/issues/1318)

**Comment by rejas** [comment]
yeah, something isnt right when using node 14....

**Comment by Markel** [comment]
Maybe we should contact appveyor through their [forums](https://help.appveyor.com/discussions) or [any of the other methods](https://www.appveyor.com/support/)???

**Comment by Markel** [comment]
> Maybe we should contact appveyor through their [forums](https://help.appveyor.com/discussions) or [any of the other methods](https://www.appveyor.com/support/)???

[Done](https://help.appveyor.com/discussions/problems/28111-code-1073741819)
