### ISSUE TITLE
Add Support for Augmented Reality / Virtual Reality 

### ISSUE THREAD

**Issue by mehmettahameral** [Modernizr/Modernizr#2588]
It would be nice to have detection that checks browser support for AR/VR.

Example AR on the browser: https://www.aybola.com/ar/

**Comment by Markel** [comment]
Hi 👋! That's a pretty good idea! However in order to implement it we would need to specify the technology the VR/AR on the web uses. I've search a little bit and found about [WebXR](https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API), is that what you are talking about?

As a sidenote, detection of WebXR should be pretty straightforward, simply detecting if `navigator.xr` is null.

**Comment by mehmettahameral** [comment]
🙋‍♂️ 
Not only WebXR, but also device information. 
Please find the list of AR supported devices here: https://developers.google.com/ar/discover/supported-devices
So if you can keep up-to-date that list, that'd be great.

**Comment by roblarsen** [comment]
A static list of devices is basically the opposite of Modernizr. 

The WebXR detect looks like an easy PR for someone 🏆

**Comment by Markel** [comment]
Yeah, a list of devices goes against the idea of Modernizr. The only thing that I think that could be feasible is if inside the result of `navigator.xr` or another object gave us a clue about whether AR is supported. However I would find it incredibly lucky if such object existed, specially as Modernizr runs on the browser, not the device

**Comment by Markel** [comment]
Okay, I've been checking out the WebXR specification and god just kill me if it is not extensive. As I see it there are only two options: we go all in or we don't but both don't make sense. A simple `navigator.xr` test would be stupid, as anybody who works with this technology is definitely capable of doing that simple check without adding an entire new library. On the other hand, I find that doing all the work to implement all the checks is kind of useless as a [quick search at Caniuse](https://caniuse.com/#search=XR) will show that when a browser supports WebXR it usually supports the submodules. I don't know, those are my conclusions, which are your opinions?

P.S.: The [https://www.aybola.com/ar/](https://www.aybola.com/ar/) website doesn't use WebXR technology as it loads in Firefox even when the flags of WebXR are deactivated

**Comment by mehmettahameral** [comment]
@Markel It's not WebXR that's true but have you tried https://www.aybola.com/ar/ on your mobile?

**Comment by Markel** [comment]
@mehmettahameral yep, tried on my 3 mobile browsers (Firefox, Opera and 'Browser') and it works perfectly

**Comment by mehmettahameral** [comment]
@Markel cool 👍 so my main request was adding supported devices into Modernizr and keep maintained it. However, as far as I can see, storing static information is against Modernizr. So I think we can close the issue now. 
_(If anyone needs further comment/question, please dm me.)_
