### ISSUE TITLE
Add simple test for the property value

### ISSUE THREAD

**Issue by Markel** [Modernizr/Modernizr#2595]
Hi 👋

> Note: Check the comment below

### What is proposed
This should be a relatively easy PR to get done. Every Modernizr test has a `property` tag on their [metadata](https://github.com/Modernizr/Modernizr/blob/master/HOW_TO_WRITE_FEATURE_DETECTS.md#metadata), this tag is always* lowercase without any punctuation. The idea would be to create a test that throws an error* whenever a property doesn't respect by this rule.

*[The Modernizr website says that this rule is just a suggestion](https://modernizr.com/docs#modernizr-addtest) but in reality it's more a rule than a recommendation. Feel free to throw a warning instead of an error if you prefer.

### How to do it
This test should be implemented in the [lib\metadata.js file](lib/metadata.js), a recent similar PR was approved (#2551) which added a similar test to this. After adding the test we would need a test for the test, this one would need to be implemented in [test\node\lib\metadata.js file](test\node\lib\metadata.js), you may check #2251 too (although the git diff is less readable in this one)

Feel free to raise any question in this issue if you stumble with problems :)

**Comment by Markel** [comment]
Okay, I should have checked before writing an issue 🤦. [An error is actually thrown if you put uppercase symbols](https://github.com/Modernizr/Modernizr/blob/1baf805e9eb54710f6ad122a4f6557f6e369c530/test/browser/integration/classes.js#L12-L14), but not for symbols like spaces or others. So yeah, the issue should continue, but you may want to [check this issue](https://github.com/Modernizr/Modernizr/pull/2108#issuecomment-619512863) to do the work. (It may actually be easier than before!)

**Comment by adzo261** [comment]
Hi, can I take this issue?

**Comment by rejas** [comment]
Sure, go for it

**Comment by rejas** [comment]
Merged!

**Comment by Markel** [comment]
I don't know, but I quite like this format to create small changes that need to be done. Like explaining the things related to the change and give like some idea from where to start. What do you think @rejas ? @adzo261, maybe you could give us some feedback :)

**Comment by adzo261** [comment]
> I don't know, but I quite like this format to create small changes that need to be done. Like explaining the things related to the change and give like some idea from where to start. What do you think @rejas ? @adzo261, maybe you could give us some feedback :)

Yes, I like this way of presenting an issue. It was indeed helpful for me. Pointers on where to start for small issues and conceptual overview for striking changes can make it less overwhelming for new comers. Also, I would vote for having an issues' template if we don't have already.

And regarding the codebase, it is well structured and maintained. And members and contributors, you guys rock🤘.
I thoroughly enjoyed the interaction we had while working on it.
@Markel @rejas 
I would love to stay connected, and may be try to work again in future.
Do we have slack or discord or gitter setup?

Thanks!

**Comment by Markel** [comment]
> Also, I would vote for having an issues' template if we don't have already.

Yeah, I had been thinking of issuing a PR to add issue templates (including test requests, bugs, ...) for a while, but I just have been too lazy to start writing them 😅. I'll probably will start working on it next.

> And members and contributors, you guys rock🤘.

🥰😍♥♥

> Do we have slack or discord or gitter setup?

I think that we don't 🤔. It may be interesting to consider creating it, but that's something that maintainers would need to decide

**Comment by rejas** [comment]
I love the idea of better issue templates, it would really help in a lot of areas (bug reportes, maintainers etc)

As for slack /discord/gitter: I like that there is only one place for working on this project. Everything is here in github and can be discussed in issues. Adding some other software/website into the mix would add more work keeping up to date with bug reports / questions while not offering more value. 

Modernizr isnt the most relevant piece of software anymore so we should keep it simple :-)
