### ISSUE TITLE
3.11.3 is not on GitHub?

### ISSUE THREAD

**Issue by roblarsen** [Modernizr/Modernizr#2605]
I am working on an update to HTML5 Boilerplate and running the build I saw a new version of Modernizr generated. Dependabot made the change three months ago and we hadn't run a build into master in the interim. The thing is- I don't see the release here on GitHub and since the site is a zombie, there's no mention of it there. The latest tag is [v3.11.2](https://github.com/Modernizr/Modernizr/releases/tag/v3.11.2) The code looks like it's in a branch ([Modernizr/package\.json at v3 · Modernizr/Modernizr](https://github.com/Modernizr/Modernizr/blob/v3/package.json)) but I had to poke around to find that.

**Comment by rejas** [comment]
You are correct, I didnt tag that release. Fixed that.
