### ISSUE TITLE
AVIF Support missing?

### ISSUE THREAD

**Issue by jmmarco** [Modernizr/Modernizr#2611]
I was looking for support with the new [AVIF image format](https://github.com/Kagami/avif.js). But it doesn't seem to be included if you type: __image__ or __avif__ on the website:
<img width="1369" alt="Screen Shot 2020-10-15 at 21 01 40" src="https://user-images.githubusercontent.com/3438337/96197915-aa4a3d80-0f29-11eb-8416-2c5afca4cfb4.png">

I cloned the project and found that feature support has indeed been added. However it doesn't seem to be present in the official build? Am I missing something? 🤔

**Comment by rejas** [comment]
The website is unfortunately outdated until @patrickkettner finds the time to update it :-( 
Also: avif detection got only merged in the future v4 branch, it isnt in the v3 branch

**Comment by livthomas** [comment]
If anybody wants to get the same output as on the website before it's updated, follow these steps:
```bash
git clone git@github.com:Modernizr/Modernizr.git
cd Modernizr
npm install
./bin/modernizr -f avif -u
```

You'll find the result in `modernizr.js` file.
