### ISSUE TITLE
Wrong property name of es6class test

### ISSUE THREAD

**Issue by toddwong** [Modernizr/Modernizr#2619]
**Type of bug**

- [ ] Differences between Can I use & Modernizr
- [ ] False positive
- [x] Modernizr error

**Describe the bug**
in Modernizr.metadata result, the `property` and `cssclass` of this test is "es6class", but  actually it is "class".

**How to Reproduce**
`modernizr -d detections.js -f es6class -o setClasses`
When include this script in html page, `Modernizr.class` is true, but `Modernizr.es6class` is undefined

**Expected behavior**
The metadata and runtime property/css-class names should be the same.

**Additional context**
Modernizr version: 3.11.4

**Comment by rejas** [comment]
Thanks for the report, will be fixed in v4
