### ISSUE TITLE
modernizr.com TLS certificate has expired

### ISSUE THREAD

**Issue by bartverdonck** [Modernizr/Modernizr#2626]
The SSL Certificat expired on 26/12/2020

**Comment by Markel** [comment]
@patrickkettner 👀👀

(It happens sometimes, sorry for the inconvenience @bartverdonck )

**Comment by Markel** [comment]
Oh wait, it seems that it has been resolved (I probably should have checked it before saying anything, sorry Patrick!)

**Comment by rejas** [comment]
It's a tradition :-) But good to see @patrickkettner still refreshing it. Happy holidays to all of you!

**Comment by Markel** [comment]
> Happy holidays to all of you!

Happy holidays 😘🥰

**Comment by bartverdonck** [comment]
thx for the fix, happy holidays
