### ISSUE TITLE
Travis CI is migrating to the .com TLD

### ISSUE THREAD

**Issue by Markel** [Modernizr/Modernizr#2632]
**The question**
Travis CI is migrating to the .com TLD, it seems that the migration process hasn't been done for the Modernizr project, I guess it would be nice to do it (?) (Note: it may not need to be done)

**Do maintainers need to follow some steps to help you out?**
I don't know how the infrastructure is established but you [may check this link to check the news :)](https://docs.travis-ci.com/user/migrate/open-source-repository-migration). Btw, it may be affecting how long does it take to get a server to test, [I guess that's why my last commit isn't getting a job](https://travis-ci.org/github/Modernizr/Modernizr/builds/755053747) (note, it may be solved by now) but even AppVeyor got the test finished first :open_mouth:.

**Comment by rejas** [comment]
Thanks for the heads up. Another project I help with (MagicMirror) just migrated over to github actions for this reason. Maybe we can / should do this too?

**Comment by Markel** [comment]
> Note: Travis-CI.com continues to be free for open source

We surely can, it would probably be an easy migration too as it is mostly and `npm test`, and migrating definitely has it advantages too, for example, it allows us to test in a single platform for Windows too (removing AppVeyor too). That being said, I'm not particularly keen on Github Actions, as it ends up eating other separate businesses that specialize on CI/CD and you create a great dependency on just a single platform which result in monopolies and that kind of stuff :upside_down_face:.

But it is just that, not that Github Actions is a bad product, actually, it's probably better than the alternatives we use, but I feel that it isn't healthy for the industry to use it :shrug:. So I'm not going to be mad or anything at all if we migrate, but I won't promote the idea of migrating, especially when the migration is easy (I just did it with my account which was something I had due :sweat_smile:):

- You have to [login into Travis](https://travis-ci.com/profile)
- Click on the migrate button 
- Click on accept and install in Github (obviously the organization account, not the personal)

But yeah, there's my opinion, anyway if you want me to make a PR with the migration or review one just say it :) (although give me 2-3 days to finish my last exam and then I'll get with it)

P.S.: I love the MagicMirror project, they look fantastic, not so sure if they are super useful (I mean Google Assistant isn't incredibly useful), but they definitely impress me. However, I don't think it would be an smart investment in my case (problems of being an student :money_with_wings:) nor I have a place to put it in my house :sweat_smile:
