### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by mrleblanc101** [Modernizr/Modernizr#2634]
Modernizr.com is down.
Which prevent custom build from being downloaded via bower.

**Comment by rejas** [comment]
@patrickkettner could you check it out?

**Comment by patrickkettner** [comment]
there was a problem with the dns hosting. it has been corrected. the TTL
will need to clear before it works automatically. This is ~20 minutes.
In the mean time, anyone can set up an /etc/hosts entry pointing directly
to the IP address (40.114.55.165)
