### ISSUE TITLE
NPM readme outdated

### ISSUE THREAD

**Issue by Markel** [Modernizr/Modernizr#2636]
**Type of bug***
A little slide with npm

**Describe the bug**
The [npm readme](https://www.npmjs.com/package/modernizr) is outdated, I actually though that npm updated it automatically with the Github but I guess that no :sweat_smile: 

**Additional context**
Funny how I discovered it (this is a side story, nothing important): yesterday while solving merge conflicts for the v4 I realised that a previous resolution from me was wrong and that [I left the deprecation section there](https://www.npmjs.com/package/modernizr#deprecation) (currently replaced by [breaking changes with v4](https://github.com/Modernizr/Modernizr#breaking-changes-with-v4)) so today when I've entered the npm page and saw that section I've just laughed, recheck, and later said: okay, it's time to bother rejas again (sorry)

**Comment by rejas** [comment]
Mhh.... 
I added the warning to the v3 branch now too, lets see if that fixes it. Lets hope the npm readme is not only updated when a new release is pushed.

**Comment by Markel** [comment]
>  Lets hope the npm readme is not only updated when a new release is pushed.

[Uh... It will definitely update by itself :) What? That why is this text a link? Oh, for nothing, don't click on me unless you want your dreams broken.](https://docs.npmjs.com/about-package-readme-files#updating-an-existing-package-readme-file)

Note: I just searched for it, I didn't knew before 😅

**Comment by Markel** [comment]
I'm going to close the issue as nothing can be done and is stupid to publish a new version solely to update the readme, just will have to keep it in mind for future versions
