### ISSUE TITLE
Usage of derogatory term in comment in `src/domPrefixes.js`

### ISSUE THREAD

**Issue by DervishD** [Modernizr/Modernizr#2645]
**The question**

First of all, thank for adhering to the Open Code of Conduct. It is because of this that I'm writing to you, because a commented line in file `src/domPrefixes.js` uses the term "kebab-case", which is derogatory for the Arabic community. Having quite a lot of friends in that community, I think it's offensive for them and their culture.

**Do maintainers need to follow some steps to help you out?**

Since kebab-case (and sorry for using the term myself, but it's needed in this context) is quite similar to snake_case, I think a good alternative for referring to it when needed would be something along the lines of `snake-dash-case` or `reptile-case`. I think `snake-dash-case` is better, though, because it doesn't introduce a new jargon term, it's obvious for the wording that it's not the usual `snake_case` and it's concise.

What do you think? And in advance, thanks A LOT for considering non-offensive language a priority for this project. Thanks for adhering to the Open Code of Conduct and for showing empathy for other communities, their cultures and their views.

**Comment by rejas** [comment]
Thanks for the report @DervishD we will definitly look into this and change it. 
Is there some site dedicated to this topic where replacement names are discussed sicne there doesnt seem to be a consensus yet on what to call it? Found dash-case and hyphen-case in a quick search so I am not sure which of all those could be the most future-proof.

**Comment by DervishD** [comment]
Well, I'm not an expert, so I can't provide a suggestion for a future-proof term. It's impossible to know if a new term used to replace `kebab-case`  is going to be offensive or derogatory for a cultural group you're not familiar with. Best you can do is not using an already tainted term on purpose, like `kebab-case`. Beyond that, nobody can blame you.

I think that maybe `hyphen-case` is marginally better because the character itself is better described (IMHO) as hyphen, since a dash is a broader term (n-dash, m-dash). Probably `hyphen-case` is a good choice because it goes to the point, it's reasonably short, it is self-explanatory, and I don't think you can actually offend hyphens! 🤣 Just joking, I think it's a safe term to use instead of `kebab-case`

Probably there's some kind of standard term to replace `kebab-case`, but I'm not aware of it, and I don't think it is widely used, if it exists at all. `hyphen-case` looks safe, would work as an standard replacement if you ask me, and in fact it's a better term because it is completely self-explanatory. `kebab-case` doesn't make ANY sense for someone not already familiar with the term, while `hyphen-case` is obvious.

So, you have my complete support for `hyphen-case`, unless you prefer `dash-case`, which I think works, too.

And again, thanks for the effort put in all this issue.

**Comment by rejas** [comment]
I tend to lean towards hyphen-case too, but to get more people into programming, maybe you want to provide the PR for this issue?

Also, to come back to my first post, is there some summary / community / forum online where this topic is discussed incl. possible alternatives?

**Comment by DervishD** [comment]
I don't know of any forum where this topic is discussed, in fact the only reason why I was aware of this was because having friends of that culture who warned me about it in the past, I noticed it in Modernizr, they didn't tell me anything about the term because of your project, was much before, so I'm a bit at a loss here. And yes, `hyphen-case` sounds better to me, too.

On the other hand, I'm happy to collaborate, but I don't know what's a PR, is some kind of patch with some special format? If you point me to some guide I can learn the format and send you a patch, but in this case I think it's just a one-line change, maybe sending a patch is too slow and overkill?

I'm happy to follow your instructions :)

**Comment by Markel** [comment]
> On the other hand, I'm happy to collaborate, but I don't know what's a PR, is some kind of patch with some special format? If you point me to some guide I can learn the format and send you a patch, but in this case I think it's just a one-line change, maybe sending a patch is too slow and overkill?

First, hi! Thank you very much for making us aware of this issue.

Back to your question, the Modernizr project is a git repository (git is a technology to manage programming files in a way that favours collaboration and maintains a log of all changes). All repositories have a main branch (master is more widely used, but it's also derogatory), which shows the current state of the code.

Everyone has the ability of making a copy of the code, which is called a fork; with your copy you may make all the changes that you want (it's yours after all). Once you've done your changes the usual thing is to present those changes to the main project (this changes can be a patch, new features, …), this is done via a PR, which is basically a message saying “Hey I've done this changes that you may find at this fork, do you want to include them in your main branch? (or another branch)”. Then the maintainers of the repository will look at your changes and say: “Yes”, “Maybe tweak this thing over there” or “No” and proceed appropriately.

[Here is a little tutorial which will guide you through the commands of git](https://github.com/firstcontributions/first-contributions/blob/master/README.md), if you do not know how to use the command line, I would recommend you using a tool like [Sublime Merge](https://www.sublimemerge.com/) to replace those parts of the tutorial (I actually use Sublime Merge a lot)

**Comment by DervishD** [comment]
Markel, thanks A LOT for the references. I already use git for my projects, even though I have to confess I only use "Push" from VSCode, to move my changes at home to my GitHub repos. I know what that does, but not much beyond that, regarding git.

So, a PR is a Pull Request. I thought it was a "Problem Report" and googling it I got confusing information. Now it's crystal clear.

I'll fork the project, make the changes and do the Pull Request, if I can manage to do it. I'm proud to help :)

Again, thanks a lot for the information, certainly I would benefit quite a lot (well, a HUGE LOT) from learning more about git.

I'll prepare my Pull Request as soon as possible ;)

**Comment by DervishD** [comment]
Well, turns out forking and creating a Pull Request (with the invaluable help of VSCode and GitHub) was extremely easy!

Thanks you all for your help.

**Comment by Markel** [comment]
Maybe it's time to close this issue, given that #2646 has been merged 🙂.

And just wanted to thank you again Raúl :)
