### ISSUE TITLE
Vulnerability with Marked, does it impact Modernizr

### ISSUE THREAD

**Issue by saurabhtripathi** [Modernizr/Modernizr#2659]
**If we are using modernizr@3.3.1 which uses marked , is this a big security issue, what is the severity? **

_For example Lodash vulnerability dosen't have big impact on Modernizr as per this ticket: https://github.com/Modernizr/Modernizr/issues/2313_ 

What about Marked?

**Comment by Markel** [comment]
Hi @saurabhtripathi 👋😃
Which vulnerability are we talking about?

**Comment by saurabhtripathi** [comment]
@Markel  
https://snyk.io/test/npm/modernizr/3.3.1?tab=issues#npm:marked:20150520
this is for Vulnerable module: marked
Introduced through: marked@0.3.5
Detailed paths
Introduced through: modernizr@3.3.1 › marked@0.3.5
Remediation: Upgrade to modernizr@3.4.0.

**This was fixed in** 
**Issue:** https://github.com/Modernizr/Modernizr/issues/2158
**PR:** https://github.com/Modernizr/Modernizr/pull/2027

however if we are using modernizr@3.3.1 which uses marked and not markdownIt or remarkable, just wanted to understand,
how much vulnerable this is, i know it's kinda subjective query, 

**would like to understand, how critical it is to update to modernizr@3.4.0. or later, because of this.**

**Comment by Markel** [comment]
I feel like it may cause more problems with the test suite, so I don't think that it is critical for you to update. Anyway, I encourage you to update if you are able to @saurabhtripathi
