### ISSUE TITLE
Publish new release (on `npm`)?

### ISSUE THREAD

**Issue by strarsis** [Modernizr/Modernizr#2668]
**What is proposed**
Publish a new release on `npm`, so new feature detects, e.g. `avif` image format support.

**How to do it**
Publish a new release to `npm`.

**Comment by nithinag10** [comment]
I am trying to do an npm release. I am doing open-source work for the first time.

Steps I followed so far
1.  I pulled the repo by executing `git pull`
2.  I executed `npm ci` and `npm run` for testing purposes.
3.  I need the authorization to publish the package to npm.  
4. I got this when I executed `npm publish`
<img width="1425" alt="Screenshot 2021-10-05 at 12 02 49 PM" src="https://user-images.githubusercontent.com/56193327/135972777-1f66a45e-0795-486a-a1bc-a5da5a17048b.png">

**Comment by rejas** [comment]
Thanks for trying to help @nithinag10 but only maintainers can publish a new release.

As for a new release @strarsis the plan was to not release a v3 with new feature-detects but wait for v4 with that. v3 should only get bugfixes.

Alas, that v4 release is getting a little stale, so maybe we need a v3 release with the latest feature detects. What do you think @patrickkettner @Markel ?

**Comment by Markel** [comment]
> Alas, that v4 release is getting a little stale, so maybe we need a v3 release with the latest feature detects. What do you think @patrickkettner @Markel ?

Yeah, I would release a v3 with the new feature detects. Honestly, I'm not entirely confident that v4 is going to release any time soon

**Comment by icetee** [comment]
Due to the vulnerability of `markdown-it`, it would be a good idea to release a new version. https://github.com/markdown-it/markdown-it/security/advisories/GHSA-6vfc-qv3f-vr6c

**Comment by rejas** [comment]
Just published version 3.12.0, hope it helps
