### ISSUE TITLE
SSL certificate on modernizr.com expired preventing bower installs

### ISSUE THREAD

**Issue by DavorLovric** [Modernizr/Modernizr#2681]
SSL certificate on modernizr.com expired preventing bower installs. :(

**Comment by DavorLovric** [comment]
@rejas I had to fix it quickly and can't test right now. I hope it now works. Thank you!

**Comment by mrleblanc101** [comment]
This happen every year. Any plan on automating the renewal ?

**Comment by roblarsen** [comment]
It's every 90 days 🍾
