### ISSUE TITLE
Server down

### ISSUE THREAD

**Issue by thomas-lepage** [Modernizr/Modernizr#2683]
Your server seem to be down since 14h...
https://www.saashub.com/modernizr-status

**Comment by rejas** [comment]
@patrickkettner ?

**Comment by thomas-lepage** [comment]
@rejas @patrickkettner  Any update?

**Comment by rejas** [comment]
sorry, patrick is the only one who could help here and I got no other way to reach him then these issue :-(

**Comment by yogarasu** [comment]
Currently the server seems to be recovering.

**Comment by rejas** [comment]
thanks for reporting. closing the issue for now.
