### ISSUE TITLE
RSS feed won’t load

### ISSUE THREAD

**Issue by simevidas** [Modernizr/Modernizr#2684]
The request for https://modernizr.com/feed hangs in Chrome and Safari for me. I guess the problem is the incorrect HTTP `Content-Type: application/octet-stream` header.

**Comment by rejas** [comment]
Cant reproduce this, chrome and safari download the feed. Maybe you tried it during a downtime the homepage had this week?

**Comment by simevidas** [comment]
Yep, the issue does no longer occur.
