### ISSUE TITLE
Expired certificate

### ISSUE THREAD

**Issue by mrleblanc101** [Modernizr/Modernizr#2695]
As it is the case every 3 months, the certificate for [modernizr.com](https://modernizr.com/) is expired which break every deploy that use a custom build of modernizr.

**Comment by zcwtl** [comment]
It happened again these days, I see that the website uses the certificate provided by let's encrypt, don't they set up a scheduled task to renew?

**Comment by rejas** [comment]
Seems to work again right?

**Comment by zcwtl** [comment]
Yes, already accessible. :)
