### ISSUE TITLE
Implementation of sticky header

### ISSUE THREAD

**Issue by arya312** [Modernizr/Modernizr#2710]
The header on this website hides as we scroll down to the end. One could use a sticky header that will help with the ease of going to whatever page of the website we want to go to.

Sticky header CSS can be added. A few lines of code from this website might work:

https://webdesign.tutsplus.com/tutorials/how-to-hide-reveal-a-sticky-header-on-scroll-with-javascript--cms-33756#:~:text=.%C2%A0Add%20the%20Sticky%20Header%20CSS

**Comment by rejas** [comment]
Is this about the npm website too?
