### ISSUE TITLE
Alignment of the headings above install section to be corrected for better UI

### ISSUE THREAD

**Issue by arya312** [Modernizr/Modernizr#2711]
<img width="887" alt="Screenshot 2022-10-16 125349" src="https://user-images.githubusercontent.com/72682508/196023586-a23e7443-e1bf-443e-9d1a-f36f4cb4395e.png">

The alignment of this header could be done towards the left side, the extra part above the install section should be blank so as to differentiate between the two sides of the page whenever changing from one header to another.

**Comment by rejas** [comment]
Hi @arya312 this is the npm website, not the modernizr website. Nothing we can do about it.

**Comment by rejas** [comment]
I closed this issue, if anybody wants to work on the modenrizr.com website, they should open an issue on the correct repository: https://github.com/Modernizr/modernizr-neue
