### ISSUE TITLE
Empty prefix class

### ISSUE THREAD

**Issue by anita-chouhan** [Modernizr/Modernizr#2717]
**Type of bug**
Modernizr adds an empty prefix class to the `<html>` tag when using _Add CSS classes_ option _with prefix_.

**How to Reproduce**
1. Select the _Webp_ under the _DOWNLOAD_ tab.
2. Goto _OPTIONS_ and select _minify_ then in the input box for _Add CSS classes_ add has-
3. Download the build file.
4. Include the `modernizr-custom.js` in the head section of the website.

**Expected behavior**
Expected classes in the `<html>` tag `has-webp has-webp-alpha has-webp-animation has-webp-lossless`

**Actual behavior**
Classes added to the `<html>` tag `has- has-webp has-webp-alpha has-webp-animation has-webp-lossless`

**Comment by balogun14** [comment]
@anita-chouhan i will like to be assigned to this issue can you explain this more

**Comment by patHyatt** [comment]
This looks to be an issue with the [modernizer.com site](https://github.com/Modernizr/modernizr-neue) itself and not [this repository](https://github.com/Modernizr/Modernizr).

The version of Modernizer for the site is 3.6.0.

The `setClasses` logic had a condition added to append only if `classes` was not empty
Current Modernizr repo on right
![image](https://github.com/user-attachments/assets/b579a2db-30e5-46fc-a997-73c73b10ed63)

Current website's `setClasses`
![image](https://github.com/user-attachments/assets/ec0a99a4-4f3a-4eb0-8a3d-7a1e8d5d9908)



The `package.json` looks to be pointing to 3.11.8, which makes me think this may be deployment issue in the site's process.

**Comment by rejas** [comment]
Unfortunately the modernizr homepage is outdated indeed. And there is no automatic deployment process to get the latest modernizr version on it.
One has to manually build modernizr if they want the latest version :-(
Any help with modernizr-neue is of course appreciated...
