### ISSUE TITLE
帮助我收集用户信息，以便我配置vite的target和加载哪些pofyliff

### ISSUE THREAD

**Issue by vaynevayne** [Modernizr/Modernizr#2742]
我希望有一个库 帮助我找到适合我的vite build target 和tsconfig的target配置
1. 获取tsc的target为esNext时，背后代表的是哪些新特性。然后去浏览器上检测，报告给我哪些太可用，
2. 获取core-js的esNext的所有特性，然后去浏览器检测，报告给我有哪些太可用，
3. 之后以此向es9 es8 es7降低检测。直到找到所有特性都支持的那个target为止
4. 我觉得这个工作流是很实用的。

**Comment by rejas** [comment]
hi, putting your words into google translate doesnt give any indication that your request is modernizr related. so please rephrase it in english or close this issue. thanks.
