### ISSUE TITLE
Vulnerability on `requirejs v2.3.6`. New version available

### ISSUE THREAD

**Issue by gian1200** [Modernizr/Modernizr#2743]
**Type of bug**

- [ ] Differences between Can I use & Modernizr
- [ ] False positive
- [ ] Modernizr error
- [x] Vulnerability on dependency

**Describe the bug**

Vulnerability on `requirejs v2.3.6` or lower. New version (2.3.7) available. https://www.npmjs.com/package/requirejs

```shell
# npm audit report

requirejs  <=2.3.6
Severity: high
jrburke requirejs vulnerable to prototype pollution - https://github.com/advisories/GHSA-x3m3-4wpv-5vgc
fix available via `npm audit fix`
node_modules/requirejs

1 high severity vulnerability

To address all issues, run:
  npm audit fix
```

**How to Reproduce**

`npm audit`

**Expected behavior**

No vulnerability

**Additional context**

**Comment by rejas** [comment]
Released new verion 3.13.1 with updated dependencies
