### ISSUE TITLE
Test for flex-gap fails on Safari if zoom is 50% or 150%

### ISSUE THREAD

**Issue by jnehlmeier** [Modernizr/Modernizr#2747]
**Type of bug**

- [ ] Differences between Can I use & Modernizr
- [ ] False positive
- [x] False negative
- [ ] Modernizr error

**Describe the bug**

**How to Reproduce**

macOS 14.x, Safari 17.x, Safari 18.x

- Zoom to 50% or 150% and [run the test](https://github.com/Modernizr/Modernizr/blob/master/feature-detects/css/flexgap.js)
- For both zoom levels `flex.scrollHeight` returns 2 instead of 1 so the test fails even though Safari supports flex-gap.

**Expected behavior**

This is likely a Safari bug but the test should workaround it as the issue exists in Safari 17 and 18 (current) and possibly in earlier versions as well.

**Comment by TusharNaugain** [comment]
I can resolve this by modifying the existing test to handle Safari's behavior under different zoom settings, ensuring accurate detection of flex-gap support. Given my experience with JavaScript and CSS properties, I'm well-equipped to tackle this issue effectively.

**Comment by PRAteek-singHWY** [comment]
@jnehlmeier please assign this issue to me, i would love to work on it .
