### ISSUE TITLE
TypeError: isArray is not a function  - jQuery 4 compatibility

### ISSUE THREAD

**Issue by joejoseph00** [Modernizr/Modernizr#2754]
**jQuery 4 compatibility**

- [x] jQuery 4 has been released with Drupal 11
- [x] an upgraded version of bootstrap is available https://bootstrap.7pro.ca which ships without Modernizr
- [ ] Modernizr error when using Modernizr with jQuery 4: `TypeError: isArray is not a function`

**Describe the bug**

Upgrade jQuery to jQuery 4.0.0-beta2 or newer

**How to Reproduce**

Upgrade jQuery to jQuery 4.0.0-beta2 or newer

**Expected behavior**

No TypeErrors, no Javascript exceptions.

**Additional context**

https://github.com/wet-boew/wet-boew/issues/9808?t=2#issuecomment-2475100033
![image](https://github.com/user-attachments/assets/51aff4bf-99a8-4df2-a6f9-b4bea3352de4)

**Comment by rejas** [comment]
thanks for the report, but we are not using the isArray function from jquery anywhere in our lib.

We do have jquery as a dev dependency, so any error would only be happening when running tests. 

When updating jquery to the v4 beta (it doesnt seem to be released publicly on npm yet?) no errors appear when running the tests.

Are you sure the TypeError is thrown inside modernizr? What is in line 1836 of your wet-boew.js file?

**Comment by joejoseph00** [comment]
I'm working on fixes for jQuery 4 compatibility,  I will push up the fixes to my fork after testing and make a pull request for you to see.

**Comment by olstjos** [comment]
I'm investigating

**Comment by joejoseph00** [comment]
Ok so the exception was actually from an underlying load of another dependency that was using $.isArray .  I'll close this issue for now, thanks!
