### ISSUE TITLE
Uncaught TypeError: Object #<Object> has no method 'load'

### ISSUE THREAD

**Issue by myradon** [Modernizr/Modernizr#307]
I'm kinda of lost about getting this error. send a mail to Paul Irish and he asked me file a ticket over here. so now I did.

This is what I get;
- Chrome developers console; Uncaught TypeError: Object #<Object> has no method 'load'
- firebug: Modernizr.load is not a function

Don't understand the problem cause doing the same with yepnope.js is nope problemo.
I'm doing this just before the body-tag;

<script>
Modernizr.load([ {
load: '//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.js',
complete: function () {
if ( !window.jQuery ) {
Modernizr.load('js/jquery-1.6.1.js');
console.log("jQuery loaded locally!");
}
}
}, {
load: '//ajax.googleapis.com/ajax/libs/jqueryui/1.8.13/jquery-ui.js',
complete: function () {
if (!$.ui) {
Modernizr.load('js/jquery-ui-1.8.13.custom.min.js');
console.log("jQuery-ui loaded locally!");
}
}
},  {
load: 'js/supersized.3.1.3.core.js',
complete: console.log("supersize.js loaded")
}, {
load: 'js/init.js'
}
]);
</script> 

By the way it's Modernizr version 2.0.4

**Comment by shafeeqthayyil** [comment]
TypeError: a is undefined
when complete event is using

  yepnope ([{
        load: 'Shopping/js/JSHomeView.js',
        callback: function (url, result, key) { console.log("callback"); 
        
        selectHotsaleproduct(); }
    }]);
