### ISSUE TITLE
Lenovo Thinkpad T400 should not be a 'touch' device

### ISSUE THREAD

**Issue by allermand** [Modernizr/Modernizr#339]
Hi, 

Great utility, we use it a lot : )

But we have an issue where a client uses a Lenovo Thinkpad T400 device. Taking a test on - http://modernizr.github.com/Modernizr/test/ - it seems that this labtop gets "touch: true" as the first test result.

I recognize that the test page above uses "Modernizr v1.8pre", but we run the "developement version" - http://www.modernizr.com/downloads/modernizr-2.0.6.js - on our developement environment and this seems to treat the device identically.

You propably don't have a Lenovo Thinkpad T400 device for testing this issue, but it would be very interesting to get test results from other users on this device.

Note that our client has tested this on at least three identical Lenovo-devices with same result.

Regards
/Jesper

**Comment by ninjaonsafari** [comment]
We have the wrong detection on our `Lenovo Thinkpad X1 Carbon` with `Windows 10 (10.0.14393)`.

**Comment by patrickkettner** [comment]
What browser?

**Comment by ninjaonsafari** [comment]
@patrickkettner on all major browsers.
