### ISSUE TITLE
Add detection for HTML5 video autoplay

### ISSUE THREAD

**Issue by feklee** [Modernizr/Modernizr#353]
Some browsers support the `video` tag, but not the `autoplay` attribute.  Example: On iOS Safari 4.3 [autoplay is disabled](http://developer.apple.com/library/safari/#documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/Device-SpecificConsiderations/Device-SpecificConsiderations.html#//apple_ref/doc/uid/TP40009523-CH5-SW1). Thus, it would be very helpful if Modernizr detects autoplay.

My assumption: `video.onplay` of a hidden video player being executed reliably tells that a video is autoplaying. In that case `autoplay` is supported. However, `autoplay` not being supported may be impossible to detect without UA sniffing.

**Comment by isarmstrong** [comment]
Hey @paulirish 

You can do it like this:
http://codepen.io/davidgenetic/pen/FmHaD

But it creates about a 150ms delay on class application, which causes havoc if you're binding the element to a document ready function, since it's defaulting to "no-autoplay" then changing on test.

**Comment by patrickkettner** [comment]
@isarmstrong we actually have a video autoplay in master, for a few years now

**Comment by isarmstrong** [comment]
Oh really? Under what label? I'm just getting:

"js flexbox flexboxlegacy canvas canvastext webgl no-touch geolocation postmessage websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers applicationcache svg inlinesvg smil svgclippaths"

I'd love to get that detection working.

**Comment by patrickkettner** [comment]
https://github.com/Modernizr/Modernizr/blob/master/feature-detects/video/autoplay.js

**Comment by patrickkettner** [comment]
its in the v3 version of modernizr - v3.modernizr.com

**Comment by isarmstrong** [comment]
That explains it. Thanks! Apologies for the necro-thread then but it Googles high, so it's probably a net benefit.

**Comment by patrickkettner** [comment]
no worries at all - cheers

On Thu, Feb 26, 2015 at 4:42 PM, Ian Armstrong <notifications@github.com>
wrote:

> That explains it. Thanks! Apologies for the necro-thread then but it
> Googles high, so it's probably a net benefit.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Modernizr/Modernizr/issues/353#issuecomment-76280247>.
>



-- 
patrick

**Comment by Matth2772** [comment]
The class prefix-video-autoplay seems to be random on Android Browser.
