### ISSUE TITLE
Modernizr.input undefined when referencing Modernizr.input.placeholder

### ISSUE THREAD

**Issue by joelvh** [Modernizr/Modernizr#409]
It appears that "Modernizr.input" is never set, so when trying to detect if "placeholder" is supported, a javascript error is thrown.

**Comment by radekolbas** [comment]
I am getting conflicts in this build http://modernizr.com/download/?-apng-backdropfilter-backgroundblendmode-backgroundcliptext-backgroundsize-bgpositionshorthand-bgpositionxy-bgrepeatspace_bgrepeatround-bgsizecover-borderimage-borderradius-boxshadow-boxsizing-canvas-canvastext-checked-cssall-cssanimations-csscalc-csschunit-csscolumns-cssescape-cssexunit-cssfilters-cssgradients-csshyphens_softhyphens_softhyphensfind-cssinvalid-cssmask-csspointerevents-csspositionsticky-csspseudoanimations-csspseudotransitions-cssreflections-cssremunit-cssresize-cssscrollbar-csstransforms-csstransforms3d-csstransitions-cssvalid-cssvhunit-cssvmaxunit-cssvwunit-cubicbezierrange-devicemotion_deviceorientation-display_runin-displaytable-ellipsis-flexbox-flexwrap-fontface-generatedcontent-hiddenscroll-hsla-ie8compat-inlinesvg-inputtypes-lastchild-mediaqueries-multiplebgs-nthchild-objectfit-opacity-overflowscrolling-preserve3d-regions-rgba-shapes-siblinggeneral-subpixelfont-supports-svg-svgasimg-svgclippaths-svgfilters-svgforeignobject-target-textalignlast-textshadow-userselect-willchange-wrapflow-printshiv-cssclassprefix:mod_ !

--------

Here is error:
TypeError: g is undefined
...){t(n[e])},0)},addTest:function(e,t,n){g.push({name:e,fn:t,options:n})},addAsync...

**Comment by SlexAxton** [comment]
Might should be a different issue but I can reproduce this.

Likely coming from this output:

![http://slex.me/image/0G2f113m0n1M/Screen%20Shot%202015-10-13%20at%202.43.50%20AM.png](http://slex.me/image/0G2f113m0n1M/Screen%20Shot%202015-10-13%20at%202.43.50%20AM.png)

**Comment by SlexAxton** [comment]
Opened https://github.com/Modernizr/Modernizr/issues/1707 for this instead.
