### ISSUE TITLE
Redesign Download/Builder page

### ISSUE THREAD

**Issue by KuraFire** [Modernizr/Modernizr#487]
As part of #486 in which all core tests are moved into the `feature-detects/` folder, the builder needs redesigning to accommodate this change. I'm splitting this aspect into its own issue so I can assign it to myself without it interfering with the code efforts.

PART OF: #486

**Comment by patrickkettner** [comment]
:tada:

**Comment by dmethvin** [comment]
:star2:

**Comment by KuraFire** [comment]
:shipit: (past tense)
