### ISSUE TITLE
Modernizr.touch detects touch events not touch devices

### ISSUE THREAD

**Issue by paulirish** [Modernizr/Modernizr#548]
IE Mobile e.g. doesnt expose webkit touch events but is a touch device..

what exactly does `Modernizr.touch` imply? We should agree so we can document it.

**Comment by beany-vu** [comment]
We can you if(Modernizr.pointerevents) {// handler for point event} to check if user touch on screen of Surface?
Btw, nice to meet you, Paul Irish. You are my idol :D

**Comment by jiji262** [comment]
So how to detect touch devices with Javascript?

**Comment by matte00** [comment]
@jiji262 
`       let supportsTouch = false;
        if ('ontouchstart' in window) // iOS & android
            supportsTouch = true;
        else if (window.navigator.msPointerEnabled) // Win8
            supportsTouch = true;
        else if ('ontouchstart' in document.documentElement) // Controversal way to check touch support
            supportsTouch = true;

        if (supportsTouch) {
            console.log('touch device');
        }`

**Comment by roblarsen** [comment]
[EVERYTHING YOU (N)EVER WANTED TO KNOW ABOUT TOUCH AND POINTER EVENTS](https://patrickhlauke.github.io/getting-touchy-presentation/)
