### ISSUE TITLE
@viewport test

### ISSUE THREAD

**Issue by ryanseddon** [Modernizr/Modernizr#604]
Opera introduced the @-o-viewport rule http://dev.opera.com/articles/view/an-introduction-to-meta-viewport-and-viewport/

Is also in IE10. Someone wanna have a go at this?

**Comment by robsonsobral** [comment]
@hexalys , hi!

I'm looking for how to test the `@viewport` support and found this topic.

Either `max-zoom`, `min-zoom`, `orientation`, `user-zoom`, `maxZoom`, `minZoom`, `orientation` or `userZoom` returns **always** true on Chrome 45.

The flags can make the unprefixed version to work.

I couldn't find a reliable way to test it, though.

Thank you for the info.
