### ISSUE TITLE
has() API adapter

### ISSUE THREAD

**Issue by paulirish** [Modernizr/Modernizr#613]
`has()` has a lot of excellent uses including its integration for optimized builds in require.js

* http://requirejs.org/docs/optimization.html#hasjs
* http://www.sitepen.com/blog/2012/06/12/feature-detection-and-device-optimized-builds/

It'd be great to make this an option for Modernizr users as well. Mimicing the `has()` api should be easy enough and would allow some good features.

**Comment by patrickkettner** [comment]
has.js' repo hasn't been updated in years, and doesn't seem to be available on npm or bower. Should we consider this a wontfix? @paulirish @SlexAxton @ryanseddon

**Comment by ryanseddon** [comment]
yep
