### ISSUE TITLE
Memory leak caused by mStyle

### ISSUE THREAD

**Issue by alexorion** [Modernizr/Modernizr#756]
We have noticed some memory leakage.

We have created a test page that just includes Modernizr and every time the page is reloaded, sIEve (a memory leak detector for IE) reports that the HTML node and a modernizr (something) has been leaked because they have been orphaned.

Going through the entire modernizr source, we've found found a variable called mStyle which referenced the style element of the modernizr node. By null'ing the mStyle variable when the modernizr was nulled, we no longer see the leak count increase on refresh in sIEve.

Unfortunately it's not as simple, albeit that the null'ing of mStyle does remove the leak, mStyle is still referenced and used by some features of the global Modernizr object.

We can reproduce it with latest version of Modernizr in IE8

**Comment by patrickkettner** [comment]
@dteirney v3 is now finally listed as stable.

good luck!
