### ISSUE TITLE
Add test for pointer-events: none support

### ISSUE THREAD

**Issue by johan** [Modernizr/Modernizr#80]
http://demos.hacks.mozilla.org/openweb/pointer-events/ is great for opacity gradients on top of trailing-off content without swallowing up mouse events, but on browsers not handling pointer-events: none, it hampers functionality. Could we get a test for this support?

**Comment by sammyhk** [comment]
Hi All,
Apart from the the false positive result in browsers, the detection code using getComputedStyle().pointerEvents which will cause JS error because getComputedStyle() return null in Firefox for some reason due to the bug https://bugzilla.mozilla.org/show_bug.cgi?id=795520
