### ISSUE TITLE
v3.0 release notes

### ISSUE THREAD

**Issue by stucox** [Modernizr/Modernizr#805]
A notepad for what we need to stick in the release notes for v3.0:

* The internal structure of Modernizr has been completely revamped, making it easier to contribute to and easier to customise/extend
* Modernizr is no longer available under a BSD licence; only MIT (#679)

**Detects**

* 76 new detects and counting (see #1230 for the full list)
* No detect names are hyphenated anymore; e.g. `battery-api` → `batteryapi`, `flexbox-legacy` → `flexboxlegacy`, etc (#719, #782)
* `Modernizr.contentsecuritypolicy` has been removed, as the JS API it was testing is deprecated (#1461)
* `Modernizr.touch` has been removed in favour of `touchevents` and `pointerevents` (#548)
* `Modernizr.pointerevents` now detects DOM PointerEvent support, rather than CSS `pointer-events` (#800)
* Detect for CSS `pointer-events` is now called `csspointerevents` (#800)
* Fixed false-positives in `fontface` detect (#1147)
* Our tests for Flexbox have been revised to better match developers’ expectations:
    * `Modernizr.flexbox` returns `true` if `flex-basis` is supported – which represents a “reasonable” modern spec implementation (Chrome, FF, Safari and IE11 all pass this)
    * `Modernizr.flexwrap` has been added to detect features missing from Firefox’s implementation
    * `Modernizr.flexboxtweener` has been added to detect the implementation used by IE10
    * `Modernizr.flexboxlegacy` remains unchanged
* `webgl` detect is now more reliable, using [`HTMLCanvasElement.supportsContext()`](http://www.w3.org/TR/2013/WD-html51-20130528/embedded-content-0.html#dom-canvas-supportscontext) where available (#689)
* WebGL extension enumerations are now attached to `Modernizr.webglextensions` rather than `Modernizr.webgl`
* `datauri` detect now has a `.over32kb` subproperty which will be `true` if the browser supports data URIs longer than 32 kB (#321)
* `audio` detect now also checks support for the [Ogg Opus](http://www.opus-codec.org/) codec, exposed as `Modernizr.audio.opus` (#699)
* `audiodata` detect has been removed, because the implementation was very poor; this spec has been deprecated in favour of the Web Audio API (#1019)
* `video` detect now has an `hls` subproperty representing support for the [HLS](http://en.wikipedia.org/wiki/HTTP_Live_Streaming) video format (#1317)
* `todataurljpeg`, `todataurlpng` and `todataurlwebp` are no longer asynchronous (#802)
* `fullscreen` detect has been updated to use `window.exitFullScreen` rather than `window.cancelFullScreen` as per [the latest spec](http://www.w3.org/TR/fullscreen/) (#739)
* `indexeddb` detect now has a `deletedatabase` subproperty, representing support for the `indexedDB.deleteDatabase()` method which isn’t implemented in some browsers (#1238)
* `webp` detect now has `lossy`, `lossless` and `alpha` subproperties, representing support for various variants of the WebP format; the root `webp` property still represents basic lossy support (#1229)
* Fixed a bug in `cssvwunit`, `cssvminunit` and `cssvmaxunit` which could give incorrect results when scrollbars are present (#1045)
* Fixed a bug in `emoji` detect where the test could stop working once minified (#899)
* Fixed a bug in `regions` detect where wrong result could be given when page is zoomed (#940)
* Fixed a bug in `csstransforms3d` detect where wrong result could be given when page is zoomed (#760)
* Fixed a false-positive for the `cssscrollbar` detect in IE9 (#698)
* Fixed a bug where `indexeddb` would throw an error if indexedDB was disabled via a browser flag (#798)
* Fixed various false-positives in `fileinput` detect (#772)
* Fixed various incorrect results in `history` detect (#733, #1471)
* Fixed a false-positive for `cookies` detect in IE9 (#666)
* Fixed a false-negative for `csstransforms3d` in WebKit browsers when certain styles are present on the page (#740)
* Fixed a bug where a page reload could crash Safari 5.1 (#524)
* Fixed `cssmask` detect (a typo meant it was ineffective) (#671)
* Fixed `userselect` detect (a typo meant it was ineffective) (#671)
* Fixed a bug in `displaytable` detect when page is in RTL (#716)
* Improved accuracy of `xhr2` detect in Firefox 3.6 (#1178)
* Improved accuracy of `customprotocolhandler` detect in Android 2.x (#992)
* Blacklisted Android 1.x & 2.x from passing the `csstransforms` detect, because it’s excessively buggy (#903)
* Fixed `backgroundblendmode` detect (#1420)

**APIs**

* Modernizr used to include a `Function.prototype.bind` polyfill (this was documented, but was somewhat hidden); this has been removed (#1278)
* `testProp()`, `testAllProps()` and `prefixed()` now use [`CSS.supports()`](https://developer.mozilla.org/en-US/docs/Web/API/CSS.supports) under the hood for most CSS feature detects where available, improving performance and accuracy (#818)
* `Modernizr.load` has been deprecated in favour of using [yepnope.js](http://yepnopejs.com) directly; from v3.0, yepnope.js must be included in the page in order for `Modernizr.load` to work: calling `.load()` will simply pass the arguments on to `yepnope()`; this will be removed fully in a future release (#1241)
* New `Modernizr.on()` API, for handling asynchronous detects (#622)
* New `prefixedCSS()` API, which functions like `prefixed()` but returns the prefixed property name in kebab-case (hyphenated, as used in CSS) instead of camelCase (#848)
* `testProp()`, `testAllProps()`, `prefixed()` and `prefixedCSS()` now accept property names in either camelCase or kebab-case; for `prefixed*()` the format of the response depends on which function you call: `prefixed()` always returns camelCase, `prefixedCSS()` always returns kebab-case) (#848)
* New `noPrefixes` build option, which forces feature detects to only return `true` if the feature is supported *without* a vendor prefix (#1082)
* New `enableJSClass` build option, which determines whether or not to add `js`/`no-js` classes to the `<html>` element when Modernizr runs; `true` by default (#1385)
* `hasEvent()` previously used "appropriate" elements for certain tests: `submit` would be tested against a `<form>` element, `error` would be tested against an `<img>` element, etc; this is no longer the case – for consistency, all will be tested against a `<div>`, unless otherwise specified by the optional `elem` argument (#636)
* `hasEvent()`'s optional `elem` argument can now be an element *or* simply a tag name, e.g. `Modernizr.hasEvent('click', 'a')` (#636)
* If a `classPrefix` is specified as a build option, it will be applied to `no-js`/`js` classes as well (previously this only applied to feature classes) (#1031)
* Fixed a bug where `classPrefix` wasn’t applied to the class set for the first-executed feature detect (#1053)
* `testProp()` and `testAllProps()` now accept up to 3 arguments: `testProp(prop, [value, [skipValueTest]])`; if a `value` is provided, Modernizr will ensure that value is supported for the named CSS property, delegating to `CSS.supports()` where available; if `skipValueTest` is `true` (default is `false`), the value test won’t be conducted when `CSS.supports()` *isn’t* available
* `addTest()` will now set subproperties if given a property name containing a period (`.`), which can be used for defining custom structured detects, or for extending existing detects (e.g. adding custom codec detects to `Modernizr.audio`) (#1089) ***(buggy: #1355)***
* Fixed a bug where calling `Modernizr.prefixed()` with an `obj` argument which doesn’t support binding would throw an exception (#1014)
* Fixed a bug where calling `Modernizr.mq()` inside a hidden iframe would throw an error in Firefox (#886)

**Comment by stucox** [comment]
Updated again with changes since August.

**Comment by FlashJunior** [comment]
Is there a release date for v3?
