### ISSUE TITLE
Add yepnope.js version to the minified source

### ISSUE THREAD

**Issue by AlexKeySmith** [Modernizr/Modernizr#806]
Hi,
Whilst investigating some problems I was having with yepnope, I was trying to work out what version of yepnope I currently had built into modernizr.

But the only way I could do it was following the link at the top of the minfied source (awesome idea by the way!) that took me back to the wizard, but I'm unsure whether when I got the source originally I had the current version built in.

It would be awesome if the modernizr generator also included a little note mentioning the version of yepnope that was bundled in.

Awesome set of projects, keep up the good work!

**Comment by wd0401** [comment]
Hi,
I use Modernizr.load like this:
Modernizr.load([
    {
        test: window.JSON,
        nope: FOL_GLOBAL.ctx + '/js/lib/json2.min.js'
    },
    {
        complete: function() {
            // FOL_GLOBAL.scriptsToLoad contains scripts included on pages using <freeman:require/> taglib
            require(['jquery', 'common','mediaMatch','enquire','responsive', 'body.header','searchbox'].concat(FOL_GLOBAL.scriptsToLoad), function($, CommonUtil){
            });
        }
    }
]);
but when i use modernizr 3.5.0 , there is a error (the property load is undefined),And what's the proplem?
Thanks.@SlexAxton @paulirish @KuraFire @ryanseddon @patrickkettner

**Comment by patrickkettner** [comment]
Just a heads up, you don't need to ping maintainers when you comment on an issue as they already get email notifications for it. 

modernizr.load was removed several years ago, in modernizr 3. You will just want to change your code to use yepnooe directly

**Comment by wd0401** [comment]
got it. thanks.@patrickkettner
