### ISSUE TITLE
Wrong flexbox detection on IE10?

### ISSUE THREAD

**Issue by oskarwrobel** [Modernizr/Modernizr#812]
Hi,

In my example on IE10 Modernizr.flexbox return true but looks like IE10 it doesn't understand flexbox css. Or maybe I'm doing something wrong?

Please take a look: http://jsfiddle.net/wGBL8/5/

(On safari Modernizr.flexbox return false, but everything looks fine)

**Comment by adammcraven** [comment]
@patrickkettner Did you backport the updated flexbox detection to 2.x? I could be wrong, but I can't see it in the latest version (2.8.3). Thanks!

**Comment by brendanfalkowski** [comment]
Looks like 2.8.3 does not have `flexboxtweener` tests for IE10, but—

The 3.x generator for mortals is working, so I was able to port to the beta version which does include the `flexboxtweener` test. Just had to swap the naming of `touch` to `touchevents` in my CSS. Otherwise working for me.

**Comment by gkiely** [comment]
=I'm still seeing flexbox in IE10, has flexboxtweener been backported?

**Comment by couchcrew-thomas** [comment]
I am also getting flexbox in IE10 again without it actually supporting full flexbox. My modernizr.js did not changed and it worked before.
I assume this has something to do with IE10 on Windows 10.
Can anyone compare win 8.1 & win 10 feature detection and reply?

**Comment by patrickkettner** [comment]
IE 10 doesn't exist on windows 10

**Comment by couchcrew-thomas** [comment]
But IE10 compatibility exists in Windows 10 for testing purposes.
And with that enabled modernizr thinks that flexbox is fully working.
On windows 8.1 and IE10 compatibility it didn't.

**Comment by patrickkettner** [comment]
> But IE10 compatibility exists in Windows 10 for testing purposes.
I work at Microsoft on Edge/IE, and it 100% does not exist for testing purposes. IE 10 mode exists in IE 11 for compatibility mode with poorly made websites, but the amount of people that are on IE 11 are very quickly going away to Edge.

I am confused, are you saying windows 8 IE 10, or windows 10 IE 10
