### ISSUE TITLE
Non-core detects don't work with dynamically provided window

### ISSUE THREAD

**Issue by mikkotikkanen** [Modernizr/Modernizr#822]
If window is redefined to point to another window (e.g. iframe) the non-code detections break as they rely on Modernizr object being defined in the same window as it's run from.

    $('<iframe />').appendTo(document.body).contents()[0].write('Dynamically generated iframe');
    var window = $('iframe')[0].contentWindow,
        document = window.document;

    // Include Modernizr here

Which leads to error:

    Uncaught ReferenceError: Modernizr is not defined 

I guess the easiest way to avoid problems like this could be to just use window.Modernizr instead of Modernizr in the calls outside the main scope.

Like so:

    Modernizr.addTest("mediaqueries",Modernizr.mq("only all"))

...becomes...

    window.Modernizr.addTest("mediaqueries",window.Modernizr.mq("only all"))

**Comment by patrickkettner** [comment]
was fixed way back in #1581
