### ISSUE TITLE
injectElementWithStyles is breaking height based viewport units in mobile Safari

### ISSUE THREAD

**Issue by GreenGremlin** [Modernizr/Modernizr#839]
It seems that inserting style elements in the body after load throws off height base viewport units in mobile Safari. So if you have an element's style set to 'height: 100vh;' when injectElementWithStyles is called the elements height increases dramatically.

**Comment by xgecko** [comment]
I was notified that this is fixed in iOS 8.3 beta. I haven't verified yet.
