### ISSUE TITLE
Publish gh-pages on successful Travis-CI build

### ISSUE THREAD

**Issue by nschonni** [Modernizr/Modernizr#867]
See https://github.com/wet-boew/wet-boew/blob/master/build/post_build.sh for an example of what we do in another project. The github token is stored in a secure variable in the Travis config https://github.com/wet-boew/wet-boew/blob/master/.travis.yml

Suggesting this since the test page is linked to from the README, but will be out of sync unless someone manually updates the gh-pages branch every time a test is changed.

**Comment by patrickkettner** [comment]
This has been added in. We publish to this repo's gh-pages (not modernzir.com) on successful master update. This keeps the static testing pages up to date.
