### ISSUE TITLE
Test if ligatures are supported in @font-face

### ISSUE THREAD

**Issue by theirf** [Modernizr/Modernizr#902]
Hello,
I am looking for some help creating a test for ligatures in a css3 @font-face. Ligatures are when multiple letters come together to form a single symbol. They can be used with custom icon fonts with @font-face to have a whole word, instead of a single character, be replaced by the icon in the font.

They are used by declaring the @font-face rule with the font that has the ligatures in it, applying the font-family to text with those multiple letters, and also applying the following styles:

        -moz-font-feature-settings:"liga=1, dlig=1";
	-moz-font-feature-settings:"liga","dlig";
	-ms-font-feature-settings:"liga","dlig";
	-o-font-feature-settings:"liga","dlig";
	-webkit-font-feature-settings:"liga","dlig";
	font-feature-settings:"liga","dlig";

They are only supported in some versions of Opera, Webkit, and Firefox. I know Chrome 14 and under and IE 9 and under do not support them.

How can I come up with a test to see if ligatures are supported?

I plan to use it like so:
if(Modernizr.fontface && Modernzr.ligatures){
    //load font with ligatures
}
elseif(Modernizr.fontface && !Modernizr.ligatures){
    //load font without ligatures
}
else{
    //@font-face is not supported and therefore neither are ligatures
    //load no custom font
}

I would greatly appreciate any and all help in making this test!

**Comment by phofm** [comment]
Thank you very much for looking into this! 
Is there any news? Just like @chriskrycho I would also like to check for ``scp``.
