### ISSUE TITLE
SVG in CSS backgrounds

### ISSUE THREAD

**Issue by inorganik** [Modernizr/Modernizr#956]
SVG in CSS backgrounds is an undetectable, but we know where it is supported, it's not going away, and we know future browsers will support it. And we desperately need a way to determine when to use a fallback. Testing for this feature will become more and more important as developers learn how versatile and useful SVG graphics are.

Would implementing a UA sniffer be out of the question here? @imulus has a great one they use on http://supportdetails.com, I wonder if they would want to fork this project and implement theirs so we could test it.

**Comment by benfrain** [comment]
Arrived here wondering if there was a specific test for SVG in background-image. 

As a mere CSS author, I think the alias idea is a good one, as in the absence of it, I'd end up choosing `.svg` as the fork, which is likely less accurate than an aliased `svgincss`.

**Comment by patrickkettner** [comment]
I went through and tested to see if `svgasimg` mapped to svg background support (test [here](http://output.jsbin.com/ciqipovudi)), and good news - it does! Im going to alias it out and call it a day (or year..or three years...)

**Comment by inorganik** [comment]
yay :)
